/**
 * Translated URL paths — server-only.
 *
 * Localized hub/calculator slugs are generated by `scripts/generate-slug-maps.mjs`
 * into `src/i18n/slug-maps/{locale}.json` (derived from the localized calculator
 * titles). English (root) URLs are unchanged; non-English locales get translated
 * path segments, e.g. /de/finanzrechner/401k-rechner.
 *
 * Resolution contract:
 *  - resolveHubSlug / resolveCalcSlug map a URL segment to its canonical
 *    registry slug plus the preferred (translated) segment for that locale.
 *  - The catch-all route permanently redirects canonical segments on non-EN
 *    locales to their translated form, and serves translated segments natively.
 *  - Segments with no translation fall back to the canonical slug (no redirect).
 */
import { isValidHubSlug } from '@/lib/hub-data'
import { routing } from '@/i18n/routing'

import esSlugMap from '@/i18n/slug-maps/es.json'
import frSlugMap from '@/i18n/slug-maps/fr.json'
import deSlugMap from '@/i18n/slug-maps/de.json'
import ptSlugMap from '@/i18n/slug-maps/pt.json'
import ruSlugMap from '@/i18n/slug-maps/ru.json'
import arSlugMap from '@/i18n/slug-maps/ar.json'
import hiSlugMap from '@/i18n/slug-maps/hi.json'
import jaSlugMap from '@/i18n/slug-maps/ja.json'
import zhSlugMap from '@/i18n/slug-maps/zh-CN.json'

export const siteUrl = 'https://www.calculat.online'

interface SlugMap {
  /** localized hub segment -> canonical hub slug */
  hubs: Record<string, string>
  /** canonical hub -> (canonical calc slug -> localized calc segment) */
  calcs: Record<string, Record<string, string>>
}

const MAPS: Record<string, SlugMap> = {
  es: esSlugMap,
  fr: frSlugMap,
  de: deSlugMap,
  pt: ptSlugMap,
  ru: ruSlugMap,
  ar: arSlugMap,
  hi: hiSlugMap,
  ja: jaSlugMap,
  'zh-CN': zhSlugMap,
}

// Lazily-built reverse indexes: locale -> (localized segment -> canonical)
const hubReverseCache = new Map<string, Map<string, string>>()
const calcReverseCache = new Map<string, Map<string, string>>() // key: `${locale}|${hub}`
// Forward index: locale -> (canonical hub -> localized segment)
const hubForwardCache = new Map<string, Map<string, string>>()

function mapFor(locale: string): SlugMap | undefined {
  return MAPS[locale]
}

function hubReverse(locale: string): Map<string, string> {
  let rev = hubReverseCache.get(locale)
  if (!rev) {
    rev = new Map()
    const hubs = mapFor(locale)?.hubs || {}
    for (const [local, canonical] of Object.entries(hubs)) rev.set(local, canonical)
    hubReverseCache.set(locale, rev)
  }
  return rev
}

function calcReverse(locale: string, hub: string): Map<string, string> {
  const key = `${locale}|${hub}`
  let rev = calcReverseCache.get(key)
  if (!rev) {
    rev = new Map()
    const map = mapFor(locale)?.calcs?.[hub] || {}
    for (const [canonical, local] of Object.entries(map)) rev.set(local, canonical)
    calcReverseCache.set(key, rev)
  }
  return rev
}

function hubForward(locale: string): Map<string, string> {
  let fwd = hubForwardCache.get(locale)
  if (!fwd) {
    fwd = new Map()
    const hubs = mapFor(locale)?.hubs || {}
    for (const [local, canonical] of Object.entries(hubs)) fwd.set(canonical, local)
    hubForwardCache.set(locale, fwd)
  }
  return fwd
}

/** Translated hub segment for this locale (identity for `en`). */
export function localizedHub(locale: string, hub: string): string {
  if (locale === 'en') return hub
  return hubForward(locale).get(hub) ?? hub
}

/** Translated calculator segment for this locale (identity for `en` / unmapped). */
export function localizedCalc(locale: string, hub: string, calc: string): string {
  if (locale === 'en') return calc
  const map = mapFor(locale)
  return map?.calcs?.[hub]?.[calc] ?? calc
}

/** Root-relative path suffix WITHOUT the locale prefix, e.g. `/finanzrechner/401k-rechner`. */
export function hubSuffix(locale: string, hub: string): string {
  return `/${localizedHub(locale, hub)}`
}

export function calcSuffix(locale: string, hub: string, calc: string): string {
  return `/${localizedHub(locale, hub)}/${localizedCalc(locale, hub, calc)}`
}

/** Root-relative path INCLUDING the locale prefix (`/de/...`; English at root). */
export function hubPath(locale: string, hub: string): string {
  const suffix = hubSuffix(locale, hub)
  return locale === 'en' ? suffix : `/${locale}${suffix}`
}

export function calcPath(locale: string, hub: string, calc: string): string {
  const suffix = calcSuffix(locale, hub, calc)
  return locale === 'en' ? suffix : `/${locale}${suffix}`
}

export function hubAbsolute(locale: string, hub: string): string {
  return `${siteUrl}${hubPath(locale, hub)}`
}

export function calcAbsolute(locale: string, hub: string, calc: string): string {
  return `${siteUrl}${calcPath(locale, hub, calc)}`
}

export interface SlugResolution {
  /** canonical registry slug (used for content lookup) */
  canonical: string
  /** preferred translated segment for this locale */
  localized: string
}

/**
 * Resolve a URL hub segment. Returns null when the segment is neither a
 * canonical hub slug nor a translated one (→ notFound).
 */
export function resolveHubSlug(locale: string, seg: string): SlugResolution | null {
  if (locale === 'en') {
    return isValidHubSlug(seg) ? { canonical: seg, localized: seg } : null
  }
  const canonical = hubReverse(locale).get(seg)
  if (canonical) return { canonical, localized: seg }
  if (isValidHubSlug(seg)) return { canonical: seg, localized: localizedHub(locale, seg) }
  return null
}

/**
 * Resolve a URL calculator segment within an already-resolved canonical hub.
 * Segments absent from the localized map are treated as canonical candidates;
 * registry membership is validated by the caller (`findCalculator`).
 */
export function resolveCalcSlug(locale: string, hub: string, seg: string): SlugResolution {
  if (locale === 'en') return { canonical: seg, localized: seg }
  const canonical = calcReverse(locale, hub).get(seg)
  if (canonical) return { canonical, localized: seg }
  return { canonical: seg, localized: localizedCalc(locale, hub, seg) }
}

/** hreflang map for a hub landing page (keys match `buildHreflang`: codes + x-default). */
export function hubHreflangs(hub: string): Record<string, string> {
  const map: Record<string, string> = { 'x-default': `${siteUrl}/${hub}` }
  for (const l of routing.locales) {
    map[l] = l === 'en' ? `${siteUrl}/${hub}` : `${siteUrl}/${l}/${localizedHub(l, hub)}`
  }
  return map
}

/** hreflang map for a calculator page — each locale links to its own translated slug. */
export function calcHreflangs(hub: string, calc: string): Record<string, string> {
  const map: Record<string, string> = { 'x-default': `${siteUrl}/${hub}/${calc}` }
  for (const l of routing.locales) {
    map[l] = l === 'en'
      ? `${siteUrl}/${hub}/${calc}`
      : `${siteUrl}/${l}/${localizedHub(l, hub)}/${localizedCalc(l, hub, calc)}`
  }
  return map
}
