'use client'

import React, { useCallback, useState } from 'react'
import { FileText, FileSpreadsheet, Printer, Share2, Download, Check, Copy, FileDown, Code } from 'lucide-react'
import { CalculatorWidget } from '@/components/premium/CalculatorWidget'

interface ExportPanelProps {
  slug: string
  title: string
  inputs?: Record<string, string>
  resultSummary?: string
  steps?: { label: string; value: string }[]
  resultValue?: string
  category?: string
}

function generateCSV(inputs?: Record<string, string>, resultSummary?: string, steps?: { label: string; value: string }[]): string {
  const rows: string[] = ['Field,Value']
  if (inputs) Object.entries(inputs).filter(([, v]) => v).forEach(([k, v]) => rows.push(`"${k}","${v}"`))
  if (resultSummary) rows.push(`"Result","${resultSummary}"`)
  if (steps) steps.forEach(s => rows.push(`"${s.label}","${s.value}"`))
  return rows.join('\n')
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function ExportPanel({ slug, title, inputs, resultSummary, steps, resultValue, category }: ExportPanelProps) {
  const [copied, setCopied] = useState(false)
  const [showEmbed, setShowEmbed] = useState(false)

  const handleExportCSV = useCallback(() => {
    const csv = generateCSV(inputs, resultSummary, steps)
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
    downloadBlob(blob, `${slug}-results.csv`)
  }, [slug, inputs, resultSummary, steps])

  const handleExportExcel = useCallback(async () => {
    const csv = generateCSV(inputs, resultSummary, steps)
    const html = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:x='urn:schemas-microsoft-com:office:excel' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset="UTF-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet>
      <x:Name>Results</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head>
      <body><table>${csv.split('\n').map(row => `<tr>${row.split(',').map(c => `<td>${c.replace(/"/g, '')}</td>`).join('')}</tr>`).join('')}</table></body></html>`
    const blob = new Blob([html], { type: 'application/vnd.ms-excel;charset=utf-8' })
    downloadBlob(blob, `${slug}-results.xls`)
  }, [slug, inputs, resultSummary, steps])

  const handleExportPDF = useCallback(async () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return
    const style = `
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; color: #333; }
        h1 { color: #06b6d4; font-size: 18px; border-bottom: 2px solid #06b6d4; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th, td { padding: 6px 10px; text-align: left; border-bottom: 1px solid #e5e7eb; font-size: 12px; }
        th { background: #f9fafb; font-weight: 600; }
        .result { font-size: 16px; font-weight: bold; color: #06b6d4; margin: 12px 0; }
        .footer { margin-top: 20px; font-size: 10px; color: #9ca3af; text-align: center; }
      </style>`
    const inputsHtml = inputs ? Object.entries(inputs).filter(([, v]) => v)
      .map(([k, v]) => `<tr><td>${k.replace(/([A-Z])/g, ' $1')}</td><td>${v}</td></tr>`).join('') : ''
    const stepsHtml = steps ? steps.map(s => `<tr><td>${s.label}</td><td>${s.value}</td></tr>`).join('') : ''
    printWindow.document.write(`<!DOCTYPE html><html><head><title>${title} - Results</title>${style}</head><body>
      <h1>${title}</h1>
      ${resultValue ? `<div class="result">Result: ${resultValue}</div>` : ''}
      ${inputsHtml ? `<h2>Inputs</h2><table>${inputsHtml}</table>` : ''}
      ${stepsHtml ? `<h2>Calculation Steps</h2><table>${stepsHtml}</table>` : ''}
      <div class="footer">Generated by JDCALC.com</div></body></html>`)
    printWindow.document.close()
    setTimeout(() => printWindow.print(), 500)
  }, [slug, title, inputs, resultSummary, steps, resultValue])

  const handleCopyAll = useCallback(async () => {
    const text = [title, '', 'Inputs:', ...(inputs ? Object.entries(inputs).filter(([, v]) => v).map(([k, v]) => `${k}: ${v}`) : []),
      ...(resultSummary ? ['', `Result: ${resultSummary}`] : []),
      ...(steps ? ['', 'Steps:', ...steps.map(s => `${s.label}: ${s.value}`)] : []),
    ].join('\n')
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {}
  }, [title, inputs, resultSummary, steps])

  const handleShare = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(window.location.href)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {}
  }, [])

  const handleCopyMarkdown = useCallback(async () => {
    const lines = [`## ${title}`, '']
    if (inputs) {
      Object.entries(inputs)
        .filter(([, v]) => v)
        .forEach(([k, v]) => lines.push(`- **${k.replace(/([A-Z])/g, ' $1').trim()}**: ${v}`))
    }
    if (resultSummary) {
      lines.push('', `**Result:** ${resultSummary}`)
    }
    if (steps) {
      lines.push('', '### Steps')
      steps.forEach((s) => lines.push(`- **${s.label}**: ${s.value}`))
    }
    lines.push('', '---', `Generated by [JDCALC.com](${window.location.href})`)
    try {
      await navigator.clipboard.writeText(lines.join('\n'))
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {}
  }, [title, inputs, resultSummary, steps])

  return (
    <div className="space-y-2">
      <p className="text-xs font-medium text-gray-500 dark:text-gray-400">Export & Share</p>
      <div className="flex flex-wrap gap-1.5">
        <button onClick={handleExportPDF} className="inline-flex items-center gap-1.5 min-h-[44px] px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-300" aria-label="Export as PDF">
          <FileDown className="w-3.5 h-3.5" /> PDF
        </button>
        <button onClick={handleExportCSV} className="inline-flex items-center gap-1.5 min-h-[44px] px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-300" aria-label="Export as CSV">
          <FileText className="w-3.5 h-3.5" /> CSV
        </button>
        <button onClick={handleExportExcel} className="inline-flex items-center gap-1.5 min-h-[44px] px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-300" aria-label="Export as Excel">
          <FileSpreadsheet className="w-3.5 h-3.5" /> Excel
        </button>
        <button onClick={handleShare} className="inline-flex items-center gap-1.5 min-h-[44px] px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-300" aria-label={copied ? 'Link copied to clipboard' : 'Copy calculator link to clipboard'}>
          {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Share2 className="w-3.5 h-3.5" />}
          {copied ? 'Copied' : 'Share'}
        </button>
        <button onClick={handleCopyAll} className="inline-flex items-center gap-1.5 min-h-[44px] px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-300" aria-label="Copy all results to clipboard">
          <Copy className="w-3.5 h-3.5" /> Copy All
        </button>
        <button onClick={handleCopyMarkdown} className="inline-flex items-center gap-1.5 min-h-[44px] px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-300" aria-label="Copy results as Markdown">
          <FileText className="w-3.5 h-3.5" /> Markdown
        </button>
        <button onClick={() => window.print()} className="inline-flex items-center gap-1.5 min-h-[44px] px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-300" aria-label="Print results">
          <Printer className="w-3.5 h-3.5" /> Print
        </button>
        <button onClick={() => setShowEmbed(!showEmbed)} className="inline-flex items-center gap-1.5 min-h-[44px] px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-300" aria-expanded={showEmbed} aria-label="Toggle embed code">
          <Code className="w-3.5 h-3.5" /> Embed
        </button>
      </div>
      {showEmbed && category && (
        <CalculatorWidget slug={slug} title={title} category={category} />
      )}
    </div>
  )
}
