import { z } from 'zod'
import { n, parseList } from '../../../lib/statistics-utils'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ x: z.string().min(1, 'Required'), y: z.string().min(1, 'Required'), z1: z.string().min(1, 'Required'), z2: z.string().min(1, 'Required') }),
  fields: [{ name: 'x', label: 'X (comma separated)', type: 'number', step: 'any' }, { name: 'y', label: 'Y (comma separated)', type: 'number', step: 'any' }, { name: 'z1', label: 'Z₁ (control, comma sep)', type: 'number', step: 'any' }, { name: 'z2', label: 'Z₂ (control, comma sep)', type: 'number', step: 'any' }],
  compute: (v) => { const x = parseList(v.x); const y = parseList(v.y); const z1 = parseList(v.z1); const z2 = parseList(v.z2); if (x.length !== y.length || x.length !== z1.length || x.length !== z2.length || x.length < 4) return { result: 'Need ≥4 obs', label: '', unit: '', steps: [] }; const mx = x.reduce((a, b) => a + b, 0) / x.length; const my = y.reduce((a, b) => a + b, 0) / y.length; const mz1 = z1.reduce((a, b) => a + b, 0) / z1.length; const mz2 = z2.reduce((a, b) => a + b, 0) / z2.length; const rxy = x.reduce((acc, xi, i) => acc + (xi - mx) * (y[i] - my), 0) / Math.sqrt(x.reduce((acc, xi) => acc + (xi - mx) ** 2, 0) * y.reduce((acc, yi) => acc + (yi - my) ** 2, 0)); const rxz1 = x.reduce((acc, xi, i) => acc + (xi - mx) * (z1[i] - mz1), 0) / Math.sqrt(x.reduce((acc, xi) => acc + (xi - mx) ** 2, 0) * z1.reduce((acc, zi) => acc + (zi - mz1) ** 2, 0)); const rxz2 = x.reduce((acc, xi, i) => acc + (xi - mx) * (z2[i] - mz2), 0) / Math.sqrt(x.reduce((acc, xi) => acc + (xi - mx) ** 2, 0) * z2.reduce((acc, zi) => acc + (zi - mz2) ** 2, 0)); const ryz1 = y.reduce((acc, yi, i) => acc + (yi - my) * (z1[i] - mz1), 0) / Math.sqrt(y.reduce((acc, yi) => acc + (yi - my) ** 2, 0) * z1.reduce((acc, zi) => acc + (zi - mz1) ** 2, 0)); const ryz2 = y.reduce((acc, yi, i) => acc + (yi - my) * (z2[i] - mz2), 0) / Math.sqrt(y.reduce((acc, yi) => acc + (yi - my) ** 2, 0) * z2.reduce((acc, zi) => acc + (zi - mz2) ** 2, 0)); const rz1z2 = z1.reduce((acc, zi, i) => acc + (zi - mz1) * (z2[i] - mz2), 0) / Math.sqrt(z1.reduce((acc, zi) => acc + (zi - mz1) ** 2, 0) * z2.reduce((acc, zi) => acc + (zi - mz2) ** 2, 0)); const rxy_z1 = (rxy - rxz1 * ryz1) / (Math.sqrt(1 - rxz1 * rxz1) * Math.sqrt(1 - ryz1 * ryz1)); return { result: rxy_z1, label: 'Partial r (XY|Z₁Z₂)', unit: '', steps: [{ label: 'r(XY)', value: `${rxy.toFixed(4)}` }, { label: 'Partial controlling Z₁', value: `${rxy_z1.toFixed(4)}` }, { label: 'Note', value: 'Partial correlation removes linear effects of all Z variables from both X and Y.' }] } },
  description: 'Partial correlation measures association between two variables while controlling for two or more covariates.',
  formula: 'r_{xy·z₁z₂} = (r_{xy·z₁} - r_{xz₂·z₁}r_{yz₂·z₁}) / √((1-r²_{xz₂·z₁})(1-r²_{yz₂·z₁}))',
  interpretation: 'Partial correlation isolates the unique linear relationship between X and Y after removing the effects of Z₁ and Z₂.'
}

export default calcDef
