"use client";

import React, { useState } from 'react';
import { CreditCardsPayoffForm } from '@/components/calculator/CreditCardsPayoffForm';
import { CreditCardsPayoffResults } from '@/components/calculator/CreditCardsPayoffResults';
import { CreditCardsPayoffArticle } from '@/components/calculator/CreditCardsPayoffArticle';

export function CreditCardsPayoffCalculator() {
  const [budget, setBudget] = useState("500");
  const [cards, setCards] = useState([
    { name: "Card 1", balance: "4,600", minPayment: "100", rate: "18.99" },
    { name: "Card 2", balance: "3,900", minPayment: "90", rate: "19.99" },
    { name: "Card 3", balance: "6,000", minPayment: "120", rate: "15.99" },
    { name: "", balance: "", minPayment: "", rate: "" },
    { name: "", balance: "", minPayment: "", rate: "" },
    { name: "", balance: "", minPayment: "", rate: "" }
  ]);

  const [results, setResults] = useState<any>(null);

  const state = { budget, cards };
  const setters = { setBudget, setCards };

  const handleClear = () => {
    setBudget("");
    setCards([
      { name: "Card 1", balance: "", minPayment: "", rate: "" },
      { name: "Card 2", balance: "", minPayment: "", rate: "" },
      { name: "Card 3", balance: "", minPayment: "", rate: "" },
      { name: "", balance: "", minPayment: "", rate: "" },
      { name: "", balance: "", minPayment: "", rate: "" },
      { name: "", balance: "", minPayment: "", rate: "" }
    ]);
    setResults(null);
  };

  const calculate = () => {
    const monthlyBudget = parseFloat(budget.replace(/,/g, '')) || 0;
    
    const activeCards = cards
      .map((c, i) => ({
        id: i,
        name: c.name || `Card ${i + 1}`,
        balance: parseFloat(c.balance.replace(/,/g, '')) || 0,
        minPayment: parseFloat(c.minPayment.replace(/,/g, '')) || 0,
        rate: (parseFloat(c.rate) || 0) / 100
      }))
      .filter(c => c.balance > 0);

    if (activeCards.length === 0) {
      setResults({ error: "Please enter at least one credit card with a balance." });
      return;
    }

    let totalMinimums = activeCards.reduce((sum, c) => sum + c.minPayment, 0);
    
    if (monthlyBudget < totalMinimums) {
      setResults({ error: "Your monthly budget is less than the total minimum payments required. You must increase your budget to pay off these cards." });
      return;
    }

    let totalInitialInterest = activeCards.reduce((sum, c) => sum + (c.balance * (c.rate / 12)), 0);
    if (monthlyBudget <= totalInitialInterest) {
      setResults({ error: "Your monthly budget is not enough to cover the monthly interest generated by your cards. Your debt will grow infinitely." });
      return;
    }

    let currentBalances = activeCards.map(c => ({...c}));
    let totalInterestPaid = 0;
    let totalPaid = 0;
    let totalMonths = 0;
    let cardStats = currentBalances.map(c => ({ id: c.id, name: c.name, interestPaid: 0, monthsToPayoff: 0 }));

    while (currentBalances.some(c => c.balance > 0.001) && totalMonths < 1200) {
      totalMonths++;
      let budgetRemaining = monthlyBudget;
      
      currentBalances.forEach(c => {
        if (c.balance > 0.001) {
          let interest = c.balance * (c.rate / 12);
          c.balance += interest;
          totalInterestPaid += interest;
          let stat = cardStats.find(s => s.id === c.id)!;
          stat.interestPaid += interest;
        }
      });

      currentBalances.forEach(c => {
        if (c.balance > 0.001) {
          let pmt = Math.min(c.minPayment, c.balance, budgetRemaining);
          c.balance -= pmt;
          budgetRemaining -= pmt;
          totalPaid += pmt;
          if (c.balance <= 0.001) {
            let stat = cardStats.find(s => s.id === c.id)!;
            if (stat.monthsToPayoff === 0) stat.monthsToPayoff = totalMonths;
          }
        }
      });

      let sortedCards = [...currentBalances].sort((a,b) => b.rate - a.rate);
      
      for (let c of sortedCards) {
        if (c.balance > 0.001 && budgetRemaining > 0.001) {
          let extraPmt = Math.min(c.balance, budgetRemaining);
          c.balance -= extraPmt;
          budgetRemaining -= extraPmt;
          totalPaid += extraPmt;
          if (c.balance <= 0.001) {
            let stat = cardStats.find(s => s.id === c.id)!;
            if (stat.monthsToPayoff === 0) stat.monthsToPayoff = totalMonths;
          }
        }
      }
    }

    if (totalMonths >= 1200) {
      setResults({ error: "Calculation reached 100 years. The debt is effectively unpayable with this budget." });
      return;
    }

    setResults({
      totalMonths,
      totalInterest: totalInterestPaid,
      totalPaid,
      cardStats
    });
  };

  return (
    <div className="max-w-[800px] mx-auto bg-white p-2 md:p-4">
      <div className="flex justify-between text-xs text-gray-500 mb-2 border-b pb-1">
        <div>home / financial / credit cards payoff calculator</div>
      </div>
      
      <h1 className="text-[26px] font-bold text-gray-800 mb-4 font-sans">Credit Cards Payoff Calculator</h1>
      <p className="mb-4 text-[13px] text-gray-800 leading-relaxed">
        This calculator creates a cost-efficient payback schedule for multiple credit cards using the Debt Avalanche method. To evaluate the repayment of a single credit card only, or for further information about credit cards and how they work, please visit our <a href="/financial-calculators/credit-card-payoff-calculator/" className="text-[#1c4587] underline">credit card calculator</a>.
      </p>

      <div className="flex flex-col md:flex-row gap-6 w-full">
        <div className="flex-1">
          <CreditCardsPayoffForm 
            state={state} 
            setters={setters} 
            handleCalculate={calculate}
            handleClear={handleClear}
          />
        </div>
        <div className="w-full md:w-[350px]">
          <CreditCardsPayoffResults results={results} />
        </div>
      </div>

      <CreditCardsPayoffArticle />
    </div>
  );
}
