"use client";

import React, { useState, useMemo } from 'react';
import { useTranslations, useLocale } from 'next-intl';
import { CreditCard, DollarSign, Clock } from 'lucide-react';
import { CreditCardsPayoffForm } from '@/components/calculator/CreditCardsPayoffForm';
import { CreditCardsPayoffResults } from '@/components/calculator/CreditCardsPayoffResults';
import { PremiumCalculatorShell } from '@/components/premium/PremiumCalculatorShell.dynamic';
import { SubCalcPanel, SubCalcGrid } from '@/components/premium/SubCalcPanel';

const calcMeta = {
  slug: 'credit-cards-payoff-calculator',
  title: 'Credit Cards Payoff Calculator',
  description: 'Find the fastest way to pay off multiple credit cards using the debt avalanche method.',
  tier: 'tier2',
  category: 'financial',
  hubSlug: 'financial-calculators',
  hubName: 'Financial Calculators',
  keywords: ['credit card payoff', 'debt avalanche', 'multiple cards', 'payoff schedule'],
};

export function CreditCardsPayoffCalculator() {
  const th = useTranslations('hubs');
  const locale = useLocale();
  const [budget, setBudget] = useState("500");
  const [cards, setCards] = useState([
    { name: "Card 1", balance: "4,600", minPayment: "100", rate: "18.99" },
    { name: "Card 2", balance: "3,900", minPayment: "90", rate: "19.99" },
    { name: "Card 3", balance: "6,000", minPayment: "120", rate: "15.99" },
    { name: "", balance: "", minPayment: "", rate: "" },
    { name: "", balance: "", minPayment: "", rate: "" },
    { name: "", balance: "", minPayment: "", rate: "" }
  ]);

  const [results, setResults] = useState<any>(null);

  const state = { budget, cards };
  const setters = { setBudget, setCards };

  const handleClear = () => {
    setBudget("");
    setCards([
      { name: "Card 1", balance: "", minPayment: "", rate: "" },
      { name: "Card 2", balance: "", minPayment: "", rate: "" },
      { name: "Card 3", balance: "", minPayment: "", rate: "" },
      { name: "", balance: "", minPayment: "", rate: "" },
      { name: "", balance: "", minPayment: "", rate: "" },
      { name: "", balance: "", minPayment: "", rate: "" }
    ]);
    setResults(null);
  };

  const calculate = () => {
    const monthlyBudget = parseFloat(budget.replace(/,/g, '')) || 0;
    
    const activeCards = cards
      .map((c, i) => ({
        id: i,
        name: c.name || `Card ${i + 1}`,
        balance: parseFloat(c.balance.replace(/,/g, '')) || 0,
        minPayment: parseFloat(c.minPayment.replace(/,/g, '')) || 0,
        rate: (parseFloat(c.rate) || 0) / 100
      }))
      .filter(c => c.balance > 0);

    if (activeCards.length === 0) {
      setResults({ error: "Please enter at least one credit card with a balance." });
      return;
    }

    let totalMinimums = activeCards.reduce((sum, c) => sum + c.minPayment, 0);
    
    if (monthlyBudget < totalMinimums) {
      setResults({ error: "Your monthly budget is less than the total minimum payments required. You must increase your budget to pay off these cards." });
      return;
    }

    let totalInitialInterest = activeCards.reduce((sum, c) => sum + (c.balance * (c.rate / 12)), 0);
    if (monthlyBudget <= totalInitialInterest) {
      setResults({ error: "Your monthly budget is not enough to cover the monthly interest generated by your cards. Your debt will grow infinitely." });
      return;
    }

    let currentBalances = activeCards.map(c => ({...c}));
    let totalInterestPaid = 0;
    let totalPaid = 0;
    let totalMonths = 0;
    let cardStats = currentBalances.map(c => ({ id: c.id, name: c.name, interestPaid: 0, monthsToPayoff: 0 }));

    while (currentBalances.some(c => c.balance > 0.001) && totalMonths < 1200) {
      totalMonths++;
      let budgetRemaining = monthlyBudget;
      
      currentBalances.forEach(c => {
        if (c.balance > 0.001) {
          let interest = c.balance * (c.rate / 12);
          c.balance += interest;
          totalInterestPaid += interest;
          let stat = cardStats.find(s => s.id === c.id)!;
          stat.interestPaid += interest;
        }
      });

      currentBalances.forEach(c => {
        if (c.balance > 0.001) {
          let pmt = Math.min(c.minPayment, c.balance, budgetRemaining);
          c.balance -= pmt;
          budgetRemaining -= pmt;
          totalPaid += pmt;
          if (c.balance <= 0.001) {
            let stat = cardStats.find(s => s.id === c.id)!;
            if (stat.monthsToPayoff === 0) stat.monthsToPayoff = totalMonths;
          }
        }
      });

      let sortedCards = [...currentBalances].sort((a,b) => b.rate - a.rate);
      
      for (let c of sortedCards) {
        if (c.balance > 0.001 && budgetRemaining > 0.001) {
          let extraPmt = Math.min(c.balance, budgetRemaining);
          c.balance -= extraPmt;
          budgetRemaining -= extraPmt;
          totalPaid += extraPmt;
          if (c.balance <= 0.001) {
            let stat = cardStats.find(s => s.id === c.id)!;
            if (stat.monthsToPayoff === 0) stat.monthsToPayoff = totalMonths;
          }
        }
      }
    }

    if (totalMonths >= 1200) {
      setResults({ error: "Calculation reached 100 years. The debt is effectively unpayable with this budget." });
      return;
    }

    setResults({
      totalMonths,
      totalInterest: totalInterestPaid,
      totalPaid,
      cardStats
    });
  };

  const totalPrincipal = useMemo(() => {
    return cards
      .map(c => parseFloat(c.balance.replace(/,/g, '')) || 0)
      .reduce((a, b) => a + b, 0);
  }, [cards]);

  const subCalcs = useMemo(() => {
    if (!results || results.error) return null;
    const years = Math.floor(results.totalMonths / 12);
    const months = results.totalMonths % 12;
    return (
      <SubCalcGrid>
        <SubCalcPanel title="Payoff Summary" icon={CreditCard} defaultOpen results={[
          { label: 'Total Debt', value: `$${totalPrincipal.toLocaleString()}`, badge: 'negative' },
          { label: 'Total Interest Paid', value: `$${results.totalInterest.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}`, badge: 'negative' },
          { label: 'Total Amount Paid', value: `$${results.totalPaid.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}` },
          { label: 'Payoff Time', value: `${years > 0 ? `${years}y ` : ''}${months}mo (${results.totalMonths} months)`, badge: 'info' },
        ]} />
        <SubCalcPanel title="Cards Breakdown" icon={DollarSign} results={
          (results.cardStats || []).map((stat: any) => ({
            label: stat.name,
            value: `${stat.monthsToPayoff} months · $${stat.interestPaid.toLocaleString(undefined, {minimumFractionDigits: 2})} interest`,
          }))
        } />
      </SubCalcGrid>
    );
  }, [results, totalPrincipal]);

  const mainValue = results ? results.totalInterest : undefined;

  return (
    <PremiumCalculatorShell
      calculator={{...calcMeta, hubName: th(calcMeta.hubSlug)}}
      form={<CreditCardsPayoffForm state={state} setters={setters} handleCalculate={calculate} handleClear={handleClear} />}
      result={<CreditCardsPayoffResults results={results} />}
      subCalcs={subCalcs}
      inputs={{ budget, cardCount: String(cards.filter(c => c.balance).length) }}
      mainValue={mainValue}
    />
  );
}
