import { useTranslations } from 'next-intl';

export function MortgageArticle() {
  const t = useTranslations('articles');
  return (
    <div className="text-[13px] font-sans text-gray-800 dark:text-gray-300 leading-normal mt-8 space-y-4">
      <p>The Mortgage Calculator helps estimate the monthly payment due along with other financial costs associated with mortgages. There are options to include extra payments or annual percentage increases of common mortgage-related expenses. The calculator is mainly intended for use by U.S. residents.</p>
      
      <h3 className="font-bold text-lg text-black dark:text-white mt-6">{t('section_headings.howItWorks')}</h3>
      <p>A mortgage is a loan secured by property, usually real estate property. Lenders define it as the money borrowed to pay for real estate. In essence, the lender helps the buyer pay the seller of a house, and the buyer agrees to repay the money borrowed over a period of time, usually 15 or 30 years in the U.S. Each month, a payment is made from buyer to lender. A portion of the monthly payment is called the principal, which is the original amount borrowed. The other portion is the interest, which is the cost paid to the lender for using the money. There may be an escrow account involved to cover the cost of property taxes and insurance. The buyer cannot be considered the full owner of the mortgaged property until the last monthly payment is made. In the U.S., the most common mortgage loan is the conventional 30-year fixed-interest loan, which represents 70% to 90% of all mortgages. Mortgages are how most people are able to own homes in the U.S.</p>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">{t('section_headings.factors')}</h3>
      <p>A mortgage usually includes the following key components. These are also the basic components of a mortgage calculator.</p>
      <ul className="list-disc pl-8 space-y-2">
        <li><b>Loan amount</b>—the amount borrowed from a lender or bank. In a mortgage, this amounts to the purchase price minus any down payment. The maximum loan amount one can borrow normally correlates with household income or affordability. To estimate an affordable amount, please use our <a href="/financial-calculators/house-affordability-calculator" className="text-blue-600 dark:text-blue-400 underline">House Affordability Calculator</a>.</li>
        <li><b>Down payment</b>—the upfront payment of the purchase, usually a percentage of the total price. This is the portion of the purchase price covered by the borrower. Typically, mortgage lenders want the borrower to put 20% or more as a down payment. In some cases, borrowers may put down as low as 3%. If the borrowers make a down payment of less than 20%, they will be required to pay private mortgage insurance (PMI). Borrowers need to hold this insurance until the loan's remaining principal dropped below 80% of the home's original purchase price. A general rule-of-thumb is that the higher the down payment, the more favorable the interest rate and the more likely the loan will be approved.</li>
        <li><b>Loan term</b>—the amount of time over which the loan must be repaid in full. Most fixed-rate mortgages are for 15, 20, or 30-year terms. A shorter period, such as 15 or 20 years, typically includes a lower interest rate.</li>
        <li><b>Interest rate</b>—the percentage of the loan charged as a cost of borrowing. Mortgages can charge either fixed-rate mortgages (FRM) or adjustable-rate mortgages (ARM). As the name implies, interest rates remain the same for the term of the FRM loan. The calculator above calculates fixed rates only. For ARMs, interest rates are generally fixed for a period of time, after which they will be periodically adjusted based on market indices. ARMs transfer part of the risk to borrowers. Therefore, the initial interest rates are normally 0.5% to 2% lower than FRM with the same loan term. Mortgage interest rates are normally expressed in Annual Percentage Rate (APR), sometimes called nominal APR or effective APR. It is the interest rate expressed as a periodic rate multiplied by the number of compounding periods in a year. For example, if a mortgage rate is 6% APR, it means the borrower will have to pay 6% divided by twelve, which comes out to 0.5% in interest every month.</li>
      </ul>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">The Full Cost of Homeownership</h3>
      <p>Monthly mortgage payments usually comprise the bulk of the financial costs associated with owning a house, but there are other substantial costs to keep in mind. These costs are separated into two categories: recurring and non-recurring.</p>
      
      <p className="font-bold text-[14px] text-black dark:text-white">Recurring Costs</p>
      <p>Most recurring costs persist throughout and beyond the life of a mortgage. They are a significant financial factor. Property taxes, home insurance, HOA fees, and other costs increase with time as a byproduct of inflation. In the calculator, the recurring costs are under the &quot;Include Options Below&quot; checkbox. There are also optional inputs within the calculator for annual percentage increases under &quot;More Options.&quot; Using these can result in more accurate calculations.</p>
      <ul className="list-disc pl-8 space-y-2">
        <li><b>Property taxes</b>—a tax that property owners pay to governing authorities. In the U.S., property tax is usually managed by municipal or county governments. All 50 states impose taxes on property at the local level. The annual real estate tax in the U.S. varies by location; on average, Americans pay about 1.1% of their property's value as property tax each year.</li>
        <li><b>Home insurance</b>—an insurance policy that protects the owner from accidents that may happen to their real estate properties. Home insurance can also contain personal liability coverage, which protects against lawsuits involving injuries that occur on and off the property. The cost of home insurance varies according to factors such as location, condition of the property, and the coverage amount.</li>
        <li><b>Private mortgage insurance (PMI)</b>—protects the mortgage lender if the borrower is unable to repay the loan. In the U.S. specifically, if the down payment is less than 20% of the property's value, the lender will normally require the borrower to purchase PMI until the loan-to-value ratio (LTV) reaches 80% or 78%. PMI price varies according to factors such as down payment, size of the loan, and credit of the borrower. The annual cost typically ranges from 0.3% to 1.9% of the loan amount.</li>
        <li><b>HOA fee</b>—a fee imposed on the property owner by a homeowner's association (HOA), which is an organization that maintains and improves the property and environment of the neighborhoods within its purview. Condominiums, townhomes, and some single-family homes commonly require the payment of HOA fees. Annual HOA fees usually amount to less than one percent of the property value.</li>
        <li><b>Other costs</b>—includes utilities, home maintenance costs, and anything pertaining to the general upkeep of the property. It is common to spend 1% or more of the property value on annual maintenance alone.</li>
      </ul>

      <p className="font-bold text-[14px] text-black dark:text-white mt-4">Non-Recurring Costs</p>
      <p>These costs aren't addressed by the calculator, but they are still important to keep in mind.</p>
      <ul className="list-disc pl-8 space-y-2">
        <li><b>Closing costs</b>—the fees paid at the closing of a real estate transaction. These are not recurring fees, but they can be expensive. In the U.S., the closing cost on a mortgage can include an attorney fee, the title service cost, recording fee, survey fee, property transfer tax, brokerage commission, mortgage application fee, points, appraisal fee, inspection fee, home warranty, pre-paid home insurance, pro-rata property taxes, pro-rata homeowner association dues, pro-rata interest, and more. These costs typically fall on the buyer, but it is possible to negotiate a &quot;credit&quot; with the seller or the lender. It is not unusual for a buyer to pay about $10,000 in total closing costs on a $400,000 transaction.</li>
        <li><b>Initial renovations</b>—some buyers choose to renovate before moving in. Examples of renovations include changing the flooring, repainting the walls, updating the kitchen, or even overhauling the entire interior or exterior. While these expenses can add up quickly, renovation costs are optional, and owners may choose not to address renovation issues immediately.</li>
        <li><b>Miscellaneous</b>—new furniture, new appliances, and moving costs are typical non-recurring costs of a home purchase. This also includes repair costs.</li>
      </ul>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">Types of Mortgages</h3>
      <p>Choosing the right loan program matters as much as choosing the right rate. The main mortgage types available to U.S. homebuyers are:</p>
      <ul className="list-disc pl-8 space-y-2">
        <li><b>Conventional fixed-rate mortgage</b>—not insured by the federal government and the most common choice in the U.S. Terms are typically 15, 20, or 30 years, with the 30-year fixed dominating the market. Loans that fall below the conforming limit published annually by the Federal Housing Financing Agency (FHFA) qualify for the best pricing. A down payment of 20% or more avoids private mortgage insurance entirely; lenders generally require a credit score of 620 or higher, while scores of 740 or above unlock the most competitive rates.</li>
        <li><b>FHA loan</b>—insured by the Federal Housing Administration and designed for borrowers with smaller down payments or thinner credit files. It is possible to put just 3.5% down with a credit score of 580 or higher (10% down for scores between 500 and 579). Because the government insures the lender against loss, mortgage insurance premiums are required regardless of the down payment size—11 years if you put at least 10% down, or for the life of the loan if you put down less.</li>
        <li><b>VA loan</b>—available to eligible veterans, active-duty service members, and surviving spouses through the Department of Veterans Affairs. VA loans require no down payment and charge no monthly mortgage insurance, though a one-time funding fee applies (waived for some borrowers, such as those receiving service-connected disability compensation). Rates are typically competitive.</li>
        <li><b>USDA loan</b>—backed by the U.S. Department of Agriculture for eligible rural and suburban properties and borrowers within program income limits. No down payment is required; instead, a guarantee fee is added to the loan.</li>
        <li><b>Jumbo loan</b>—needed when the borrowing amount exceeds the FHFA conforming limit for the area. Because these loans cannot be sold to Fannie Mae or Freddie Mac, lenders carry more risk and usually require larger down payments, lower debt-to-income ratios, and substantial cash reserves. Jumbo rates are often slightly above conforming rates.</li>
        <li><b>Adjustable-rate mortgage (ARM)</b>—written as 5/1, 7/1, or 10/1, meaning the rate is fixed for the first 5, 7, or 10 years and then adjusts once per year based on a market index plus a margin. Adjustments are limited by caps—for example 2% per adjustment, 1% per year, and 5% over the life of the loan (the common &quot;2/1/5&quot; structure). ARMs start roughly 0.5% to 2% below comparable fixed rates, which helps buyers qualify for more home, but they transfer interest-rate risk to the borrower. This calculator computes fixed-rate payments; for an ARM, model the initial fixed period and assume the payment can rise at each cap when planning long term.</li>
      </ul>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">{t('section_headings.howToUse')}</h3>
      <ol className="list-decimal pl-8 space-y-2">
        <li><b>Enter the property details.</b> Start with the home price (or your current loan balance if you already own the home) and the down payment. The calculator converts these into the starting loan amount—price minus down payment.</li>
        <li><b>Set the interest rate and loan term.</b> Use a rate from an actual lender quote rather than a national average, since individual offers vary by credit, points, and property. The 30-year term is the standard; shorter terms carry lower rates but higher monthly payments.</li>
        <li><b>Turn on additional costs.</b> Enable the extra-cost options to include property taxes, home insurance, and HOA fees, and enter them as annual amounts. If your loan requires PMI, add its estimated annual cost as well. The annual percentage-increase fields model inflation on these expenses so the estimate stays realistic over time.</li>
        <li><b>Model extra payments.</b> If your loan allows prepayment, add a recurring extra payment, a one-time lump sum, or a rounded-up payment amount. The results show how much sooner the loan is paid off and how much interest is saved.</li>
        <li><b>Read the payment breakdown.</b> The results separate principal from interest for each payment. Early in the loan most of the payment goes to interest—this is normal for amortizing loans and improves steadily every month.</li>
        <li><b>Compare scenarios.</b> Change the rate, down payment, or term and watch the payment-sensitivity panel update. This makes it easy to see what a rate move, a larger deposit, or a shorter term does to the monthly budget before committing.</li>
      </ol>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">{t('section_headings.example')}</h3>
      <p>Suppose you are buying a $400,000 home with 10% down ($40,000), so you finance $360,000 at 6.5% over 30 years.</p>
      <ul className="list-disc pl-8 space-y-2">
        <li>Convert the rate to a monthly rate: 6.5% ÷ 12 = 0.5417%, or 0.005417. The loan has 30 × 12 = 360 payments.</li>
        <li>Apply the formula: M = 360,000 × [0.005417 × (1.005417)<sup>360</sup>] ÷ [(1.005417)<sup>360</sup> − 1].</li>
        <li>The monthly principal-and-interest payment is approximately <b>$2,276</b>.</li>
        <li>Over 30 years you would repay about $819,000 in total, of which roughly <b>$459,000 is interest</b>.</li>
      </ul>
      <p>The interest rate has an enormous effect on that total. At 7.5%, the same $360,000 loan costs about $2,517 per month—$241 more every month, or close to <b>$87,000 more</b> over the full term. This is why it pays to shop several lenders and to weigh discount points carefully.</p>
      <p>Extra payments compound the benefit. Adding just $200 per month at 6.5% pays the loan off in about 24 years instead of 30 and saves roughly <b>$108,000</b> in interest. Because a 10% down payment is below the 20% threshold, PMI is also required: at typical pricing of 0.5% to 1% of the loan amount per year, that is about $150 to $300 per month until the balance falls to 80% of the home&apos;s value.</p>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">{t('section_headings.tips')}</h3>
      <ul className="list-disc pl-8 space-y-2">
        <li><b>Sharpen your credit profile first.</b> Scores of 740 or higher generally secure the best pricing, and even a 20- to 40-point difference can move the rate by 0.125% to 0.25%. Check your reports for errors, avoid opening new credit, and pay down revolving balances in the months before applying.</li>
        <li><b>Shop multiple lenders within a short window.</b> Mortgage inquiries made within roughly 45 days typically count as a single inquiry for scoring purposes, so request Loan Estimates from three to five lenders—banks, credit unions, and brokers—and compare them side by side.</li>
        <li><b>Lower your debt-to-income ratio.</b> Lenders like the housing payment to stay under about 28% of gross income and total debts under about 36%. Paying off an auto loan or credit cards before applying can raise your approval amount and improve your rate.</li>
        <li><b>Save more for the down payment—but keep reserves.</b> Every extra point of down payment reduces the loan, lowers or removes PMI, and improves pricing. Still, never empty the emergency fund: closing costs, immediate repairs, and moving expenses come due all at once.</li>
        <li><b>Compare APR and total cost, not just the headline rate.</b> A lower rate bought with discount points can cost more upfront. Divide the points cost by the monthly savings to find the break-even; if you expect to sell or refinance before that date, the cheaper rate loses money.</li>
        <li><b>Lock the rate deliberately.</b> Most locks run 30 to 60 days, which should cover closing once under contract. Ask about extensions and whether a float-down option lets you benefit if rates fall while you wait to close.</li>
        <li><b>Weigh a 15-year term.</b> Fifteen-year rates are typically a quarter to a half percent lower than 30-year rates and the total interest is dramatically smaller, but the monthly payment is about 30% to 40% higher. Choose it only if the payment still fits comfortably in the budget.</li>
      </ul>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">Common Mistakes to Avoid</h3>
      <ul className="list-disc pl-8 space-y-2">
        <li><b>Budgeting only for principal and interest.</b> Taxes, insurance, PMI, and HOA dues can add several hundred dollars to the monthly outlay. Always enable the extra-cost options in the calculator so the true payment—not just the lender&apos;s number—fits the budget.</li>
        <li><b>Treating the approval amount as a budget.</b> Prequalification answers one question: how much a lender will lend. It does not account for childcare, travel, retirement savings, or the 1%-plus-per-year maintenance rule. Decide on a comfortable payment independently, then borrow less than the maximum.</li>
        <li><b>Spending every dollar at closing.</b> Buyers who put all their cash into the down payment start homeownership with no buffer. A single HVAC failure or roof repair can then land on a credit card at 20% interest.</li>
        <li><b>Forgetting to cancel PMI.</b> Federal law requires automatic cancellation at 78% of the original value, and you may request cancellation at 80% once the loan is current—but servicers rarely do it for you. Track the balance and submit a written request when you qualify.</li>
        <li><b>Ignoring ARM risk.</b> If you expect to keep the home well past the fixed period, an ARM can reset sharply upward. Model the worst-case capped payment before choosing it.</li>
        <li><b>Skipping the fine print on prepayment penalties and lender credits.</b> Prepayment penalties are uncommon on conforming loans today but do exist on some niche products, and lender credits that lower closing costs permanently raise the rate. Read the Loan Estimate, not just the summary.</li>
        <li><b>Not rechecking rates before closing.</b> Rates move daily, and offers are not final until lock. If market rates fall meaningfully after your lock expires or while you still have time, ask the lender to reprice or shop the loan elsewhere.</li>
      </ul>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">When Refinancing Makes Sense</h3>
      <p>Refinancing replaces your existing mortgage with a new one, usually to capture a lower rate, shorten the term, or access equity. The classic guideline is to refinance when you can cut the rate by at least 0.75% to 1%, but the honest test is the break-even point: divide the closing costs by the monthly savings.</p>
      <p>For example, paying $8,000 in closing costs to move a $300,000 loan from 6.5% to 5.75% saves about $146 per month, so the break-even is roughly 55 months—about four and a half years. If you expect to keep the home longer than that, the refinance pays for itself and saves money thereafter; if you may move sooner, it does not. Our <a href="/financial-calculators/refinance-calculator" className="text-blue-600 dark:text-blue-400 underline">Refinance Calculator</a> runs this comparison for you.</p>
      <p>Two cautions apply. First, refinancing resets the amortization schedule: staying 20 years into a 30-year loan and refinancing into a fresh 30-year term can raise total interest even at a lower rate, so consider a shorter term such as 15 or 20 years. Second, cash-out refinancing typically carries a higher rate and must keep the loan-to-value ratio at or below 80% to avoid PMI—use the proceeds for high-value purposes like eliminating higher-interest debt, not for consumption. To see exactly how extra payments or a shorter term change your payoff date, use the <a href="/financial-calculators/mortgage-payoff-calculator" className="text-blue-600 dark:text-blue-400 underline">Mortgage Payoff Calculator</a> and review your loan&apos;s amortization schedule with the <a href="/financial-calculators/amortization-calculator" className="text-blue-600 dark:text-blue-400 underline">Amortization Calculator</a>.</p>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">{t('section_headings.faq')}</h3>
      <h4 className="font-semibold text-black dark:text-white mt-4">How much house can I afford?</h4>
      <p>A common guideline is to keep total housing costs at or below 28% of gross household income and all debt payments below 36%—the so-called 28/36 rule. Lenders may prequalify you for more, especially with automated underwriting, but a larger approval is not a comfortable budget. Start from the payment you want to live with, not the maximum you can borrow, and confirm it with the <a href="/financial-calculators/house-affordability-calculator" className="text-blue-600 dark:text-blue-400 underline">House Affordability Calculator</a>.</p>
      <h4 className="font-semibold text-black dark:text-white mt-4">Do I need a 20% down payment?</h4>
      <p>No. Conventional loans are available with 3% to 5% down, FHA requires 3.5%, and VA and USDA loans require nothing down for eligible borrowers. However, any down payment below 20% triggers PMI on conventional loans, and a smaller down payment means a larger loan, a higher payment, and less equity if home values fall. Twenty percent remains the fastest way to minimize the total cost of the loan.</p>
      <h4 className="font-semibold text-black dark:text-white mt-4">What is the difference between the interest rate and the APR?</h4>
      <p>The interest rate determines the monthly principal-and-interest payment. The annual percentage rate (APR) folds in points, origination fees, and other financed closing costs to express the yearly cost of the loan as a whole. APR is the better number for comparing offers with different fee structures, but also compare total interest paid over the life of the loan, since APR assumes you keep it for the full term.</p>
      <h4 className="font-semibold text-black dark:text-white mt-4">Is a 15-year mortgage always better than a 30-year?</h4>
      <p>Not always. The 15-year loan carries a lower rate and far less total interest, and it builds equity quickly, but the payment is roughly 30% to 40% higher. If that payment strains the budget, a 30-year loan with extra payments directed at principal often achieves a similar result with more flexibility—borrowers can always pay more, but they cannot pay less when money is tight.</p>
      <h4 className="font-semibold text-black dark:text-white mt-4">How can I pay off my mortgage early?</h4>
      <p>Three reliable methods are making an extra payment each year (a biweekly schedule produces exactly that, 13 monthly payments a year), adding a fixed extra amount every month, and applying windfalls such as bonuses or tax refunds directly to principal. Confirm your loan has no prepayment penalty—rare on conforming loans today—and check how the extra amount is applied so it reduces principal rather than future payments.</p>
      <h4 className="font-semibold text-black dark:text-white mt-4">Should I pay discount points?</h4>
      <p>Points lower your rate in exchange for upfront cash at closing, and each point typically costs 1% of the loan amount and reduces the rate by about 0.25%. Divide the cost of the points by the monthly savings to get the break-even period in months. If you will keep the loan past that point, points save money; if you are likely to sell or refinance sooner, they do not.</p>
      <h4 className="font-semibold text-black dark:text-white mt-4">When does PMI fall off?</h4>
      <p>On a primary-residence conventional loan, PMI cancels automatically once the balance reaches 78% of the home&apos;s original value, and you may request cancellation at 80% once the loan is current and payments are not delinquent. Contact your servicer in writing when you qualify—cancellation is not always automatic at the 80% mark, and waiting can cost hundreds of dollars a month.</p>

      <h3 className="font-bold text-lg text-black dark:text-white mt-6">{t('section_headings.summary')}</h3>
      <p>A mortgage is the largest financial commitment most households ever take on, and small differences in rate, term, and down payment compound into tens of thousands of dollars over the life of the loan. The Mortgage Calculator turns that complexity into clear numbers: enter the price, down payment, rate, and term, layer in taxes, insurance, and PMI, and experiment with extra payments to see exactly how each decision changes the monthly payment and total interest. Use it together with the affordability, refinance, payoff, and amortization calculators linked above, shop at least three lenders using the Loan Estimate form, keep a cash reserve after closing, and revisit the numbers whenever rates or your plans change.</p>
    </div>
  );
}
