import { useTranslations } from 'next-intl';

export function PaymentArticle() {
  const t = useTranslations('articles');
  return (
    <div className="text-[13px] font-sans text-gray-800 leading-relaxed mt-8 space-y-4">
      <p>The Payment Calculator can determine the monthly payment amount or loan term for a fixed interest loan. Use the "Fixed Term" tab to calculate the monthly payment of a fixed-term loan. Use the "Fixed Payments" tab to calculate the time to pay off a loan with a fixed monthly payment. For more information about or to do calculations specifically for car payments, please use the <a href="/financial-calculators/auto-loan-calculator/" className="text-blue-600 underline">Auto Loan Calculator</a>. To find net payment of salary after taxes and deductions, use the <a href="/financial-calculators/salary-calculator/" className="text-blue-600 underline">Take-Home-Pay Calculator</a>.</p>
      
      <p>A loan is a contract between a borrower and a lender in which the borrower receives an amount of money (principal) that they are obligated to pay back in the future. Loans can be customized based on various factors. The number of available options can be overwhelming. Two of the most common deciding factors are the term and monthly payment amount, which are separated by tabs in the calculator above.</p>

      <h3 className="font-bold text-lg text-black mt-6">{t('section_headings.howItWorks')}</h3>
      <p>Mortgages, auto, and many other loans tend to use the time limit approach to the repayment of loans. For mortgages, in particular, choosing to have routine monthly payments between 30 years or 15 years or other terms can be a very important decision because how long a debt obligation lasts can affect a person's long-term financial goals. Some examples include:</p>
      <ul className="list-disc pl-8 space-y-2">
        <li>Choosing a shorter mortgage term because of the uncertainty of long-term job security or preference for a lower interest rate while there is a sizable amount in savings</li>
        <li>Choosing a longer mortgage term in order to time it correctly with the release of Social Security retirement benefits, which can be used to pay off the mortgage</li>
      </ul>
      <p>The Payment Calculator can help sort out the fine details of such considerations. It can also be used when deciding between financing options for a car, which can range from 12 months to 96 months periods. Even though many car buyers will be tempted to take the longest option that results in the lowest monthly payment, the shortest term typically results in the lowest total paid for the car (interest + principal). Car buyers should experiment with the variables to see which term is best accommodated by their budget and situation. For additional information about or to do calculations involving mortgages or auto loans, please visit the <a href="/financial-calculators/mortgage-calculator/" className="text-blue-600 underline">Mortgage Calculator</a> or <a href="/financial-calculators/auto-loan-calculator/" className="text-blue-600 underline">Auto Loan Calculator</a>.</p>

      <h3 className="font-bold text-lg text-black mt-6">{t('section_headings.howItWorks')}</h3>
      <p>This method helps determine the time required to pay off a loan and is often used to find how fast the debt on a credit card can be repaid. This calculator can also estimate how early a person who has some extra money at the end of each month can pay off their loan. Simply add the extra into the "Monthly Pay" section of the calculator.</p>
      <p>It is possible that a calculation may result in a certain monthly payment that is not enough to repay the principal and interest on a loan. This means that interest will accrue at such a pace that repayment of the loan at the given "Monthly Pay" cannot keep up. If so, simply adjust one of the three inputs until a viable result is calculated. Either "Loan Amount" needs to be lower, "Monthly Pay" needs to be higher, or "Interest Rate" needs to be lower.</p>

      <h3 className="font-bold text-lg text-black mt-6">Interest Rate (APR)</h3>
      <p>When using a figure for this input, it is important to make the distinction between interest rate and annual percentage rate (APR). Especially when very large loans are involved, such as mortgages, the difference can be up to thousands of dollars. By definition, the interest rate is simply the cost of borrowing the principal loan amount. On the other hand, APR is a broader measure of the cost of a loan, which rolls in other costs such as broker fees, discount points, closing costs, and administrative fees. In other words, instead of upfront payments, these additional costs are added onto the cost of borrowing the loan and prorated over the life of the loan instead. If there are no fees associated with a loan, then the interest rate equals the APR. For more information about or to do calculations involving APR or Interest Rate, please visit the <a href="/financial-calculators/interest-rate-calculator/" className="text-blue-600 underline">APR Calculator</a> or <a href="/financial-calculators/interest-rate-calculator/" className="text-blue-600 underline">Interest Rate Calculator</a>.</p>
      <p>Borrowers can input both interest rate and APR (if they know them) into the calculator to see the different results. Use interest rate in order to determine loan details without the addition of other costs. To find the total cost of the loan, use APR. The advertised APR generally provides more accurate loan details.</p>

      <h3 className="font-bold text-lg text-black mt-6">{t('section_headings.factors')}</h3>
      <p>When it comes to loans, there are generally two available interest options to choose from: variable (sometimes called adjustable or floating) or fixed. The majority of loans have fixed interest rates, such as conventionally amortized loans like mortgages, auto loans, or student loans. Examples of variable loans include adjustable-rate mortgages, home equity lines of credit (HELOC), and some personal and student loans. For more information about or to do calculations involving any of these other loans, please visit the <a href="/financial-calculators/mortgage-calculator/" className="text-blue-600 underline">Mortgage Calculator</a>, <a href="/financial-calculators/auto-loan-calculator/" className="text-blue-600 underline">Auto Loan Calculator</a>, <a href="/financial-calculators/student-loan-calculator/" className="text-blue-600 underline">Student Loan Calculator</a>, or <a href="/financial-calculators/personal-loan-calculator/" className="text-blue-600 underline">Personal Loan Calculator</a>.</p>

      <h3 className="font-bold text-lg text-black mt-6">Variable Rate Information</h3>
      <p>In variable rate loans, the interest rate may change based on indices such as inflation or the central bank rate (all of which are usually in movement with the economy). The most common financial index that lenders reference for variable rates is the key index rate set by the U.S. Federal Reserve or the London Interbank Offered Rate (Libor).</p>
      <p>Because rates of variable loans vary over time, fluctuations in rates will alter routine payment amounts; the rate change in one month changes the monthly payment due for that month as well as the total expected interest owed over the life of the loan. Some lenders may place caps on variable loan rates, which are maximum limits on the interest rate charged, regardless of how much the index interest rate changes. Lenders only update interest rates periodically at a frequency agreed to by the borrower, most likely disclosed in a loan contract. As a result, a change to an indexed interest rate does not necessarily mean an immediate change to a variable loan's interest rate. Broadly speaking, variable rates are more favorable to the borrower when indexed interest rates are trending downward.</p>
      <p>Credit card rates can be fixed or variable. Credit card issuers aren't required to give advanced notice of an interest rate increase for credit cards with variable interest rates. It is possible for borrowers with excellent credit to request more favorable rates on their variable loans or credit cards. For more information or to perform calculations that involve paying off a credit card, use the <a href="/financial-calculators/credit-card-payoff-calculator/" className="text-blue-600 underline">Credit Card Calculator</a> or use the <a href="/financial-calculators/credit-card-payoff-calculator/" className="text-blue-600 underline">Credit Cards Payoff Calculator</a> for paying off multiple credit cards.</p>
    </div>
  );
}
