import { z } from 'zod'
import type { CalcDef } from './types'

function n(v: string | number | undefined): number { 
  if (typeof v === 'number') return isNaN(v) ? 0 : v; 
  const x = parseFloat(v ?? ''); return isNaN(x) ? 0 : x 
}

export const calcDefsGroup6: Record<string, CalcDef> = {

'roofing-shingle': { schema: z.object({ roofArea: z.string(), shingleType: z.string() }), fields: [{ name: 'roofArea', label: 'Roof Area (sq ft)', step: 100, min: 100 }, { name: 'shingleType', label: 'Shingle Type', type: 'select', options: [{ label: '3-Tab', value: '3-tab' }, { label: 'Architectural', value: 'architectural' }, { label: 'Luxury', value: 'luxury' }] }], compute: (v) => { const area = n(v.roofArea), st = v.shingleType ?? '3-tab'; const coverage: Record<string, number> = { '3-tab': 33.33, architectural: 33.33, luxury: 20 }; const cpg = coverage[st] ?? 33.33; const bundles = Math.ceil(area / cpg); const waste = st === '3-tab' ? 5 : st === 'architectural' ? 10 : 15; const total = Math.ceil(bundles * (1 + waste / 100)); return { result: total, label: 'Shingle Bundles Needed', unit: 'bundles', steps: [`Roof area: ${Math.round(area)} sq ft`, `${st} covers ${cpg} sq ft per bundle`, `Adding ${waste}% waste: ${total} bundles`] } }, description: 'Estimate asphalt shingle bundles for a roof.', formula: 'Bundles = ceil(RoofArea / CoveragePerBundle) × (1 + Waste/100)', interpretation: '3-tab and architectural: 3 bundles per square. Luxury: 5 bundles per square.' },

'stucco-calculator': { schema: z.object({ wallArea: z.string(), numCoats: z.string() }), fields: [{ name: 'wallArea', label: 'Wall Area (sq ft)', step: 1, min: 0 }, { name: 'numCoats', label: 'Number of Coats', step: 1, min: 1, placeholder: '3' }], compute: (v) => { const coats = n(v.numCoats || '3'); const mixBags = Math.ceil(n(v.wallArea) * coats / 80); return { result: mixBags, label: 'Stucco Mix Bags (80 lb)', unit: 'bags', steps: [`Area: ${n(v.wallArea)} sq ft × ${coats} coats`, `Each 80 lb bag covers ~80 sq ft per coat`, `Bags: ~${mixBags}`] } }, description: 'Estimate stucco materials for exterior walls.', formula: 'Bags = ceil(Area × Coats / 80)', interpretation: 'Traditional 3-coat: scratch, brown, finish. Each bag covers ~80 sq ft per coat.' },

'shed-calculator': { schema: z.object({ shedLength: z.string(), shedWidth: z.string(), shedHeight: z.string() }), fields: [{ name: 'shedLength', label: 'Shed Length (ft)', step: 0.5, min: 0 }, { name: 'shedWidth', label: 'Shed Width (ft)', step: 0.5, min: 0 }, { name: 'shedHeight', label: 'Wall Height (ft)', step: 0.5, min: 0, placeholder: '8' }], compute: (v) => { const floorArea = n(v.shedLength) * n(v.shedWidth); const wallArea = 2 * (n(v.shedLength) + n(v.shedWidth)) * (n(v.shedHeight || '8')); return { result: floorArea, label: 'Shed Floor Area', unit: 'sq ft', steps: [`Floor: ${floorArea.toFixed(1)} sq ft`, `Walls: ${wallArea.toFixed(1)} sq ft`] } }, description: 'Estimate shed materials based on dimensions.', formula: 'Floor = L × W, Walls = 2 × (L + W) × H', interpretation: 'Foundation options: gravel pad, concrete slab, or skids.' },

'roof-sheathing': { schema: z.object({ roofArea: z.string(), sheetSize: z.string() }), fields: [{ name: 'roofArea', label: 'Roof Area (sq ft)', step: 100, min: 0 }, { name: 'sheetSize', label: 'Sheet Size', type: 'select', options: [{ label: '4×8 ft (32 sq ft)', value: '32' }, { label: '4×10 ft (40 sq ft)', value: '40' }] }], compute: (v) => { const sheetArea = n(v.sheetSize || '32'); const sheets = Math.ceil(n(v.roofArea) / sheetArea); return { result: sheets, label: 'Sheathing Sheets Needed', unit: 'sheets', steps: [`Roof area: ${n(v.roofArea)} sq ft`, `Each sheet: ${sheetArea} sq ft`, `Sheets: ${sheets}`] } }, description: 'Estimate plywood sheathing needed for roof decking.', formula: 'Sheets = ceil(RoofArea / SheetSize)', interpretation: '4×8 standard. Add 10% for waste on hips and valleys.' },

'gravel-base': { schema: z.object({ length: z.string(), width: z.string(), depth: z.string() }), fields: [{ name: 'length', label: 'Length (ft)', step: 1, min: 0 }, { name: 'width', label: 'Width (ft)', step: 1, min: 0 }, { name: 'depth', label: 'Depth (in)', step: 0.5, min: 1 }], compute: (v) => { const cf = n(v.length) * n(v.width) * (n(v.depth) / 12); const cy = cf / 27; return { result: cy, label: 'Gravel Base Needed', unit: 'cu yd', steps: [`Volume: ${cf.toFixed(2)} cu ft`, `Cubic yards: ${cy.toFixed(3)}`] } }, description: 'Calculate gravel base material volume.', formula: 'CY = (L × W × D/12) / 27', interpretation: 'Compact in 4" lifts. Add 10% for compaction loss.' },

'paver-sand': { schema: z.object({ area: z.string(), depth: z.string() }), fields: [{ name: 'area', label: 'Paver Area (sq ft)', step: 1, min: 0 }, { name: 'depth', label: 'Sand Depth (in)', placeholder: '1', step: 0.25, min: 0.25 }], compute: (v) => { const cf = n(v.area) * (n(v.depth) / 12); const tons = cf * 0.1; return { result: tons, label: 'Paver Sand Needed', unit: 'tons', steps: [`Volume: ${cf.toFixed(2)} cu ft`, `Sand: ${tons.toFixed(2)} tons`] } }, description: 'Estimate paver sand for bedding layer.', formula: 'Tons = (Area × Depth/12) × 100 / 2000', interpretation: 'Sand bedding 1" for paver installation. Compact and screed level.' },

'mulch-coverage': { schema: z.object({ area: z.string(), depth: z.string() }), fields: [{ name: 'area', label: 'Area (sq ft)', step: 1, min: 0 }, { name: 'depth', label: 'Depth (in)', placeholder: '3', step: 0.5, min: 0 }], compute: (v) => { const cf = n(v.area) * (n(v.depth) / 12); const cy = cf / 27; const bags = Math.ceil(cf / 2); return { result: cy, label: 'Mulch Needed', unit: 'cu yd', steps: [`Volume: ${cf.toFixed(2)} cu ft = ${cy.toFixed(2)} cu yd`, `Or ~${bags} bags (2 cu ft each)`] } }, description: 'Estimate mulch volume for garden beds.', formula: 'CY = (Area × Depth/12) / 27', interpretation: 'Apply 2-4" depth for weed suppression and moisture retention.' },

'seed-coverage': { schema: z.object({ lawnArea: z.string(), grassType: z.string() }), fields: [{ name: 'lawnArea', label: 'Lawn Area (sq ft)', step: 100, min: 0 }, { name: 'grassType', label: 'Grass Type', type: 'select', options: [{ label: 'Fescue', value: 'fescue' }, { label: 'Bluegrass', value: 'bluegrass' }, { label: 'Rye', value: 'rye' }, { label: 'Bermuda', value: 'bermuda' }] }], compute: (v) => { const rates: Record<string, number> = { fescue: 8, bluegrass: 3, rye: 10, bermuda: 2 }; const rate = rates[v.grassType] || 8; const lb = +(n(v.lawnArea) / rate).toFixed(1); return { result: lb, label: 'Seed Needed', unit: 'lb', steps: [`Seeding rate: 1 lb per ${rate} sq ft`, `Seed: ${lb} lb`] } }, description: 'Calculate grass seed needed for lawn.', formula: 'Seed lb = Area / SeedingRate', interpretation: 'Apply with spreader. Water daily until germination.' },

'sod-estimate': { schema: z.object({ lawnLength: z.string(), lawnWidth: z.string() }), fields: [{ name: 'lawnLength', label: 'Lawn Length (ft)', step: 1, min: 0 }, { name: 'lawnWidth', label: 'Lawn Width (ft)', step: 1, min: 0 }], compute: (v) => { const area = n(v.lawnLength) * n(v.lawnWidth); const rolls = Math.ceil(area / 10); return { result: rolls, label: 'Sod Rolls Needed', unit: 'rolls', steps: [`Lawn area: ${area.toFixed(1)} sq ft`, `Each roll ~10 sq ft`, `Rolls: ~${rolls}`] } }, description: 'Estimate sod rolls for a lawn.', formula: 'Rolls = ceil(Area / 10)', interpretation: 'Sod by roll (~10 sq ft) or pallet (~450-500 sq ft). Install within 24 hrs.' },

'fence-post-depth': { schema: z.object({ fenceHeight: z.string(), frostDepth: z.string() }), fields: [{ name: 'fenceHeight', label: 'Fence Height (ft)', step: 0.5, min: 0 }, { name: 'frostDepth', label: 'Frost Depth (in)', placeholder: '36', step: 6, min: 0 }], compute: (v) => { const depth = Math.max(n(v.frostDepth || '36'), n(v.fenceHeight) * 12 * 0.33); return { result: depth, label: 'Post Hole Depth', unit: 'in', steps: [`Fence: ${n(v.fenceHeight)} ft tall`, `Min depth: ${depth.toFixed(0)} in (${(depth / 12).toFixed(1)} ft)`] } }, description: 'Calculate fence post hole depth.', formula: 'Depth = max(FrostDepth, FenceHt × 12 × 0.33)', interpretation: '1/3 of post length below ground. Below frost line in cold climates.' },

'stair-runner-length': { schema: z.object({ stairsCount: z.string(), treadRun: z.string(), stairWidth: z.string() }), fields: [{ name: 'stairsCount', label: 'Number of Stairs', step: 1, min: 1 }, { name: 'treadRun', label: 'Tread Depth (in)', placeholder: '11', step: 0.5, min: 0 }, { name: 'stairWidth', label: 'Stair Width (ft)', step: 0.5, min: 0 }], compute: (v) => { const steps = n(v.stairsCount), tread = n(v.treadRun || '11'); const totalInches = steps * tread + 12; return { result: totalInches / 12, label: 'Runner Length Needed', unit: 'ft', steps: [`${steps} treads × ${tread} in = ${(steps * tread).toFixed(1)} in`, `Add 12" for top landing = ${totalInches.toFixed(1)} in = ${(totalInches / 12).toFixed(1)} ft`] } }, description: 'Calculate stair runner carpet length.', formula: 'Length = (Steps × Tread) + 12 / 12', interpretation: 'Measure from top of stairs to bottom tread edge. Add 12" for wrapping top nosing.' },

'handrail-angle': { schema: z.object({ stairRise: z.string(), stairRun: z.string() }), fields: [{ name: 'stairRise', label: 'Total Rise (in)', step: 1, min: 0 }, { name: 'stairRun', label: 'Total Run (in)', step: 1, min: 0 }], compute: (v) => { const angle = Math.atan2(n(v.stairRise), n(v.stairRun)) * 180 / Math.PI; return { result: angle, label: 'Handrail Angle', unit: 'degrees', steps: [`Angle: atan2(${n(v.stairRise)}, ${n(v.stairRun)}) = ${angle.toFixed(1)}°`] } }, description: 'Calculate handrail angle from stair dimensions.', formula: 'θ = arctan(Rise / Run)', interpretation: 'Handrail must be 34-38" above stair nosing per IRC.' },

'railing-post-spacing': { schema: z.object({ railingLength: z.string(), postCount: z.string() }), fields: [{ name: 'railingLength', label: 'Railing Length (ft)', step: 0.5, min: 0 }, { name: 'postCount', label: 'Number of Posts', step: 1, min: 2 }], compute: (v) => { const spacing = n(v.railingLength) / (n(v.postCount) - 1); return { result: spacing, label: 'Post Spacing', unit: 'ft', steps: [`${n(v.railingLength)} ft / ${n(v.postCount) - 1} spans = ${spacing.toFixed(2)} ft OC`] } }, description: 'Calculate railing post spacing.', formula: 'Spacing = Length / (Posts - 1)', interpretation: 'Max post spacing 6 ft per IRC. Closer spacing for heavier rail materials.' },

'deck-beam-span': { schema: z.object({ beamLength: z.string(), beamSize: z.string() }), fields: [{ name: 'beamLength', label: 'Maximum Beam Length (ft)', step: 1, min: 0 }, { name: 'beamSize', label: 'Beam Size', type: 'select', options: [{ label: '2-2×8', value: '2-2x8' }, { label: '2-2×10', value: '2-2x10' }, { label: '2-2×12', value: '2-2x12' }, { label: '3-2×8', value: '3-2x8' }, { label: '3-2×10', value: '3-2x10' }, { label: '3-2×12', value: '3-2x12' }] }], compute: (v) => { const beamSpans: Record<string, number> = { '2-2x8': 6, '2-2x10': 8, '2-2x12': 10, '3-2x8': 8, '3-2x10': 10, '3-2x12': 12 }; const maxSpan = beamSpans[v.beamSize] || 8; const ok = n(v.beamLength) <= maxSpan; return { result: maxSpan, label: 'Max Beam Span', unit: 'ft', steps: [`Beam: ${v.beamSize}, Max span: ${maxSpan} ft`, `${n(v.beamLength)} ft span: ${ok ? 'ADEQUATE' : 'OVERSPANNED — reduce span or upsize beam'}`] } }, description: 'Check deck beam span per IRC.', formula: 'IRC Table R507.5', interpretation: 'Doubled 2×10 spans ~8 ft, 2×12 spans ~10 ft. Depends on joist span and load.' },

'deck-joist-span': { schema: z.object({ joistLength: z.string(), joistSize: z.string(), spacing: z.string() }), fields: [{ name: 'joistLength', label: 'Joist Length (ft)', step: 1, min: 0 }, { name: 'joistSize', label: 'Joist Size', type: 'select', options: [{ label: '2×6', value: '2x6' }, { label: '2×8', value: '2x8' }, { label: '2×10', value: '2x10' }, { label: '2×12', value: '2x12' }] }, { name: 'spacing', label: 'Spacing', type: 'select', options: [{ label: '12" OC', value: '12' }, { label: '16" OC', value: '16' }, { label: '24" OC', value: '24' }] }], compute: (v) => { const spans: Record<string, Record<string, number>> = { '2x6': { '12': 9.5, '16': 8.5, '24': 7 }, '2x8': { '12': 12.5, '16': 11.5, '24': 9.5 }, '2x10': { '12': 16, '16': 14.5, '24': 12 }, '2x12': { '12': 19, '16': 17.5, '24': 14.5 } }; const maxSpan = (spans[v.joistSize] || spans['2x8'])[v.spacing || '16'] || 11.5; const ok = n(v.joistLength) <= maxSpan; return { result: maxSpan, label: 'Max Joist Span', unit: 'ft', steps: [`${v.joistSize} @ ${v.spacing}" OC: max ${maxSpan} ft`, `${n(v.joistLength)} ft: ${ok ? 'ADEQUATE' : 'OVERSPANNED'}`] } }, description: 'Max deck joist span per IRC.', formula: 'IRC Table R507.4', interpretation: 'Spans for #2 SPF. Joist cantilever limited to 1/4 of back span.' },

'roof-ventilation-2': { schema: z.object({ atticArea: z.string() }), fields: [{ name: 'atticArea', label: 'Attic Floor Area (sq ft)', step: 100, min: 0 }], compute: (v) => { const nfa = n(v.atticArea) / 300; return { result: nfa, label: 'Net Free Vent Area', unit: 'sq ft', steps: [`NFA: ${n(v.atticArea)} / 300 = ${nfa.toFixed(2)} sq ft`, `Intake (soffit): ${(nfa / 2).toFixed(2)} sq ft, Exhaust (ridge): ${(nfa / 2).toFixed(2)} sq ft`] } }, description: 'Calculate attic ventilation needs.', formula: 'NFA = AtticArea / 300', interpretation: '1:300 ratio with vapor barrier. 50% intake, 50% exhaust.' },

'gutter-sizing': { schema: z.object({ roofArea: z.string(), rainfall: z.string() }), fields: [{ name: 'roofArea', label: 'Roof Area (sq ft)', step: 100, min: 0 }, { name: 'rainfall', label: 'Rainfall Intensity (in/hr)', placeholder: '3', step: 0.5, min: 0 }], compute: (v) => { const cfm = n(v.roofArea) * (n(v.rainfall || '3') / 12) / 60; return { result: cfm, label: 'Peak Flow Rate', unit: 'CFM', steps: [`Flow: ${cfm.toFixed(2)} CFM`, `5" K-style handles ~2.5 CFM per downspout`] } }, description: 'Size gutters for roof drainage.', formula: 'CFM = RoofArea × Rainfall / 12 / 60', interpretation: '5" K-style gutters handle ~2.5 CFM. Downspouts every 40 ft.' },

'downspout-spacing': { schema: z.object({ gutterLength: z.string() }), fields: [{ name: 'gutterLength', label: 'Gutter Length (ft)', step: 10, min: 0 }], compute: (v) => { const downspouts = Math.ceil(n(v.gutterLength) / 40); return { result: downspouts, label: 'Downspouts Needed', unit: 'downspouts', steps: [`Gutter: ${n(v.gutterLength)} ft`, `Downspouts every 40 ft: ${downspouts}`] } }, description: 'Determine downspout spacing.', formula: 'Downspouts = ceil(GutterLength / 40)', interpretation: 'Place at roof valleys and building corners.' },

'skylight-size': { schema: z.object({ roomArea: z.string(), desiredDaylight: z.string() }), fields: [{ name: 'roomArea', label: 'Room Area (sq ft)', step: 50, min: 0 }, { name: 'desiredDaylight', label: 'Desired Daylight Factor (%)', placeholder: '5', step: 0.5, min: 0 }], compute: (v) => { const glazing = n(v.roomArea) * (n(v.desiredDaylight || '5') / 100); return { result: glazing, label: 'Skylight Glazing Area', unit: 'sq ft', steps: [`Room: ${n(v.roomArea)} sq ft`, `Glazing needed: ${glazing.toFixed(1)} sq ft`, `Typical skylight: 1 per ~50 sq ft of roof`] } }, description: 'Size skylight for desired daylight.', formula: 'Glazing = RoomArea × DaylightFactor / 100', interpretation: 'Daylight factor 2-5% typical. South-facing preferred for passive solar.' },

'door-jamb': { schema: z.object({ doorWidth: z.string(), doorHeight: z.string() }), fields: [{ name: 'doorWidth', label: 'Door Width (ft)', step: 0.5, min: 0 }, { name: 'doorHeight', label: 'Door Height (ft)', step: 0.5, min: 0 }], compute: (v) => { const perimeter = 2 * (n(v.doorWidth) + n(v.doorHeight)) + 3; return { result: perimeter, label: 'Jamb Length Needed', unit: 'linear ft', steps: [`Door: ${n(v.doorWidth)} × ${n(v.doorHeight)} ft`, `Jamb: 2×(W+H)+3 = ${perimeter.toFixed(1)} ft`] } }, description: 'Calculate door jamb material needed.', formula: 'Jamb LF = 2 × (W + H) + 3', interpretation: 'Standard jamb depth: 4-9/16" for 2×4 walls, 6-9/16" for 2×6 walls.' },

'door-header': { schema: z.object({ openingWidth: z.string(), loadBearing: z.string() }), fields: [{ name: 'openingWidth', label: 'Opening Width (ft)', step: 0.5, min: 0 }, { name: 'loadBearing', label: 'Wall Type', type: 'select', options: [{ label: 'Load Bearing', value: 'bearing' }, { label: 'Non-Load Bearing', value: 'nonBearing' }] }], compute: (v) => { const isBearing = v.loadBearing === 'bearing'; const depth = isBearing ? Math.ceil(n(v.openingWidth) * 0.5) * 2 : 4; return { result: depth, label: 'Header Depth', unit: 'in', steps: [`Opening: ${n(v.openingWidth)} ft`, `Header: ${depth} in (${isBearing ? '2-ply' : 'single 2×4'})`] } }, description: 'Size door header per IRC.', formula: 'Bearing header depth ~1" per ft of span', interpretation: '2-2×6 for 6 ft, 2-2×8 for 8 ft, 2-2×10 for 10 ft openings.' },

'window-header': { schema: z.object({ openingWidth: z.string() }), fields: [{ name: 'openingWidth', label: 'Opening Width (ft)', step: 0.5, min: 0 }], compute: (v) => { const depth = Math.ceil(n(v.openingWidth) * 0.5) * 2; return { result: depth, label: 'Min Header Depth', unit: 'in', steps: [`Opening: ${n(v.openingWidth)} ft`, `Header: ${depth} in`] } }, description: 'Size window header per IRC.', formula: 'Header depth ~1" per ft of span', interpretation: 'Same as door headers. Use 2-2×6 for 6ft, 2-2×8 for 8ft openings.' },

'window-trim': { schema: z.object({ windowWidth: z.string(), windowHeight: z.string(), numWindows: z.string() }), fields: [{ name: 'windowWidth', label: 'Window Width (ft)', step: 0.5, min: 0 }, { name: 'windowHeight', label: 'Window Height (ft)', step: 0.5, min: 0 }, { name: 'numWindows', label: 'Number of Windows', step: 1, min: 1 }], compute: (v) => { const perWindow = 2 * (n(v.windowWidth) + n(v.windowHeight)); const total = perWindow * n(v.numWindows); return { result: total, label: 'Trim Length Needed', unit: 'linear ft', steps: [`Per window: 2×(${n(v.windowWidth)}+${n(v.windowHeight)}) = ${perWindow.toFixed(1)} ft`, `${n(v.numWindows)} windows: ${total.toFixed(1)} ft`] } }, description: 'Calculate window trim casing needed.', formula: 'Trim = 2 × (W + H) × Quantity', interpretation: 'Standard casing 2-3/8" or 3-1/2". Add miter allowance for corners.' },

'window-well': { schema: z.object({ windowWidth: z.string(), windowHeight: z.string(), wellDepth: z.string() }), fields: [{ name: 'windowWidth', label: 'Window Width (ft)', step: 0.5, min: 0 }, { name: 'windowHeight', label: 'Window Height (ft)', step: 0.5, min: 0 }, { name: 'wellDepth', label: 'Well Depth (ft)', step: 0.5, min: 0 }], compute: (v) => { const area = (n(v.windowWidth) + 2) * n(v.wellDepth); const gravel = area * 1.5 / 27; return { result: area, label: 'Well Opening Area', unit: 'sq ft', steps: [`Well: ${(n(v.windowWidth) + 2).toFixed(1)} ft × ${n(v.wellDepth)} ft = ${area.toFixed(1)} sq ft`, `Gravel for drainage: ~${gravel.toFixed(2)} cu yd`] } }, description: 'Calculate egress window well size.', formula: 'Area = (WindowWidth + 2) × Depth', interpretation: 'Egress window well must extend 36" from wall per IRC. Include drainage gravel.' },

'door-casing': { schema: z.object({ doorWidth: z.string(), doorHeight: z.string(), numDoors: z.string() }), fields: [{ name: 'doorWidth', label: 'Door Width (ft)', step: 0.5, min: 0 }, { name: 'doorHeight', label: 'Door Height (ft)', step: 0.5, min: 0 }, { name: 'numDoors', label: 'Number of Doors', step: 1, min: 1 }], compute: (v) => { const perDoor = 2 * (n(v.doorWidth) + n(v.doorHeight)) + 3; const total = perDoor * n(v.numDoors); return { result: total, label: 'Casing Length Needed', unit: 'linear ft', steps: [`Per door: ${perDoor.toFixed(1)} ft`, `${n(v.numDoors)} doors: ${total.toFixed(1)} ft`] } }, description: 'Calculate door casing trim needed.', formula: 'Casing = (2×(W+H)+3) × Quantity', interpretation: 'Standard casing width 2-1/4" to 3-1/2". Measure each door individually.' },

'baseboard-length': { schema: z.object({ roomLength: z.string(), roomWidth: z.string(), doorWidth: z.string() }), fields: [{ name: 'roomLength', label: 'Room Length (ft)', step: 1, min: 0 }, { name: 'roomWidth', label: 'Room Width (ft)', step: 1, min: 0 }, { name: 'doorWidth', label: 'Deduct Doorway (ft)', placeholder: '3', step: 0.5, min: 0 }], compute: (v) => { const perimeter = 2 * (n(v.roomLength) + n(v.roomWidth)); const net = perimeter - n(v.doorWidth || '3'); const pieces = Math.ceil(net / 12); return { result: net, label: 'Baseboard Needed', unit: 'linear ft', steps: [`Perimeter: ${perimeter} ft`, `Less door: ${n(v.doorWidth || '3')} ft`, `Net: ${net.toFixed(1)} ft = ${pieces} pieces (12 ft)`] } }, description: 'Calculate baseboard molding length.', formula: 'Baseboard = 2×(L+W) - DoorWidths', interpretation: 'Standard baseboard 3-5" tall in 12-16 ft lengths. Subtract door casing to floor.' },

'chair-rail-height': { schema: z.object({ ceilingHeight: z.string() }), fields: [{ name: 'ceilingHeight', label: 'Ceiling Height (ft)', step: 0.5, min: 0 }], compute: (v) => { const h = n(v.ceilingHeight); const railH = Math.min(48, Math.max(36, h * 12 / 3)); return { result: railH, label: 'Recommended Chair Rail Height', unit: 'in', steps: [`Ceiling: ${h} ft`, `Rail height: ${railH.toFixed(0)} in`] } }, description: 'Determine chair rail height.', formula: 'Height = min(48, max(36, CeilingHt×12/3))', interpretation: 'Traditional chair rail at 1/3 wall height, typically 32-36".' },

'wainscoting-layout': { schema: z.object({ wallLength: z.string(), wallHeight: z.string(), panelWidth: z.string() }), fields: [{ name: 'wallLength', label: 'Wall Length (ft)', step: 1, min: 0 }, { name: 'wallHeight', label: 'Wainscot Height (ft)', step: 0.5, min: 0 }, { name: 'panelWidth', label: 'Panel Width (ft)', placeholder: '2', step: 0.5, min: 0 }], compute: (v) => { const pw = n(v.panelWidth || '2'); const panels = Math.ceil(n(v.wallLength) / pw); const area = n(v.wallLength) * n(v.wallHeight); return { result: panels, label: 'Wainscot Panels Needed', unit: 'panels', steps: [`Wall: ${n(v.wallLength)} ft, panels at ${pw} ft: ${panels}`, `Area: ${area.toFixed(1)} sq ft`] } }, description: 'Layout wainscoting panel count.', formula: 'Panels = ceil(WallLength / PanelWidth)', interpretation: 'Adjust panel width for equal spacing. Include top rail and bottom base.' },

'picture-rail': { schema: z.object({ roomPerimeter: z.string() }), fields: [{ name: 'roomPerimeter', label: 'Room Perimeter (ft)', step: 1, min: 0 }], compute: (v) => { const total = n(v.roomPerimeter); return { result: total, label: 'Picture Rail Length', unit: 'linear ft', steps: [`Room perimeter: ${total} ft, Order ${Math.ceil(total / 12)} pieces (12 ft)`] } }, description: 'Calculate picture rail molding length.', formula: 'Length = RoomPerimeter', interpretation: 'Picture rail installed 6-12" below ceiling. Use corner blocks for inside/outside corners.' },

'shoe-molding': { schema: z.object({ roomLength: z.string(), roomWidth: z.string() }), fields: [{ name: 'roomLength', label: 'Room Length (ft)', step: 1, min: 0 }, { name: 'roomWidth', label: 'Room Width (ft)', step: 1, min: 0 }], compute: (v) => { const total = 2 * (n(v.roomLength) + n(v.roomWidth)); return { result: total, label: 'Shoe Molding Needed', unit: 'linear ft', steps: [`Perimeter: 2×(${n(v.roomLength)}+${n(v.roomWidth)}) = ${total} ft`] } }, description: 'Calculate shoe molding (quarter round) length.', formula: 'Length = 2 × (L + W)', interpretation: 'Shoe molding covers gap between baseboard and floor. Use flexible quarter round for curves.' },

'crown-molding-angle': { schema: z.object({ wallAngle: z.string(), moldingSpring: z.string() }), fields: [{ name: 'wallAngle', label: 'Corner Angle (degrees)', placeholder: '90', step: 1, min: 0 }, { name: 'moldingSpring', label: 'Spring Angle', type: 'select', options: [{ label: '45/45', value: '45' }, { label: '52/38', value: '52' }] }], compute: (v) => { const wallAng = n(v.wallAngle || '90'); const spring = n(v.moldingSpring || '45') * Math.PI / 180; const miter = Math.atan(Math.tan(spring) * Math.cos(wallAng * Math.PI / 360)) * 180 / Math.PI; const bevel = Math.asin(Math.sin(spring) * Math.sin(wallAng * Math.PI / 360)) * 180 / Math.PI; return { result: miter, label: 'Miter Angle', unit: 'degrees', steps: [`Wall angle: ${wallAng}°`, `Miter: ${miter.toFixed(1)}°, Bevel: ${bevel.toFixed(1)}°`] } }, description: 'Calculate crown molding miter and bevel angles.', formula: 'Miter = atan(tan(Spring)×cos(Wall/2)), Bevel = asin(sin(Spring)×sin(Wall/2))', interpretation: 'Standard spring angles: 45/45 or 52/38. Use compound miter saw.' },

'corner-bead': { schema: z.object({ cornerCount: z.string(), cornerHeight: z.string() }), fields: [{ name: 'cornerCount', label: 'Number of Corners', step: 1, min: 1 }, { name: 'cornerHeight', label: 'Wall Height (ft)', step: 0.5, min: 0 }], compute: (v) => { const total = n(v.cornerCount) * n(v.cornerHeight); return { result: total, label: 'Corner Bead Needed', unit: 'linear ft', steps: [`${n(v.cornerCount)} corners × ${n(v.cornerHeight)} ft = ${total} ft`, `Order ${Math.ceil(total / 10)} pieces (10 ft)`] } }, description: 'Calculate corner bead length for drywall.', formula: 'Total = Corners × WallHeight', interpretation: 'Standard 10 ft lengths. Use bullnose bead for rounded corners.' },

'drywall-mud': { schema: z.object({ drywallArea: z.string(), coats: z.string() }), fields: [{ name: 'drywallArea', label: 'Drywall Area (sq ft)', step: 50, min: 0 }, { name: 'coats', label: 'Number of Coats', step: 1, min: 1, placeholder: '3' }], compute: (v) => { const gallons = n(v.drywallArea) * n(v.coats) / 300; return { result: Math.ceil(gallons * 4) / 4, label: 'Joint Compound Needed', unit: 'gallons', steps: [`Area: ${n(v.drywallArea)} sq ft × ${n(v.coats)} coats`, `Coverage: ~300 sq ft/gal per coat`, `Compound: ${(Math.ceil(gallons * 4) / 4).toFixed(2)} gal`] } }, description: 'Estimate drywall joint compound needed.', formula: 'Gallons = Area × Coats / 300', interpretation: 'Standard: 3 coats (tape, fill, finish). 5-gal bucket covers ~500 sq ft.' },

'drywall-tape': { schema: z.object({ drywallArea: z.string() }), fields: [{ name: 'drywallArea', label: 'Drywall Area (sq ft)', step: 50, min: 0 }], compute: (v) => { const rolls = Math.ceil(n(v.drywallArea) / 100); return { result: rolls, label: 'Drywall Tape Rolls Needed', unit: 'rolls (500 ft)', steps: [`Area: ${n(v.drywallArea)} sq ft`, `~1 roll per 100 sq ft of board`, `Rolls: ${rolls}`] } }, description: 'Estimate drywall tape needed.', formula: 'Rolls = ceil(Area / 100)', interpretation: 'Paper tape: 500 ft rolls. Mesh tape: 150-300 ft rolls.' },

'drywall-sheets': { schema: z.object({ wallArea: z.string(), sheetSize: z.string() }), fields: [{ name: 'wallArea', label: 'Total Wall Area (sq ft)', step: 10, min: 0 }, { name: 'sheetSize', label: 'Sheet Size', type: 'select', options: [{ label: '4×8 (32 sq ft)', value: '32' }, { label: '4×10 (40 sq ft)', value: '40' }, { label: '4×12 (48 sq ft)', value: '48' }] }], compute: (v) => { const size = n(v.sheetSize || '32'); const sheets = Math.ceil(n(v.wallArea) / size); return { result: sheets, label: 'Drywall Sheets Needed', unit: 'sheets', steps: [`Area: ${n(v.wallArea)} sq ft`, `Sheet size: ${size} sq ft`, `Sheets: ${sheets} (add 10% waste)`] } }, description: 'Estimate drywall sheet count.', formula: 'Sheets = ceil(Area / SheetSize)', interpretation: '4×8 sheets standard. Use 4×12 for taller walls to reduce horizontal joints.' },

'built-in-shelving': { schema: z.object({ shelfWidth: z.string(), shelfCount: z.string(), shelfDepth: z.string() }), fields: [{ name: 'shelfWidth', label: 'Shelf Width (ft)', step: 1, min: 0 }, { name: 'shelfCount', label: 'Number of Shelves', step: 1, min: 1 }, { name: 'shelfDepth', label: 'Shelf Depth (in)', placeholder: '12', step: 1, min: 0 }], compute: (v) => { const boardFt = n(v.shelfWidth) * n(v.shelfCount) * (n(v.shelfDepth || '12') / 12); return { result: boardFt, label: 'Board Feet Needed', unit: 'bd ft', steps: [`${n(v.shelfCount)} shelves × ${n(v.shelfWidth)} ft = ${(n(v.shelfCount) * n(v.shelfWidth)).toFixed(1)} linear ft`, `Depth: ${n(v.shelfDepth || '12')} in = ${((n(v.shelfDepth || '12')) / 12).toFixed(2)} ft`, `Total: ${boardFt.toFixed(2)} bd ft`] } }, description: 'Calculate lumber for built-in shelves.', formula: 'BoardFt = ShelfWidth × Count × (Depth/12)', interpretation: 'Standard shelf depth: 12" for books, 16" for储物. Use 3/4" plywood or solid lumber.' },

'closet-rod-length': { schema: z.object({ closetWidth: z.string(), rodCount: z.string() }), fields: [{ name: 'closetWidth', label: 'Closet Width (ft)', step: 0.5, min: 0 }, { name: 'rodCount', label: 'Number of Rods', step: 1, min: 1, placeholder: '2' }], compute: (v) => { const total = n(v.closetWidth) * n(v.rodCount); return { result: total, label: 'Closet Rod Length Needed', unit: 'linear ft', steps: [`Closet: ${n(v.closetWidth)} ft × ${n(v.rodCount)} rods = ${total} ft`] } }, description: 'Calculate closet rod length.', formula: 'Length = ClosetWidth × RodCount', interpretation: 'Upper rod ~80" for hanging, lower rod ~40" for folded. Max unsupported span: 4 ft.' },

'garage-shelving': { schema: z.object({ wallLength: z.string(), shelfDepth: z.string(), tierCount: z.string() }), fields: [{ name: 'wallLength', label: 'Wall Length (ft)', step: 1, min: 0 }, { name: 'shelfDepth', label: 'Shelf Depth (in)', placeholder: '18', step: 1, min: 0 }, { name: 'tierCount', label: 'Number of Tiers', step: 1, min: 1, placeholder: '3' }], compute: (v) => { const woodLF = n(v.wallLength) * n(v.tierCount); const area = woodLF * (n(v.shelfDepth || '18') / 12); return { result: area, label: 'Shelf Storage Area', unit: 'sq ft', steps: [`Tiers: ${n(v.tierCount)}, Length: ${n(v.wallLength)} ft`, `Total shelf area: ${area.toFixed(1)} sq ft`] } }, description: 'Plan garage shelving layout.', formula: 'ShelfArea = WallLength × Tiers × (Depth/12)', interpretation: '18-24" deep shelves for garage storage. Heavy items on lower shelves.' },

'workbench-height': { schema: z.object({ userHeight: z.string(), workType: z.string() }), fields: [{ name: 'userHeight', label: 'User Height (ft/inches)', placeholder: '5.10', step: 0.01, min: 0 }, { name: 'workType', label: 'Work Type', type: 'select', options: [{ label: 'General (40%)', value: 'general' }, { label: 'Detail (45%)', value: 'detail' }, { label: 'Heavy (35%)', value: 'heavy' }] }], compute: (v) => { const h = n(v.userHeight); const pct: Record<string, number> = { general: 0.4, detail: 0.45, heavy: 0.35 }; const benchH = h * (pct[v.workType] || 0.4); return { result: benchH, label: 'Recommended Workbench Height', unit: 'ft', steps: [`User height: ${h} ft`, `Work type: ${v.workType}`, `Bench height: ${benchH.toFixed(2)} ft (${(benchH * 12).toFixed(0)} in)`] } }, description: 'Determine ergonomic workbench height.', formula: 'Height = UserHeight × WorkFactor', interpretation: 'General: 40% (30-32"). Detail: 45% (35-38"). Heavy: 35% (28-30").' },

'shop-lighting': { schema: z.object({ shopArea: z.string(), taskType: z.string() }), fields: [{ name: 'shopArea', label: 'Shop Area (sq ft)', step: 50, min: 0 }, { name: 'taskType', label: 'Task Type', type: 'select', options: [{ label: 'General/Storage (30 lm/sqft)', value: 'general' }, { label: 'Medium (50 lm/sqft)', value: 'medium' }, { label: 'Fine (75 lm/sqft)', value: 'fine' }, { label: 'Precision (100 lm/sqft)', value: 'precision' }] }], compute: (v) => { const levels: Record<string, number> = { general: 30, medium: 50, fine: 75, precision: 100 }; const lumens = n(v.shopArea) * (levels[v.taskType] || 50); const fixtures4ft = Math.ceil(lumens / 3200); return { result: fixtures4ft, label: '4-ft LED Fixtures Needed', unit: 'fixtures', steps: [`Area: ${n(v.shopArea)} sq ft, Target: ${levels[v.taskType] || 50} lm/sqft`, `Total lumens: ${lumens.toFixed(0)}`, `4ft LED (~3200 lm each): ${fixtures4ft}`] } }, description: 'Plan shop lighting layout.', formula: 'Fixtures = Area × TargetLumensPerSqFt / LumensPerFixture', interpretation: '4-ft LED shop lights ~3200 lm. 8-10 ft mounting height for even coverage.' },

'parking-stall': { schema: z.object({ vehicleType: z.string(), accessible: z.string() }), fields: [{ name: 'vehicleType', label: 'Vehicle Type', type: 'select', options: [{ label: 'Standard Car', value: 'car' }, { label: 'Truck/SUV', value: 'truck' }, { label: 'Parallel', value: 'parallel' }] }, { name: 'accessible', label: 'Accessible Space?', type: 'select', options: [{ label: 'No', value: 'no' }, { label: 'Yes (ADA)', value: 'ada' }] }], compute: (v) => { const dims: Record<string, { w: number; l: number }> = { car: { w: 9, l: 18 }, truck: { w: 10, l: 20 }, parallel: { w: 8, l: 22 } }; const dim = dims[v.vehicleType] || dims.car; const wAdj = v.accessible === 'ada' ? 4 : 0; return { result: (dim.w + wAdj) * dim.l, label: 'Stall Area', unit: 'sq ft', steps: [`Vehicle: ${v.vehicleType}`, `Dimensions: ${(dim.w + wAdj)} ft × ${dim.l} ft`, `Area: ${(dim.w + wAdj) * dim.l} sq ft`] } }, description: 'Determine parking stall dimensions.', formula: 'Dims per parking code. ADA adds 4 ft access aisle.', interpretation: 'Standard: 9×18 ft. ADA: 12×18 ft (including 4 ft access aisle).' },

'driveway-slope': { schema: z.object({ drivewayLength: z.string(), elevationChange: z.string() }), fields: [{ name: 'drivewayLength', label: 'Driveway Length (ft)', step: 10, min: 0 }, { name: 'elevationChange', label: 'Elevation Change (ft)', step: 0.5, min: 0 }], compute: (v) => { const pct = n(v.drivewayLength) > 0 ? (n(v.elevationChange) / n(v.drivewayLength)) * 100 : 0; return { result: pct, label: 'Driveway Slope', unit: '%', steps: [`Grade change: ${n(v.elevationChange)} ft over ${n(v.drivewayLength)} ft`, `Slope: ${pct.toFixed(1)}%`, `${pct <= 15 ? 'WITHIN LIMITS' : 'EXCEEDS max 15% for residential'}`] } }, description: 'Calculate driveway slope percentage.', formula: 'Slope% = (Rise / Run) × 100', interpretation: 'Max 15% for residential, 8% preferred. Steeper slopes need textured surface.' },

'driveway-thickness': { schema: z.object({ vehicleLoad: z.string(), baseType: z.string() }), fields: [{ name: 'vehicleLoad', label: 'Vehicle Type', type: 'select', options: [{ label: 'Passenger Cars', value: 'car' }, { label: 'Light Trucks', value: 'truck' }, { label: 'Heavy Trucks', value: 'heavy' }] }, { name: 'baseType', label: 'Base Type', type: 'select', options: [{ label: 'Gravel/Compacted Soil', value: 'gravel' }, { label: 'Concrete/Asphalt', value: 'concrete' }] }], compute: (v) => { const loads: Record<string, number> = { car: 4, truck: 5, heavy: 6 }; const base: Record<string, number> = { gravel: 0, concrete: 0.5 }; const thick = (loads[v.vehicleLoad] || 4) + (base[v.baseType] || 0); return { result: thick, label: 'Minimum Slab Thickness', unit: 'in', steps: [`Vehicle: ${v.vehicleLoad}`, `Thickness: ${thick} in`] } }, description: 'Determine driveway slab thickness.', formula: 'Min thickness: 4" car, 5" truck, 6" heavy', interpretation: '4" for cars, 5" for light trucks, 6" for heavy vehicles. Add 1/2" for bonded overlay.' },

'sidewalk-slope': { schema: z.object({ sidewalkLength: z.string(), maxRise: z.string() }), fields: [{ name: 'sidewalkLength', label: 'Sidewalk Length (ft)', step: 10, min: 0 }, { name: 'maxRise', label: 'Max Elevation Change (in)', step: 1, min: 0 }], compute: (v) => { const pct = n(v.sidewalkLength) > 0 ? ((n(v.maxRise) / 12) / n(v.sidewalkLength)) * 100 : 0; return { result: pct, label: 'Sidewalk Slope', unit: '%', steps: [`Rise: ${n(v.maxRise)} in (${(n(v.maxRise) / 12).toFixed(2)} ft) over ${n(v.sidewalkLength)} ft`, `Slope: ${pct.toFixed(2)}%`, `${pct <= 8.33 ? 'ADA COMPLIANT' : 'EXCEEDS ADA max 8.33% (1:12)'}`] } }, description: 'Check sidewalk slope per ADA.', formula: 'Slope% = (Rise / Run) × 100', interpretation: 'ADA max 8.33% (1:12). Max 5% preferred. Landings every 30 ft for changes.' },

'curb-ramp': { schema: z.object({ curbHeight: z.string(), rampLength: z.string() }), fields: [{ name: 'curbHeight', label: 'Curb Height (in)', step: 0.5, min: 0 }, { name: 'rampLength', label: 'Ramp Length (ft)', step: 0.5, min: 0 }], compute: (v) => { const slope = n(v.rampLength) > 0 ? (n(v.curbHeight) / 12) / n(v.rampLength) * 100 : 0; const compliant = slope <= 8.33; return { result: slope, label: 'Ramp Slope', unit: '%', steps: [`Curb: ${n(v.curbHeight)} in, Ramp: ${n(v.rampLength)} ft`, `Slope: ${slope.toFixed(2)}% — ${compliant ? 'ADA OK' : 'TOO STEEP — extend ramp'}`] } }, description: 'Check curb ramp slope per ADA.', formula: 'Slope% = (CurbHeight/12) / RampLength × 100', interpretation: 'ADA max 8.33% for curb ramps. Minimum 36" width with flared sides.' },

'asphalt-tonnage': { schema: z.object({ area: z.string(), depth: z.string() }), fields: [{ name: 'area', label: 'Paving Area (sq ft)', step: 100, min: 0 }, { name: 'depth', label: 'Depth (in)', step: 0.5, min: 0 }], compute: (v) => { const cf = n(v.area) * (n(v.depth) / 12); const tons = cf * 145 / 2000; return { result: Math.ceil(tons * 2) / 2, label: 'Asphalt Tonnage', unit: 'tons', steps: [`Volume: ${cf.toFixed(2)} cu ft`, `Tons: ${tons.toFixed(2)} (order ${Math.ceil(tons * 2) / 2} tons)`] } }, description: 'Calculate asphalt tonnage needed.', formula: 'Tons = (Area × Depth/12) × 145 / 2000', interpretation: 'Asphalt density ~145 lb/cu ft. Compact in 2" lifts. Add 5% for waste.' },

'crushed-stone': { schema: z.object({ length: z.string(), width: z.string(), depth: z.string() }), fields: [{ name: 'length', label: 'Length (ft)', step: 1, min: 0 }, { name: 'width', label: 'Width (ft)', step: 1, min: 0 }, { name: 'depth', label: 'Depth (in)', step: 0.5, min: 1 }], compute: (v) => { const cf = n(v.length) * n(v.width) * (n(v.depth) / 12); const tons = cf * 0.055; return { result: Math.ceil(tons * 2) / 2, label: 'Crushed Stone Needed', unit: 'tons', steps: [`Volume: ${cf.toFixed(2)} cu ft`, `Tons: ${tons.toFixed(2)} (order ${Math.ceil(tons * 2) / 2} tons)`] } }, description: 'Calculate crushed stone tonnage.', formula: 'Tons = L × W × D/12 × 0.055', interpretation: 'Crushed stone ~110 lb/cu ft. #57 stone typical for drainage and base.' },

'topsoil-volume': { schema: z.object({ length: z.string(), width: z.string(), depth: z.string() }), fields: [{ name: 'length', label: 'Length (ft)', step: 1, min: 0 }, { name: 'width', label: 'Width (ft)', step: 1, min: 0 }, { name: 'depth', label: 'Depth (in)', step: 0.5, min: 2 }], compute: (v) => { const cf = n(v.length) * n(v.width) * (n(v.depth) / 12); const cy = cf / 27; return { result: cy, label: 'Topsoil Needed', unit: 'cu yd', steps: [`Volume: ${cf.toFixed(2)} cu ft = ${cy.toFixed(3)} cu yd`, `Covers ~${(cy * 54).toFixed(0)} sq ft at 6" deep`] } }, description: 'Calculate topsoil volume for landscaping.', formula: 'CY = (L × W × D/12) / 27', interpretation: 'One cubic yard covers ~54 sq ft at 6" depth. Add 10% for settling.' },

'survey-baseline': { schema: z.object({ baselineLength: z.string(), tapeTemp: z.string(), calibration: z.string() }), fields: [{ name: 'baselineLength', label: 'Measured Length (ft)', step: 1, min: 0 }, { name: 'tapeTemp', label: 'Tape Temperature (°F)', placeholder: '68', step: 1, min: 0 }, { name: 'calibration', label: 'Calibration Correction (ft)', placeholder: '0', step: 0.001, min: 0 }], compute: (v) => { const tempCorr = n(v.baselineLength) * 0.00000645 * (n(v.tapeTemp || '68') - 68); const total = n(v.baselineLength) + tempCorr + n(v.calibration || '0'); return { result: total, label: 'Corrected Baseline Length', unit: 'ft', steps: [`Temp correction: ${tempCorr.toFixed(4)} ft`, `Calibration: ±${n(v.calibration || '0').toFixed(4)} ft`, `Corrected: ${total.toFixed(4)} ft`] } }, description: 'Apply tape corrections to survey baseline.', formula: 'Corrected = Measured + CTemp + CCal', interpretation: 'Steel tape coefficient: 0.00000645/°F. Apply tension and sag corrections separately.' },

'tape-correction': { schema: z.object({ measuredLength: z.string(), tapeLength: z.string(), actualLength: z.string() }), fields: [{ name: 'measuredLength', label: 'Measured Length (ft)', step: 1, min: 0 }, { name: 'tapeLength', label: 'Nominal Tape Length (ft)', placeholder: '100', step: 1, min: 0 }, { name: 'actualLength', label: 'Actual Tape Length (ft)', placeholder: '100.01', step: 0.01, min: 0 }], compute: (v) => { const corr = n(v.measuredLength) * ((n(v.actualLength || '100.01') - n(v.tapeLength || '100')) / n(v.tapeLength || '100')); return { result: n(v.measuredLength) + corr, label: 'Corrected Distance', unit: 'ft', steps: [`Correction: ${corr.toFixed(4)} ft`, `Corrected: ${(n(v.measuredLength) + corr).toFixed(4)} ft`] } }, description: 'Apply tape calibration correction.', formula: 'Corr = Measured × (Actual - Nominal) / Nominal', interpretation: 'Tapes stretch over time. Use standardized baseline for calibration.' },

'traverse-closure': { schema: z.object({ northing: z.string(), easting: z.string(), closure: z.string() }), fields: [{ name: 'northing', label: 'Δ Northing (ft)', step: 0.01, min: 0 }, { name: 'easting', label: 'Δ Easting (ft)', step: 0.01, min: 0 }, { name: 'closure', label: 'Traverse Perimeter (ft)', step: 1, min: 0 }], compute: (v) => { const err = Math.sqrt(n(v.northing) ** 2 + n(v.easting) ** 2); const precision = n(v.closure) > 0 ? err / n(v.closure) : 0; return { result: err, label: 'Closure Error', unit: 'ft', steps: [`Error: ${err.toFixed(4)} ft`, `Precision: 1:${precision > 0 ? Math.round(1 / precision).toFixed(0) : 'N/A'}`] } }, description: 'Calculate traverse closure accuracy.', formula: 'Error = √(ΔN² + ΔE²), Precision = Error / Perimeter', interpretation: 'Typical survey precision: 1:5000 to 1:10000. Re-measure if precision exceeds 1:3000.' },

'leveling-net': { schema: z.object({ backsight: z.string(), foresight: z.string() }), fields: [{ name: 'backsight', label: 'Backsight (BS) Reading (ft)', step: 0.001, min: 0 }, { name: 'foresight', label: 'Foresight (FS) Reading (ft)', step: 0.001, min: 0 }], compute: (v) => { const diff = n(v.backsight) - n(v.foresight); return { result: diff, label: 'Elevation Difference', unit: 'ft', steps: [`Δ = BS - FS = ${n(v.backsight).toFixed(3)} - ${n(v.foresight).toFixed(3)} = ${diff.toFixed(3)} ft`] } }, description: 'Calculate elevation difference from level readings.', formula: 'ΔH = BS - FS', interpretation: 'Add Δ to benchmark elevation for new point elevation. Close loop within 0.01 ft × √miles.' },

'contour-interval': { schema: z.object({ elevationRange: z.string(), contourCount: z.string() }), fields: [{ name: 'elevationRange', label: 'Total Elevation Range (ft)', step: 10, min: 0 }, { name: 'contourCount', label: 'Number of Contour Lines', step: 1, min: 1 }], compute: (v) => { const interval = n(v.contourCount) > 0 ? n(v.elevationRange) / (n(v.contourCount) - 1) : 0; return { result: interval, label: 'Contour Interval', unit: 'ft', steps: [`Range: ${n(v.elevationRange)} ft, Lines: ${n(v.contourCount)}`, `Interval: ${interval.toFixed(2)} ft`, `Recommend: ${interval < 2 ? '2 ft' : interval < 5 ? '5 ft' : interval < 10 ? '10 ft' : '20 ft'} map`] } }, description: 'Determine contour interval for topographic mapping.', formula: 'Interval = Range / (Lines - 1)', interpretation: 'Standard intervals: 2 ft (flat), 5 ft (moderate), 10-20 ft (steep).' },

'slope-stake': { schema: z.object({ cutFill: z.string(), slopeRatio: z.string(), distance: z.string() }), fields: [{ name: 'cutFill', label: 'Centerline Cut/Fill (ft)', step: 0.5, min: 0 }, { name: 'slopeRatio', label: 'Side Slope Ratio (H:1)', placeholder: '1.5', step: 0.5, min: 0 }, { name: 'distance', label: 'Distance from Centerline (ft)', step: 1, min: 0 }], compute: (v) => { const offset = n(v.distance); const cfs = n(v.slopeRatio || '1.5') * n(v.cutFill); const hingePt = offset + cfs; return { result: hingePt, label: 'Hinge Point Distance', unit: 'ft', steps: [`Cut/fill: ${n(v.cutFill)} ft, Slope: ${n(v.slopeRatio || '1.5')}:1`, `Hinge point: ${offset} + ${cfs.toFixed(2)} = ${hingePt.toFixed(2)} ft`] } }, description: 'Calculate slope stake hinge point.', formula: 'Hinge = Offset + SlopeRatio × CutFill', interpretation: 'Offset from centerline to slope intercept. Set stakes at top of cut or toe of fill.' },

'cut-fill-calc': { schema: z.object({ gridArea: z.string(), gridCount: z.string(), avgCut: z.string(), avgFill: z.string() }), fields: [{ name: 'gridArea', label: 'Grid Cell Area (sq ft)', step: 100, min: 0 }, { name: 'gridCount', label: 'Number of Grid Cells', step: 1, min: 1 }, { name: 'avgCut', label: 'Average Cut Depth (ft)', step: 0.5, min: 0 }, { name: 'avgFill', label: 'Average Fill Depth (ft)', step: 0.5, min: 0 }], compute: (v) => { const cutCY = n(v.gridArea) * n(v.gridCount) * n(v.avgCut) / 27; const fillCY = n(v.gridArea) * n(v.gridCount) * n(v.avgFill) / 27; return { result: cutCY - fillCY, label: 'Net Cut Volume', unit: 'cu yd', steps: [`Cut: ${cutCY.toFixed(2)} CY`, `Fill: ${fillCY.toFixed(2)} CY`, `Net ${cutCY >= fillCY ? 'Cut' : 'Fill'}: ${Math.abs(cutCY - fillCY).toFixed(2)} CY`] } }, description: 'Calculate cut and fill volumes from grid method.', formula: 'V = Area × Count × Depth / 27', interpretation: 'Positive = cut (export), negative = fill (import). Swell factor: 20-30%.' },

'excavation-slope': { schema: z.object({ depth: z.string(), soilType: z.string() }), fields: [{ name: 'depth', label: 'Excavation Depth (ft)', step: 1, min: 0 }, { name: 'soilType', label: 'Soil Type', type: 'select', options: [{ label: 'Type A (stable)', value: 'a' }, { label: 'Type B (moderate)', value: 'b' }, { label: 'Type C (unstable)', value: 'c' }] }], compute: (v) => { const slopes: Record<string, number> = { a: 0.75, b: 1, c: 1.5 }; const s = slopes[v.soilType] || 1; const width = s * n(v.depth); return { result: width, label: 'Slope Width from Edge', unit: 'ft', steps: [`Soil Type ${v.soilType.toUpperCase()}: ${s}:1 slope`, `Width: ${n(v.depth)} ft × ${s} = ${width.toFixed(1)} ft per side`] } }, description: 'Calculate excavation slope width per OSHA.', formula: 'Width = Depth × SlopeRatio', interpretation: 'Type A: 0.75:1, Type B: 1:1, Type C: 1.5:1. Benching required for deep excavations.' },

'trench-safety': { schema: z.object({ depth: z.string(), soilType: z.string(), protectiveSys: z.string() }), fields: [{ name: 'depth', label: 'Trench Depth (ft)', step: 1, min: 0 }, { name: 'soilType', label: 'Soil Type', type: 'select', options: [{ label: 'Type A', value: 'a' }, { label: 'Type B', value: 'b' }, { label: 'Type C', value: 'c' }] }, { name: 'protectiveSys', label: 'Protective System', type: 'select', options: [{ label: 'Sloping', value: 'sloping' }, { label: 'Shoring', value: 'shoring' }, { label: 'Shielding', value: 'shielding' }] }], compute: (v) => { const slopes: Record<string, number> = { a: 0.75, b: 1, c: 1.5 }; const s = slopes[v.soilType] || 1; const width = s * n(v.depth) * 2; const reqProtection = n(v.depth) >= 5; return { result: width, label: 'Top Opening Width', unit: 'ft', steps: [`Depth: ${n(v.depth)} ft, Soil: Type ${v.soilType.toUpperCase()}`, `${v.protectiveSys} selected`, `${reqProtection ? '√ Protection required ≥5 ft' : 'Protection recommended but not required'}`, `Top opening: ${width.toFixed(1)} ft`] } }, description: 'Determine trench protective system requirements per OSHA 1926.652.', formula: 'OSHA 29 CFR 1926 Subpart P', interpretation: 'All trenches ≥5 ft deep require protective system. Spoil pile ≥2 ft from edge.' },

'cofferdam-design': { schema: z.object({ waterDepth: z.string(), cofferdamHeight: z.string(), soilType: z.string() }), fields: [{ name: 'waterDepth', label: 'Water Depth (ft)', step: 1, min: 0 }, { name: 'cofferdamHeight', label: 'Cofferdam Height (ft)', step: 1, min: 0 }, { name: 'soilType', label: 'Soil Type', type: 'select', options: [{ label: 'Sand', value: 'sand' }, { label: 'Clay', value: 'clay' }, { label: 'Rock', value: 'rock' }] }], compute: (v) => { const hydrostatic = 62.4 * n(v.waterDepth); const passive = n(v.soilType === 'rock' ? 500 : v.soilType === 'clay' ? 300 : 200); const totalP = hydrostatic + passive; return { result: totalP, label: 'Lateral Pressure', unit: 'psf', steps: [`Hydrostatic: ${hydrostatic.toFixed(0)} psf`, `Passive soil: ${passive} psf`, `Total: ${totalP.toFixed(0)} psf`] } }, description: 'Cofferdam lateral pressure calculation.', formula: 'P = γw × Hw + PassiveSoil', interpretation: 'Sheet pile design must resist water and soil pressure. Dewatering inside required.' },

'dewatering-flow': { schema: z.object({ permeability: z.string(), headDiff: z.string(), flowPath: z.string(), length: z.string() }), fields: [{ name: 'permeability', label: 'Soil Permeability (ft/day)', step: 0.1, min: 0 }, { name: 'headDiff', label: 'Head Difference (ft)', step: 1, min: 0 }, { name: 'flowPath', label: 'Flow Path Length (ft)', step: 1, min: 0 }, { name: 'length', label: 'Excavation Length (ft)', step: 10, min: 0 }], compute: (v) => { const k = n(v.permeability), dh = n(v.headDiff), L = n(v.flowPath), l = n(v.length); const q = k * dh * l / L * 7.481 * 60; return { result: q, label: 'Dewatering Flow Rate', unit: 'GPM', steps: [`Flow: ${q.toFixed(1)} GPM`, `Pump capacity: ~${Math.ceil(q * 1.5)} GPM (with 50% safety)`] } }, description: 'Estimate dewatering flow rate for excavation.', formula: 'Q = k × ΔH × L / Lpath × 7.481 × 60', interpretation: 'Darcy\'s law for groundwater flow. Install well points or sump pumps.' },

'pile-driving': { schema: z.object({ pileLength: z.string(), pileType: z.string(), soilType: z.string() }), fields: [{ name: 'pileLength', label: 'Pile Length (ft)', step: 5, min: 0 }, { name: 'pileType', label: 'Pile Type', type: 'select', options: [{ label: 'Concrete', value: 'concrete' }, { label: 'Steel H', value: 'steel' }, { label: 'Timber', value: 'timber' }] }, { name: 'soilType', label: 'Soil Type', type: 'select', options: [{ label: 'Sand', value: 'sand' }, { label: 'Clay', value: 'clay' }, { label: 'Mixed', value: 'mixed' }] }], compute: (v) => { const capacities: Record<string, Record<string, number>> = { concrete: { sand: 100, clay: 80, mixed: 90 }, steel: { sand: 80, clay: 60, mixed: 70 }, timber: { sand: 40, clay: 30, mixed: 35 } }; const capPerFt = (capacities[v.pileType] || capacities.concrete)[v.soilType] || 80; const capacity = capPerFt * n(v.pileLength); return { result: capacity, label: 'Estimated Pile Capacity', unit: 'tons', steps: [`Pile: ${v.pileType}, Length: ${n(v.pileLength)} ft`, `Soil: ${v.soilType}, Capacity: ~${capacity.toFixed(0)} tons`] } }, description: 'Estimate driven pile capacity.', formula: 'Capacity = CapacityPerFoot × Length', interpretation: 'Verify with PDA or static load test. Safety factor: 2-3.' },

'drilled-shaft': { schema: z.object({ shaftDiameter: z.string(), shaftLength: z.string(), soilType: z.string() }), fields: [{ name: 'shaftDiameter', label: 'Shaft Diameter (ft)', step: 0.5, min: 0 }, { name: 'shaftLength', label: 'Shaft Length (ft)', step: 5, min: 0 }, { name: 'soilType', label: 'Soil Type', type: 'select', options: [{ label: 'Sand', value: 'sand' }, { label: 'Clay', value: 'clay' }, { label: 'Rock', value: 'rock' }] }], compute: (v) => { const endBearing: Record<string, number> = { sand: 40, clay: 30, rock: 200 }; const skinFriction: Record<string, number> = { sand: 2, clay: 1.5, rock: 5 }; const eb = (Math.PI * (n(v.shaftDiameter) / 2) ** 2) * (endBearing[v.soilType] || 40); const sf = Math.PI * n(v.shaftDiameter) * n(v.shaftLength) * (skinFriction[v.soilType] || 2); const total = eb + sf; return { result: total, label: 'Shaft Capacity', unit: 'tons', steps: [`End bearing: ${eb.toFixed(0)} tons`, `Skin friction: ${sf.toFixed(0)} tons`, `Total: ${total.toFixed(0)} tons`] } }, description: 'Estimate drilled shaft (caisson) capacity.', formula: 'Q = Qend + Qskin = (πD²/4)×qb + (πDL)×qs', interpretation: 'End bearing dominates in rock. Skin friction dominates in sand/clay.' },

'helical-pile': { schema: z.object({ torque: z.string(), helixDiameter: z.string(), helixCount: z.string() }), fields: [{ name: 'torque', label: 'Installation Torque (ft-lb)', step: 500, min: 0 }, { name: 'helixDiameter', label: 'Helix Diameter (in)', placeholder: '12', step: 1, min: 0 }, { name: 'helixCount', label: 'Number of Helices', step: 1, min: 1, placeholder: '2' }], compute: (v) => { const kt = 10; const capacity = n(v.torque) * kt / 2000; return { result: capacity, label: 'Helical Pile Capacity', unit: 'tons', steps: [`Torque: ${n(v.torque)} ft-lb × kt=${kt}`, `Capacity: ${capacity.toFixed(1)} tons (${(capacity * 2000).toFixed(0)} lbs)`] } }, description: 'Estimate helical pile capacity from installation torque.', formula: 'Capacity = Torque × kt / 2000 (kt=10)', interpretation: 'Capacity confirmed by torque correlation factor (kt). Verify with load test.' },

'tieback-anchor': { schema: z.object({ anchorLoad: z.string(), soilStrength: z.string(), bondLength: z.string() }), fields: [{ name: 'anchorLoad', label: 'Design Load (kips)', step: 10, min: 0 }, { name: 'soilStrength', label: 'Soil Strength (psf)', placeholder: '2000', step: 200, min: 0 }, { name: 'bondLength', label: 'Bond Length (ft)', step: 5, min: 0 }], compute: (v) => { const bond = Math.PI * (6 / 12) * n(v.bondLength) * (n(v.soilStrength || '2000') / 144) / 1000; const adequate = bond >= n(v.anchorLoad); return { result: bond, label: 'Anchor Capacity', unit: 'kips', steps: [`Bond: ${bond.toFixed(1)} kips`, `${adequate ? 'ADEQUATE' : 'INADEQUATE — increase bond length'}`, `Load: ${n(v.anchorLoad)} kips`] } }, description: 'Determine tieback anchor bond length.', formula: 'Capacity = π × D × Lbond × SkinFriction', interpretation: '6" drill hole typical. Verify with proof test to 133% of design load.' },

'shotcrete-thickness': { schema: z.object({ wallHeight: z.string(), soilPressure: z.string() }), fields: [{ name: 'wallHeight', label: 'Wall Height (ft)', step: 1, min: 0 }, { name: 'soilPressure', label: 'Soil Pressure (psf)', placeholder: '60', step: 5, min: 0 }], compute: (v) => { const thick = Math.max(4, n(v.wallHeight) * 12 * 0.03 + n(v.soilPressure || '60') / 1000 * 12); return { result: thick, label: 'Minimum Shotcrete Thickness', unit: 'in', steps: [`Height: ${n(v.wallHeight)} ft, Soil: ${n(v.soilPressure || '60')} psf`, `Thickness: ${thick.toFixed(1)} in (min 4 in)`] } }, description: 'Determine shotcrete thickness for slope stabilization.', formula: 't = max(4", H×12×0.03 + p×0.012)', interpretation: '4-6" typical. Wire mesh reinforcement required. Drainage behind shotcrete essential.' },

'grout-consolidation': { schema: z.object({ voidVolume: z.string(), groutStrength: z.string(), wcRatio: z.string() }), fields: [{ name: 'voidVolume', label: 'Void Volume (cu ft)', step: 1, min: 0 }, { name: 'groutStrength', label: 'Target Strength (psi)', placeholder: '3000', step: 500, min: 0 }, { name: 'wcRatio', label: 'W/C Ratio', placeholder: '0.5', step: 0.05, min: 0 }], compute: (v) => { const cementBags = n(v.voidVolume) / 1; const waterGal = cementBags * (n(v.wcRatio || '0.5') || 0.5) * 8.34; return { result: cementBags, label: 'Cement Bags Needed (94 lb)', unit: 'bags', steps: [`Void: ${n(v.voidVolume)} cu ft`, `Cement: ${cementBags.toFixed(0)} bags`, `Water: ${waterGal.toFixed(1)} gal`] } }, description: 'Estimate grout materials for void consolidation.', formula: 'CementBags = VoidVolume / 1 (1 bag = 1 cu ft grout)', interpretation: 'One 94 lb bag cement ≈ 1 cu ft grout. W/C ratio 0.45-0.55 for pumpable grout.' },

'cold-joint': { schema: z.object({ pourDelay: z.string(), surfaceCondition: z.string(), temperature: z.string() }), fields: [{ name: 'pourDelay', label: 'Pour Delay (hours)', step: 1, min: 0 }, { name: 'surfaceCondition', label: 'Surface Condition', type: 'select', options: [{ label: 'Clean Rough', value: 'clean' }, { label: 'Dirty Smooth', value: 'dirty' }] }, { name: 'temperature', label: 'Concrete Temp (°F)', placeholder: '70', step: 5, min: 0 }], compute: (v) => { const risk = n(v.pourDelay) / (n(v.temperature || '70') > 80 ? 2 : n(v.temperature || '70') > 60 ? 3 : 4); const highRisk = risk > (v.surfaceCondition === 'clean' ? 3 : 2); return { result: risk, label: 'Cold Joint Risk Score', unit: '', steps: [`Delay: ${n(v.pourDelay)} hrs at ${n(v.temperature || '70')}°F`, `Score: ${risk.toFixed(1)} — ${highRisk ? 'TREAT AS COLD JOINT' : 'OK to continue pour'}`] } }, description: 'Check concrete cold joint risk between pours.', formula: 'Risk = Delay / SettingTimeFactor', interpretation: 'Cold joint occurs if new concrete placed after initial set. Score > 2 requires treatment.' },

'expansion-joint': { schema: z.object({ slabLength: z.string(), tempRange: z.string() }), fields: [{ name: 'slabLength', label: 'Slab Length (ft)', step: 10, min: 0 }, { name: 'tempRange', label: 'Temperature Range (°F)', placeholder: '70', step: 10, min: 0 }], compute: (v) => { const exp = n(v.slabLength) * 12 * 0.0000055 * (n(v.tempRange || '70')); return { result: Math.ceil(exp * 10) / 10, label: 'Joint Width Needed', unit: 'in', steps: [`Expansion: ${exp.toFixed(3)} in`, `Joint width: ${(Math.ceil(exp * 10) / 10).toFixed(1)} in`] } }, description: 'Determine expansion joint width for concrete.', formula: 'Δ = L × 12 × α × ΔT (α = 5.5×10⁻⁶/°F)', interpretation: 'Joint spacing: 15-20 ft for sidewalks, 10-15 ft for slabs. Fill with compressible filler.' },

'control-joint': { schema: z.object({ slabLength: z.string(), slabThickness: z.string() }), fields: [{ name: 'slabLength', label: 'Slab Length (ft)', step: 5, min: 0 }, { name: 'slabThickness', label: 'Slab Thickness (in)', step: 1, min: 0 }], compute: (v) => { const spacing = Math.min(15, Math.max(8, n(v.slabThickness) * 2.5)); const joints = Math.ceil(n(v.slabLength) / spacing) - 1; return { result: spacing, label: 'Recommended Joint Spacing', unit: 'ft', steps: [`Slab: ${n(v.slabThickness)} in thick`, `Joint spacing: ${spacing.toFixed(0)} ft`, `Joints needed: ${joints >= 0 ? joints : 0}`] } }, description: 'Determine control joint spacing for concrete slabs.', formula: 'Spacing = min(15, max(8, Thickness×2.5)) ft', interpretation: 'Cut joints 1/4 slab depth within 6-12 hrs after finishing. Max spacing: 15 ft.' },

'isolation-joint': { schema: z.object({ columnSize: z.string(), slabArea: z.string() }), fields: [{ name: 'columnSize', label: 'Column Width (in)', step: 1, min: 0 }, { name: 'slabArea', label: 'Slab Area (sq ft)', step: 100, min: 0 }], compute: (v) => { const jointLF = 4 * (n(v.columnSize) / 12); return { result: jointLF, label: 'Isolation Joint Material', unit: 'linear ft', steps: [`Column perimeter: 4 × ${(n(v.columnSize) / 12).toFixed(2)} ft = ${jointLF.toFixed(2)} ft per column`] } }, description: 'Calculate isolation joint material around columns.', formula: 'Joint LF = 4 × ColumnWidth/12', interpretation: 'Isolate columns and walls from slab with 1/2" compressible filler.' },

'waterstop': { schema: z.object({ jointLength: z.string(), waterstopType: z.string(), waterstopSize: z.string() }), fields: [{ name: 'jointLength', label: 'Joint Length (ft)', step: 10, min: 0 }, { name: 'waterstopType', label: 'Waterstop Type', type: 'select', options: [{ label: 'PVC', value: 'pvc' }, { label: 'Bentonite', value: 'bentonite' }, { label: 'Hydrophilic', value: 'hydrophilic' }] }, { name: 'waterstopSize', label: 'Size (in)', type: 'select', options: [{ label: '6"', value: '6' }, { label: '9"', value: '9' }] }], compute: (v) => { const rolls = Math.ceil(n(v.jointLength) / 50); return { result: rolls, label: 'Waterstop Rolls Needed', unit: 'rolls (50 ft)', steps: [`Joint: ${n(v.jointLength)} ft, Type: ${v.waterstopType}, Size: ${v.waterstopSize}"`, `Rolls: ${rolls}`] } }, description: 'Estimate waterstop material for construction joints.', formula: 'Rolls = ceil(JointLength / 50)', interpretation: 'PVC waterstop for movement joints. Bentonite for cold joints. Laps: 4-6".' },

'scaffold-ties': { schema: z.object({ scaffoldHeight: z.string(), scaffoldLength: z.string(), tiePattern: z.string() }), fields: [{ name: 'scaffoldHeight', label: 'Scaffold Height (ft)', step: 5, min: 0 }, { name: 'scaffoldLength', label: 'Scaffold Length (ft)', step: 10, min: 0 }, { name: 'tiePattern', label: 'Tie Pattern', type: 'select', options: [{ label: '6×6 ft', value: '6x6' }, { label: '8×8 ft', value: '8x8' }] }], compute: (v) => { const pt: Record<string, number> = { '6x6': 6, '8x8': 8 }; const s = pt[v.tiePattern] || 6; const ties = Math.ceil((n(v.scaffoldHeight) / s) * (n(v.scaffoldLength) / s + 1)); return { result: ties, label: 'Number of Tie Points', unit: 'ties', steps: [`Height: ${n(v.scaffoldHeight)} ft, Length: ${n(v.scaffoldLength)} ft`, `Pattern: ${v.tiePattern}, Ties: ~${ties}`] } }, description: 'Determine scaffold tie requirements per OSHA.', formula: 'Ties per OSHA 1926.452: 6×6 or 8×8 pattern', interpretation: 'Ties required every 6-8 ft horizontally and vertically. Use wall ties or guying.' },

'fall-protection': { schema: z.object({ workingHeight: z.string(), systemType: z.string(), maxFreeFall: z.string() }), fields: [{ name: 'workingHeight', label: 'Working Height (ft)', step: 5, min: 0 }, { name: 'systemType', label: 'System Type', type: 'select', options: [{ label: 'PFAS (lanyard)', value: 'pfas' }, { label: 'Guardrail', value: 'guardrail' }, { label: 'Safety Net', value: 'safety-net' }] }, { name: 'maxFreeFall', label: 'Max Free Fall (ft)', placeholder: '6', step: 1, min: 0 }], compute: (v) => { const required = n(v.workingHeight) >= 6; const totalFall = n(v.maxFreeFall || '6') + 3.5 + 2; const clearanceOk = n(v.workingHeight) > totalFall; return { result: totalFall, label: 'Total Fall Distance', unit: 'ft', steps: [`System: ${v.systemType}, Height: ${n(v.workingHeight)} ft`, `Total fall: ${totalFall.toFixed(1)} ft`, `${clearanceOk ? '√ Adequate clearance' : 'INSUFFICIENT — increase height or reduce free fall'}`, `${required ? '√ Fall protection required ≥6 ft' : 'No fall protection required by OSHA'}`] } }, description: 'Check fall protection requirements per OSHA 1926.501.', formula: 'TotalFall = FreeFall + D-RingSlip + HarnessStretch', interpretation: 'OSHA requires fall protection at ≥6 ft in construction. PFAS must limit free fall to 6 ft.' },

'ladder-angle': { schema: z.object({ ladderHeight: z.string(), baseDistance: z.string() }), fields: [{ name: 'ladderHeight', label: 'Ladder Height (ft)', step: 1, min: 0 }, { name: 'baseDistance', label: 'Base from Wall (ft)', step: 0.5, min: 0 }], compute: (v) => { const ratio = n(v.ladderHeight) > 0 ? n(v.baseDistance) / n(v.ladderHeight) : 0; const angle = Math.acos(ratio) * 180 / Math.PI; const ok = ratio >= 0.25 && ratio <= 0.286; return { result: angle, label: 'Ladder Angle', unit: 'degrees', steps: [`Set base ${(n(v.ladderHeight) * 0.25).toFixed(1)}-${(n(v.ladderHeight) * 0.286).toFixed(1)} ft from wall`, `Angle: ${angle.toFixed(1)}° — ${ok ? 'SAFE (4:1)' : 'ADJUST position'}`] } }, description: 'Check ladder angle per OSHA 4:1 rule.', formula: 'Base = Height × 0.25 (4:1 ratio)', interpretation: 'For every 4 ft of height, base 1 ft from wall. Optimal angle: 75.5°.' },

'confined-space': { schema: z.object({ spaceVolume: z.string(), oxygenLevel: z.string(), contaminantPct: z.string() }), fields: [{ name: 'spaceVolume', label: 'Space Volume (cu ft)', step: 100, min: 0 }, { name: 'oxygenLevel', label: 'Oxygen Level (%)', placeholder: '20.8', step: 0.1, min: 0 }, { name: 'contaminantPct', label: 'Contaminant (LEL%)', placeholder: '0', step: 1, min: 0 }], compute: (v) => { const o2Ok = n(v.oxygenLevel || '20.8') >= 19.5 && n(v.oxygenLevel || '20.8') <= 23.5; const lelOk = n(v.contaminantPct || '0') < 10; const ventilationCFM = n(v.spaceVolume) * 4 / 60; return { result: ventilationCFM, label: 'Required Ventilation', unit: 'CFM', steps: [`O₂: ${n(v.oxygenLevel || '20.8')}% ${o2Ok ? 'OK' : 'HAZARD'}`, `LEL: ${n(v.contaminantPct || '0')}% ${lelOk ? 'OK' : 'HAZARD'}`, `Ventilation: ${ventilationCFM.toFixed(0)} CFM`] } }, description: 'Evaluate confined space entry requirements per OSHA 1910.146.', formula: 'Ventilation = Volume × 4 ACH / 60', interpretation: 'Permit-required confined space: O₂ 19.5-23.5%, LEL <10%, H₂S <10 ppm, CO <35 ppm.' },

'lockout-tagout': { schema: z.object({ energySources: z.string(), employees: z.string() }), fields: [{ name: 'energySources', label: 'Energy Sources', placeholder: '3', step: 1, min: 1 }, { name: 'employees', label: 'Affected Employees', step: 1, min: 1 }], compute: (v) => { const locks = n(v.energySources) * n(v.employees) * 1.5; const tags = Math.ceil(locks); return { result: tags, label: 'LOTO Equipment Needed', unit: 'tags/locks', steps: [`Sources: ${n(v.energySources)}, Employees: ${n(v.employees)}`, `Locks: ${locks.toFixed(0)}, Tags: ${tags}, Hasps: ${Math.ceil(locks / n(v.employees))}`] } }, description: 'Plan lockout/tagout equipment per OSHA 1910.147.', formula: 'Locks = Sources × Employees × 1.5', interpretation: 'Each authorized employee needs personal lock. Group LOTO for crews. Verify energy isolation.' },

'crane-safety': { schema: z.object({ capacity: z.string(), loadWeight: z.string(), radius: z.string() }), fields: [{ name: 'capacity', label: 'Rated Capacity (tons)', step: 5, min: 0 }, { name: 'loadWeight', label: 'Load Weight (lbs)', step: 100, min: 0 }, { name: 'radius', label: 'Load Radius (ft)', step: 5, min: 0 }], compute: (v) => { const rated = n(v.capacity) * 2000; const pct = rated > 0 ? n(v.loadWeight) / rated * 100 : 0; const ok = pct <= 75; return { result: pct, label: 'Capacity Utilization', unit: '%', steps: [`Load: ${n(v.loadWeight).toFixed(0)} lbs`, `Rated at radius: ${rated.toFixed(0)} lbs (${n(v.capacity)} tons)`, `Usage: ${pct.toFixed(1)}% — ${ok ? 'SAFE' : pct <= 90 ? 'CAUTION' : 'OVERLOAD'}`] } }, description: 'Check crane load capacity per OSHA 1926.1400.', formula: 'Utilization% = Load / RatedCapacity × 100', interpretation: 'Never exceed 75% for lifts. 90% for critical lifts with engineered lift plan.' },

'hoist-speed': { schema: z.object({ liftHeight: z.string(), hoistSpeed: z.string(), acceleration: z.string() }), fields: [{ name: 'liftHeight', label: 'Lift Height (ft)', step: 10, min: 0 }, { name: 'hoistSpeed', label: 'Hoist Speed (fpm)', placeholder: '30', step: 5, min: 0 }, { name: 'acceleration', label: 'Start/Stop Time (sec)', placeholder: '2', step: 0.5, min: 0 }], compute: (v) => { const speed = n(v.hoistSpeed || '30'); const accel = n(v.acceleration || '2'); const totalSec = (n(v.liftHeight) / speed * 60) + accel * 2; return { result: totalSec / 60, label: 'Total Lift Cycle Time', unit: 'minutes', steps: [`Speed: ${speed} fpm, Height: ${n(v.liftHeight)} ft`, `Run time: ${(n(v.liftHeight) / speed * 60).toFixed(1)} sec`, `Cycle: ${(totalSec / 60).toFixed(2)} min`] } }, description: 'Calculate hoist cycle time.', formula: 'Time = Height / Speed × 60 + Accel × 2', interpretation: 'includes acceleration and deceleration. Production hoists: 30-60 fpm typical.' },

'as-built': { schema: z.object({ designElevation: z.string(), asBuiltElevation: z.string(), tolerance: z.string() }), fields: [{ name: 'designElevation', label: 'Design Elevation (ft)', step: 0.01, min: 0 }, { name: 'asBuiltElevation', label: 'As-Built Elevation (ft)', step: 0.01, min: 0 }, { name: 'tolerance', label: 'Tolerance (± ft)', placeholder: '0.1', step: 0.01, min: 0 }], compute: (v) => { const diff = n(v.asBuiltElevation) - n(v.designElevation); const tol = n(v.tolerance || '0.1'); const ok = Math.abs(diff) <= tol; return { result: diff, label: 'Elevation Deviation', unit: 'ft', steps: [`Design: ${n(v.designElevation).toFixed(3)} ft`, `As-built: ${n(v.asBuiltElevation).toFixed(3)} ft`, `Diff: ${diff.toFixed(3)} ft (tol: ±${tol.toFixed(3)})`, `${ok ? 'WITHIN TOLERANCE' : 'OUT OF TOLERANCE — rework required'}`] } }, description: 'Check as-built measurement against design.', formula: 'Deviation = AsBuilt - Design', interpretation: 'Track deviations for construction quality control. Foundation tolerance typically ±0.1 ft.' },

'water-heater-size': { schema: z.object({ householdSize: z.string(), tankType: z.string() }), fields: [{ name: 'householdSize', label: 'Household Size (people)', step: 1, min: 1 }, { name: 'tankType', label: 'Tank Type', type: 'select', options: [{ label: 'Electric', value: 'electric' }, { label: 'Gas', value: 'gas' }, { label: 'Heat Pump', value: 'heat-pump' }, { label: 'Tankless', value: 'tankless' }] }], compute: (v) => { const hh = n(v.householdSize), tankType = v.tankType ?? 'electric'; const fhr = hh * 12 + 20; const tankFactors: Record<string, number> = { electric: 1.0, gas: 1.2, 'heat-pump': 0.9, tankless: 0.5 }; const tf = tankFactors[tankType as keyof typeof tankFactors] ?? 1.0; const adjFHR = Math.round(fhr * tf); return { result: adjFHR, label: 'First Hour Rating', unit: 'gallons (FHR)', steps: [`Base FHR: ${hh}×12+20 = ${fhr}`, `${tankType} factor: ${tf}`, `Adjusted: ${adjFHR} gal`] } }, description: 'Calculate required water heater first-hour rating.', formula: 'FHR = HouseholdSize × 12 + 20', interpretation: 'Match to manufacturer FHR ratings. Gas has faster recovery than electric.' },

'closet-organizer-2': { schema: z.object({ closetWidth: z.string(), closetDepth: z.string(), shelfTiers: z.string() }), fields: [{ name: 'closetWidth', label: 'Closet Width (ft)', step: 1, min: 0 }, { name: 'closetDepth', label: 'Closet Depth (ft)', step: 0.5, min: 0 }, { name: 'shelfTiers', label: 'Shelf Tiers', step: 1, min: 1, placeholder: '3' }], compute: (v) => { const shelfLF = n(v.closetWidth) * n(v.shelfTiers); const rodLF = n(v.closetWidth); const totalArea = n(v.closetWidth) * n(v.closetDepth); return { result: shelfLF, label: 'Shelf Linear Feet', unit: 'linear ft', steps: [`Closet: ${n(v.closetWidth)} ft × ${n(v.closetDepth)} ft`, `Shelf tiers: ${n(v.shelfTiers)}`, `Shelf LF: ${shelfLF} ft, Rod: ${rodLF} ft`] } }, description: 'Plan closet organizer layout.', formula: 'ShelfLF = Width × Tiers', interpretation: 'Design for hanging rods at 80" and 40". Shelf depth: 12-16".' },

'stone-veneer-2': { schema: z.object({ wallArea: z.string(), stoneType: z.string() }), fields: [{ name: 'wallArea', label: 'Wall Area (sq ft)', step: 10, min: 0 }, { name: 'stoneType', label: 'Stone Type', type: 'select', options: [{ label: 'Natural', value: 'natural' }, { label: 'Cultured/Manufactured', value: 'cultured' }] }], compute: (v) => { const coverage = n(v.wallArea); const waste = coverage * 0.1; return { result: coverage + waste, label: 'Stone Veneer to Order', unit: 'sq ft', steps: [`Net area: ${coverage} sq ft`, `Add 10% waste: ${waste.toFixed(1)} sq ft`, `Total: ${(coverage + waste).toFixed(1)} sq ft`] } }, description: 'Calculate stone veneer material needed.', formula: 'Total = Area × 1.1', interpretation: 'Natural stone varies in coverage. Manufactured stone has consistent sizing. Add corner pieces separately.' },

'snow-guard': { schema: z.object({ roofLength: z.string(), roofPitch: z.string(), region: z.string() }), fields: [{ name: 'roofLength', label: 'Roof Length (ft)', step: 5, min: 0 }, { name: 'roofPitch', label: 'Roof Pitch', type: 'select', options: [{ label: '3:12-6:12', value: 'low' }, { label: '7:12-12:12', value: 'medium' }, { label: '>12:12', value: 'steep' }] }, { name: 'region', label: 'Snow Zone', type: 'select', options: [{ label: 'Low (<30 psf)', value: 'low' }, { label: 'Moderate (30-60)', value: 'moderate' }, { label: 'High (>60 psf)', value: 'high' }] }], compute: (v) => { const factors: Record<string, Record<string, number>> = { low: { low: 1, moderate: 2, high: 3 }, moderate: { low: 2, moderate: 3, high: 4 }, high: { low: 3, moderate: 4, high: 5 } }; const rows = (factors[v.region] || factors.moderate)[v.roofPitch] || 2; const total = n(v.roofLength) / rows; return { result: total, label: 'Snow Guards Needed', unit: 'guards', steps: [`Roof: ${n(v.roofLength)} ft, rows at ~${rows} ft spacing`, `Total guards: ~${Math.ceil(total)} per row × ${rows} rows = ${Math.ceil(total) * rows}`] } }, description: 'Estimate snow guard quantity for metal roofs.', formula: 'Rows based on pitch and snow zone; guards every 4-5 ft in row', interpretation: 'Install above eaves, valleys, and obstructions. More rows needed in heavy snow zones.' },

}
