import { notFound } from 'next/navigation'
import { getHubMeta, findCalculator } from '@/lib/hub-data'
import { ClientOnlyPage } from '@/components/ClientOnlyPage'
import { CalculatorRenderer } from '@/components/hub-calculators/CalculatorRenderer'
import { getClusterBySlug, generateClusterMetadata, isClusterSlug } from '@/lib/seo-clusters'
import { getLocale, getTranslations } from 'next-intl/server'
import { routing } from '@/i18n/routing'
import { financialCalculators } from '@calcuniverse/calculator-registry'

const siteUrl = 'https://www.jdcalc.com'

function buildHreflang(baseUrl: string) {
  const path = baseUrl.replace(siteUrl, '')
  const map: Record<string, string> = { 'x-default': `${siteUrl}/en${path}` }
  for (const l of routing.locales) {
    map[l] = `${siteUrl}/${l}${path}`
  }
  return map
}

export async function generateCalculatorMetadata(hubSlug: string, slug: string) {
  const locale = await getLocale()

  if (isClusterSlug(slug)) {
    const cluster = getClusterBySlug(slug)
    const meta = generateClusterMetadata(slug, locale)
    if (meta) {
      if (cluster) {
        const ct = await getTranslations('clusters')
        const variantTitle = ct(`${slug}_title`) !== `${slug}_title` ? ct(`${slug}_title`) : cluster.variant.title
        const variantDesc = ct(`${slug}_description`) !== `${slug}_description` ? ct(`${slug}_description`) : cluster.variant.description
        return {
          ...meta,
          title: variantTitle,
          description: variantDesc,
          openGraph: { ...meta.openGraph, title: variantTitle, description: variantDesc },
          twitter: { ...meta.twitter, title: variantTitle, description: variantDesc },
        }
      }
      return meta
    }
  }

  const calc = await findCalculator(slug, hubSlug, locale) || financialCalculators.find(c => c.slug === slug)
  if (!calc) return { title: 'Calculator Not Found' }

  const title = calc.title
  const description = calc.description
  const url = `${siteUrl}/${locale}/${hubSlug}/${slug}`
  const localeStr = locale === 'en' ? 'en_US' : locale === 'zh-CN' ? 'zh_CN' : `${locale}_${locale.toUpperCase()}`
  const isAutoGenerated = /\d$/.test(slug)
  return {
    title,
    description,
    alternates: { canonical: url, languages: buildHreflang(`${siteUrl}/${hubSlug}/${slug}`) },
    openGraph: { title, description, url, siteName: 'JDCALC.com', type: 'website', locale: localeStr, images: [{ url: `${siteUrl}/api/og/${slug}?locale=${locale}`, width: 1200, height: 630 }] },
    twitter: { card: 'summary_large_image', title, description },
    robots: isAutoGenerated ? { index: false, follow: true } : { index: true, follow: true },
    keywords: calc.keywords?.slice(0, 8).join(', ') || '',
  }
}

export async function CalculatorPageContent({ hubSlug, slug }: { hubSlug: string, slug: string }) {
  const locale = await getLocale()

  const cluster = getClusterBySlug(slug)
  if (cluster) {
    const meta = await getHubMeta(hubSlug)
    if (!meta) notFound()
    const calc = meta.calculators.find(c => c.slug === cluster.primarySlug)
    if (!calc) notFound()
    const clusterCalc = { ...calc, title: cluster.variant.title, description: cluster.variant.description }
    return (
      <ClientOnlyPage>
        <CalculatorRenderer hubSlug={hubSlug} calculator={clusterCalc} />
      </ClientOnlyPage>
    )
  }

  const meta = await getHubMeta(hubSlug, locale)
  if (!meta) notFound()
  const calc = await findCalculator(slug, hubSlug, locale) || financialCalculators.find(c => c.slug === slug) || meta.calculators.find(c => c.slug === slug)
  if (!calc) notFound()

  return (
    <ClientOnlyPage>
      <CalculatorRenderer hubSlug={hubSlug} calculator={calc} />
    </ClientOnlyPage>
  )
}
