import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ salePrice: z.string().min(1, 'Required').refine(v => parseFloat(v) > 0, '>0'), costBasis: z.string().min(1, 'Required').refine(v => parseFloat(v) > 0, '>0'), improvements: z.string().min(1, 'Required').refine(v => parseFloat(v) >= 0, '>=0'), deprecRecapture: z.string().min(1, 'Required').refine(v => parseFloat(v) >= 0, '>=0'), newPropertyPrice: z.string().min(1, 'Required').refine(v => parseFloat(v) > 0, '>0'), stateRate: z.string().min(1, 'Required').refine(v => parseFloat(v) >= 0 && parseFloat(v) <= 15, '0-15') }),
  fields: [{ name: 'salePrice', label: 'Sale Price of Relinquished Property ($)', type: 'number', min: 0, step: '10000' }, { name: 'costBasis', label: 'Original Cost Basis ($)', type: 'number', min: 0, step: '10000' }, { name: 'improvements', label: 'Capital Improvements ($)', type: 'number', min: 0, step: '1000' }, { name: 'deprecRecapture', label: 'Depreciation Recapture ($)', type: 'number', min: 0, step: '1000' }, { name: 'newPropertyPrice', label: 'Replacement Property Price ($)', type: 'number', min: 0, step: '10000' }, { name: 'stateRate', label: 'State Capital Gains Tax Rate (%)', type: 'number', min: 0, max: 15, step: '0.5' }],
  compute: (v) => { const sp = parseFloat(v.salePrice) || 0; const cb = parseFloat(v.costBasis) || 0; const imp = parseFloat(v.improvements) || 0; const dep = parseFloat(v.deprecRecapture) || 0; const npp = parseFloat(v.newPropertyPrice) || 0; const sr = parseFloat(v.stateRate) || 0; const adjustedBasis = cb + imp; const totalGain = sp - adjustedBasis; const fedCapGainsRate = 0.2; const fedDepRecapRate = 0.25; const stateCapGainRate = sr / 100; const boot = Math.max(0, sp - npp); const deferredGain = totalGain - boot; const taxIfSold = (totalGain - dep) * fedCapGainsRate + dep * fedDepRecapRate + totalGain * stateCapGainRate; const taxesWith1031 = boot > 0 ? boot * fedCapGainsRate + dep * fedDepRecapRate : 0; const taxSavings = taxIfSold - taxesWith1031; return { result: taxSavings, label: 'Tax Savings via 1031', unit: '$', steps: [{ label: 'Total Gain', value: `$${totalGain.toFixed(2)}` }, { label: 'Tax if Sold', value: `$${taxIfSold.toFixed(2)}` }, { label: 'Tax with 1031 Exchange', value: `$${taxesWith1031.toFixed(2)}` }, { label: 'Tax Savings', value: `$${taxSavings.toFixed(2)}` }] } },
  description: 'A 1031 exchange allows real estate investors to defer capital gains taxes by reinvesting proceeds from a property sale into a like-kind replacement property.',
  formula: 'Deferred Gain = Total Gain - Boot | Tax Savings = Tax if Sold - Tax with 1031 | Boot = Sale Price - New Property Price',
  interpretation: 'A 1031 exchange defers both federal and state capital gains taxes. To fully defer taxes, the replacement property must be of equal or greater value (no boot received).'
}

export default calcDef
