import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ currentAge: z.string().min(1, 'Required').refine(v => parseInt(v) >= 18 && parseInt(v) <= 80, '18-80'), retirementAge: z.string().min(1, 'Required').refine(v => parseInt(v) >= 30 && parseInt(v) <= 100, '30-100'), currentBalance: z.string().min(1, 'Required').refine(v => parseFloat(v) >= 0, '>=0'), annualContrib: z.string().min(1, 'Required').refine(v => parseFloat(v) >= 0, '>=0'), employerMatch: z.string().min(1, 'Required').refine(v => parseFloat(v) >= 0 && parseFloat(v) <= 100, '0-100'), returnRate: z.string().min(1, 'Required').refine(v => parseFloat(v) >= 0 && parseFloat(v) <= 30, '0-30') }),
  fields: [{ name: 'currentAge', label: 'Current Age', type: 'number', min: 18, max: 80, step: '1' }, { name: 'retirementAge', label: 'Desired Retirement Age', type: 'number', min: 30, max: 100, step: '1' }, { name: 'currentBalance', label: 'Current 401(k) Balance ($)', type: 'number', min: 0, step: '1000' }, { name: 'annualContrib', label: 'Annual Contribution ($)', type: 'number', min: 0, step: '500' }, { name: 'employerMatch', label: 'Employer Match (%)', type: 'number', min: 0, max: 100, step: '0.5' }, { name: 'returnRate', label: 'Expected Annual Return (%)', type: 'number', min: 0, max: 30, step: '0.1' }],
  compute: (v) => { const ca = parseInt(v.currentAge) || 30; const ra = parseInt(v.retirementAge) || 65; const cb = parseFloat(v.currentBalance) || 0; const ac = parseFloat(v.annualContrib) || 0; const emp = parseFloat(v.employerMatch) || 0; const rr = parseFloat(v.returnRate) || 0; const y = Math.max(1, ra - ca); const totalAnnualContrib = ac * (1 + emp / 100); const mr = rr / 100 / 12; const m = y * 12; let fv = cb; if (mr > 0) fv = cb * Math.pow(1 + mr, m) + (totalAnnualContrib / 12) * ((Math.pow(1 + mr, m) - 1) / mr); else fv = cb + totalAnnualContrib * y; const annualIncome4pct = fv * 0.04; return { result: fv, label: 'Projected 401(k) Balance', unit: '$', steps: [{ label: 'Years to Retirement', value: `${y}` }, { label: 'Total Annual Contrib (with match)', value: `$${totalAnnualContrib.toFixed(2)}` }, { label: 'Projected Balance', value: `$${fv.toFixed(2)}` }, { label: 'Est. Annual Income (4% Rule)', value: `$${annualIncome4pct.toFixed(2)}` }] } },
  description: 'A 401(k) is an employer-sponsored retirement savings plan that allows employees to contribute pre-tax dollars, often with employer matching.',
  formula: 'FV = PV(1+r)^n + PMT × ((1+r)^n - 1)/r | 4% Rule: Annual Income = Balance × 0.04',
  interpretation: 'Maximize your 401(k) by contributing at least enough to get the full employer match. The 2025-2026 contribution limit is $23,500 ($31,000 with catch-up for age 50+).'
}

export default calcDef
