// Add 6 missing Math calcDefs
const fs = require('fs');
const fp = 'src/components/hub-calculators/GenericMathCalculator.tsx';
let c = fs.readFileSync(fp, 'utf8');

// Find the closing } of calcDefs object - it's the last occurrence before resolveCalcDef
const idx = c.lastIndexOf('\n}\n');
if (idx < 0) { console.log('ERROR: no closing }'); process.exit(1); }

const entries = `
  '30-60-90-triangle': { schema: z.object({ side: z.string().min(1) }), fields: [{ name: 'side', label: 'Short Side Length', step: '0.1', min: 0 }], defaults: { side: '1' }, compute: (v) => { const s = n(v.side); const hyp = 2 * s; const long = s * Math.sqrt(3); const area = s * long / 2; return { result: hyp, label: 'Hypotenuse', unit: '', steps: ['Short side: ' + s, 'Long side: ' + long.toFixed(3), 'Hypotenuse: ' + hyp.toFixed(3), 'Area: ' + area.toFixed(3)], value: hyp }; }, formula: '30-60-90: sides in ratio 1:sqrt(3):2', description: 'Solve 30-60-90 triangle sides and area.', interpretation: 'Short:long:hypotenuse = 1:sqrt(3):2. Memory: half equilateral triangle.' },
  '45-45-90-triangle': { schema: z.object({ leg: z.string().min(1) }), fields: [{ name: 'leg', label: 'Leg Length', step: '0.1', min: 0 }], defaults: { leg: '1' }, compute: (v) => { const a = n(v.leg); const hyp = a * Math.sqrt(2); const area = a * a / 2; return { result: hyp, label: 'Hypotenuse', unit: '', steps: ['Leg: ' + a, 'Hypotenuse: ' + hyp.toFixed(3), 'Area: ' + area.toFixed(3)], value: hyp }; }, formula: '45-45-90: sides in ratio 1:1:sqrt(2)', description: 'Solve 45-45-90 triangle sides and area.', interpretation: 'Legs equal. Hypotenuse = leg x sqrt(2). Isosceles right triangle.' },
  '2x2-matrix-calculator': { schema: z.object({ a: z.string(), b: z.string(), c: z.string(), d: z.string() }), fields: [{ name: 'a', label: 'a (row1 col1)', step: '1', min: -9999 }, { name: 'b', label: 'b (row1 col2)', step: '1', min: -9999 }, { name: 'c', label: 'c (row2 col1)', step: '1', min: -9999 }, { name: 'd', label: 'd (row2 col2)', step: '1', min: -9999 }], defaults: { a: '1', b: '0', c: '0', d: '1' }, compute: (v) => { const a = n(v.a), b = n(v.b), c = n(v.c), d = n(v.d); const det = a * d - b * c; return { result: det, label: 'Determinant', unit: '', steps: ['|' + a + ' ' + b + '|', '|' + c + ' ' + d + '|', 'det = ' + a + '*' + d + ' - ' + b + '*' + c + ' = ' + det.toFixed(2)], value: det }; }, formula: 'det = ad - bc', description: 'Calculate 2x2 matrix determinant.', interpretation: 'Non-zero determinant means matrix is invertible. det=0 means singular matrix.' },
  '3x3-matrix-calculator': { schema: z.object({ a: z.string(), b: z.string(), c: z.string(), d: z.string(), e: z.string(), f: z.string(), g: z.string(), h: z.string(), i: z.string() }), fields: [{ name: 'a', label: 'a', step: '1', min: -9999 }, { name: 'b', label: 'b', step: '1', min: -9999 }, { name: 'c', label: 'c', step: '1', min: -9999 }, { name: 'd', label: 'd', step: '1', min: -9999 }, { name: 'e', label: 'e', step: '1', min: -9999 }, { name: 'f', label: 'f', step: '1', min: -9999 }, { name: 'g', label: 'g', step: '1', min: -9999 }, { name: 'h', label: 'h', step: '1', min: -9999 }, { name: 'i', label: 'i', step: '1', min: -9999 }], defaults: { a: '1', b: '0', c: '0', d: '0', e: '1', f: '0', g: '0', h: '0', i: '1' }, compute: (v) => { const a=n(v.a),b=n(v.b),c=n(v.c),d=n(v.d),e=n(v.e),f=n(v.f),g=n(v.g),h=n(v.h),i=n(v.i); const det = a*(e*i-f*h)-b*(d*i-f*g)+c*(d*h-e*g); return { result: det, label: 'Determinant', unit: '', steps: ['det = ' + det.toFixed(2)], value: det }; }, formula: 'det = a(ei-fh) - b(di-fg) + c(dh-eg)', description: 'Calculate 3x3 matrix determinant.', interpretation: 'Sarrus rule or cofactor expansion. det=0 if matrix is singular.' },
  '30-60-90-calc': { schema: z.object({ side: z.string().min(1) }), fields: [{ name: 'side', label: 'Short Side Length', step: '0.1', min: 0 }], defaults: { side: '1' }, compute: (v) => { const s = n(v.side); const hyp = 2 * s; const long = s * Math.sqrt(3); const area = s * long / 2; return { result: hyp, label: 'Hypotenuse', unit: '', steps: ['Short side: ' + s, 'Long side: ' + long.toFixed(3), 'Hypotenuse: ' + hyp.toFixed(3), 'Area: ' + area.toFixed(3)], value: hyp }; }, formula: '30-60-90: sides in ratio 1:sqrt(3):2', description: 'Solve 30-60-90 triangle sides and area.', interpretation: 'Short:long:hypotenuse = 1:sqrt(3):2.' },
  '45-45-90-calc': { schema: z.object({ leg: z.string().min(1) }), fields: [{ name: 'leg', label: 'Leg Length', step: '0.1', min: 0 }], defaults: { leg: '1' }, compute: (v) => { const a = n(v.leg); const hyp = a * Math.sqrt(2); const area = a * a / 2; return { result: hyp, label: 'Hypotenuse', unit: '', steps: ['Leg: ' + a, 'Hypotenuse: ' + hyp.toFixed(3), 'Area: ' + area.toFixed(3)], value: hyp }; }, formula: '45-45-90: sides in ratio 1:1:sqrt(2)', description: 'Solve 45-45-90 triangle sides and area.', interpretation: 'Legs equal. Hypotenuse = leg x sqrt(2).' },
`;

c = c.substring(0, idx) + entries + c.substring(idx);
fs.writeFileSync(fp, c);
console.log('Added 6 math entries');
