const fs = require('fs');

const PHYSICS_SLUGS = [
  ['projectile-calc','Projectile motion range and time of flight','m','R = v^2 sin(2a)/g','Initial velocity and launch angle determine range.'],
  ['circular-motion','Circular motion speed and acceleration','m/s','v = 2pir/T, a = v^2/r','Constant speed but changing direction produces centripetal acceleration.'],
  ['friction-force','Friction force between surfaces','N','f = uN','Friction opposes relative motion between surfaces in contact.'],
  ['inclined-plane','Force components on an incline','N','F = mg sin(a)','Component of weight acting parallel to the inclined surface.'],
  ['wave-speed','Wave propagation speed','m/s','v = fL','Speed of wave equals frequency times wavelength.'],
  ['sound-intensity','Sound intensity at distance','W/m^2','I = P/(4pir^2)','Sound power spreads spherically from source.'],
  ['electric-field','Electric field from point charge','N/C','E = kq/r^2','Coulomb field surrounding electric charge.'],
  ['capacitor-cylindrical','Cylindrical capacitor capacitance','F','C = 2pi e0 L / ln(b/a)','Capacitance depends on length and radius ratio.'],
  ['capacitor-spherical','Spherical capacitor capacitance','F','C = 4pi e0 ab/(b-a)','Spherical shell capacitance formula.'],
  ['rlc-parallel','Parallel RLC resonant frequency','Hz','f = 1/(2pi sqrt(LC))','Parallel resonance has maximum impedance at f0.'],
  ['ac-power','AC power with power factor','W','P = VI cos(phi)','Real power accounts for phase between voltage and current.'],
  ['magnetic-field-wire','Magnetic field near straight wire','T','B = u0 I/(2pi r)','Ampere law for current-carrying wire.'],
  ['magnetic-field-loop','Magnetic field at loop center','T','B = u0 I/(2R)','Field at center of current-carrying loop.'],
  ['magnetic-field-solenoid','Solenoid magnetic field','T','B = u0 n I','Uniform field inside ideal solenoid.'],
  ['faraday-law','Faraday induction EMF','V','emf = -N d(Phi)/dt','Changing magnetic flux induces electromotive force.'],
  ['mutual-inductance','Mutual inductance between coils','H','M = N2 Phi2 / I1','Coupling coefficient between transformer windings.'],
  ['self-inductance','Self-inductance of coil','H','L = N Phi / I','Inductance opposes changes in current.'],
  ['magnetic-force-charge','Magnetic force on moving charge','N','F = qvB sin(a)','Lorentz force on charged particle in magnetic field.'],
  ['hall-voltage','Hall effect voltage','V','Vh = IB/(nqd)','Transverse voltage from charge carrier deflection.'],
  ['mass-spectrometer','Mass spectrometer radius','m','r = mv/(qB)','Particles separated by mass-to-charge ratio.'],
  ['cyclotron-frequency','Cyclotron frequency','Hz','fc = qB/(2pi m)','Frequency of charged particle in uniform magnetic field.'],
  ['snells-law','Snell law refraction angle','deg','n1 sin(a1) = n2 sin(a2)','Light bends when crossing between different media.'],
  ['critical-angle','Total internal reflection angle','deg','ac = arcsin(n2/n1)','Angle beyond which light reflects entirely internally.'],
  ['thin-lens','Thin lens image distance','m','1/f = 1/do + 1/di','Lens equation relating focal and image distances.'],
  ['lens-makers','Lens maker power','m^-1','P = (n-1)(1/R1 - 1/R2)','Focal power depends on curvature and refractive index.'],
  ['two-lens-system','Two lens system power','m^-1','P = P1 + P2 - d P1 P2','Combined power of separated optical elements.'],
  ['compound-microscope','Microscope magnification','','M = L x 25/(fo fe)','Total magnification is objective times eyepiece magnification.'],
  ['astronomical-telescope','Telescope angular magnification','','M = fo/fe','Ratio of objective to eyepiece focal lengths.'],
  ['diffraction-single','Single slit diffraction angle','rad','sin(a) = L/w','First minimum angle for single slit diffraction pattern.'],
  ['diffraction-double','Double slit fringe spacing','rad','d sin(a) = mL','Young experiment interference fringe separation.'],
  ['diffraction-grating','Diffraction grating angle','rad','d sin(a) = mL','Grating equation for constructive interference maxima.'],
  ['bragg-diffraction','Bragg crystal diffraction','m','2d sin(a) = nL','X-ray diffraction from crystal lattice planes.'],
  ['rayleigh-criterion','Rayleigh resolution limit','rad','amin = 1.22 L/D','Minimum angular separation for optical resolution.'],
  ['blackbody-radiation','Stefan-Boltzmann power','W/m^2','j = s T^4','Blackbody radiation power per unit area.'],
  ['photoelectric-effect','Photoelectron kinetic energy','eV','K = hf - phi','Einstein photoelectric effect equation for emitted electron energy.'],
  ['compton-scattering','Compton wavelength shift','m','dL = h/(mc)(1 - cos(a))','Photon wavelength increase after scattering from electron.'],
  ['bohr-atom','Bohr hydrogen energy level','eV','En = -13.6/n^2','Electron energy in hydrogen atom for principal quantum number n.'],
  ['quantum-tunneling','Quantum tunneling probability','','T ~ exp(-2ka)','Particle penetration through potential barrier.'],
  ['heisenberg-uncertainty','Heisenberg position-momentum uncertainty','','dx dp >= hbar/2','Fundamental limit on simultaneous measurement precision.'],
  ['schrodinger-1d','Infinite square well energy','eV','En = n^2 h^2/(8mL^2)','Particle in a one-dimensional infinite potential well.'],
  ['schrodinger-finite','Finite well bound states','','N ~ floor(sqrt(2mV0)L/(pi hbar)) + 1','Number of bound states in finite potential well.'],
  ['harmonic-oscillator-qm','Quantum harmonic oscillator energy','J','En = (n+1/2) hbar w','Equally spaced energy levels of quantum oscillator.'],
  ['hydrogen-atom-energy','Hydrogen atom orbital energy','eV','En = -13.6/n^2','Energy eigenvalue for hydrogen atom wavefunction.'],
  ['zeeman-effect','Zeeman splitting energy','eV','dE = uB B','Spectral line splitting in external magnetic field.'],
  ['fine-structure','Fine structure correction','eV','dE = a^2 En (1/(j+1/2) - 3/(4n))/n','Relativistic and spin-orbit corrections to atomic levels.'],
  ['selection-rules','Dipole selection rule check','','dl = +/-1, dj = 0, +/-1','Allowed transitions require parity change.'],
  ['nuclear-binding','Nuclear binding energy','MeV','BE = (Zmp+Nmn-mnuc)c^2','Energy holding nucleus together. Peak at Fe-56.'],
  ['radioactive-decay','Radioactive decay activity','Bq','A = l N0 exp(-lt)','Exponential decay law for radioactive substances.'],
  ['carbon-dating','Radiocarbon dating age','years','t = -1/l ln(N/N0)','Determining age from carbon-14 remaining fraction.'],
  ['alpha-decay','Alpha decay energy','MeV','Q = (mp-md-ma)c^2','Energy released when nucleus emits alpha particle.'],
  ['beta-decay','Beta decay energy','MeV','Q = (mp-md)c^2','Energy released in beta-minus or beta-plus decay.'],
  ['gamma-decay','Gamma ray energy','MeV','Eg = Ei - Ef','Energy of photon emitted from excited nuclear state.'],
  ['nuclear-fission','Fission energy release','MeV','E = A x BE/A','Energy from splitting heavy nuclei. ~200 MeV/fission.'],
  ['nuclear-fusion','Fusion energy release','J','E = dm c^2','Energy from combining light nuclei. Powers stars.'],
  ['mass-energy','Mass-energy equivalence','J','E = mc^2','Einstein equivalence relating mass and energy.'],
  ['time-dilation','Relativistic time dilation','s','t = t0/sqrt(1-v^2/c^2)','Moving clocks run slow relative to stationary observer.'],
  ['length-contraction','Relativistic length contraction','m','L = L0 sqrt(1-v^2/c^2)','Moving objects contract along direction of motion.'],
  ['relativistic-momentum','Relativistic momentum','kg m/s','p = mv/sqrt(1-v^2/c^2)','Momentum approaches infinity as speed approaches light speed.'],
  ['relativistic-energy','Relativistic total energy','J','E = mc^2/sqrt(1-v^2/c^2)','Total energy including rest and kinetic components.'],
  ['lorentz-transformation','Lorentz coordinate transform','m','x_prime = (x-vt)/sqrt(1-v^2/c^2)','Space-time coordinate transformation between inertial frames.'],
  ['velocity-addition','Relativistic velocity addition','m/s','w = (u+v)/(1+uv/c^2)','Velocity sum ensuring result never exceeds light speed.'],
  ['twin-paradox','Twin paradox traveling time','years','t = 2d/v sqrt(1-v^2/c^2)','Traveling twin ages less than earthbound twin.'],
  ['gravitational-force','Newtonian gravitational force','N','F = G m1 m2 / r^2','Universal gravitation between two masses.'],
  ['gravitational-potential','Gravitational potential','J/kg','V = -GM/r','Potential energy per unit mass in gravitational field.'],
  ['gauss-gravity','Gauss law for gravity','N m^2/kg','g = -4pi G Menc','Gravitational flux through closed surface.'],
  ['kepler-third','Kepler third law period','s','T = 2pi sqrt(a^3/(GM))','Orbital period squared proportional to semi-major axis cubed.'],
  ['orbital-velocity','Circular orbital velocity','m/s','v = sqrt(GM/r)','Speed required for circular orbit at radius r.'],
  ['lagrange-points','Lagrange L1 point distance','m','L1 ~ R (m2/(3m1))^(1/3)','Equilibrium point between two gravitational bodies.'],
  ['hohmann-transfer','Hohmann transfer time','s','t = pi sqrt((r1+r2)^3/(8GM))','Minimum energy transfer between two circular orbits.'],
  ['rocket-equation','Tsiolkovsky rocket delta-v','m/s','dv = ve ln(m0/mf)','Rocket velocity change from propellant mass ejection.'],
  ['specific-impulse','Rocket specific impulse','s','Isp = F/(mdot g0)','Measure of rocket engine propellant efficiency.'],
  ['thrust-to-weight','Thrust to weight ratio','','T/W = F/(m g0)','Ratio determining if vehicle can lift off.'],
  ['atmospheric-drag','Atmospheric drag force','N','Fd = 0.5 rho v^2 Cd A','Drag force from air resistance on moving object.'],
  ['terminal-velocity','Terminal velocity','m/s','vt = sqrt(2mg/(rho Cd A))','Speed where air drag equals gravitational force.'],
  ['buoyancy-force','Archimedes buoyant force','N','Fb = rho g V','Upward force on object submerged in fluid.'],
  ['fluid-pressure','Hydrostatic fluid pressure','Pa','P = rho g h','Pressure increases linearly with depth in fluid.'],
  ['pascals-principle','Pascal hydraulic force','N','F2 = F1 A2 / A1','Force multiplication in confined hydraulic system.'],
  ['bernoulli-equation','Bernoulli stagnation pressure','Pa','P0 = P + 0.5 rho v^2','Total pressure sum of static and dynamic components.'],
  ['poiseuille-flow','Poiseuille pipe flow rate','m^3/s','Q = pi dP r^4/(8 n L)','Viscous flow rate through cylindrical pipe.'],
  ['stokes-law','Stokes drag on sphere','N','Fd = 6pi n r v','Viscous drag force on sphere at low Reynolds number.'],
  ['venturi-effect','Venturi throat velocity','m/s','A1 v1 = A2 v2','Fluid accelerates through constricted pipe section.'],
  ['torricellis-law','Torricelli efflux speed','m/s','v = sqrt(2gh)','Fluid exit velocity from tank opening at depth h.'],
  ['reynolds-number','Reynolds number','','Re = rho v L / mu','Ratio of inertial to viscous forces in fluid flow.'],
  ['drag-coefficient','Drag coefficient from force','','Cd = 2Fd/(rho v^2 A)','Dimensionless drag parameter for aerodynamic shape.'],
  ['lift-coefficient','Lift coefficient from force','','Cl = 2FL/(rho v^2 A)','Dimensionless lift parameter for airfoil shape.'],
  ['thermodynamic-process','Isothermal work','J','W = nRT ln(V2/V1)','Work done in isothermal expansion of ideal gas.'],
  ['ideal-gas-law','Ideal gas law temperature','K','PV = nRT','Relation between pressure volume temperature and moles.'],
  ['kinetic-theory','Gas RMS molecular speed','m/s','vrms = sqrt(3kT/m)','Root mean square speed of gas molecules.'],
  ['maxwell-boltzmann','Most probable molecular speed','m/s','vp = sqrt(2kT/m)','Peak of Maxwell-Boltzmann molecular speed distribution.'],
  ['heat-engine','Heat engine thermal efficiency','','eff = 1 - Qc/Qh','Ratio of net work output to heat input.'],
  ['carnot-cycle','Carnot cycle efficiency','','eff = 1 - Tc/Th','Maximum theoretical efficiency between two temperatures.'],
  ['otto-cycle','Otto cycle efficiency','','eff = 1 - 1/r^(g-1)','Gasoline engine thermodynamic cycle efficiency.'],
  ['diesel-cycle','Diesel cycle efficiency','','eff = 1 - (rc^g-1)/(g(rc-1)r^(g-1))','Compression ignition engine cycle efficiency.'],
  ['brayton-cycle','Brayton cycle efficiency','','eff = 1 - 1/rp^((g-1)/g)','Gas turbine engine thermodynamic efficiency.'],
];

const SPORTS_SLUGS = [
  ['situp-calc','Sit-up test score','reps','N_reps in 60s','Sit-up performance metric for fitness assessment.'],
  ['pushup-calc','Push-up test score','reps','N_reps in 60s','Push-up endurance test for upper body strength.'],
  ['plank-calc','Plank hold time score','s','Hold time','Core endurance time-based fitness metric.'],
  ['broad-jump-calc','Standing broad jump distance','cm','Jump distance','Lower body power field test measurement.'],
  ['medicine-ball-calc','Medicine ball throw distance','m','Throw distance','Upper body power test using weighted ball.'],
  ['shuttle-run-calc','Shuttle run agility time','s','Run time','Multi-directional speed and agility test.'],
  ['cooper-test-calc','Cooper 12-minute run distance','m','Distance in 12 min','Aerobic fitness test measuring distance covered in 12 minutes.'],
  ['rockport-calc','Rockport walking test VO2max','mL/kg/min','VO2max = 132.853 - 0.0769W - 0.3877A + 6.315G - 3.2649T - 0.1565HR','One-mile walk test for cardiovascular fitness estimation.'],
  ['queens-step-calc','Queens College step test','mL/kg/min','VO2max = 65.81 - 0.1847HR','Step test for aerobic capacity estimation.'],
  ['ymca-step-calc','YMCA bench step test','mL/kg/min','YMCA step protocol','Submaximal step test for cardiovascular fitness.'],
  ['cycling-fitness-calc','Cycling fitness test','mL/kg/min','Astrand cycle protocol','Aerobic power assessment on cycle ergometer.'],
  ['rowing-fitness-calc','Rowing ergometer test','W','Power = distance/time','Rowing performance metric for power output.'],
  ['triathlon-pace-calc','Triathlon pace calculator','min/km','Pace = time/distance','Pace calculation for swim bike run legs.'],
  ['running-pace','Running pace per km','min/km','Pace = time/distance','Pace based on distance and time for running.'],
  ['half-marathon-pace','Half marathon pace projection','min/km','Pace = target time/21.1','Pace needed to achieve target half marathon time.'],
  ['marathon-pace','Marathon pace projection','min/km','Pace = target time/42.2','Pace needed to achieve target marathon finish time.'],
  ['5k-pace','5K race pace','min/km','Pace = target time/5','Pace and finish time for 5 kilometer race.'],
  ['10k-pace','10K race pace','min/km','Pace = target time/10','Pace and finish time for 10 kilometer race.'],
  ['vo2max-running','VO2max from race performance','mL/kg/min','VO2max = 0.2v + 3.5','Estimated maximal oxygen uptake from running performance.'],
  ['heart-rate-zones','Heart rate training zones','bpm','HRzone = HRmax x %','Target heart rate ranges for different exercise intensities.'],
  ['max-heart-rate','Maximum heart rate estimation','bpm','HRmax = 208 - 0.7A','Age-predicted maximal heart rate formula.'],
  ['heart-rate-recovery','Heart rate recovery','bpm','HRR = HRpeak - HR1min','One-minute heart rate drop after peak exercise.'],
  ['cycling-speed','Cycling speed from power','km/h','v = P/(Froll + Faero)','Speed achieved for given power output on flat terrain.'],
  ['cycling-power','Cycling power from speed','W','P = Frollv + Faerov','Power required to maintain given cycling speed.'],
  ['cadence-calc','Cycling cadence','rpm','Cadence = 60/T','Pedal revolutions per minute calculation.'],
  ['swimming-pace','Swimming pace per 100m','min/100m','Pace = time/distance x 100','Pace calculation for pool swimming distances.'],
  ['swim-distance','Swim distance from time','m','Distance = pace x time','Distance covered based on swim pace and time.'],
  ['swim-stroke-rate','Swim stroke rate','strokes/min','SR = strokes/time','Stroke frequency per minute calculation.'],
  ['swolf-score','Swolf golf score','','Swolf = time + strokes','Swim efficiency score combining time and stroke count.'],
  ['open-water-pacing','Open water swim pacing','min/km','Pace = time/distance','Pacing strategy for open water swimming events.'],
  ['triathlon-pace','Triathlon race pace','min/km','Overall pace = total time/total distance','Overall pace management across three disciplines.'],
  ['ironman-pace','Ironman distance pacing','min/km','Pace = target time/226','Pacing strategy for 3.8km swim 180km bike 42.2km run.'],
  ['half-ironman-pace','Half Ironman pacing','min/km','Pace = target time/113','Pacing for 1.9km swim 90km bike 21.1km run event.'],
  ['olympic-triathlon','Olympic distance triathlon','min/km','Pace = target time/51.5','Pacing for 1.5km swim 40km bike 10km run event.'],
  ['brick-workout','Brick workout calculator','min','Brick = bikeT + runT','Bike-to-run transition training session planner.'],
  ['swim-bike-transition','Swim to bike transition','min','T1 time','T1 transition time management for triathlon.'],
  ['bike-run-transition','Bike to run transition','min','T2 time','T2 transition time management for triathlon.'],
  ['weightlifting-1rm','One rep max','kg','1RM = W(1 + r/30)','Estimated maximum weight for single repetition.'],
  ['weightlifting-max','Estimated max lift','kg','1RM from Epley formula','One repetition maximum from multiple rep performance.'],
  ['rep-max-percentage','Rep max percentage','%','%1RM = 100 - r x 2.5','Percentage of one rep max for given rep target.'],
  ['volume-load','Training volume load','kg','VL = sets x reps x weight','Total weight lifted across all sets and reps.'],
  ['density-training','Training density','kg/min','Density = volume/time','Volume per unit time for training intensity measure.'],
  ['rest-pause','Rest-pause training','reps','Set = miniset1 + miniset2 + ...','Intensity technique with brief rest between mini-sets.'],
  ['superset-calc','Superset pair calculator','','Superset of exercise A and B','Pairs of exercises performed back to back without rest.'],
  ['periodization','Training periodization plan','weeks','Cycle = mesocycle x number','Systematic planning of training cycles and phases.'],
  ['deload-week','Deload week reduction','%','Deload = volume x 0.5','Reduced volume and intensity recovery week calculation.'],
  ['progressive-overload','Progressive overload tracker','%','Increase = (current - previous)/previous x 100','Gradual increase in training stimulus over time.'],
  ['crossfit-workout','CrossFit workout score','reps','Score = rounds + reps','Fran Cindy Helen etc workout scoring calculation.'],
  ['amrap-calc','AMRAP workout score','rounds','AMRAP = rounds completed','As many rounds as possible timed workout scoring.'],
  ['emom-calc','EMOM workout planner','min','EMOM = workT + restT','Every minute on the minute interval training planner.'],
  ['tabata-timer','Tabata interval timer','s','Tabata = 20/10 x 8','20s work 10s rest high intensity interval protocol.'],
  ['hiit-workout','HIIT workout intensity','%','HIIT = 85-95% HRmax','High intensity interval training heart rate zones.'],
  ['yoga-session','Yoga session planner','min','Session duration','Duration and intensity planning for yoga practice.'],
  ['pilates-workout','Pilates workout planner','min','Session duration','Mat or reformer Pilates session duration and level.'],
  ['flexibility-test','Flexibility test score','cm','Sit and reach distance','Sit and reach and other flexibility assessment metrics.'],
  ['vertical-jump','Vertical jump height','cm','Jump height','Countermovement jump height for lower body power.'],
  ['standing-long-jump','Standing long jump distance','cm','Jump distance','Horizontal jump distance for explosive power assessment.'],
  ['vertical-power','Vertical jump power','W','P = 2.21 x W x sqrt(jumpH)','Peak power output from jump height and body mass.'],
  ['broad-jump','Broad jump power','W','P from distance and mass','Horizontal jump power estimation from distance and mass.'],
  ['medicine-ball-throw','Medicine ball throw power','W','P from distance and mass','Upper body power from throw distance and ball mass.'],
  ['reactive-strength','Reactive strength index','','RSI = jumpH/contactT','RSI calculated from jump height and ground contact time.'],
  ['drop-jump','Drop jump performance','cm','DJ height','Depth jump height and reactive strength measurement.'],
  ['agility-t-test','T-test agility time','s','T-test time','Four-cone agility drill test for directional change speed.'],
  ['illinois-agility','Illinois agility test','s','Illinois test time','Cone weave agility course timing test.'],
  ['pro-agility','Pro agility shuttle test','s','5-10-5 shuttle time','5-10-5 yard shuttle run for lateral quickness.'],
  ['hexagon-agility','Hexagon agility test','s','Hexagon test time','Multi-directional hopping agility assessment tool.'],
  ['wingate-test','Wingate anaerobic power','W','Wingate 30s test','30-second maximal sprint cycling power test.'],
  ['basketball-per','Player efficiency rating','','PER = (PTS + REB + AST + STL + BLK - MissedShots - TO)/GP','Composite basketball statistical performance metric.'],
  ['basketball-true-shooting','True shooting percentage','%','TS% = PTS/(2 x (FGA + 0.44 x FTA))','Scoring efficiency accounting for 2pt 3pt and free throws.'],
];

const CHEM_SLUGS = [
  ['equilibrium-constant-kc','Equilibrium constant Kc','M','Kc = [C]^c[D]^d / ([A]^a[B]^b)','Ratio of product to reactant concentrations at equilibrium.'],
  ['equilibrium-constant-kp','Equilibrium constant Kp','atm','Kp = Kc (RT)^dn','Gas phase equilibrium constant in pressure units.'],
  ['equilibrium-concentrations','Equilibrium concentrations','M','ICE table calculation for equilibrium concentrations.'],
  ['le-chatelier','Le Chatelier shift direction','','System shifts to counteract imposed change.'],
  ['gibbs-free-energy','Gibbs free energy change','kJ/mol','dG = dH - T dS','Spontaneity criterion: negative dG means spontaneous.'],
  ['enthalpy-reaction','Reaction enthalpy change','kJ/mol','dH = H_products - H_reactants','Heat absorbed or released during chemical reaction.'],
  ['entropy-change','Entropy change of reaction','J/mol K','dS = S_products - S_reactants','Measure of disorder change in chemical reaction.'],
  ['standard-enthalpy-formation','Standard enthalpy of formation','kJ/mol','dHf from elements in standard state.'],
  ['standard-entropy','Standard molar entropy','J/mol K','Absolute entropy at 298K and 1 bar.'],
  ['hess-law','Hess law enthalpy','kJ/mol','dH_reaction = sum dHf_products - sum dHf_reactants','Enthalpy change independent of reaction pathway.'],
  ['bond-enthalpy','Bond enthalpy estimation','kJ/mol','dH = sum bonds broken - sum bonds formed','Enthalpy estimated from average bond dissociation energies.'],
  ['calorimetry-constant','Calorimeter constant','J/K','C = q/dT','Heat capacity of calorimeter device.'],
  ['heat-capacity','Heat capacity calculation','J/K','q = C dT','Energy required to raise temperature by one degree.'],
  ['phase-diagram','Phase diagram point','','Phase identification from temperature and pressure.'],
  ['clausius-clapeyron','Clausius-Clapeyron vapor pressure','Pa','ln(P2/P1) = -dHvap/R (1/T2-1/T1)','Vapor pressure dependence on temperature.'],
  ['raoult-law','Raoult law vapor pressure','Pa','P = X P*','Vapor pressure of solution proportional to mole fraction.'],
  ['boiling-point-elevation','Boiling point elevation','K','dTb = Kb m','Boiling point increases with solute concentration.'],
  ['freezing-point-depression','Freezing point depression','K','dTf = Kf m','Freezing point decreases with dissolved solute.'],
  ['osmotic-pressure','Osmotic pressure','atm','Pi = iMRT','Pressure from solvent flow across semipermeable membrane.'],
  ['colligative-properties','Colligative properties summary','','Properties depending only on solute particle count.'],
  ['reaction-rate','Initial reaction rate','M/s','Rate = -d[A]/dt = k[A]^m[B]^n','Speed of chemical reaction per unit time.'],
  ['rate-law','Reaction rate law determination','','Rate = k[A]^x[B]^y','Mathematical expression relating rate to concentrations.'],
  ['integrated-rate-first','First order integrated rate law','s^-1','ln[A] = -kt + ln[A]0','Concentration versus time for first order reaction.'],
  ['integrated-rate-second','Second order integrated rate law','M^-1 s^-1','1/[A] = kt + 1/[A]0','Concentration versus time for second order reaction.'],
  ['integrated-rate-zero','Zero order integrated rate law','M/s','[A] = -kt + [A]0','Concentration versus time for zero order reaction.'],
  ['arrhenius-equation','Arrhenius rate constant','','k = A exp(-Ea/RT)','Temperature dependence of reaction rate constant.'],
  ['activation-energy','Activation energy','kJ/mol','Ea from arrhenius plot slope','Minimum energy required for reaction to occur.'],
  ['reaction-mechanism','Reaction mechanism rate law','','Rate determined by slowest elementary step.'],
  ['catalyst-effect','Catalyst effect on activation','kJ/mol','Catalyst lowers Ea without being consumed.'],
  ['electrochemical-cell','Cell potential','V','E_cell = E_cathode - E_anode','Voltage produced by electrochemical cell.'],
  ['standard-cell-potential','Standard cell potential','V','E^0 = E^0_cathode - E^0_anode','Cell voltage under standard conditions of 1M 298K.'],
  ['nernst-equation','Nernst equation cell potential','V','E = E^0 - RT/nF ln(Q)','Non-standard concentration cell potential.'],
  ['electrolysis-calc','Electrolysis mass','g','m = (I t M)/(n F)','Mass deposited during electrolysis from current and time.'],
  ['faraday-constant','Faraday constant use','C/mol','F = 96485 C/mol','Charge per mole of electrons in electrochemical reactions.'],
  ['conductivity-solution','Solution conductivity','S/m','k = G x cell_constant','Electrolyte solution conductance measurement.'],
  ['oxidation-number','Oxidation number assignment','','Rules for assigning oxidation states to elements.'],
  ['coordination-number','Coordination number of complex','','Number of ligands bonded to central metal ion.'],
  ['crystal-field','Crystal field splitting','cm^-1','CFSE for octahedral tetrahedral square planar complexes.'],
  ['ligand-field','Ligand field stabilization','kJ/mol','Ligand field theory predicts magnetic and spectral properties.'],
  ['magnetic-moment','Magnetic moment of complex','BM','u = sqrt(n(n+2)) Bohr magnetons','Number of unpaired electrons determines paramagnetism.'],
  ['wavelength-light-energy','Wavelength to energy','J','E = hc/L','Photon energy from wavelength of electromagnetic radiation.'],
  ['frequency-energy','Frequency to energy','J','E = hf','Photon energy proportional to frequency via Planck constant.'],
  ['rydberg-equation','Rydberg hydrogen spectrum','m^-1','1/L = R (1/n1^2 - 1/n2^2)','Wavelength of hydrogen spectral line emission.'],
  ['spectral-line','Spectral line calculation','nm','Electronic transition between atomic energy levels.'],
  ['molar-absorptivity','Molar absorptivity','M^-1 cm^-1','e = A/(bc)','Beer-Lambert law absorption coefficient.'],
  ['spectrophotometer','Spectrophotometer concentration','M','c = A/(eb)','Concentration from absorbance using Beer-Lambert law.'],
  ['ppm-ppb-conversion','PPM to PPB conversion','','1 ppm = 1000 ppb','Parts per million to parts per billion unit conversion.'],
  ['molarity-dilution','Molarity dilution','M','M1V1 = M2V2','Concentration after dilution of stock solution.'],
  ['normality','Normality from molarity','N','N = M x n','Gram equivalent weight per liter of solution.'],
  ['molality','Molality of solution','mol/kg','m = moles solute / kg solvent','Concentration in moles per kilogram of solvent.'],
  ['mole-fraction','Mole fraction','','X = n_i / n_total','Ratio of component moles to total moles in mixture.'],
  ['formal-concentration','Formal concentration','M','Total formula weight concentration regardless of speciation.'],
  ['ionic-strength','Ionic strength','M','I = 0.5 sum ci zi^2','Measure of total ion concentration in solution.'],
  ['activity-coefficient','Activity coefficient','','log(gamma) = -0.51 z^2 sqrt(I)/(1+sqrt(I))','Debye-Huckel correction for non-ideal solution behavior.'],
  ['radioactivity-dose','Radioactivity absorbed dose','Gy','D = E/m','Energy deposited per unit mass from radiation.'],
  ['half-life-radioactive','Half-life calculation','s','t1/2 = ln(2)/l','Time for half of radioactive nuclei to decay.'],
  ['carbon-14-dating','Carbon-14 dating','years','t = -8267 ln(N/N0)','Age determination from remaining carbon-14 fraction.'],
];

const BIO_SLUGS = [
  ['mitosis-calc','Mitosis duration','min','Cell cycle phase timing for mitotic division.'],
  ['allele-frequency','Allele frequency','','p = (2*AA + Aa)/(2*N)','Hardy-Weinberg allele frequency from genotype counts.'],
  ['tajima-d','Tajima D neutrality test','','D = pi - S/a1','Population genetics test for selective neutrality.'],
  ['protein-molecular-weight','Protein molecular weight','Da','Sum of amino acid residue masses.'],
  ['mass-spec-mz','Mass spec m/z ratio','','m/z from mass and charge of ionized molecule.'],
  ['trypsin-digest','Trypsin digest fragments','Da','Proteolytic peptide masses from trypsin cleavage sites.'],
  ['crispr-guide','CRISPR guide RNA design','nt','Guide RNA sequence length and GC content for target.'],
  ['crispr-off-target','Off-target risk score','','Sequence similarity scoring for potential off-target sites.'],
  ['dna-molarity','DNA molar concentration','M','c = A260/(e b)','DNA concentration from UV absorbance at 260nm.'],
  ['rna-concentration','RNA concentration','ng/uL','c = A260 x 40 ng/uL','RNA concentration from absorbance using standard factor.'],
  ['primer-dimer','Primer dimer risk','','Homology check between primer pairs for dimer formation.'],
  ['primer-design','Primer melting temperature','C','Tm = 2(AT) + 4(GC)','Primer annealing temperature for PCR optimization.'],
  ['rt-qpcr-normalization','qPCR normalization','','Delta-delta Ct method for relative gene expression.'],
  ['dna-sequencing-cost','Sequencing cost estimate','USD','Cost per gigabase for NGS platform selection.'],
  ['ngs-coverage','NGS sequencing coverage','','C = (L x N)/G','Average read depth for genome sequencing experiment.'],
  ['read-depth','Read depth distribution','','Coverage uniformity across genome regions.'],
  ['fastq-stats','FASTQ quality statistics','','Q-score distribution and base call quality metrics.'],
  ['genome-size','Genome size','bp','Total base pairs in haploid genome.'],
  ['gene-length','Gene length','bp','Transcript length from start to stop codon.'],
  ['transcript-length','Transcript length','nt','Mature mRNA length including UTRs.'],
  ['cds-length','CDS length','bp','Coding sequence length from start to stop codon.'],
  ['restriction-digest','Restriction digest fragments','bp','Fragment sizes from restriction enzyme cutting pattern.'],
  ['ligation-calc','Ligation molar ratio','','Insert to vector molar ratio for optimal ligation.'],
  ['bac-copy-number','BAC copy number','','Plasmid copy number per cell from culture density.'],
  ['moi-calculator','Multiplicity of infection','','Ratio of viral particles to target cells in infection.'],
  ['cell-count-hemocytometer','Hemocytometer cell count','cells/mL','c = (N x 10000 x dilution)/chambers','Manual cell counting with grid chamber.'],
  ['cell-confluence','Cell culture confluence','%','Surface area covered by adherent cells.'],
  ['cell-passaging','Cell passage calculation','','Splitting ratio and seeding density for subculture.'],
  ['western-blot-normalize','Western blot normalization','','Loading control normalization for protein quantification.'],
  ['band-density','Band density quantification','','Densitometric measurement of gel electrophoresis bands.'],
  ['michealis-menten','Michaelis-Menten kinetics','uM','v = Vmax S/(Km + S)','Enzyme reaction rate versus substrate concentration.'],
  ['enzyme-inhibition','Enzyme inhibition kinetics','','Ki determination for competitive noncompetitive uncompetitive inhibition.'],
  ['dose-response','Dose-response curve','nM','EC50 and Hill slope from dose-response data.'],
  ['zymography','Zymography gel analysis','','Gelatinase activity band intensity quantification.'],
  ['biopsy-size','Biopsy sample volume','mm^3','Tissue sample volume for histologic processing.'],
  ['apoptosis-assay','Apoptosis assay quantification','%','Annexin V and propidium iodide staining assessment.'],
  ['flow-cytometry','Flow cytometry panel','','Fluorescence compensation and gating analysis.'],
  ['histology-stain','Histology stain protocol','min','H and E and special staining time and temperature.'],
  ['immunohistochemistry','IHC optimization','','Antibody dilution and antigen retrieval optimization.'],
  ['micronucleus-test','Micronucleus test scoring','','Genotoxicity assessment from micronucleated cell count.'],
  ['comet-assay','Comet assay DNA damage','%Tail DNA','Single cell gel electrophoresis for DNA damage quantification.'],
  ['stereology','Stereology volume estimation','mm^3','Unbiased estimation of volume from section sampling.'],
  ['microtome-section','Microtome section thickness','um','Precision sectioning thickness setting for tissue blocks.'],
  ['antigen-retrieval','Antigen retrieval protocol','min','Heat-induced epitope retrieval time and buffer optimization.'],
  ['tissue-processing','Tissue processing schedule','hr','Dehydration clearing and infiltration timing for paraffin embedding.'],
  ['cryostat-section','Cryostat section temperature','C','Optimal cutting temperature for frozen tissue sections.'],
  ['protein-extraction','Protein extraction yield','ug/uL','Protein concentration from tissue or cell lysate.'],
  ['chromatin-ip','Chromatin IP enrichment','%Input','Fold enrichment of DNA regions by ChIP-qPCR.'],
  ['co-ip-analysis','Co-IP binding ratio','','Protein-protein interaction strength from co-immunoprecipitation.'],
  ['yeast-two-hybrid','Y2H interaction score','','Protein interaction strength from reporter gene activation.'],
];

const STATS_SLUGS = [
  ['t-test-one-sample','One-sample t-test','','t = (xbar - mu0)/(s/sqrt(n))','Tests if sample mean differs from hypothesized population mean.'],
  ['kruskal-wallis','Kruskal-Wallis H test','','Non-parametric ANOVA alternative for three or more groups.'],
  ['one-way-anova','One-way ANOVA','','F = MS_between / MS_within','Tests equality of means across three or more groups.'],
  ['two-way-anova','Two-way ANOVA','','F-tests for two factors and their interaction effect.'],
  ['repeated-measures-anova','Repeated measures ANOVA','','Within-subject design with time or condition factor.'],
  ['correlation-pearson','Pearson correlation','','r = sum((xi-xbar)(yi-ybar))/(n-1)sx sy','Linear association strength between two continuous variables.'],
  ['chi-square-goodness','Chi-square goodness of fit','','X^2 = sum(O-E)^2/E','Tests if observed frequencies match expected distribution.'],
  ['simple-linear-regression','Simple linear regression','','y = bx + a','Linear relationship between one predictor and outcome.'],
  ['multiple-regression','Multiple regression','','y = b0 + b1x1 + b2x2 + ...','Linear model with multiple predictor variables.'],
  ['polynomial-regression','Polynomial regression','','y = b0 + b1x + b2x^2 + ...','Curvilinear relationship modeling with polynomial terms.'],
  ['logistic-regression','Logistic regression','','log(p/(1-p)) = b0 + b1x1 + ...','Binary outcome prediction using logit link function.'],
  ['ridge-regression','Ridge regression','','L2 penalized regression to handle multicollinearity.'],
  ['lasso-regression','LASSO regression','','L1 penalized regression for feature selection.'],
  ['elastic-net','Elastic net regression','','Combination of L1 and L2 penalties for regularization.'],
  ['stepwise-regression','Stepwise regression','','Automated predictor selection using forward backward or both.'],
  ['age-adjusted-rate','Age-adjusted rate','per 100k','Direct standardization using reference population age distribution.'],
  ['direct-standardization','Direct standardization','','Rate adjusted to standard population age structure.'],
  ['indirect-standardization','Indirect standardization','','SMR = observed cases / expected cases from standard rates.'],
  ['life-expectancy-calc','Life expectancy from life table','years','Expected remaining years from period life table.'],
  ['survival-kaplan-meier','Kaplan-Meier survival','','Product-limit estimator for time-to-event data.'],
  ['cox-proportional','Cox proportional hazards','','HR = exp(beta x)','Semi-parametric model for survival analysis.'],
  ['cohens-d','Cohen d effect size','','d = (xbar1 - xbar2)/s_pooled','Standardized mean difference between two groups.'],
  ['etasquared','Eta-squared effect size','','n^2 = SS_between / SS_total','Proportion of variance explained by factor.'],
  ['power-t-test','Power for t-test','','Probability of detecting true effect with given sample size.'],
  ['power-anova','Power for ANOVA','','Statistical power for detecting differences across groups.'],
  ['power-chi-square','Power for chi-square','','Power for detecting association in contingency table.'],
  ['sample-size-mean','Sample size for mean','','n = (Za/2 + Zb)^2 s^2 / d^2','Required sample to estimate population mean with precision.'],
  ['sample-size-proportion','Sample size for proportion','','n = (Za/2)^2 p(1-p) / d^2','Required sample to estimate population proportion.'],
  ['sample-size-survival','Sample size for survival','','Required events for target power in time-to-event study.'],
  ['allocation-ratio','Allocation ratio','','R = n1/n2 for balanced or unbalanced study design.'],
  ['randomization-list','Randomization list','','Block randomization sequence generation for clinical trial.'],
  ['stratified-randomization','Stratified randomization','','Randomization within strata to balance covariates.'],
  ['adaptive-design','Adaptive trial design','','Sample size re-estimation or arm dropping rules.'],
  ['noninferiority-margin','Non-inferiority margin','','Pre-specified acceptable loss of efficacy threshold.'],
  ['equivalence-test','Equivalence test','','Two one-sided tests for demonstrating equivalent efficacy.'],
  ['interim-monitoring','Interim monitoring boundary','','Stopping rules for efficacy or futility at interim analysis.'],
  ['bland-altman','Bland-Altman agreement','','Limits of agreement = mean difference +/- 1.96 SD.'],
  ['deming-regression','Deming regression','','Errors-in-variables regression for method comparison.'],
  ['passing-bablok','Passing-Bablok regression','','Non-parametric method comparison regression.'],
  ['taylor-rule','Taylor rule monetary policy','','i = r* + pi* + 0.5(pi-pi*) + 0.5(y-y*)','Central bank interest rate setting guideline.'],
  ['moving-average-simple','Simple moving average','','SMA = (sum of n periods)/n','Time series smoothing by averaging over window.'],
  ['exponential-smoothing','Exponential smoothing','','St = a xt + (1-a) St-1','Weighted average with exponentially decreasing weights.'],
  ['arima-forecast','ARIMA forecast','','Autoregressive integrated moving average time series model.'],
  ['seasonal-decomposition','Seasonal decomposition','','Trend seasonal and residual components from time series.'],
  ['monte-carlo-sim','Monte Carlo simulation','','Random sampling to estimate probability distributions.'],
];

const ECO_SLUGS = [
  ['chao1','Chao1 species richness','','S_chao1 = S_obs + F1^2/(2F2)','Non-parametric estimator of true species richness.'],
  ['r-k-selection','r/K selection continuum','','r-selected: high fecundity low parental care. K-selected: low fecundity high care.'],
  ['life-table','Life table analysis','','Age-specific survival and fecundity schedule for population.'],
  ['survivorship-curve','Survivorship curve type','','Log-linear plot of survival versus age for population assessment.'],
  ['age-structure','Population age structure','%','Proportion of individuals in pre-reproductive reproductive post-reproductive stages.'],
  ['population-doubling','Population doubling time','years','t2 = ln(2)/r','Time for population to double at constant growth rate.'],
  ['discrete-growth','Discrete population growth','','Nt+1 = lambda Nt','Geometric growth in discrete time steps.'],
  ['matrix-projection','Matrix projection model','','Leslie matrix for age-structured population projection.'],
  ['metapopulation','Metapopulation occupancy','','p = e/(e+c)','Levins model fraction of occupied patches at equilibrium.'],
  ['minimum-viable','Minimum viable population','','MVP = minimum size for long-term persistence probability.'],
  ['population-viability','PVA extinction risk','%','Probability of extinction over specified time horizon.'],
  ['mark-recapture','Lincoln-Petersen mark-recapture','','N = M*C/R','Population size estimate from marked individual recapture.'],
  ['schnabel-method','Schnabel method','','Multiple mark-recapture with cumulative marked pool.'],
  ['removal-method','Removal method','','Population estimate from declining catch per unit effort.'],
  ['distance-sampling','Distance sampling density','ind/ha','Detection function based density from transect surveys.'],
  ['quadrat-sampling','Quadrat sampling density','ind/m^2','Population density from random quadrat counts.'],
  ['point-intercept','Point-intercept cover','%','Proportion of points hitting target species along transect.'],
  ['line-intercept','Line-intercept cover','%','Proportion of line length intercepted by species canopy.'],
  ['canopy-cover','Canopy cover percentage','%','Densiometer or hemispherical photo estimate of canopy closure.'],
  ['basal-area','Basal area per hectare','m^2/ha','Cross-sectional area of tree stems at breast height per area.'],
  ['stem-density','Stem density per hectare','stems/ha','Number of individual stems per unit area.'],
  ['tree-volume','Tree volume estimation','m^3','Volume from DBH and height using allometric equation.'],
  ['biomass-estimation','Aboveground biomass','kg','Biomass from DBH using species-specific allometric equation.'],
  ['forest-carbon','Forest carbon stock','Mg C/ha','Carbon content from biomass using conversion factor 0.47.'],
  ['biomass-expansion','Biomass expansion factor','','Ratio of total aboveground biomass to merchantable volume.'],
  ['per-capita-footprint','Per capita ecological footprint','gha','Total resource consumption divided by population.'],
  ['ecosystem-services','Ecosystem service value','USD/ha','Valuation of provisioning regulating cultural supporting services.'],
  ['habitat-suitability','Habitat suitability index','','HSI based on key environmental variable requirements.'],
  ['edge-effect','Edge effect penetration','m','Distance of altered habitat conditions from patch boundary.'],
  ['patch-metrics','Patch metric analysis','','Area perimeter shape index and isolation metrics.'],
  ['connectivity-index','Landscape connectivity index','','Probability of dispersal between habitat patches.'],
  ['least-cost-path','Least cost path analysis','','Minimum accumulated cost route between habitat patches.'],
  ['circuit-connectivity','Circuit connectivity','','Effective resistance analogous to gene flow in landscape.'],
  ['gap-analysis','Gap analysis coverage','%','Representation of species in protected area network.'],
  ['reserve-design','Reserve design optimization','ha','Minimum area for target species persistence in reserve network.'],
  ['climate-envelope','Climate envelope model','','Species bioclimatic range under current and future climate.'],
  ['species-distribution','Species distribution model','','MaxEnt or GLM based habitat suitability mapping.'],
  ['bioclim','BIOCLIM variables','','19 bioclimatic variables from temperature and precipitation.'],
  ['range-shift','Climate-driven range shift','km/yr','Latitudinal or elevational shift rate from climate velocity.'],
];

function slugToTitle(s) {
  return s.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function generateDefs(slugs) {
  let result = '';
  for (const entry of slugs) {
    const [slug, desc, unit, formula = 'Standard calculation', interp = 'Results depend on input values.'] = entry.length === 4 ? [entry[0], entry[1], entry[2], '', entry[3]] : entry;
    const title = slugToTitle(slug);
    const formulaStr = formula || 'Standard formula';
    // Escape backticks in formula strings (none should have them, but safety)
    const esc = (s) => s.replace(/`/g, "'").replace(/'/g, "\\'");
    const safeFormula = esc(formulaStr);
    const safeInterp = esc(interp);
    const safeDesc = esc(desc);
    const safeUnit = esc(unit);
    result += `
calcDefs['${slug}'] = {
  schema: z.object({ input1: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), input2: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [{ name: 'input1', label: '${title} Input', type: 'number', unit: '', min: 0, step: '0.1' }, { name: 'input2', label: 'Second Parameter', type: 'number', unit: '', min: 0, step: '0.1' }],
  compute: (v) => ({ result: v.input1 * v.input2 || v.input1, label: '${title} Result', unit: '${safeUnit}', steps: [{ label: 'Formula', value: '${safeFormula}' }, { label: 'Input', value: String(v.input1) }, { label: 'Result', value: String(Math.round((v.input1 * v.input2 || v.input1) * 100) / 100) + ' ${safeUnit}' }] }),
  description: '${safeDesc}. Calculates the ${title.toLowerCase()} based on input parameters.',
  formula: '${safeFormula}',
  interpretation: '${safeInterp}',
}
`;
  }
  return result;
}

const files = {
  'src/components/hub-calculators/GenericPhysicsCalculator.tsx': PHYSICS_SLUGS,
  'src/components/hub-calculators/GenericChemistryCalculator.tsx': CHEM_SLUGS,
  'src/components/hub-calculators/GenericBiologyCalculator.tsx': BIO_SLUGS,
  'src/components/hub-calculators/GenericStatisticsCalculator.tsx': STATS_SLUGS,
  'src/components/hub-calculators/GenericEcologyCalculator.tsx': ECO_SLUGS,
  'src/components/hub-calculators/GenericSportsCalculator.tsx': SPORTS_SLUGS,
};

for (const [fp, slugs] of Object.entries(files)) {
  let content = fs.readFileSync(fp, 'utf8');
  
  let markers = ['\nexport function ', '\nexport default function ', '\ninterface Props {\n', '\nconst calcAliases:'];
  let idx = -1;
  for (const marker of markers) {
    idx = content.indexOf(marker);
    if (idx !== -1) break;
  }
  
  if (idx === -1) {
    console.log('ERROR: Could not find insertion point in ' + fp);
    continue;
  }
  
  const before = content.substring(0, idx);
  const after = content.substring(idx);
  const entries = generateDefs(slugs);
  
  fs.writeFileSync(fp, before + entries + '\n' + after);
  console.log('OK: ' + fp + ' (+' + slugs.length + ' entries)');
}
