var fs = require('fs');

// Template: slug -> [desc, formula, interpret, [[fieldName, label, step, min], ...], computeCode]
// computeCode uses n() for parsing, returns CalcResult, uses + for concat
var slugs = [
['paver-sand', 'Estimate sand needed for paver base and joints.', 'Sand (tons) = Area x depth x density', 'Covers both base sand and joint sand. Average depth 1in base + 0.5in joints.', [['area','Area (sq ft)',0.1,0],['depth','Depth (in)',0.25,0.5]], 'var a=n(v.area),d=n(v.depth||"1.5");var cf=a*d/12;var tons=cf*0.1;return{result:tons,label:"Sand Needed",unit:"tons",steps:["Area: "+a+" sq ft","Depth: "+d+" in = "+(d/12).toFixed(3)+" ft","Volume: "+cf.toFixed(1)+" cu ft","Sand: "+tons.toFixed(2)+" tons"]}'],
['asphalt-tonnage', 'Estimate asphalt tonnage for paving projects.', 'Tons = Length x Width x Depth x 0.055', 'Assumes 110 lbs per sq ft per inch of depth. Adjust for compaction factor of 1.05.', [['length','Length (ft)',1,0],['width','Width (ft)',1,0],['depth','Depth (in)',0.5,2]], 'var l=n(v.length),w=n(v.width),d=n(v.depth||"3");var tons=l*w*d*0.055;return{result:tons,label:"Asphalt Needed",unit:"tons",steps:["Area: "+l+"x"+w+" = "+(l*w)+" sq ft","Depth: "+d+" in","Tons: "+tons.toFixed(2)+" tons"]}'],
['gravel-base', 'Estimate gravel base material for driveways and foundations.', 'Gravel = Area x Depth x 1.4 (tons)', 'Base gravel typically 6-8in deep for driveways. Includes 15% compaction factor.', [['area','Area (sq ft)',1,0],['depth','Depth (in)',0.5,4]], 'var a=n(v.area),d=n(v.depth||"6");var tons=a*(d/12)*1.4;return{result:tons,label:"Gravel Needed",unit:"tons",steps:["Area: "+a+" sq ft","Depth: "+d+" in = "+(d/12).toFixed(2)+" ft","Gravel: "+tons.toFixed(2)+" tons"]}'],
['crushed-stone', 'Estimate crushed stone needed for construction.', 'Stone (tons) = Area x Depth x 1.35', 'Crushed stone density ~1.35 tons per cubic yard. Add 5-10% for compaction.', [['area','Area (sq ft)',1,0],['depth','Depth (in)',0.5,3]], 'var a=n(v.area),d=n(v.depth||"4");var cYds=a*(d/12)/27;var tons=cYds*1.35;return{result:tons,label:"Crushed Stone",unit:"tons",steps:["Area: "+a+" sq ft","Depth: "+d+" in","Volume: "+cYds.toFixed(2)+" cu yd","Stone: "+tons.toFixed(2)+" tons"]}'],
['mulch-coverage', 'Calculate mulch needed for garden beds.', 'Mulch = Area x Depth / 324 (cubic yards)', 'Standard depth is 2-3in. One cubic yard covers ~108 sq ft at 3in depth.', [['area','Area (sq ft)',1,0],['depth','Depth (in)',0.5,2]], 'var a=n(v.area),d=n(v.depth||"3");var cYds=a*(d/12)/27;return{result:cYds,label:"Mulch Needed",unit:"cu yd",steps:["Area: "+a+" sq ft","Depth: "+d+" in","Mulch: "+cYds.toFixed(2)+" cu yd","Bags (2cf): "+Math.ceil(cYds*13.5)+" bags"]}'],
['sod-estimate', 'Estimate sod needed for lawn installation.', 'Sod = Length x Width (sq ft) + 5-10% waste', 'One pallet covers ~450-500 sq ft. Add 5-10% for cutting/waste.', [['length','Length (ft)',1,0],['width','Width (ft)',1,0]], 'var l=n(v.length),w=n(v.width);var area=l*w;var waste=area*0.1;return{result:area,label:"Sod Area",unit:"sq ft",steps:["Area: "+l+"x"+w+" = "+area+" sq ft","With 10% waste: "+(area+waste).toFixed(0)+" sq ft","Pallets: ~"+Math.ceil((area+waste)/500)+" pallets"]}'],
['seed-coverage', 'Calculate grass seed needed for lawn.', 'Seed (lbs) = Area x Rate per 1000 sq ft', 'Kentucky bluegrass: 2-3lbs/1000sqft, fescue: 5-8lbs/1000sqft, ryegrass: 5-7lbs/1000sqft.', [['area','Area (sq ft)',100,0],['rate','Rate (lbs/1000sqft)',0.5,5]], 'var a=n(v.area),r=n(v.rate||"5");var seed=a/1000*r;return{result:seed,label:"Seed Needed",unit:"lbs",steps:["Area: "+a+" sq ft","Rate: "+r+" lbs/1000 sq ft","Seed: "+seed.toFixed(1)+" lbs"]}'],
['fence-post-depth', 'Determine proper fence post depth and concrete needs.', 'Depth = Post height x 0.33 + 6in minimum', 'General rule: 1/3 of post height below ground. Minimum 24in for 6ft fence.', [['postHeight','Post Height (ft)',0.5,4],['postWidth','Post Width (in)',0.5,4]], 'var h=n(v.postHeight),w=n(v.postWidth||"4");var depth=Math.max(h*12*0.33,24);var concrete=depth*w*w/144*0.5;return{result:depth,label:"Post Depth",unit:"in",steps:["Post height: "+h+" ft = "+(h*12)+" in","Min depth: "+(h*12*0.33).toFixed(0)+" in (1/3 rule)","Use: "+Math.round(depth)+" in"]}'],
['deck-beam-span', 'Determine maximum beam span for deck construction.', 'Max span = Beam depth x 1.5 (for 40psf live load)', '2x8 beam max ~6ft, 2x10 beam max ~8ft, 2x12 beam max ~10ft span between posts.', [['beamSize','Beam Size (inches)',1,6],['load','Load (psf)',5,40]], 'var b=n(v.beamSize),l=n(v.load||"40");var span=b*1.5*(40/l);return{result:span,label:"Max Beam Span",unit:"ft",steps:["Beam depth: "+b+" in","Load: "+l+" psf","Span: "+span.toFixed(1)+" ft"]}'],
['deck-joist-span', 'Calculate maximum joist span for deck framing.', 'Max span = Joist depth x 1.8 (16in OC, 40psf)', '2x6 max ~8ft, 2x8 max ~10ft, 2x10 max ~13ft at 16in OC. Reduce for 12in OC.', [['joistSize','Joist Size (in)',1,6],['spacing','Spacing (in)',2,12],['load','Load (psf)',5,40]], 'var j=n(v.joistSize),s=n(v.spacing||"16"),l=n(v.load||"40");var span=j*1.8*(40/l)*Math.sqrt(16/s);return{result:span,label:"Max Joist Span",unit:"ft",steps:["Joist: "+j+"in at "+s+"in OC","Load: "+l+" psf","Span: "+span.toFixed(1)+" ft"]}'],
['railing-post-spacing', 'Determine proper railing post spacing for safety.', 'Max spacing = 6ft for 4x4 posts, 8ft for 6x6 posts', 'IRC code: max 6ft between posts for 4x4. Max 4in between balusters. Post must resist 200lb lateral load.', [['postSize','Post Size',1,4]], 'var p=n(v.postSize||"4");var max=p==6?8:p==4?6:4;return{result:max,label:"Max Post Spacing",unit:"ft",steps:["Post: "+p+"x"+p,"Max spacing: "+max+" ft"]}'],
['stair-runner-length', 'Calculate stair runner carpet length.', 'Runner = (Riser x tread) x steps x 1.1', 'Standard stair: 7in rise, 11in run. Add 10% for waste and pattern matching.', [['steps','Number of Steps',1,1],['rise','Rise (in)',0.25,7],['tread','Tread Depth (in)',0.25,11]], 'var s=n(v.steps),r=n(v.rise||"7"),t=n(v.tread||"11");var len=s*(r+t)/12*1.1;return{result:len,label:"Runner Length",unit:"ft",steps:["Steps: "+s,"Per step: "+(r+t).toFixed(1)+" in","Length: "+len.toFixed(1)+" ft (with waste)"]}'],
['handrail-angle', 'Calculate handrail angle for stairs and ramps.', 'Angle = atan(rise / run)', 'Max stair angle: 42 degrees for residential, 32 degrees for commercial. Optimal: 30-35 degrees.', [['riseTotal','Total Rise (in)',1,0],['runTotal','Total Run (in)',1,0]], 'var r=n(v.riseTotal),u=n(v.runTotal);var angle=Math.atan2(r,u)*180/Math.PI;var len=Math.sqrt(r*r+u*u)/12;return{result:angle,label:"Handrail Angle",unit:"deg",steps:["Rise: "+r+" in","Run: "+u+" in","Angle: "+angle.toFixed(1)+" deg","Rail length: "+len.toFixed(1)+" ft"]}'],
['roof-sheathing', 'Estimate roof sheathing (plywood/OSB) needed.', 'Sheets = Roof area / 32 (4x8 sheets)', 'Standard sheet is 4x8ft = 32sqft. Add 10% for waste and hips/valleys. Roof pitch increases effective area.', [['length','Roof Length (ft)',1,0],['width','Roof Width (ft)',1,0],['pitch','Roof Pitch (in12)',1,4]], 'var l=n(v.length),w=n(v.width),p=n(v.pitch||"6");var pf=Math.sqrt(144+p*p)/12;var area=l*w*pf;var sheets=Math.ceil(area/32*1.1);return{result:sheets,label:"Sheets Needed",unit:"4x8 sheets",steps:["Base area: "+l+"x"+w+" = "+(l*w)+" sq ft","Pitch factor: "+pf.toFixed(2),"Actual area: "+area.toFixed(0)+" sq ft","Sheets: "+sheets+" (4x8)"]}'],
['downspout-spacing', 'Calculate recommended downspout placement.', 'Max spacing = 40ft per downspout (standard roof)', 'IRC: max 40ft between downspouts. Each downspout handles ~600sqft of roof area. Minimum 2 per building side.', [['roofArea','Roof Area (sq ft)',100,0],['gutterLength','Gutter Length (ft)',5,0]], 'var a=n(v.roofArea),l=n(v.gutterLength);var perDrain=a<1200?1:a<2400?2:3;var spacing=l/perDrain;return{result:spacing,label:"Downspout Spacing",unit:"ft",steps:["Roof area: "+a+" sq ft","Gutter length: "+l+" ft","Downspouts: "+perDrain,"Spacing: "+spacing.toFixed(0)+" ft OC"]}'],
['snow-guard', 'Calculate snow guard placement for metal roofs.', 'Guards = Roof length x 2 (per row) + staggered rows', 'Metal roofs need snow guards at eave edge + every 4ft up roof. Use 2 guards per 12in of roof edge.', [['roofLength','Roof Edge Length (ft)',1,0],['roofPitch','Roof Pitch (in12)',1,4]], 'var l=n(v.roofLength),p=n(v.roofPitch||"6");var perRow=Math.ceil(l*2);var rows=Math.ceil(Math.sqrt(144+p*p)/12*2);var total=perRow*rows;return{result:total,label:"Snow Guards",unit:"pcs",steps:["Edge: "+l+" ft","Guards per row: "+perRow,"Rows up roof: "+rows,"Total: "+total+" guards"]}'],
['skylight-size', 'Determine optimal skylight size for room lighting.', 'Skylight area = Room area x 0.05 (well factor)', 'Standard: skylight should be 5% of room area for good daylighting. Max 15% to avoid overheating. Well depth reduces effective area.', [['roomArea','Room Area (sq ft)',10,0],['wellDepth','Well Depth (ft)',0.5,0]], 'var a=n(v.roomArea),d=n(v.wellDepth||"0");var effArea=a*0.05;var wellLoss=Math.min(d*0.1,0.5);var skylight=effArea*(1+wellLoss);return{result:skylight,label:"Skylight Size",unit:"sq ft",steps:["Room: "+a+" sq ft","5% of room: "+(a*0.05).toFixed(0)+" sq ft","Skylight: "+skylight.toFixed(0)+" sq ft"]}'],
['door-jamb', 'Calculate door jamb dimensions and material.', 'Jamb length = 2 x height + width + 10% waste', 'Standard interior door: 80in height, 30-36in width. Jamb depth = wall thickness + 2 x 0.5in.', [['doorHeight','Door Height (in)',1,80],['doorWidth','Door Width (in)',1,30],['wallThick','Wall Thickness (in)',0.5,5.5]], 'var h=n(v.doorHeight),w=n(v.doorWidth),t=n(v.wallThick||"4.5");var jambLen=2*h+w+w*0.1;return{result:jambLen,label:"Jamb Length",unit:"in",steps:["Door: "+h+"x"+w+" in","Wall: "+t+" in thick","Jamb material: "+(jambLen/12).toFixed(1)+" ft"]}'],
['door-header', 'Size door header for load-bearing walls.', 'Header size = span x 1.5 (roof load) or span x 1.0 (floor load)', 'For 6ft span roof load: use 2x8. For 8ft span: use 2x10. Doubled 2x with 0.5in plywood spacer.', [['span','Span (in)',1,36],['loadType','Load Type',1,1]], 'var s=n(v.span),lt=n(v.loadType||"1");var factor=lt==1?1.5:1.0;var depth=s/12*factor;return{result:depth,label:"Header Depth",unit:"in",steps:["Span: "+s+" in = "+(s/12).toFixed(1)+" ft","Load factor: "+factor,"Depth: "+depth.toFixed(0)+" in"]}'],
['window-header', 'Size window header for load-bearing walls.', 'Header depth = Span / 12 x 1.25', 'Use doubled 2x lumber with plywood spacer. 2x4 for up to 3ft, 2x6 for 4-5ft, 2x8 for 6ft span.', [['span','Rough Opening Width (in)',1,24]], 'var s=n(v.span);var depth=Math.ceil(s/12*1.25);return{result:depth,label:"Header Depth",unit:"in",steps:["Opening: "+s+" in = "+(s/12).toFixed(1)+" ft","Use: "+depth+"in (e.g. 2x"+depth+")"]}'],
['window-well', 'Size window well for egress windows.', 'Well area = Window area x 1.5 (min 9sqft total)', 'IRC: egress well must provide min 9sqft at bottom. Project at least 36in from window. Ladder required if >44in deep.', [['windowWidth','Window Width (in)',1,28],['windowHeight','Window Height (in)',1,20],['wellDepth','Well Depth (in)',1,44]], 'var w=n(v.windowWidth),h=n(v.windowHeight),d=n(v.wellDepth||"44");var minArea=Math.max(w*h/144*1.5,9);return{result:minArea,label:"Min Well Floor Area",unit:"sq ft",steps:["Window: "+w+"x"+h+" in = "+(w*h/144).toFixed(0)+" sq ft","Min area: "+minArea.toFixed(1)+" sq ft"]}'],
['drywall-tape', 'Estimate drywall tape needed.', 'Tape (rolls) = Total joint length / 500 (ft per roll)', 'Standard rolls 500ft. Each 4x8 sheet has ~16ft of joints. Includes inside/outside corners.', [['sheets','Number of 4x8 Sheets',1,0]], 'var s=n(v.sheets);var jointLen=s*16;var rolls=Math.ceil(jointLen/500);return{result:rolls,label:"Tape Rolls",unit:"500ft rolls",steps:["Sheets: "+s,"Joint length: "+jointLen+" ft","Tape: "+rolls+" rolls"]}'],
['drywall-mud', 'Calculate drywall joint compound (mud) needed.', 'Mud (gallons) = Sheets x 0.1 (first coat)', 'Standard: 1 gal per 100 sq ft per coat. 3 coats: tape, fill, finish. Lightweight compound for best results.', [['sheets','Number of 4x8 Sheets',1,0],['coats','Number of Coats',1,3]], 'var s=n(v.sheets),c=n(v.coats||"3");var gal=s*0.1*c;return{result:gal,label:"Joint Compound",unit:"gal",steps:["Sheets: "+s+" sq ft = "+(s*32)+" sq ft","Coats: "+c,"Compound: "+gal.toFixed(1)+" gallons"]}'],
['corner-bead', 'Estimate corner bead lengths needed.', 'Bead (ft) = Outside corners x 8ft (per story)', 'Standard 8ft or 10ft lengths. Each outside corner needs one piece per floor. Use 1.5in bullnose for rounded corners.', [['corners','Number of Outside Corners',1,0],['ceilingHeight','Ceiling Height (ft)',0.5,8]], 'var c=n(v.corners),h=n(v.ceilingHeight||"8");var len=c*h;var pieces=Math.ceil(c*h/10);return{result:len,label:"Corner Bead",unit:"ft",steps:["Corners: "+c,"Height: "+h+" ft","Length: "+len+" ft","Pieces (10ft): "+pieces]}'],
['wainscoting-layout', 'Plan wainscoting panel layout.', 'Panels = Wall length / (panel_width + spacing)', 'Standard wainscoting: 32-42in height. Panel width typically 2-3ft. Equal spacing to avoid narrow end panels.', [['wallLength','Wall Length (in)',1,0],['panelWidth','Panel Width (in)',1,24],['spacing','Spacing (in)',0.5,2]], 'var l=n(v.wallLength),w=n(v.panelWidth||"24"),s=n(v.spacing||"2");var panels=Math.floor((l+s)/(w+s));var leftover=l-(panels*w+(panels-1)*s);return{result:panels,label:"Number of Panels",unit:"",steps:["Wall: "+l+" in","Panel width: "+w+" in at "+s+"in spacing","Panels: "+panels,"Remainder: "+leftover.toFixed(1)+" in"]}'],
['chair-rail-height', 'Calculate optimal chair rail height.', 'Classic height = Wall height x 0.33 | Modern = 36-42in', 'Traditional: 1/3 wall height. Standard: 32-36in for 8ft ceiling, 36-42in for 9ft+. Consider window trim alignment.', [['ceilingHeight','Ceiling Height (ft)',0.5,8]], 'var h=n(v.ceilingHeight||"8");var classic=h*12*0.33;var modern=Math.min(42,Math.max(32,classic));return{result:modern,label:"Chair Rail Height",unit:"in",steps:["Ceiling: "+h+" ft = "+(h*12)+" in","Classic (1/3): "+classic.toFixed(0)+" in","Recommended: "+modern+" in"]}'],
['baseboard-length', 'Calculate baseboard trim needed.', 'Baseboard = Perimeter - door_widths + 10% waste', 'Measure each wall separately. Subtract door openings at base. Add 10% for miters and waste.', [['perimeter','Room Perimeter (ft)',1,0],['doors','Number of Doors',1,1]], 'var p=n(v.perimeter),d=n(v.doors||"1");var net=p-d*3;var total=net*1.1;return{result:total,label:"Baseboard Length",unit:"ft",steps:["Perimeter: "+p+" ft","Less doors: "+(d*3)+" ft","Net: "+net+" ft","With 10% waste: "+total.toFixed(0)+" ft"]}'],
['shoe-molding', 'Calculate shoe molding (quarter round) needed.', 'Shoe = Perimeter + 10% waste', 'Shoe molding covers expansion gap between floor and baseboard. Same length as baseboard minus doorways. Miter at corners.', [['perimeter','Room Perimeter (ft)',1,0]], 'var p=n(v.perimeter);var total=p*1.1;return{result:total,label:"Shoe Molding",unit:"ft",steps:["Perimeter: "+p+" ft","With waste: "+total.toFixed(0)+" ft"]}'],
['door-casing', 'Calculate door casing trim lengths.', 'Casing = 2 x height + width + 15% waste', 'Standard casing: 2.25-3.5in wide. Mitered corners at 45 degrees. Add length for returns.', [['doorHeight','Door Height (in)',1,80],['doorWidth','Door Width (in)',1,30]], 'var h=n(v.doorHeight),w=n(v.doorWidth);var len=(2*h+w)/12*1.15;return{result:len,label:"Casing Length",unit:"ft",steps:["Door: "+h+"x"+w+" in","Casing length: "+len.toFixed(1)+" ft"]}'],
['window-trim', 'Calculate window casing and stool trim.', 'Trim = 2 x height + 2 x width + 15% waste', 'Includes casing (sides/top) and stool (bottom). Standard stool projects 1-2in beyond casing.', [['windowHeight','Window Height (in)',1,36],['windowWidth','Window Width (in)',1,30]], 'var h=n(v.windowHeight),w=n(v.windowWidth);var len=(2*h+2*w)/12*1.15;return{result:len,label:"Window Trim",unit:"ft",steps:["Window: "+h+"x"+w+" in","Trim length: "+len.toFixed(1)+" ft"]}'],
['picture-rail', 'Calculate picture rail molding needed.', 'Rail = Perimeter + 10% waste, at 1/6 wall height from ceiling', 'Victorian style: installed 6-18in below ceiling. Width 1.5-3in. Supports hanging wires with hooks.', [['perimeter','Room Perimeter (ft)',1,0],['ceilingHeight','Ceiling Height (ft)',0.5,8]], 'var p=n(v.perimeter),h=n(v.ceilingHeight||"8");var height=h*12/6;var len=p*1.1;return{result:len,label:"Picture Rail",unit:"ft",steps:["Perimeter: "+p+" ft","Install at: "+height.toFixed(0)+" in from ceiling","Length: "+len.toFixed(0)+" ft"]}'],
['built-in-shelving', 'Plan built-in shelving dimensions and materials.', 'Shelves = Width x depth x shelves x material_factor', 'Standard shelf depth: 12in for books, 16in for storage. Shelf span max 36in for 0.75in material. Adjustable shelf pins every 2in.', [['width','Unit Width (in)',1,48],['height','Unit Height (in)',1,84],['depth','Shelf Depth (in)',1,12]], 'var w=n(v.width),h=n(v.height),d=n(v.depth||"12");var shelves=Math.floor(h/14);var boardFt=w*h/144*1.15;return{result:shelves,label:"Number of Shelves",unit:"",steps:["Opening: "+w+"x"+h+"in depth "+d+"in","Max shelves: "+shelves+" at 14in spacing","Plywood: "+boardFt.toFixed(0)+" sq ft"]}'],
['closet-rod-length', 'Calculate closet rod length and support spacing.', 'Rod supports = Rod length / 48in intervals', 'Max unsupported rod span: 48in for wood, 60in for metal. Heavy coats: reduce to 36in. Double rod: upper at 80in, lower at 42in.', [['closetWidth','Closet Width (in)',1,60]], 'var w=n(v.closetWidth);var supports=Math.ceil(w/48);return{result:supports,label:"Rod Supports",unit:"",steps:["Closet width: "+w+" in","Rod length: "+w+" in","Supports: "+supports]}'],
['garage-shelving', 'Plan garage shelving layout.', 'Shelf area = Width x depth x levels', 'Standard garage shelf: 24in deep, 48-96in long, mounted 18in above floor. Heavy items: max 50lbs per linear ft.', [['wallWidth','Available Wall Width (ft)',1,0],['shelfDepth','Shelf Depth (in)',1,24],['levels','Number of Shelf Levels',1,3]], 'var w=n(v.wallWidth),d=n(v.shelfDepth||"24"),l=n(v.levels||"3");var area=w*d/12*l;return{result:area,label:"Shelf Area",unit:"sq ft",steps:["Wall: "+w+" ft, depth "+d+" in","Levels: "+l,"Total shelf area: "+area.toFixed(0)+" sq ft"]}'],
['workbench-height', 'Calculate optimal workbench height for tasks.', 'Bench height = 0.53 x height (precision) to 0.61 x height (heavy)', 'Precision (36-42in): 0.53xheight. Light (34-37in): 0.57xheight. Heavy (30-34in): 0.61xheight.', [['userHeight','Your Height (in)',1,69],['workType','Work Type',1,1]], 'var h=n(v.userHeight),wt=n(v.workType||"1");var labels=["Precision (fine work)","General (light assembly)","Heavy (woodworking)"];var factors=[0.53,0.57,0.61];var bench=h*factors[Math.min(wt,3)-1];return{result:bench,label:"Bench Height",unit:"in",steps:["Height: "+h+" in","Type: "+labels[Math.min(wt,3)-1],"Bench height: "+bench.toFixed(0)+" in"]}'],
['shop-lighting', 'Calculate workshop lighting requirements.', 'Lumens = Area x foot-candle requirement', 'General workshop: 50-75 fc. Detail work: 100-150 fc. LED: ~100 lumens/watt. 4ft LED strip: ~4000 lumens.', [['length','Room Length (ft)',1,0],['width','Room Width (ft)',1,0],['fc','Target Foot-Candles',10,50]], 'var l=n(v.length),w=n(v.width),fc=n(v.fc||"75");var area=l*w;var lumens=area*fc;var fixtures=Math.ceil(lumens/4000);return{result:lumens,label:"Required Lumens",unit:"lm",steps:["Area: "+l+"x"+w+" = "+area+" sq ft","Target: "+fc+" fc","Lumens: "+lumens.toFixed(0)+" lm","4ft LED strips: "+fixtures]}'],
['driveway-slope', 'Calculate driveway slope for proper drainage.', 'Grade (%) = Rise / Run x 100', 'Recommended: 1-5% slope (1/8-5/8in per ft). Min 1% for drainage. Max 15% for passenger vehicles.', [['rise','Total Rise (in)',0.25,0],['run','Total Run (in)',12,0]], 'var r=n(v.rise),u=n(v.run);var grade=r/u*100;var fpt=r/(u/12);var msg=grade<1?"Too flat, add slope":grade>15?"Too steep for cars":"Acceptable";return{result:grade,label:"Slope",unit:"%",steps:["Rise: "+r+" in over "+u+" in run","Grade: "+grade.toFixed(2)+"% = "+fpt.toFixed(3)+" in/ft",msg]}'],
['driveway-thickness', 'Determine concrete driveway thickness.', 'Thickness = 4in (cars) to 6in (trucks) + base', 'Passenger cars: 4in concrete + 4in base. Light trucks: 5in + 4in base. Heavy vehicles: 6in + 6in base.', [['vehicle','Vehicle Type',1,1],['baseType','Base Type',1,1]], 'var vt=n(v.vehicle||"1");var thick=[4,5,6];var labels=["Passenger cars","Light trucks","Heavy vehicles"];return{result:thick[Math.min(vt,3)-1],label:"Slab Thickness",unit:"in",steps:["Use: "+labels[Math.min(vt,3)-1],"Concrete: "+thick[Math.min(vt,3)-1]+"in"]}'],
['parking-stall', 'Calculate parking stall dimensions.', 'Standard stall: 9ft x 18ft (90deg) | Compact: 8ft x 16ft', 'Standard: 9x18ft (9x20ft for ADA accessible). 60deg: 9x20ft. Parallel: 8x22ft. ADA: 8ft + 5ft access aisle.', [['angle','Angle (degrees)',1,90]], 'var a=n(v.angle||"90");var w=a==90?9:a==60?9:8;var l=a==90?18:a==60?20:22;return{result:w+"x"+l,label:"Stall Size",unit:"ft",steps:["Angle: "+a+" degrees","Width: "+w+" ft","Length: "+l+" ft"]}'],
['sidewalk-slope', 'Calculate proper sidewalk slope for drainage and ADA.', 'Slope = 1/4in per ft (2%) max for ADA, 1/8in per ft (1%) min', 'ADA max cross slope: 2% (1/4in per ft). Min for drainage: 1% (1/8in per ft). Running slope max 5% without landing.', [['length','Sidewalk Length (ft)',1,0],['desiredSlope','Desired Slope (in/ft)',0.125,0.25]], 'var l=n(v.length),s=n(v.desiredSlope||"0.25");var rise=l*s;var grade=s/12*100;return{result:rise,label:"Total Rise",unit:"in",steps:["Length: "+l+" ft","Slope: "+s+" in/ft = "+grade.toFixed(2)+"%","Rise: "+rise.toFixed(1)+" in"]}'],
['curb-ramp', 'Design ADA-compliant curb ramp dimensions.', 'Ramp length = Curb height x 12 (ADA 1:12 max)', 'ADA: max 1:12 slope (8.33%). Min width 36in. Flared sides max 1:10. Detectable warning required.', [['curbHeight','Curb Height (in)',0.5,6],['width','Ramp Width (in)',1,48]], 'var h=n(v.curbHeight),w=n(v.width||"48");var rampLen=h*12;return{result:rampLen,label:"Ramp Length",unit:"in",steps:["Curb: "+h+" in","Min length (1:12): "+rampLen+" in = "+(rampLen/12).toFixed(1)+" ft","Width: "+w+" in = "+(w/12).toFixed(0)+" ft"]}'],
['as-built', 'Calculate as-built measurement adjustments.', 'True distance = Measured x tape_correction factor', 'Tape correction accounts for temperature, tension, and sag. Standard: 100ft steel tape at 68F, 10lb tension, fully supported.', [['measured','Measured Distance (ft)',1,0],['corrFactor','Correction Factor',0.00001,1]], 'var m=n(v.measured),c=n(v.corrFactor||"1");var trueDist=m*c;return{result:trueDist,label:"True Distance",unit:"ft",steps:["Measured: "+m+" ft","Factor: "+c,"True: "+trueDist.toFixed(2)+" ft"]}'],
['tape-correction', 'Calculate steel tape temperature correction.', 'Ct = 0.00000645 x L x (T - 68)', 'Steel expansion coefficient: 0.00000645 per deg F. Add to measured length if above 68F, subtract if below.', [['length','Measured Length (ft)',1,0],['temp','Temperature (F)',1,68]], 'var l=n(v.length),t=n(v.temp||"68");var ct=0.00000645*l*(t-68);var corr=l+ct;return{result:corr,label:"Corrected Length",unit:"ft",steps:["Measured: "+l+" ft at "+t+"F","Correction: "+ct.toFixed(4)+" ft","True: "+corr.toFixed(2)+" ft"]}'],
['survey-baseline', 'Calculate survey baseline distance and accuracy.', 'Baseline = Measured x (1 + 1/1000000)', 'EGP baseline accuracy: 1:1,000,000 or better. Multiple measurements required. Temperature and pressure correction applied.', [['measured','Measured Distance (m)',1,0]], 'var m=n(v.measured);var corr=m*(1+1/1000000);var error=m/1000000;return{result:corr,label:"Baseline Distance",unit:"m",steps:["Measured: "+m+" m","Error: "+error.toFixed(3)+" m","Corrected: "+corr.toFixed(3)+" m"]}'],
['traverse-closure', 'Calculate traverse closure error and adjustment.', 'Closure = sqrt(dE2 + dN2) / Perimeter', 'Allowable error depends on survey class. First-order: 1:10,000. Second-order: 1:5,000. Third-order: 1:2,000.', [['dE','Latitude Error (ft)',0.001,0],['dN','Departure Error (ft)',0.001,0],['perimeter','Traverse Perimeter (ft)',1,0]], 'var de=n(v.dE),dn=n(v.dN),p=n(v.perimeter);var closure=Math.sqrt(de*de+dn*dn)/p;var ratio=closure>0?1/closure:0;return{result:ratio>0?ratio:0,label:"Closure Ratio",unit:"1:",steps:["dE: "+de+" ft, dN: "+dn+" ft","Closure: "+(closure*100).toFixed(4)+"%","Ratio: 1:"+(ratio>0?ratio.toFixed(0):"N/A")]}'],
['leveling-net', 'Calculate leveling network adjustment.', 'Misclosure = Σ backsight - Σ foresight - known ΔH', 'Allowable: ±0.007ft x sqrt(distance in miles) for first-order. Differential leveling with turning points.', [['bsSum','Sum of Backsights (ft)',0.001,0],['fsSum','Sum of Foresights (ft)',0.001,0],['knownDH','Known Elevation Diff (ft)',0.001,0]], 'var bs=n(v.bsSum),fs=n(v.fsSum),kdh=n(v.knownDH);var mis=bs-fs-kdh;return{result:mis,label:"Misclosure",unit:"ft",steps:["BS sum: "+bs.toFixed(3)+" ft","FS sum: "+fs.toFixed(3)+" ft","Misclosure: "+mis.toFixed(3)+" ft"]}'],
['contour-interval', 'Determine contour interval for topographic maps.', 'CI = 1/2000 x scale denominator (imperial: 1/1000)', 'Flat terrain: 1ft, Rolling: 2-5ft, Mountainous: 10-25ft. Map scale 1:24000 typically uses 5-10ft CI.', [['scale','Map Scale Denominator',1000,24000],['terrain','Terrain Type',1,1]], 'var s=n(v.scale),t=n(v.terrain||"1");var factors=[1,2,5,10];var ci=Math.round(s/2000)*factors[Math.min(t,4)-1]/10;return{result:ci,label:"Contour Interval",unit:"ft",steps:["Scale: 1:"+s,"CI: "+ci.toFixed(1)+" ft"]}'],
['slope-stake', 'Calculate slope stake offset for construction.', 'Offset = Cut/Fill x slope_ratio', 'Common slopes: 1:1 (45 deg), 1.5:1 (34 deg), 2:1 (26 deg). Stake offset from centerline at each station.', [['height','Cut/Fill Height (ft)',0.5,0],['slopeRatio','Slope Ratio (H:V)',0.5,1.5]], 'var h=n(v.height),sr=n(v.slopeRatio||"1.5");var offset=h*sr;return{result:offset,label:"Slope Stake Offset",unit:"ft",steps:["Cut/Fill: "+h+" ft","Slope: "+sr+":1","Offset: "+offset.toFixed(2)+" ft from hinge"]}'],
['cut-fill-calc', 'Calculate cut and fill volumes for earthwork.', 'Volume = Area x Average depth (end area method)', 'Use cross-section end areas at regular stations. Cut and fill balanced for mass haul. Shrinkage/swell factor: 1.25 for clay, 1.15 for sand.', [['area1','Cross-section Area 1 (sq ft)',1,0],['area2','Cross-section Area 2 (sq ft)',1,0],['stationDist','Station Distance (ft)',1,50]], 'var a1=n(v.area1),a2=n(v.area2),d=n(v.stationDist||"50");var vol=(a1+a2)/2*d/27;return{result:vol,label:"Volume",unit:"cu yd",steps:["Area 1: "+a1+" sq ft, Area 2: "+a2+" sq ft","Avg area: "+((a1+a2)/2).toFixed(0)+" sq ft","Volume: "+vol.toFixed(1)+" cu yd"]}'],
['excavation-slope', 'Calculate excavation slope angles for safety.', 'Slope angle = atan(1/slope_ratio) | Max = 1.5:1 (34 deg)', 'OSHA Type A: 0.75:1 (53 deg). Type B: 1:1 (45 deg). Type C: 1.5:1 (34 deg). Benching required >20ft depth.', [['soilType','Soil Type',1,1],['depth','Excavation Depth (ft)',1,0]], 'var st=n(v.soilType||"1"),d=n(v.depth);var ratios=[0.75,1,1.5];var labels=["Type A (stable)","Type B (moderate)","Type C (unstable)"];var r=ratios[Math.min(st,3)-1];var angle=Math.atan2(1,r)*180/Math.PI;var width=d*r;return{result:angle,label:"Slope Angle",unit:"deg",steps:["Soil: "+labels[Math.min(st,3)-1],"Ratio: "+r+":1","Angle: "+angle.toFixed(1)+" deg","Width at top: "+width.toFixed(1)+" ft"]}'],
['trench-safety', 'Calculate trench safety requirements per OSHA.', 'Protection required >5ft depth >20ft = engineered', 'OSHA: less than 5ft can be stable. 5-20ft requires shoring, shielding, or sloping. Over 20ft requires engineered design.', [['depth','Trench Depth (ft)',0.5,0],['length','Trench Length (ft)',1,0],['soilType','Soil Type',1,1]], 'var d=n(v.depth),l=n(v.length),st=n(v.soilType);var req=d>5?(d>20?"Engineered design required":"Shoring/shielding/sloping required"):"No protection required";var spoil=d*2;return{result:req,label:"Protection Requirement",unit:"",steps:["Depth: "+d+" ft","Spoil min distance: "+spoil.toFixed(0)+" ft",req]}'],
['cofferdam-design', 'Calculate cofferdam sheet pile requirements.', 'Depth = H x (gw / geff) x FS', 'Sheet pile cofferdam: cantilever or braced. Cantilever max ~15ft for light conditions. Braced for deeper excavations.', [['waterDepth','Water Depth (ft)',1,0],['excavDepth','Excavation Depth (ft)',1,0]], 'var wd=n(v.waterDepth),ed=n(v.excavDepth);var pileDepth=Math.max(wd+ed,wd*1.5)+5;return{result:pileDepth,label:"Pile Depth",unit:"ft",steps:["Water: "+wd+" ft, Excavation: "+ed+" ft","Estimated pile depth: "+pileDepth.toFixed(0)+" ft"]}'],
['dewatering-flow', 'Calculate dewatering flow rate for excavations.', 'Q = k x H x L / R (Dupuit equation)', 'k = hydraulic conductivity (ft/day). H = head (ft). L = excavation length (ft). R = radius of influence (~100-1000ft for sand).', [['k','Hydraulic Conductivity (ft/day)',0.1,10],['head','Head Difference (ft)',1,0],['length','Excavation Length (ft)',1,0]], 'var k=n(v.k||"10"),h=n(v.head),l=n(v.length);var q=k*h*l/200;return{result:q,label:"Flow Rate",unit:"gpm",steps:["k="+k+" ft/day, head="+h+" ft","Q: "+q.toFixed(1)+" gpm"]}'],
['pile-driving', 'Estimate pile driving capacity and requirements.', 'Capacity = (Wxh)/(S+0.1) x 2 (Engineering News formula)', 'ENR formula: allowable capacity = 2Wh/(S+0.1). W=hammer weight (kips), h=fall (ft), S=set (in/blow). Safety factor 2-6.', [['hammerWt','Hammer Weight (kips)',0.5,5],['drop','Hammer Drop (ft)',0.5,3],['setSet','Set (in/blow)',0.01,0.25]], 'var w=n(v.hammerWt),h=n(v.drop),s=n(v.setSet||"0.1");var cap=2*w*h/(s+0.1);return{result:cap,label:"Allowable Capacity",unit:"kips",steps:["Hammer: "+w+" kips, drop "+h+" ft","Set: "+s+" in/blow","Capacity: "+cap.toFixed(1)+" kips"]}'],
['drilled-shaft', 'Calculate drilled shaft (caisson) dimensions.', 'Capacity = End bearing + Skin friction (alpha-method)', 'Drilled shafts: 2-10ft diameter, up to 100ft+ deep. End bearing in rock: 50-100ksf. Skin friction varies by soil type.', [['diameter','Shaft Diameter (ft)',0.5,3],['depth','Shaft Depth (ft)',1,0],['endBearing','End Bearing Capacity (ksf)',1,50]], 'var d=n(v.diameter),dep=n(v.depth),eb=n(v.endBearing||"50");var endArea=Math.PI*d*d/4;var endCap=endArea*eb;var skinCap=dep*Math.PI*d*2;return{result:endCap+skinCap,label:"Estimated Capacity",unit:"kips",steps:["Diameter: "+d+" ft, Depth: "+dep+" ft","End bearing: "+endCap.toFixed(0)+" kips","Skin friction: "+skinCap.toFixed(0)+" kips"]}'],
['helical-pile', 'Calculate helical pile capacity and sizing.', 'Capacity = sum(helix_area x bearing_capacity)', 'Helical piles: 1.5-3in shaft, 8-14in helix plates. Min 2 helixes, 3D spacing. Torque correlation: capacity = torque x 10 (kips).', [['helixDiam','Helix Diameter (in)',1,10],['numHelix','Number of Helices',1,2],['torqueM','Installation Torque (ft-lbs)',100,0]], 'var d=n(v.helixDiam||"10"),nh=n(v.numHelix||"2"),t=n(v.torqueM);var area=nh*Math.PI*d*d/4/144;var cap=t*10/1000;return{result:cap,label:"Compression Capacity",unit:"kips",steps:["Helix: "+d+"in x "+nh+" = "+area.toFixed(2)+" sq ft","Torque: "+t+" ft-lbs","Capacity: "+cap.toFixed(1)+" kips"]}'],
['tieback-anchor', 'Design tieback anchor for retaining walls.', 'Capacity = Bond_length x grout_diameter x bond_stress', 'Tiebacks: 15-30 degree inclination. Bond zone in competent soil/rock. Grout diameter: 6-12in. Bond stress: 5-20psi.', [['bondLen','Bond Length (ft)',1,20],['groutDiam','Grout Hole Diameter (in)',1,8],['bondStress','Bond Stress (psi)',1,10]], 'var l=n(v.bondLen),d=n(v.groutDiam||"8"),s=n(v.bondStress||"10");var area=l*d/12*Math.PI*144;var cap=area*s/1000;return{result:cap,label:"Anchor Capacity",unit:"kips",steps:["Bond length: "+l+" ft, diameter: "+d+" in","Capacity: "+cap.toFixed(0)+" kips"]}'],
['shotcrete-thickness', 'Calculate shotcrete thickness for slope stabilization.', 'Thickness = 4-6in for temporary, 6-12in for permanent', 'Temporary slope stabilization: 4-6in with WWF. Permanent: 6-12in with rebar. Max unsupported span: 15ft.', [['type','Application Type',1,1],['slopeHeight','Slope Height (ft)',1,0]], 'var t=n(v.type||"1"),sh=n(v.slopeHeight);var thick=t==1?6:10;var rebar=thick>6?"#4 @ 12in OC":"WWF 6x6 W2.9";return{result:thick,label:"Shotcrete Thickness",unit:"in",steps:["Type: "+(t==1?"Temporary":"Permanent"),"Thickness: "+thick+" in","Reinforcement: "+rebar]}'],
['grout-consolidation', 'Estimate grout volume for soil consolidation.', 'Grout = Porosity x treatment_volume x (1 + waste)', 'Permeation grouting: fine sand 20-40% porosity. Fracture grouting: larger volume. Waste factor: 20-30% for bleed/leakage.', [['porosity','Soil Porosity (%)',1,20],['length','Treatment Length (ft)',1,0],['width','Treatment Width (ft)',1,0],['depth','Treatment Depth (ft)',1,0]], 'var p=n(v.porosity||"20"),l=n(v.length),w=n(v.width),d=n(v.depth);var vol=l*w*d*p/100*1.25;return{result:vol,label:"Grout Volume",unit:"cu ft",steps:["Treatment: "+l+"x"+w+"x"+d+" ft","Porosity: "+p+"%","Grout: "+vol.toFixed(0)+" cu ft"]}'],
['cold-joint', 'Calculate cold joint spacing in concrete placement.', 'Max interval = Initial set time / placement rate', 'Cold joint occurs when new concrete placed on partially set concrete (typically >2 hours delay in hot weather).', [['setTime','Initial Set Time (hours)',0.25,2],['pourRate','Placement Rate (cu yd/hr)',1,0]], 'var st=n(v.setTime||"2"),pr=n(v.pourRate);var maxVol=st*pr;return{result:maxVol,label:"Max Volume per Lift",unit:"cu yd",steps:["Set time: "+st+" hours","Rate: "+pr+" cu yd/hr","Max: "+maxVol.toFixed(0)+" cu yd"]}'],
['control-joint', 'Calculate control joint spacing for concrete slabs.', 'Joint spacing = Slab thickness x 24-36 (in)', 'Interior slabs: 2-3x thickness in feet (e.g., 4in slab to 8-12ft). Exterior: 1.5x. Max 15ft. Cut 1/4 depth within 24hrs.', [['slabThick','Slab Thickness (in)',0.5,4],['exposure','Exposure',1,1]], 'var t=n(v.slabThick),e=n(v.exposure||"1");var factor=e==1?30:24;var spacing=t*factor/12;return{result:spacing,label:"Joint Spacing",unit:"ft",steps:["Slab: "+t+" in "+(e==1?"interior":"exterior"),"Spacing: "+spacing.toFixed(0)+" ft"]}'],
['isolation-joint', 'Calculate isolation joint material needs.', 'Joint material = Perimeter x joint_thickness', 'Isolate slabs from columns, walls, and footings. Use 0.5-1in compressible filler (asphalt-impregnated fiberboard).', [['perimeter','Perimeter (ft)',1,0],['jointThick','Joint Thickness (in)',0.25,0.5]], 'var p=n(v.perimeter),jt=n(v.jointThick||"0.5");var area=p*jt/12;return{result:area,label:"Joint Material",unit:"sq ft",steps:["Perimeter: "+p+" ft","Thickness: "+jt+" in","Material: "+area.toFixed(2)+" sq ft"]}'],
['waterstop', 'Calculate waterstop requirements for construction joints.', 'Waterstop length = Joint length x 1.1 (overlaps)', 'PVC waterstop: 6-9in wide. Minimum 4in embedment each side. Lap splices: 4in minimum. Use at below-grade construction joints.', [['jointLength','Joint Length (ft)',1,0],['jointType','Joint Type',1,1]], 'var l=n(v.jointLength),jt=n(v.jointType||"1");var len=l*1.1;return{result:len,label:"Waterstop Length",unit:"ft",steps:["Joint: "+l+" ft","With laps: "+len.toFixed(1)+" ft"]}'],
['scaffold-ties', 'Calculate scaffold tie spacing and requirements.', 'Tie spacing = 30ft horizontal x 26ft vertical (light duty)', 'OSHA: ties required when height > 4x base width. Max horizontal: 30ft. Max vertical: 26ft. Use 5000lb rated ties.', [['scaffoldHeight','Scaffold Height (ft)',1,0],['scaffoldWidth','Scaffold Width (ft)',1,5]], 'var h=n(v.scaffoldHeight),w=n(v.scaffoldWidth);var req=h>4*w;return{result:req?"Ties required":"No ties needed",label:"Result",unit:"",steps:["Height: "+h+" ft, width: "+w+" ft",req?"Ties required at max 26ft vertical":"No ties needed - height less than 4x width"]}'],
['ladder-angle', 'Calculate safe ladder angle and placement.', 'Angle = arccos(base/height) | 4:1 rule: base at 1ft for 4ft height', 'OSHA 4:1 rule: base 1ft out for every 4ft of height (about 75.5 degrees). Extension ladder: extend 3ft above landing.', [['ladderHeight','Ladder Working Height (ft)',1,0]], 'var h=n(v.ladderHeight);var base=h/4;var angle=Math.acos(base/h)*180/Math.PI;return{result:angle,label:"Safe Angle",unit:"deg",steps:["Ladder: "+h+" ft","Base out: "+base.toFixed(1)+" ft (4:1 rule)","Angle: "+angle.toFixed(1)+" deg"]}'],
['fall-protection', 'Calculate fall protection lanyard requirements.', 'Total fall distance = lanyard + deceleration + D-ring to feet + safety factor', '6ft lanyard + 3.5ft deceleration + 5ft D-ring height + 2ft safety = 16.5ft min clearance. PFAS required for >6ft in construction.', [['lanyardLen','Lanyard Length (ft)',0.5,6],['workingHeight','Working Height (ft)',1,0]], 'var ll=n(v.lanyardLen||"6"),wh=n(v.workingHeight);var fallDist=ll+3.5+5+2;return{result:fallDist,label:"Min Clearance",unit:"ft",steps:["Lanyard: "+ll+" ft, decel: 3.5 ft, D-ring: 5 ft, safety: 2 ft","Total fall distance: "+fallDist.toFixed(1)+" ft",wh>fallDist?"SAFE":"NEED SHORTER LANYARD"]}'],
['confined-space', 'Calculate confined space ventilation requirements.', 'Ventilation = 6 air changes/hour min', 'OSHA: 19.5-23.5% O2. Ventilation rate: 2000 cfm minimum for general space. Continuous monitoring required for permit spaces.', [['length','Space Length (ft)',1,0],['width','Space Width (ft)',1,0],['height','Space Height (ft)',1,0]], 'var l=n(v.length),w=n(v.width),h=n(v.height);var vol=l*w*h;var cfm=vol*6/60;return{result:cfm,label:"Required Ventilation",unit:"cfm",steps:["Space: "+l+"x"+w+"x"+h+" = "+vol+" cu ft","Changes: 6/hour = "+cfm.toFixed(0)+" cfm"]}'],
['lockout-tagout', 'Calculate lockout/tagout device requirements.', 'Locks = Energy sources x workers + 1 group lock', 'OSHA: each worker needs personal lock. Group LOTO uses hasp with multiple locks. Verify zero energy state after application.', [['energySources','Energy Sources',1,1],['workers','Number of Workers',1,1]], 'var es=n(v.energySources),wk=n(v.workers);var locks=es*wk+1;return{result:locks,label:"Locks Required",unit:"",steps:["Energy sources: "+es+", workers: "+wk,"Locks: "+locks]}'],
['hoist-speed', 'Calculate hoist lifting speed and capacity.', 'Speed = Motor power x efficiency / Load', 'Typical construction hoist: 100-200 ft/min. Material hoist: 50-100 ft/min. Factor of safety: 5:1 for personnel, 3:1 for material.', [['load','Load Weight (lbs)',100,0],['motorHP','Motor Power (HP)',1,5]], 'var l=n(v.load),hp=n(v.motorHP||"5");var speed=hp*33000*0.8/l;return{result:speed,label:"Lifting Speed",unit:"ft/min",steps:["Load: "+l+" lbs, motor: "+hp+" HP","Speed: "+speed.toFixed(0)+" ft/min"]}'],
];

// Read group5.ts
var fp = 'src/lib/constructionCalcDefs/group5.ts';
var c = fs.readFileSync(fp, 'utf8');

// Find the closing of the calcDefsGroup5 object
var idx = c.lastIndexOf('};\n');
if (idx < 0) idx = c.lastIndexOf('};');
if (idx < 0) idx = c.lastIndexOf('\n}');
if (idx < 0) { console.log('ERROR: cannot find closing of group5'); process.exit(1); }

// Generate entries
var out = '';
slugs.forEach(function(s) {
  out += "\n'" + s[0] + "': {\n    schema: z.object({";
  var fields = s[4];
  fields.forEach(function(f, i) {
    if (i > 0) out += ', ';
    out += f[0] + ': z.string()';
  });
  out += ' }),\n    fields: [\n';
  fields.forEach(function(f) {
    out += '      { name: \'' + f[0] + '\', label: \'' + f[1] + '\', step: ' + f[2] + ', min: ' + f[3] + ' },\n';
  });
  out += '    ],\n    compute: (v: Record<string, string>) => {\n      ' + s[5] + '\n    },\n';
  out += '    description: \'' + s[1] + '\',\n';
  out += '    formula: \'' + s[2] + '\',\n';
  out += '    interpretation: \'' + s[3] + '\',\n';
  out += '  },';
});

c = c.substring(0, idx-1) + out + '\n' + c.substring(idx-1);
fs.writeFileSync(fp, c);
console.log('Added ' + slugs.length + ' construction entries to group5.ts');
