const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'components', 'hub-calculators', 'GenericEducationCalculator.tsx');
let content = fs.readFileSync(filePath, 'utf8');

// Build entries as a plain string - no JS template literals to avoid ${} conflicts with TypeScript code
var entries = [];

entries.push("  'scholarship-calc': { schema: z.object({ gpa: z.string(), testScore: z.string(), activities: z.string(), essays: z.string(), recommendations: z.string() }), fields: [{ name: 'gpa', label: 'GPA (4.0 scale)', step: 0.01, min: 0, max: 4 }, { name: 'testScore', label: 'Test Score (SAT/ACT)', step: 10, min: 0 }, { name: 'activities', label: 'Activities Impact (1-10)', step: 1, min: 1, max: 10 }, { name: 'essays', label: 'Essay Quality (1-10)', step: 1, min: 1, max: 10 }, { name: 'recommendations', label: 'Recommendations (1-10)', step: 1, min: 1, max: 10 }], compute: (v) => { var score = n(v.gpa)/4*25 + Math.min(n(v.testScore)/1600*20,20) + n(v.activities)*5 + n(v.essays)*5 + n(v.recommendations)*5; return { result: Math.min(100,score), label: 'Scholarship Competitiveness', unit: '%', steps: ['GPA: ' + n(v.gpa).toFixed(2) + '/4.0 (' + (n(v.gpa)/4*25).toFixed(0) + ' pts)', 'Test: ' + n(v.testScore).toFixed(0) + ' (' + Math.min(n(v.testScore)/1600*20,20).toFixed(0) + ' pts)', 'Activities: ' + n(v.activities) + ' (' + (n(v.activities)*5).toFixed(0) + ' pts)', 'Essays: ' + n(v.essays) + ' (' + (n(v.essays)*5).toFixed(0) + ' pts)', 'Recs: ' + n(v.recommendations) + ' (' + (n(v.recommendations)*5).toFixed(0) + ' pts)', 'Total: ' + score.toFixed(0) + '/100'] } }, description: 'Evaluate scholarship application competitiveness.', formula: 'Score = GPA pts + Test pts + Activities*5 + Essays*5 + Recs*5', interpretation: 'Score > 80: strong candidate. 60-80: competitive. < 60: improve profile.' },");

entries.push("  'recommendation-requests': { schema: z.object({ schools: z.string(), recommenders: z.string(), deadline: z.string(), waiveRight: z.string() }), fields: [{ name: 'schools', label: 'Number of Schools', step: 1, min: 1 }, { name: 'recommenders', label: 'Number of Recommenders', step: 1, min: 1 }, { name: 'deadline', label: 'Days Until Deadline', step: 1, min: 1 }, { name: 'waiveRight', label: 'Waive FERPA Right?', type: 'select', options: [{ label: 'Yes, waive right', value: 'yes' }, { label: 'No, keep right', value: 'no' }] }], compute: (v) => { var totalRequests = n(v.schools) * n(v.recommenders); var perDay = totalRequests / Math.max(1, n(v.deadline)); var recsPerRecommender = n(v.schools); return { result: totalRequests, label: 'Total Recommendation Requests', unit: '', steps: ['Schools: ' + n(v.schools), 'Recommenders: ' + n(v.recommenders), 'Total requests: ' + totalRequests, 'Per recommender: ' + recsPerRecommender + ' letters', 'Need ' + perDay.toFixed(1) + ' request(s) per day', String(v.waiveRight) === 'yes' ? 'Waiving FERPA right = stronger letters' : 'Not waiving may weaken letters' ] } }, description: 'Manage recommendation letter requests.', formula: 'Requests = Schools x Recommenders', interpretation: 'Give recommenders 3-4 weeks. Waive FERPA right for stronger letters. Send reminders 2 weeks before deadline.' },");

entries.push("  'corneil-notes': { schema: z.object({ pages: z.string(), cues: z.string(), notes: z.string(), summary: z.string() }), fields: [{ name: 'pages', label: 'Notebook Pages Used', step: 1, min: 0 }, { name: 'cues', label: 'Cues/Questions Written', step: 1, min: 0 }, { name: 'notes', label: 'Notes Sections Completed', step: 1, min: 0 }, { name: 'summary', label: 'Summaries Written', step: 1, min: 0 }], compute: (v) => { var completeness = n(v.notes)>0?(n(v.cues)+n(v.notes)+n(v.summary))/(n(v.notes)*3)*100:0; return { result: Math.min(100,completeness), label: 'Cornell Notes Score', unit: '%', steps: ['Pages: ' + n(v.pages), 'Cues: ' + n(v.cues), 'Notes: ' + n(v.notes), 'Summaries: ' + n(v.summary), 'Completeness: ' + Math.min(100,completeness).toFixed(0) + '%', completeness>=80?'Good note-taking habits':completeness>=50?'Room for improvement':'Include all sections for best results'] } }, description: 'Evaluate Cornell note-taking effectiveness.', formula: 'Score = (Cues + Notes + Summaries) / (Notes x 3) x 100', interpretation: 'Cornell method: cues column (left), notes (right), summary (bottom). Each page should have all three.' },");

entries.push("  'flashcard-ratings': { schema: z.object({ totalCards: z.string(), knownCards: z.string(), incorrectCards: z.string(), reviewTime: z.string() }), fields: [{ name: 'totalCards', label: 'Total Flashcards', step: 1, min: 1 }, { name: 'knownCards', label: 'Cards Known Correctly', step: 1, min: 0 }, { name: 'incorrectCards', label: 'Cards Answered Incorrectly', step: 1, min: 0 }, { name: 'reviewTime', label: 'Review Time (minutes)', step: 1, min: 1 }], compute: (v) => { var retention = n(v.totalCards)>0?n(v.knownCards)/n(v.totalCards)*100:0; var mastery = n(v.totalCards)>0?(n(v.knownCards)-n(v.incorrectCards))/n(v.totalCards)*100:0; var cardsPerMin = n(v.reviewTime)>0?n(v.totalCards)/n(v.reviewTime):0; return { result: retention, label: 'Flashcard Retention Rate', unit: '%', steps: ['Total: ' + n(v.totalCards), 'Known: ' + n(v.knownCards), 'Incorrect: ' + n(v.incorrectCards), 'Retention: ' + retention.toFixed(1) + '%', 'Mastery: ' + mastery.toFixed(1) + '%', cardsPerMin.toFixed(1) + ' cards/min', retention>=80?'Good retention':retention>=60?'Needs review':'Review more frequently'] } }, description: 'Rate flashcard study effectiveness.', formula: 'Retention = Known/Total x 100 | Mastery = (Known-Incorrect)/Total x 100', interpretation: 'Leitner system: space repetition. Target 80%+ retention. Cards with errors need more frequent review.' },");

entries.push("  'lab-notebook': { schema: z.object({ experiments: z.string(), procedures: z.string(), observations: z.string(), conclusions: z.string(), safetyNotes: z.string() }), fields: [{ name: 'experiments', label: 'Experiments Recorded', step: 1, min: 0 }, { name: 'procedures', label: 'Procedure Sections Complete', step: 1, min: 0 }, { name: 'observations', label: 'Observation Entries', step: 1, min: 0 }, { name: 'conclusions', label: 'Conclusion Sections', step: 1, min: 0 }, { name: 'safetyNotes', label: 'Safety Notes Included', step: 1, min: 0 }], compute: (v) => { var total = n(v.experiments)+n(v.procedures)+n(v.observations)+n(v.conclusions)+n(v.safetyNotes); var completeness = n(v.experiments)>0?total/(n(v.experiments)*5)*100:0; return { result: Math.min(100,completeness), label: 'Lab Notebook Score', unit: '%', steps: ['Experiments: ' + n(v.experiments), 'Procedures: ' + n(v.procedures) + '/' + n(v.experiments), 'Observations: ' + n(v.observations) + '/' + n(v.experiments), 'Conclusions: ' + n(v.conclusions) + '/' + n(v.experiments), 'Safety: ' + n(v.safetyNotes) + '/' + n(v.experiments), 'Completeness: ' + Math.min(100,completeness).toFixed(0) + '%'] } }, description: 'Evaluate lab notebook completeness.', formula: 'Score = (Procs + Obs + Conc + Safety) / (Experiments x 4) x 100', interpretation: 'Lab notebooks need: procedure, observations, data, conclusions, safety notes for each experiment. Dated entries with permanent ink.' },");

entries.push("  'quiz-generator': { schema: z.object({ topics: z.string(), questions: z.string(), difficulty: z.string(), timePerQ: z.string() }), fields: [{ name: 'topics', label: 'Number of Topics', step: 1, min: 1 }, { name: 'questions', label: 'Questions per Topic', step: 1, min: 1 }, { name: 'difficulty', label: 'Difficulty Level (1-5)', step: 1, min: 1, max: 5 }, { name: 'timePerQ', label: 'Time per Question (min)', placeholder: '1', step: 0.5, min: 0.5 }], compute: (v) => { var totalQ = n(v.topics)*n(v.questions); var totalTime = totalQ*(n(v.timePerQ)||1); return { result: totalQ, label: 'Total Quiz Questions', unit: '', steps: ['Topics: ' + n(v.topics), 'Questions per topic: ' + n(v.questions), 'Total: ' + totalQ + ' questions', 'Difficulty: ' + n(v.difficulty) + '/5', 'Est. time: ' + totalTime.toFixed(0) + ' min', totalQ>50?'Consider reducing question count for quiz length':'Good quiz size'] } }, description: 'Generate quiz parameters and estimates.', formula: 'Total = Topics x Questions/Topic | Time = Total x Time per Question', interpretation: 'Short quizzes: 10-20 questions. Unit tests: 20-40. Final exams: 50-100. Mix difficulty levels.' },");

entries.push("  'test-builder': { schema: z.object({ sections: z.string(), mcqPerSec: z.string(), essayPerSec: z.string(), ptsMCQ: z.string(), ptsEssay: z.string(), timeLimit: z.string() }), fields: [{ name: 'sections', label: 'Number of Sections', step: 1, min: 1 }, { name: 'mcqPerSec', label: 'MCQs per Section', step: 1, min: 0 }, { name: 'essayPerSec', label: 'Essay Questions per Section', step: 1, min: 0 }, { name: 'ptsMCQ', label: 'Points per MCQ', step: 1, min: 1, placeholder: '2' }, { name: 'ptsEssay', label: 'Points per Essay', step: 5, min: 1, placeholder: '10' }, { name: 'timeLimit', label: 'Time Limit (minutes)', step: 5, min: 1 }], compute: (v) => { var mcqTotal = n(v.sections)*n(v.mcqPerSec); var essayTotal = n(v.sections)*n(v.essayPerSec); var totalPts = mcqTotal*(n(v.ptsMCQ)||2)+essayTotal*(n(v.ptsEssay)||10); var ptsPerMin = n(v.timeLimit)>0?totalPts/n(v.timeLimit):0; return { result: totalPts, label: 'Total Test Points', unit: '', steps: ['Sections: ' + n(v.sections), 'MCQs: ' + mcqTotal + ' x ' + (n(v.ptsMCQ)||2) + ' pts = ' + mcqTotal*(n(v.ptsMCQ)||2), 'Essays: ' + essayTotal + ' x ' + (n(v.ptsEssay)||10) + ' pts = ' + essayTotal*(n(v.ptsEssay)||10), 'Total: ' + totalPts + ' points', 'Time: ' + n(v.timeLimit) + ' min', ptsPerMin.toFixed(1) + ' pts/min'] } }, description: 'Design test structure and scoring.', formula: 'Total = (MCQ x Pts/MCQ) + (Essays x Pts/Essay)', interpretation: 'Balance question types. MCQs: quick knowledge checks. Essays: deeper understanding. Aim for 1-2 pts per minute.' },");

entries.push("  'unit-test-builder': { schema: z.object({ modules: z.string(), objectives: z.string(), itemTypes: z.string(), totalItems: z.string(), passingPct: z.string() }), fields: [{ name: 'modules', label: 'Number of Modules', step: 1, min: 1 }, { name: 'objectives', label: 'Learning Objectives', step: 1, min: 1 }, { name: 'itemTypes', label: 'Question Types (comma-sep)', placeholder: 'MCQ, True/False, Short Answer' }, { name: 'totalItems', label: 'Total Test Items', step: 1, min: 1 }, { name: 'passingPct', label: 'Passing Score (%)', placeholder: '70', step: 5, min: 0, max: 100 }], compute: (v) => { var itemsPerObj = n(v.totalItems)/Math.max(1,n(v.objectives)); var itemsPerMod = n(v.totalItems)/Math.max(1,n(v.modules)); var passing = n(v.totalItems)*(n(v.passingPct||'70')/100); var types = String(v.itemTypes||'MCQ').split(',').length; return { result: itemsPerObj, label: 'Items per Objective', unit: '', steps: ['Modules: ' + n(v.modules), 'Objectives: ' + n(v.objectives), 'Total items: ' + n(v.totalItems), 'Items/objective: ' + itemsPerObj.toFixed(1), 'Items/module: ' + itemsPerMod.toFixed(1), 'Question types: ' + types, 'Passing: ' + passing.toFixed(0) + '/' + n(v.totalItems) + ' (' + (n(v.passingPct||'70')) + ')%'] } }, description: 'Plan unit test structure from learning objectives.', formula: 'Items/Obj = Total / Objectives', interpretation: 'Each objective needs 2-4 items for reliable assessment. More items = more valid assessment. Minimum 10 items per unit.' },");

entries.push("  'lexile-score': { schema: z.object({ words: z.string(), sentences: z.string(), syllables: z.string(), characters: z.string() }), fields: [{ name: 'words', label: 'Total Words', step: 1, min: 1 }, { name: 'sentences', label: 'Number of Sentences', step: 1, min: 1 }, { name: 'syllables', label: 'Total Syllables', step: 1, min: 1 }, { name: 'characters', label: 'Total Characters', step: 1, min: 1 }], compute: (v) => { var avgWordsPerSentence = n(v.sentences)>0?n(v.words)/n(v.sentences):0; var avgSyllablesPerWord = n(v.words)>0?n(v.syllables)/n(v.words):0; var avgCharsPerWord = n(v.words)>0?n(v.characters)/n(v.words):0; var lexile = Math.round(avgWordsPerSentence*3.3 + avgSyllablesPerWord*59.1 - 220); var clamped = Math.max(0,Math.min(1800,lexile)); var grade = {'0':'K-1','150':'1-2','300':'2-3','500':'3-4','650':'4-5','750':'5-6','850':'6-7','950':'7-8','1000':'8-9','1100':'9-10','1200':'11-12','1300':'College'}; var bands = Object.keys(grade).map(Number).sort(function(a,b){return b-a}); var band = null; for (var i=0;i<bands.length;i++) { if (clamped >= bands[i]) { band = grade[String(bands[i])]; break; } } return { result: clamped, label: 'Lexile Score', unit: 'L', steps: ['Words/sentence: ' + avgWordsPerSentence.toFixed(1), 'Syllables/word: ' + avgSyllablesPerWord.toFixed(2), 'Lexile: ' + clamped + 'L', band ? 'Approx grade: ' + band : ''] } }, description: 'Estimate Lexile text complexity score.', formula: 'Lexile = (AvgWords/Sent x 3.3) + (AvgSyllables/Word x 59.1) - 220', interpretation: 'Lexile range: 0L-1800L. Higher = more complex. K-1: ~200L. Grade 6: ~900L. College: ~1300L.' },");

entries.push("  'typing-speed-test': { schema: z.object({ wpm: z.string(), accuracy: z.string(), time: z.string(), targetWpm: z.string() }), fields: [{ name: 'wpm', label: 'Your WPM', step: 1, min: 0 }, { name: 'accuracy', label: 'Accuracy (%)', step: 1, min: 0, max: 100 }, { name: 'time', label: 'Test Duration (minutes)', step: 0.5, min: 0.5 }, { name: 'targetWpm', label: 'Target WPM', placeholder: '60', step: 5, min: 0 }], compute: (v) => { var target = n(v.targetWpm||'60'); var adjWpm = n(v.wpm)*(n(v.accuracy)/100); var progress = target>0?adjWpm/target*100:0; var cat = adjWpm>=target?'Target met!':adjWpm>=target*0.8?'Close to target':'Needs practice'; return { result: adjWpm, label: 'Effective WPM', unit: 'WPM', steps: ['Raw WPM: ' + n(v.wpm), 'Accuracy: ' + n(v.accuracy) + '%', 'Effective: ' + adjWpm.toFixed(1) + ' WPM', 'Target: ' + target + ' WPM', 'Progress: ' + progress.toFixed(0) + '%', cat] } }, description: 'Calculate effective typing speed with accuracy adjustment.', formula: 'Effective WPM = Raw WPM x (Accuracy / 100)', interpretation: 'Accuracy matters more than speed. Target 60+ WPM with 95%+ accuracy. Professional: 65-80 WPM. Practice daily 15 min.' },");

var insertionText = entries.join('\n');

var marker = "'study-abroad-calc'";
var lastEntryIdx = content.lastIndexOf(marker);
if (lastEntryIdx === -1) {
  console.error("Could not find last entry marker 'study-abroad-calc'");
  process.exit(1);
}

var afterLastEntry = content.indexOf('\n', lastEntryIdx);
var closeBraceIdx = content.indexOf('\n}', afterLastEntry);
if (closeBraceIdx === -1) {
  console.error("Could not find closing brace of calcDefs");
  process.exit(1);
}

var newContent = content.slice(0, closeBraceIdx) + '\n' + insertionText + '\n' + content.slice(closeBraceIdx);

fs.writeFileSync(filePath, newContent, 'utf8');
console.log('Inserted ' + entries.length + ' new calcDef entries before closing brace');
