import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dictDir = join(__dirname, 'dict');
mkdirSync(dictDir, { recursive: true });

const es = {
  // Scientific/technical terms
  "Effect":"Efecto","Method":"Método","Theorem":"Teorema","Law":"Ley","Principle":"Principio",
  "Equation":"Ecuación","Number":"Número","Index":"Índice","Score":"Puntuación",
  "Ratio":"Relación","Test":"Prueba","Model":"Modelo","Curve":"Curva","Rate":"Tasa",
  "Value":"Valor","Level":"Nivel","Analysis":"Análisis","Calculation":"Cálculo",
  "Distance":"Distancia","Speed":"Velocidad","Pressure":"Presión","Temperature":"Temperatura",
  "Volume":"Volumen","Area":"Área","Mass":"Masa","Weight":"Peso","Force":"Fuerza",
  "Power":"Potencia","Energy":"Energía","Frequency":"Frecuencia","Length":"Longitud",
  "Width":"Ancho","Height":"Altura","Depth":"Profundidad","Thickness":"Grosor",
  "Diameter":"Diámetro","Radius":"Radio","Angle":"Ángulo","Time":"Tiempo","Age":"Edad",
  "Size":"Tamaño","Cost":"Costo","Price":"Precio","Tax":"Impuesto","Interest":"Interés",
  "Payment":"Pago","Balance":"Saldo","Savings":"Ahorros","Loan":"Préstamo","Debt":"Deuda",
  "Income":"Ingresos","Expense":"Gasto","Budget":"Presupuesto","Return":"Retorno",
  "Growth":"Crecimiento","Risk":"Riesgo","Investment":"Inversión","Retirement":"Jubilación",
  "Health":"Salud","Heart":"Corazón","Blood":"Sangre","Body":"Cuerpo","Fat":"Grasa",
  "Calorie":"Caloría","Protein":"Proteína","Vitamin":"Vitamina","Drug":"Medicamento",
  "Dose":"Dosis","Strength":"Fuerza","Duration":"Duración","Intensity":"Intensidad",
  "Capacity":"Capacidad","Efficiency":"Eficiencia","Accuracy":"Precisión","Limit":"Límite",
  "Maximum":"Máximo","Minimum":"Mínimo","Average":"Promedio","Median":"Mediana",
  "Standard":"Estándar","Normal":"Normal","Critical":"Crítico","Optimal":"Óptimo",
  "Grade":"Grado","Quality":"Calidad","Phase":"Fase","Wave":"Onda","Signal":"Señal",
  "Noise":"Ruido","Amplitude":"Amplitud","Wavelength":"Longitud de Onda",
  "Velocity":"Velocidad","Acceleration":"Aceleración","Momentum":"Momento","Work":"Trabajo",
  "Heat":"Calor","Current":"Corriente","Voltage":"Voltaje","Resistance":"Resistencia",
  "Density":"Densidad","Viscosity":"Viscosidad","Tension":"Tensión","Stress":"Esfuerzo",
  "Strain":"Deformación","Modulus":"Módulo","Elastic":"Elástico","Plastic":"Plástico",
  "Thermal":"Térmico","Electrical":"Eléctrico","Magnetic":"Magnético","Optical":"Óptico",
  "Hydraulic":"Hidráulico","Static":"Estático","Dynamic":"Dinámico","Kinetic":"Cinético",
  "Potential":"Potencial","Mechanical":"Mecánico","Chemical":"Químico","Physical":"Físico",
  "Star":"Estrella","Moon":"Luna","Sun":"Sol","Earth":"Tierra","Water":"Agua","Air":"Aire",
  "Soil":"Suelo","Sea":"Mar","Wind":"Viento","Rain":"Lluvia","Snow":"Nieve","Ice":"Hielo",
  "Fire":"Fuego","Light":"Luz","Sound":"Sonido","Color":"Color","Shape":"Forma",
  "Direction":"Dirección","Position":"Posición","Motion":"Movimiento","Rotation":"Rotación",
  "Orbit":"Órbita","Axis":"Eje","Plane":"Plano","Slope":"Pendiente","Surface":"Superficie",
  "Absorption":"Absorción","Transmission":"Transmisión","Reflection":"Reflexión",
  "Refraction":"Refracción","Diffraction":"Difracción","Scattering":"Dispersión",
  "Radiation":"Radiación","Emission":"Emisión","Conduction":"Conducción","Convection":"Convección",
  "Friction":"Fricción","Flow":"Flujo","Particle":"Partícula","Array":"Arreglo",
  "Matrix":"Matriz","Vector":"Vector","Field":"Campo","Function":"Función",
  "Transform":"Transformada","Operator":"Operador","Factor":"Factor",
  "Coefficient":"Coeficiente","Constant":"Constante","Variable":"Variable",
  "Parameter":"Parámetro","Formula":"Fórmula","Group":"Grupo","Space":"Espacio",
  "Dimension":"Dimensión","Algebra":"Álgebra","Calculus":"Cálculo",
  "Statistics":"Estadística","Probability":"Probabilidad","Distribution":"Distribución",
  "Correlation":"Correlación","Regression":"Regresión","Variance":"Varianza",
  "Deviation":"Desviación","Error":"Error","Margin":"Margen","Confidence":"Confianza",
  "Hypothesis":"Hipótesis","Population":"Población","Sample":"Muestra","Survey":"Encuesta",
  "Forecast":"Pronóstico","Trend":"Tendencia","Cycle":"Ciclo","Season":"Temporada",
  "Period":"Período","Annual":"Anual","Monthly":"Mensual","Weekly":"Semanal","Daily":"Diario",
  "Net":"Neto","Gross":"Bruto","Total":"Total","Compound":"Compuesto","Simple":"Simple",
  "Fixed":"Fijo","Variable":"Variable","Net":"Neto","Gross":"Bruto","Total":"Total",
  "Partial":"Parcial","Direct":"Directo","Indirect":"Indirecto","Absolute":"Absoluto",
  "Relative":"Relativo","Initial":"Inicial","Final":"Final","Primary":"Primario",
  "Secondary":"Secundario","Major":"Mayor","Minor":"Menor","Basic":"Básico",
  "Advanced":"Avanzado","Automatic":"Automático","Manual":"Manual",
  "Interactive":"Interactivo","Numerical":"Numérico","Digital":"Digital",
  "Analog":"Analógico","Virtual":"Virtual","Simulation":"Simulación",
  "Estimation":"Estimación","Prediction":"Predicción","Detection":"Detección",
  "Analysis":"Análisis","Evaluation":"Evaluación","Measurement":"Medición",
  "Comparison":"Comparación","Conversion":"Conversión","Processing":"Procesamiento",
  // Non-scientific nouns
  "Balance":"Balance","White":"Blanco","Aperture":"Apertura","Stop":"Parada",
  "Thread":"Rosca","Pitch":"Paso","Bolt":"Perno","Nut":"Tuerca",
  "Dimensions":"Dimensiones","Oil":"Aceite","Coolant":"Refrigerante","Mixture":"Mezcla",
  "Battery":"Batería","Watt":"Vatio","Hour":"Hora","Hours":"Horas","Life":"Vida",
  "Solar":"Solar","Wattage":"Potencia","Inverter":"Inversor","Sizing":"Dimensionamiento",
  "Wire":"Cable","AWG":"AWG","Capacitor":"Condensador","Code":"Código",
  "Resistor":"Resistencia","Band":"Banda","Transformer":"Transformador","Turns":"Vueltas",
  "Gain":"Ganancia","Timer":"Temporizador","Stepper":"Paso a Paso","Motor":"Motor",
  "Orifice":"Orificio","Weir":"Vertedero","Pump":"Bomba","Head":"Altura",
  "Exchanger":"Intercambiador","Boiling":"Ebullición","Point":"Punto","Altitude":"Altitud",
  "Enthalpy":"Entalpía","Fan":"Ventilador","Laws":"Leyes","Gear":"Engranaje",
  "Spring":"Resorte","Beam":"Viga","Deflection":"Deflexión","Column":"Columna",
  "Buckling":"Pandeo","Flange":"Brida","Rating":"Clasificación","Concrete":"Hormigón",
  "Mix":"Mezcla","Rebar":"Varilla","Development":"Desarrollo","Bearing":"Carga",
  "Pile":"Pilote","Seismic":"Sísmico","Shear":"Corte","Loss":"Pérdida",
  "Building":"Edificio","Cooling":"Enfriamiento","Load":"Carga","Chiller":"Enfriador",
  "Tonnage":"Tonelaje","Boiler":"Caldera","Horsepower":"Caballos","Crane":"Grúa",
  "Compressor":"Compresor","Vacuum":"Vacío","Module":"Módulo","Hardness":"Dureza",
  "Chill":"Sensación Térmica","Humidex":"Humidex","Noon":"Mediodía","Golden":"Dorado",
  "Twilight":"Crepúsculo","Blue":"Azul","Elevation":"Elevación","Azimuth":"Acimut",
  "Equinox":"Equinoccio","Solstice":"Solsticio","Magnitude":"Magnitud","Orbital":"Orbital",
  "Escape":"Escape","Synodic":"Sinódico","Habitable":"Habitable","Zone":"Zona",
  "Lens":"Lente","Prism":"Prisma","Birefringence":"Birrefringencia","Laser":"Láser",
  "Pulse":"Pulso","Coupling":"Acoplamiento","Antenna":"Antena","Path":"Trayecto",
  "Coax":"Coaxial","Impedance":"Impedancia","Fiber":"Fibra","Attenuation":"Atenuación",
  "Bandwidth":"Ancho de Banda","Trace":"Traza","Atmospheric":"Atmosférico",
  "Horizon":"Horizonte","Radar":"Radar","Range":"Alcance","Section":"Sección",
  "Sonar":"Sonar","Underwater":"Subacuático","Dive":"Buceo","Decompression":"Descompresión",
  "Nitrox":"Nitrox","Airspeed":"Velocidad Aérea","Altimeter":"Altímetro","Setting":"Ajuste",
  "True":"Verdadera","Crosswind":"Viento Cruzado","Component":"Componente",
  "Headwind":"Viento de Frente","Fuel":"Combustible","Burn":"Consumo","Line":"Línea",
  "Magnetic":"Magnético","Variation":"Variación","North":"Norte","Correction":"Corrección",
  "Ship":"Barco","Displacement":"Desplazamiento","Container":"Contenedor","Pallet":"Palé",
  "Port":"Puerto","Draft":"Calado","Anchoring":"Anclaje","Scope":"Alcance",
  "Bridge":"Puente","Blanket":"Global","Distressed":"En Dificultades","Property":"Propiedad",
  "Opportunity":"Oportunidad","Sale":"Venta","Segregation":"Segregación","Credit":"Crédito",
  "Offer":"Oferta","Compromise":"Compromiso","Installment":"Plazos","Agreement":"Acuerdo",
  "Penalty":"Penalización","Trust":"Fideicomiso","Fund":"Fondo","Gift":"Donación",
  "Exclusion":"Exclusión","Lifetime":"Vitalicio","Deduction":"Deducción",
  "Special":"Especial","Needs":"Necesidades","Pension":"Pensión",
  "Survivor":"Superviviente","Divorce":"Divorcio","Early":"Anticipada","Delay":"Retraso",
  "Credits":"Créditos","Federal":"Federal","Military":"Militar","State":"Estatal",
  "Teacher":"Docente","Police":"Policial","Cash":"Efectivo","Plan":"Plan",
  "Solo":"Individual","Inherited":"Heredado","Student":"Estudiante","Parent":"Padre",
  "Consolidation":"Consolidación","Default":"Incumplimiento","Type":"Tipo",
  "Insulin":"Insulina","Sensitivity":"Sensibilidad","Glucose":"Glucosa",
  "Counting":"Conteo","Metabolic":"Metabólico","Syndrome":"Síndrome","Profile":"Perfil",
  "Cholesterol":"Colesterol","Deficit":"Déficit","Surplus":"Superávit","Macros":"Macros",
  "Loss":"Pérdida","Muscle":"Músculo","Gain":"Ganancia","Fasting":"Ayuno",
  "Oral":"Oral","Tolerance":"Tolerancia","Glycemic":"Glucémico","Load":"Carga",
  "Thyroid":"Tiroides","Melatonin":"Melatonina","Dosage":"Dosis","Iron":"Hierro",
  "Deficiency":"Deficiencia","Roundness":"Redondez","Adiposity":"Adiposidad",
  "Navy":"Naval","Fat":"Grasa","Skinfold":"Pliegue Cutáneo","Sodium":"Sodio",
  "Potassium":"Potasio","Hydration":"Hidratación","Status":"Estado","Urine":"Orina",
  "Specific":"Específico","Gravity":"Gravedad","Sweat":"Sudor","Pulmonary":"Pulmonar",
  "Gradient":"Gradiente","Dead":"Muerto","Shunt":"Cortocircuito","Fraction":"Fracción",
  "Gas":"Gas","Anion":"Anión","Gap":"Brecha","Osmolar":"Osmolar",
  "Bilirubin":"Bilirrubina","Fractions":"Fracciones","Comorbidity":"Comorbilidad",
  "Dosing":"Dosificación","Creatinine":"Creatinina","Clearance":"Depuración",
  "Percentile":"Percentil","Chart":"Tabla","Circumference":"Circunferencia",
  "Triceps":"Tríceps","Subscapular":"Subescapular","Suprailiac":"Suprailíaco",
  "Pregnancy":"Embarazo","Athlete":"Atleta","Waist":"Cintura","Hip":"Cadera",
  "Neck":"Cuello","Calf":"Pantorrilla","Wrist":"Muñeca","Cardiac":"Cardíaco",
  "Output":"Gasto","Ejection":"Eyección","Shortening":"Acortamiento",
  "Hypertrophy":"Hipertrofia","Tricuspid":"Tricúspide","Interval":"Intervalo",
  "Dispersion":"Dispersión","Criteria":"Criterios","Rule":"Regla",
  "Pancreatitis":"Pancreatitis","Semester":"Semestre","Cumulative":"Acumulado",
  "Weighted":"Ponderado","Unweighted":"No Ponderado","Rating":"Calificación","Rank":"Rango",
  "Honor":"Honor","Roll":"Lista","Graduation":"Graduación","Requirements":"Requisitos",
  "Degree":"Título","Audit":"Auditoría","Course":"Curso","Academic":"Académico",
  "College":"Universidad","Admission":"Admisión","Chance":"Probabilidad",
  "Decision":"Decisión","Action":"Acción","Grant":"Beca","Scholarship":"Beca",
  "Search":"Búsqueda","Comparison":"Comparación","Plagiarism":"Plagio","Grammar":"Gramática",
  "School":"Escuela","Fundraiser":"Recaudación","Classroom":"Aula","Supplies":"Suministros",
  "Schedule":"Horario","Recommendation":"Recomendación","Requests":"Solicitudes",
  "Homeschool":"Educación en Casa","Assessment":"Evaluación","Learning":"Aprendizaje",
  "Style":"Estilo","Active":"Activo","Recall":"Recuerdo","Study":"Estudio",
  "Flashcard":"Tarjeta","Deck":"Mazo","Notes":"Notas","Ratings":"Calificaciones",
  "Research":"Investigación","Proposal":"Propuesta","Dissertation":"Tesis",
  "Timeline":"Cronograma","Lab":"Laboratorio","Notebook":"Cuaderno","Science":"Ciencia",
  "Fair":"Feria","Judging":"Evaluación","Reading":"Lectura","Log":"Registro",
  "Comprehension":"Comprensión","Summer":"Verano","Book":"Libro","Report":"Informe",
  "Math":"Matemáticas","Drill":"Ejercicio","Project":"Proyecto","Peer":"Compañero",
  "Assignments":"Tareas","Objectives":"Objetivos","Curriculum":"Currículum","Map":"Mapa",
  "Lesson":"Lección","Participation":"Participación","Late":"Tardío","Extra":"Extra",
  "Accommodations":"Adaptaciones","Proficiency":"Competencia","Gifted":"Dotado",
  "Identification":"Identificación","Dyslexia":"Dislexia","Screener":"Evaluador",
  "Words":"Palabras","Spelling":"Ortografía","Typing":"Mecanografía",
  "Keyboarding":"Teclado","Skills":"Habilidades","Safety":"Seguridad","Media":"Medios",
  "Literacy":"Alfabetización","Coding":"Programación","Kinematics":"Cinemática",
  "Motion":"Movimiento","Projectile":"Proyectil","Circular":"Circular","Relative":"Relativo",
  "Inclined":"Inclinado","Plane":"Plano","Machine":"Máquina","Pendulum":"Péndulo",
  "Simple":"Simple","Physical":"Físico","Torsion":"Torsión","Damped":"Amortiguado",
  "Harmonic":"Armónico","Driven":"Forzado","Coupled":"Acoplados","Standing":"Estacionaria",
  "Doppler":"Doppler","Sound":"Sonido","Light":"Luz","Inverse":"Inversa",
  "Square":"Cuadrada","Electric":"Eléctrico","Parallel":"Paralelo","Plate":"Placa",
  "Capacitor":"Condensador","Cylindrical":"Cilíndrico","Spherical":"Esférico",
  "Loop":"Espira","Solenoid":"Solenoide","Faraday":"Faraday","Mutual":"Mutua",
  "Self":"Propia","Charge":"Carga","Hall":"Hall","Voltage":"Voltaje","Mass":"Masa",
  "Spectrometer":"Espectrómetro","Snell":"Snell","Thin":"Delgado","System":"Sistema",
  "Microscope":"Microscopio","Astronomical":"Astronómico","Telescope":"Telescopio",
  "Single":"Simple","Slit":"Rendija","Double":"Doble","Bragg":"Bragg",
  "Rayleigh":"Rayleigh","Criterion":"Criterio","Blackbody":"Cuerpo Negro",
  "Photoelectric":"Fotoeléctrico","Compton":"Compton","Bohr":"Bohr","Atom":"Átomo",
  "Quantum":"Cuántico","Tunneling":"Túnel","Heisenberg":"Heisenberg",
  "Uncertainty":"Incertidumbre","Schrodinger":"Schrödinger","Box":"Caja",
  "Finite":"Finita","Well":"Pozo","Oscillator":"Oscilador","Hydrogen":"Hidrógeno",
  "Levels":"Niveles","Zeeman":"Zeeman","Structure":"Estructura","Selection":"Selección",
  "Rules":"Reglas","Nuclear":"Nuclear","Binding":"Enlace","Radioactive":"Radiactivo",
  "Decay":"Desintegración","Carbon":"Carbono","Dating":"Datación","Alpha":"Alfa",
  "Beta":"Beta","Gamma":"Gamma","Fission":"Fisión","Fusion":"Fusión",
  "Equivalence":"Equivalencia","Dilation":"Dilatación","Contraction":"Contracción",
  "Relativistic":"Relativista","Lorentz":"Lorentz","Transformation":"Transformación",
  "Twin":"Gemelos","Paradox":"Paradoja","Gravitational":"Gravitatorio","Gravity":"Gravedad",
  "Kepler":"Kepler","Third":"Tercera","Lagrange":"Lagrange","Points":"Puntos",
  "Hohmann":"Hohmann","Transfer":"Transferencia","Rocket":"Cohete","Impulse":"Impulso",
  "Drag":"Arrastre","Terminal":"Terminal","Pascal":"Pascal","Bernoulli":"Bernoulli",
  "Poiseuille":"Poiseuille","Stokes":"Stokes","Venturi":"Venturi","Torricelli":"Torricelli",
  "Reynolds":"Reynolds","Lift":"Sustentación","Thermodynamic":"Termodinámico",
  "Process":"Proceso","Ideal":"Ideal","Kinetic":"Cinética","Theory":"Teoría",
  "Carnot":"Carnot","Otto":"Otto","Diesel":"Diesel","Brayton":"Brayton",
  "Percent":"Porcentaje","Empirical":"Empírica","Molecular":"Molecular",
  "Hydrate":"Hidrato","Yield":"Rendimiento","Limiting":"Limitante","Reactant":"Reactivo",
  "Theoretical":"Teórico","Reaction":"Reacción","Stoichiometry":"Estequiometría",
  "Balancing":"Balanceo","Redox":"Redox","Net":"Neta","Ionic":"Iónica",
  "Titration":"Valoración","Strong":"Fuerte","Weak":"Débil","Buffer":"Amortiguador",
  "pH":"pH","Salt":"Sal","Hydrolysis":"Hidrólisis","Amphoteric":"Anfótero",
  "Common":"Común","Ion":"Ión","Solubility":"Solubilidad","Product":"Producto",
  "Molar":"Molar","Precipitation":"Precipitación","Conditions":"Condiciones",
  "Complex":"Complejo","Equilibrium":"Equilibrio","Quotient":"Cociente",
  "Concentrations":"Concentraciones","Le Chatelier":"Le Chatelier","Gibbs":"Gibbs",
  "Free":"Libre","Enthalpy":"Entalpía","Entropy":"Entropía","Change":"Cambio",
  "Formation":"Formación","Hess":"Hess","Bond":"Enlace","Calorimetry":"Calorimetría",
  "Specific":"Específico","Latent":"Latente","Diagram":"Diagrama",
  "Freezing":"Congelación","Depression":"Descenso","Colligative":"Coligativas",
  "Properties":"Propiedades","Arrhenius":"Arrhenius","Activation":"Activación",
  "Mechanism":"Mecanismo","Catalyst":"Catalizador","Electrochemical":"Electroquímica",
  "Cell":"Celda","Standard":"Estándar","Nernst":"Nernst","Electrolysis":"Electrólisis",
  "Conductivity":"Conductividad","Solution":"Solución","Oxidation":"Oxidación",
  "Coordination":"Coordinación","Crystal":"Cristal","Field":"Campo","Ligand":"Ligando",
  "Moment":"Momento","Rydberg":"Rydberg","Spectral":"Espectrales","Lines":"Líneas",
  "Molarity":"Molaridad","Dilution":"Dilución","Normality":"Normalidad",
  "Molality":"Molalidad","Mole":"Mol","Fraction":"Fracción","Formal":"Formal",
  "Concentration":"Concentración","Activity":"Actividad","Radioactivity":"Radiactividad",
  "Truss":"Armadura","Joints":"Nudos","Sections":"Secciones","Frame":"Marco",
  "Reactions":"Reacciones","Moment":"Momento","Conjugate":"Conjugado","Virtual":"Virtual",
  "Strain":"Deformación","Indeterminate":"Indeterminada","Distribution":"Distribución",
  "Stiffness":"Rigidez","Flexibility":"Flexibilidad","Influence":"Influencia",
  "Plastic":"Plástico","Modulus":"Módulo","Inertia":"Inercia","Shape":"Forma",
  "Principal":"Principal","Shaft":"Eje","Walled":"Pared","Vessel":"Vaso",
  "Thick":"Gruesa","Cylinder":"Cilindro","Combined":"Combinado","Mohr":"Mohr",
  "Circle":"Círculo","Failure":"Falla","Theories":"Teorías","Fatigue":"Fatiga",
  "Goodman":"Goodman","Soderberg":"Soderberg","Gerber":"Gerber","Parabola":"Parábola",
  "Concentration":"Concentración","Crack":"Grieta","Growth":"Crecimiento",
  "Fracture":"Fractura","Toughness":"Tenacidad","Euler":"Euler","Plate":"Placa",
  "Shell":"Cáscara","Vibration":"Vibración","Modal":"Modal","Base":"Base",
  "Isolation":"Aislamiento","Pipe":"Tubería","Losses":"Pérdidas","Network":"Red",
  "Open":"Abierto","Channel":"Canal","Notch":"Muesca","Hydraulic":"Hidráulico",
  "Jump":"Salto","Sediment":"Sedimento","Transport":"Transporte","Mixing":"Mezcla",
  "Tank":"Tanque","Conduction":"Conducción","Convection":"Convección",
  "Radiation":"Radiación","Fins":"Aletas","Transient":"Transitorio",
  "Refrigeration":"Refrigeración","Nozzle":"Tobera","Diffuser":"Difusor","Shock":"Choque",
  "Performance":"Rendimiento","Map":"Mapa","Gas":"Gas","Turbine":"Turbina",
  "Steam":"Vapor","Rankine":"Rankine","Cogeneration":"Cogeneración",
  "Tower":"Torre","Duct":"Conducto","Design":"Diseño","Friction":"Fricción",
  "Cyclone":"Ciclón","Separator":"Separador","Filter":"Filtro",
  "Electrostatic":"Electrostático","Precipitator":"Precipitador",
  "Distillation":"Destilación","Column":"Columna","Absorption":"Absorción",
  "Extraction":"Extracción","Adsorption":"Adsorción","Membrane":"Membrana",
  "Separation":"Separación","Crystallization":"Cristalización","Drying":"Secado",
  "Rate":"Velocidad","Filtration":"Filtración","Centrifugación":"Centrifugación",
  "Mixer":"Mezclador","Agitated":"Agitado","Tuning":"Sintonización","Control":"Control",
  "Loop":"Lazo","Stability":"Estabilidad","Block":"Bloque","Reduction":"Reducción",
  "Bode":"Bode","Nyquist":"Nyquist","Plot":"Diagrama","Tip":"Propina",
  "Split":"Dividir","Bill":"Cuenta","Coupon":"Cupón","Stacking":"Acumulación",
  "Loyalty":"Lealtad","Rewards":"Recompensas","Unit":"Unidad","Pricing":"Precios",
  "Deal":"Oferta","Mileage":"Rendimiento","Public":"Público","Transit":"Transporte",
  "Fare":"Tarifa","Packing":"Empaque","List":"Lista","Travel":"Viaje",
  "Insurance":"Seguro","Security":"Seguridad","Deposit":"Depósito",
  "Streaming":"Streaming","Cable":"Cable","Gym":"Gimnasio","Membership":"Membresía",
  "Pet":"Mascota","Home":"Hogar","Maintenance":"Mantenimiento","Cleaning":"Limpieza",
  "Electric":"Eléctrica","Appliance":"Electrodoméstico","Generator":"Generador",
  "Charity":"Caridad","Donation":"Donación","Goal":"Meta",
  "Auction":"Subasta","Lottery":"Lotería","Odds":"Probabilidades","Raffle":"Rifa",
  "Entry":"Participación","Bingo":"Bingo","Poker":"Póquer","Hand":"Mano",
  "Blackjack":"Blackjack","Strategy":"Estrategia","Roulette":"Ruleta","Craps":"Craps",
  "Betting":"Apuestas","Parlay":"Combinada","Fantasy":"Fantástico",
  "Football":"Fútbol Americano","Snowball":"Bola de Nieve","Side":"Adicional",
  "Freelance":"Freelance","Passive":"Pasivo","Worth":"Patrimonio",
  "Easter":"Pascua","Passover":"Pésaj","Ramadan":"Ramadán","Chinese":"Chino",
  "New":"Nuevo","Year":"Año","Diwali":"Diwali","Hanukkah":"Janucá",
  "Thanksgiving":"Acción de Gracias","Memorial":"Conmemorativo","Labor":"Trabajo",
  "Mothers":"Madre","Fathers":"Padre","Start":"Inicio","End":"Fin",
  "Billing":"Facturación","Invoice":"Factura","Due":"Vencimiento","Grace":"Gracia",
  "Lease":"Arrendamiento","Term":"Plazo","Subscription":"Suscripción","Renewal":"Renovación",
  "Warranty":"Garantía","Milestone":"Hito","Gantt":"Gantt","Stopwatch":"Cronómetro",
  "Lap":"Vuelta","Addition":"Suma","Subtraction":"Resta","Unix":"Unix",
  "Timestamp":"Marca de Tiempo","Julian":"Juliano","Indian":"Indio","National":"Nacional",
  "Buddhist":"Budista","Date":"Fecha","Dates":"Fechas",
  "One":"Una","Two":"Dos","Paired":"Pareada","Independent":"Independiente",
  "Welch":"Welch","Signed":"Firmado","Friedman":"Friedman","Repeated":"Repetidas",
  "Measures":"Medidas","Tukey":"Tukey","Bonferroni":"Bonferroni","Dunnett":"Dunnett",
  "Pearson":"Pearson","Spearman":"Spearman","Kendall":"Kendall","Tau":"Tau",
  "Partial":"Parcial","Biserial":"Biserial","Phi":"Phi","Cramer":"Cramer",
  "Contingency":"Contingencia","Cohen":"Cohen","Kappa":"Kappa","Fisher":"Fisher",
  "Exact":"Exacto","McNemar":"McNemar","Cochran":"Cochran","Linear":"Lineal",
  "Multiple":"Múltiple","Polynomial":"Polinomial","Logistic":"Logística",
  "Multinomial":"Multinomial","Ordered":"Ordenada","Poisson":"Poisson",
  "Negative":"Negativa","Binomial":"Binomial","Ridge":"Ridge","Lasso":"Lasso",
  "Elastic":"Elástica","Net":"Red","Stepwise":"Paso a Paso",
  "Hierarchical":"Jerárquico","Naive":"Ingenuo","Bayes":"Bayes",
  "Classifier":"Clasificador","Decision":"Decisión","Tree":"Árbol","Random":"Aleatorio",
  "Forest":"Bosque","Crude":"Bruta","Standardization":"Estandarización",
  "Expectancy":"Esperanza","Survival":"Supervivencia","Proportional":"Proporcionales",
  "Hazards":"Riesgos","Difference":"Diferencia","Likelihood":"Verosimilitud",
  "Diagnostic":"Diagnóstica","Youden":"Youden","Hedges":"Hedges","Power":"Potencia",
  "Sample":"Muestra","Size":"Tamaño","Mean":"Media","Proportion":"Proporción",
  "Allocation":"Asignación","Stratified":"Estratificada","Adaptive":"Adaptativo",
  "Monitoring":"Monitoreo","Deming":"Deming","Taylor":"Taylor","Gini":"Gini",
  "Lorenz":"Lorenz","Theil":"Theil","Moving":"Móvil","Exponential":"Exponencial",
  "Smoothing":"Suavizado","Seasonal":"Estacional","Decomposition":"Descomposición",
  "Monte Carlo":"Monte Carlo","Splitting":"División","Dog":"Perro","Years":"Años",
  "Human":"Humano","Furniture":"Muebles","Arrangement":"Disposición",
  "Profit":"Ganancia","Service":"Servicio","Coverage":"Cobertura","Charge":"Cargo",
  "Times":"Veces","Earned":"Ganado","Earnings":"Ganancias","Share":"Acción",
  "Business":"Negocio","Appreciation":"Apreciación","Seller":"Vendedor",
  "Financing":"Financiamiento","Contract":"Contrato","Deed":"Escritura",
  "Portfolio":"Cartera","Rental":"Alquiler","Perpetuity":"Perpetuidad",
  "Dividend":"Dividendo","Reinvestment":"Reinversión","Asset":"Activo",
  "Pricing":"Valoración","Security":"Seguridad","Social":"Social","Disability":"Discapacidad",
  "Spousal":"Conyugales","Benefits":"Beneficios","Traditional":"Tradicional",
  "Gig":"Trabajo Independiente","Economy":"Economía","Marginal":"Marginal",
  "Effective":"Efectiva","Itemized":"Detallada","Payoff":"Liquidación",
  "Affordability":"Capacidad de Pago","Value":"Valor","Contribution":"Contribución",
  "Operating":"Operativo","Leverage":"Apalancamiento","Financial":"Financiero",
  "Term":"Plazo","Deductible":"Deducible","Maximum":"Máximo","Payout":"Pago",
  "Renters":"Inquilinos","Telescope":"Telescopio",
  // Add missing
  "Gram":"Gramo","Scale":"Escala","Thread":"Roscado","Allowance":"Asignación",
  "Audit":"Auditoría","Binding":"Vinculante","Check":"Verificación","Constriction":"Constricción",
  "Heat":"Calor","Integrity":"Integridad","Planter":"Macetero","Stamping":"Estampado",
  "Bottle":"Botella","Residual":"Residual","Forming":"Formado","Sealer":"Sellador",
  "Coating":"Revestimiento","Wrap":"Envoltura","Header":"Cabecero","Jamb":"Jamba",
  "Trim":"Moldura","Casing":"Marco","Molding":"Moldura","Wainscoting":"Zócalo",
  "Stair":"Escalera","Stringer":"Larguero","Railing":"Baranda","Post":"Poste",
  "Spacing":"Espaciado","Deck":"Cubierta","Joist":"Vigueta","Beam":"Viga",
  "Sheathing":"Revestimiento","Ventilation":"Ventilación","Gutter":"Canaleta",
  "Downspout":"Bajante","Guard":"Protector","Door":"Puerta","Window":"Ventana",
  "Well":"Pozo","Drywall":"Panel de Yeso","Sheets":"Planchas","Tape":"Cinta",
  "Mud":"Pasta","Corner":"Esquina","Bead":"Cuenta","Shoe":"Zapato","Casing":"Marco",
  "Picture":"Cuadro","Rail":"Riel","Built":"Empotrado","Shelving":"Estantería",
  "Closet":"Armario","Organizer":"Organizador","Garage":"Garaje","Shop":"Taller",
  "Lighting":"Iluminación","Driveway":"Entrada","Parking":"Estacionamiento",
  "Stall":"Espacio","Sidewalk":"Acera","Curb":"Bordillo","Ramp":"Rampa",
  "Trench":"Zanja","Cofferdam":"Ataguía","Dewatering":"Desagüe","Drilled":"Perforado",
  "Shaft":"Pozo","Helical":"Helicoidal","Tieback":"Anclaje","Anchor":"Anclaje",
  "Grout":"Lechada","Consolidation":"Consolidación","Joint":"Junta","Cold":"Fría",
  "Expansion":"Expansión","Control":"Control","Isolation":"Aislamiento",
  "Waterstop":"Junta de Agua","Scaffold":"Andamio","Ties":"Ataduras","Load":"Carga",
  "Fall":"Caída","Confined":"Confinado","Lockout":"Bloqueo","Tagout":"Etiquetado",
  // Additional education terms  
  "Spaced":"Espaciada","Repetition":"Repetición","Pomodoro":"Pomodoro",
  "Gratitude":"Gratitud","Journal":"Diario","Prompt":"Indicación",
  // Additional physics
  "Coupled":"Acoplados","Oscillators":"Osciladores",
  "Standing":"Estacionaria","Beats":"Pulsaciones","Inverse":"Inversa",
  "Mutual":"Mutua","Self":"Propia",
  "Cyclotron":"Ciclotrón","Maker":"Fabricante","Grinding":"Rejilla",
  "Lines":"Líneas","Absorptivity":"Absortividad",
  "Beer-Lambert":"Beer-Lambert","Spectrophotometer":"Espectrofotómetro",
  "M1V1":"M1V1",
  "Debye-Hückel":"Debye-Hückel","Half-Life":"Vida Media",
  "Carbon-14":"Carbono-14","Method":"Método","Joints":"Nudos",
  "Section":"Sección","Modulus":"Módulo","Product":"Producto",
  "Plate":"Placa","Shell":"Cáscara","SDOF":"1GL","MDOF":"MGL",
  "VAV":"VAV","HVAC":"HVAC","Handler":"Manejador",
  "Differential":"Diferencial","Settling":"Sedimentación",
  "CSTR":"CSTR","PFR":"PFR","Batch":"Discontinuo","Bed":"Lecho",
  "McCabe-Thiele":"McCabe-Thiele","Liquid-Liquid":"Líquido-Líquido",
  "Pinch":"Pinch","Mass":"Masa","Energy":"Energía","PID":"PID",
  "Root":"Lugar","Locus":"de las Raíces",
  "Takeout":"Comida para Llevar","Cooking":"Cocinar",
  "Per":"Por","BOGO":"2x1","Gas":"Gasolina","EV":"VE",
  "Cell":"Celular","Phone":"Teléfono",
  "Travel":"Viaje","Insurance":"Seguro","Security":"Seguridad",
  "Utility":"Servicio","Estimate":"Estimación",
  "Phantom":"Fantasma","Incandescent":"Incandescente",
  "Santa":"Santa","Secret":"Secreto","eBay":"eBay","Etsy":"Etsy",
  "PayPal":"PayPal","Stripe":"Stripe","Yard":"Jardín",
  "Craigslist":"Craigslist","Pawn":"Prendario","Consignment":"Consignación",
  "Horse":"Caballos","Racing":"Carreras","Sports":"Deportivas",
  "Proposition":"Propuesta","Hustle":"Trabajo Extra",
  "Mothers":"Madre","Fathers":"Padre","Billing":"Facturación",
  "Half":"Medio","Birthday":"Cumpleaños",
  "Z-Test":"Prueba Z","T-Test":"Prueba T","Mann-Whitney":"Mann-Whitney",
  "Wilcoxon":"Wilcoxon","Kruskal-Wallis":"Kruskal-Wallis",
  "One-Way":"Unidireccional","Two-Way":"Bidireccional",
  "ANCOVA":"ANCOVA","MANOVA":"MANOVA",
  "HSD":"HSD","Post-Hoc":"Post-Hoc","Scheffe":"Scheffé",
  "Contingency":"Contingencia","Chi-Square":"Chi-Cuadrado",
  "Goodness":"Bondad","Fit":"Ajuste",
  "Multiple":"Múltiple","Poisson":"Poisson",
  "Elastic":"Elástica","Naive":"Ingenuo","Bayes":"Bayes",
  "KNN":"KNN","SVM":"SVM",
  "Kaplan-Meier":"Kaplan-Meier","Cox":"Cox","Odds":"Probabilidades",
  "Diagnostic":"Diagnóstica",
  "Eta-Squared":"Eta al Cuadrado","Omega-Squared":"Omega al Cuadrado",
  "Bland-Altman":"Bland-Altman","Passing-Bablok":"Passing-Bablok",
  "Herfindahl-Hirschman":"Herfindahl-Hirschman",
  "ARIMA":"ARIMA","Monte Carlo":"Monte Carlo",
  "PCA":"ACP","K-Means":"K-Medias","DBSCAN":"DBSCAN",
  "ChIP-qPCR":"ChIP-qPCR","Codominance":"Codominancia",
  "Grade":"Calificación","Growth":"Crecimiento",
  "Mifflin":"Mifflin","BMR":"TMB","Katch-McArdle":"Katch-McArdle",
  "TDEE":"GET","Body":"Corporal","Recomposition":"Recomposición",
  "Macros":"Macros","Loss":"Pérdida","Gain":"Ganancia",
  "Glycemic":"Glucémico","Index":"Índice","Load":"Carga",
  "Melatonin":"Melatonina","Omega-3":"Omega-3",
  "Body":"Corporal","Navy":"Naval",
  "Urine":"Orina","Specific":"Específico","Gravity":"Gravedad",
  "Sweat":"Sudor","Pulmonary":"Pulmonar",
  "Blood":"Sangre","Gas":"Gas","Interpreter":"Intérprete",
  "Anion":"Anión","Gap":"Brecha","Osmolar":"Osmolar",
  "Bilirubin":"Bilirrubina","Fractions":"Fracciones",
  "MELD-Na":"MELD-Na","FIB-4":"FIB-4","NASH":"NASH",
  "Charlson":"Charlson","Comorbidity":"Comorbilidad",
  "SAPS":"SAPS","SOFA":"SOFA","APACHE":"APACHE",
  "RRT":"TRR","Dosing":"Dosificación","FeNa":"FeNa","FeCl":"FeCl",
  "URR":"URR","Kt/V":"Kt/V","eGFR":"TFGe","CKD-EPI":"CKD-EPI",
  "Z-Score":"Puntuación Z","Percentile":"Percentil",
  "Mid-Arm":"Braquial","Triceps":"Tríceps","Subscapular":"Subescapular",
  "Suprailiac":"Suprailíaco","Age-Adjusted":"Ajustado por Edad",
  "Waist":"Cintura","Hip":"Cadera","Neck":"Cuello","Calf":"Pantorrilla",
  "Wrist":"Muñeca","ABI":"ÍTB","JVP":"PY","CVP":"PVC",
  "PAP":"PAP","PCWP":"PCP","PVR":"RVP","SVR":"RVS",
  "QT":"QT","Interval":"Intervalo","Dispersion":"Dispersión",
  "Epsilon":"Épsilon","Wave":"Onda","Sgarbossa":"Sgarbossa",
  "Well":"Well","DVT":"TVP","PE":"TEP","PERC":"PERC",
  "Padua":"Padua","HAS-BLED":"HAS-BLED","CHADS2":"CHADS2",
  "CHA2DS2-VASc":"CHA2DS2-VASc","MELD":"MELD","Child-Pugh":"Child-Pugh",
  "Ranson":"Ranson","BISAP":"BISAP","Glasgow":"Glasgow",
  "Procalcitonin":"Procalcitonina","Apgar":"Apgar","Ballard":"Ballard",
  "Dubowitz":"Dubowitz","Newborn":"Recién Nacido","Weight":"Peso",
  "Loss":"Pérdida","Jaundice":"Ictericia","Phototherapy":"Fototerapia",
  "Exchange":"Intercambio","Transfusion":"Transfusión",
  "Linear":"Lineal","Interpolation":"Interpolación","Bilinear":"Bilineal",
  "Spline":"Spline","Lagrange":"Lagrange",
  "Newton":"Newton","Forward":"Progresiva","Backward":"Regresiva",
  "Divided":"Dividida","Difference":"Diferencia","Least":"Mínimos",
  "Squares":"Cuadrados","Line":"Línea","Parabola":"Parábola",
  "Exponential":"Exponencial","Raphson":"Raphson",
  "Bisection":"Bisección","Secant":"Secante","False":"Falsa",
  "Position":"Posición","Fixed":"Fijo","Point":"Punto","Iteration":"Iteración",
  "Simpson":"Simpson","Trapezoidal":"Trapezoidal","Boole":"Boole",
  "Romberg":"Romberg","Integration":"Integración",
  "Gauss-Legendre":"Gauss-Legendre","Gauss-Laguerre":"Gauss-Laguerre",
  "Gauss-Hermite":"Gauss-Hermite","Gauss-Chebyshev":"Gauss-Chebyshev",
  "Euler":"Euler","Heun":"Heun","Runge-Kutta":"Runge-Kutta",
  "RK2":"RK2","RK4":"RK4","Fehlberg":"Fehlberg",
  "Dormand-Prince":"Dormand-Prince","Adams-Bashforth":"Adams-Bashforth",
  "Adams-Moulton":"Adams-Moulton","Finite":"Finita",
  "Difference":"Diferencia","Crank-Nicolson":"Crank-Nicolson",
  "Matrix":"Matriz","Inverse":"Inversa","Determinant":"Determinante",
  "Eigenvalues":"Valores Propios","Eigenvectors":"Vectores Propios",
  "LU":"LU","Decomposition":"Descomposición","Cholesky":"Cholesky",
  "QR":"QR","SVD":"SVD","Jacobi":"Jacobi","Iteration":"Iteración",
  "Gauss-Seidel":"Gauss-Seidel","Conjugate":"Conjugado","Gradient":"Gradiente",
  "Extended":"Extendido","Euclidean":"Euclidiano","Diophantine":"Diofántica",
  "Euler":"Euler","Totient":"Totiente","Mobius":"Möbius","Function":"Función",
  "Prime":"Factores","Factorization":"Primos","Sieve":"Criba",
  "Eratosthenes":"Eratóstenes","Goldbach":"Goldbach","Conjecture":"Conjetura",
  "Catalan":"Catalan","Numbers":"Números","Bell":"Bell",
  "Stirling":"Stirling","First":"Primer","Kind":"Tipo","Second":"Segundo",
  "Eulerian":"Eulerianos","Bernoulli":"Bernoulli","Numbers":"Números",
  "Fibonacci":"Fibonacci","Nth":"N-ésimo","Lucas":"Lucas","Tribonacci":"Tribonacci",
  "Sequence":"Secuencia","Pascal":"Pascal","Triangle":"Triángulo",
  "Binomial":"Binomial","Coefficient":"Coeficiente","Multinomial":"Multinomial",
  "Derangements":"Desarreglos","Combinations":"Combinaciones","Repetition":"Repetición",
  "Permutations":"Permutaciones","Circular":"Circular",
  "Partial":"Parciales","Fractions":"Fracciones",
  "Polynomial":"Polinomial","Division":"División","GCD":"MCD",
  "Resultant":"Resultante","Discriminant":"Discriminante",
  "Horner":"Horner","Minimax":"Minimax","Padé":"Padé",
  "Approximant":"Aproximante","Continued":"Continua","Fraction":"Fracción",
  "Babylonian":"Babilónico","Square":"Cuadrada","Root":"Raíz",
  "Date":"Fecha","Difference":"Diferencia","Days":"Días",
  "Calendar":"Calendario","Month":"Mes","View":"Vista",
  "Business":"Laborables","Between":"Entre","Add":"Agregar",
  "Leap":"Bisiesto","Year":"Año","Check":"Verificación",
  "Day":"Día","Year":"Año","Quarter":"Trimestre","Time":"Tiempo",
  "Duration":"Duración","HMS":"HMS","Difference":"Diferencia",
  "Minutes":"Minutos","Seconds":"Segundos","Timecard":"Tarjeta de Tiempo",
  "Clock":"Reloj","Punch":"Marcar","Overtime":"Horas Extra",
  "Rotating":"Rotativo","Shift":"Turno","Night":"Nocturno",
  "Zone":"Zona","Abbreviation":"Abreviatura","DST":"HVD",
  "World":"Mundial","Exact":"Exacta",
  "Since":"Desde","Between":"Entre","Months":"Meses","Years":"Años",
  "Easter":"Pascua","Passover":"Pésaj","Ramadan":"Ramadán",
  "Chinese":"Chino","New":"Nuevo","Year":"Año","Diwali":"Diwali",
  "Hanukkah":"Janucá","Dates":"Fechas","Thanksgiving":"Acción de Gracias",
  "Memorial":"Conmemorativo","Labor":"Trabajo","Day":"Día",
  "Mothers":"Madre","Fathers":"Padre","DST":"HVD","Start":"Inicio","End":"Fin",
  "Solstice":"Solsticio","Equinox":"Equinoccio",
  "Grace":"Gracia","Period":"Período","Lease":"Arrendamiento",
  "Term":"Plazo","Subscription":"Suscripción","Renewal":"Renovación",
  "Warranty":"Garantía","Expiration":"Vencimiento","Project":"Proyecto",
  "Milestone":"Hito","Gantt":"Gantt","Timeline":"Cronograma",
  "Pomodoro":"Pomodoro","Timer":"Temporizador","Interval":"Intervalo",
  "Stopwatch":"Cronómetro","Lap":"Vuelta","Time":"Tiempo",
  "Addition":"Suma","Subtraction":"Resta","Unix":"Unix",
  "Timestamp":"Marca de Tiempo","Julian":"Juliano","Date":"Fecha",
  "Modified":"Modificado","Indian":"Indio","National":"Nacional",
  "Buddhist":"Budista","Calendar":"Calendario",
  "Shear":"Corte","Wall":"Muro","Rebar":"Varilla","Spacing":"Espaciado",
  "Lap":"Solape","Splice":"Empalme","Cylinder":"Cilíndrica",
  "Slump":"Asentamiento","Mortar":"Mortero","Brick":"Ladrillo",
  "Block":"Bloque","Estimate":"Estimación","Stone":"Piedra","Veneer":"Revestimiento",
  "Paver":"Adoquín","Sand":"Arena","Asphalt":"Asfalto","Gravel":"Grava",
  "Crushed":"Triturada","Mulch":"Acodo","Coverage":"Cobertura","Sod":"Césped",
  "Grass":"Hierba","Seed":"Semilla","Roof":"Techo",
  "Ventilation":"Ventilación","Gutter":"Canaleta","Downspout":"Bajante",
  "Guard":"Protector","Door":"Puerta","Jamb":"Jamba","Header":"Cabecero",
  "Window":"Ventana","Well":"Pozo","Drywall":"Panel de Yeso",
  "Sheets":"Planchas","Tape":"Cinta","Mud":"Pasta","Corner":"Esquina",
  "Bead":"Cuenta","Wainscoting":"Zócalo","Layout":"Diseño",
  "Shoe":"Zapato","Molding":"Moldura","Casing":"Marco","Trim":"Moldura",
  "Picture":"Cuadro","Rail":"Riel","Built":"Empotrado",
  "Shelving":"Estantería","Closet":"Armario","Organizer":"Organizador",
  "Garage":"Garaje","Shop":"Taller","Lighting":"Iluminación",
  "Driveway":"Entrada","Parking":"Estacionamiento","Stall":"Espacio",
  "Sidewalk":"Acera","Curb":"Bordillo","Ramp":"Rampa",
  "As-Built":"Construido","Measurement":"Medición","Tape":"Cinta",
  "Survey":"Topográfico","Baseline":"Línea Base","Traverse":"Poligonal",
  "Closure":"Cierre","Leveling":"Nivelación","Network":"Red",
  "Contour":"Curva de Nivel","Staking":"Replanteo","Excavation":"Excavación",
  "Trench":"Zanja","Safety":"Seguridad","Cofferdam":"Ataguía",
  "Design":"Diseño","Dewatering":"Desagüe","Driving":"Hincado",
  "Drilled":"Perforado","Shaft":"Pozo","Helical":"Helicoidal","Pile":"Pilote",
  "Tieback":"Anclaje","Anchor":"Anclaje","Grout":"Lechada",
  "Consolidation":"Consolidación","Joint":"Junta","Cold":"Fría",
  "Expansion":"Expansión","Control":"Control","Isolation":"Aislamiento",
  "Waterstop":"Junta de Agua","Scaffold":"Andamio","Ties":"Ataduras",
  "Load":"Carga","Fall":"Caída","Protection":"Protección",
  "Confined":"Confinado","Space":"Espacio","Lockout":"Bloqueo","Tagout":"Etiquetado",
  "Crane":"Grúa","Safety":"Seguridad",
  "Permutations":"Permutaciones","Combinations":"Combinaciones",
  // Specific named scientific terms
  "Wien":"Wien","Stefan-Boltzmann":"Stefan-Boltzmann",
  "Chandrasekhar":"Chandrasekhar","Eddington":"Eddington",
  "Fresnel":"Fresnel","Planck":"Planck",
  "Van der Waals":"Van der Waals","Maxwell-Boltzmann":"Maxwell-Boltzmann",
  "Clausius-Clapeyron":"Clausius-Clapeyron","Raoult":"Raoult",
  "Arrhenius":"Arrhenius","Nernst":"Nernst","Hess":"Hess",
  "Le Chatelier":"Le Chatelier","Gibbs":"Gibbs",
  "Newton-Raphson":"Newton-Raphson",
  // Quality-of-life terms
  "Itemized":"Detallada","Standard":"Estándar","Deduction":"Deducción",
  "Required":"Requerida","Minimum":"Mínima","Distribution":"Distribución",
  "Stretch":"Extendida","Traditional":"Tradicional",
  "Inherited":"Heredada","Backdoor":"Trasero",
  "Effective":"Efectiva","Marginal":"Marginal",
  "Gig":"Trabajo Independiente","Economy":"Economía",
  "Consolidation":"Consolidación","Affordability":"Capacidad de Pago",
  "Contribution":"Contribución","Operating":"Operativo",
  "Leverage":"Apalancamiento","Financial":"Financiero",
  "Deductible":"Deducible","Out-of-Pocket":"De Bolsillo",
  "Maximum":"Máximo","Dividend":"Dividendo","Growth":"Crecimiento",
  "Payout":"Pago","Retention":"Retención","Plowback":"Reinversión",
  "Admission":"Admisión","Chance":"Probabilidad",
  "In-State":"Estatal","Out-of-State":"Fuera del Estado",
  "Meal":"Comida","Living":"Vida","Expenses":"Gastos",
  "Plagiarism":"Plagio","Grammar":"Gramática",
  "Fundraiser":"Recaudación de Fondos",
  "Group":"Grupo","Project":"Proyecto","Peer":"Compañero",
  "Evaluation":"Evaluación","Weekly":"Semanales",
  "Assignments":"Tareas","Learning":"Aprendizaje","Objectives":"Objetivos",
  "Lesson":"Lección","Plan":"Plan","Duration":"Duración",
  "Late":"Tardío","Work":"Trabajo","Penalty":"Penalización",
  "Extra":"Extra","Credit":"Crédito","Make-Up":"Recuperación",
  "IEP":"IEP","Accommodations":"Adaptaciones","ELL":"ELL",
  "Gifted":"Dotado","Identification":"Identificación",
  "Dyslexia":"Dislexia","Screener":"Evaluador",
  "Lexile":"Lexile","Dolch":"Dolch","Sight":"Visuales","Words":"Palabras",
  "Typing":"Mecanografía","Speed":"Velocidad","Test":"Prueba",
  "Keyboarding":"Teclado","Skills":"Habilidades",
  "Internet":"Internet","Safety":"Seguridad",
  "Media":"Medios","Literacy":"Alfabetización",
  "Coding":"Programación","1D":"1D",
  "Mass":"Masa","Energy":"Energía",
  "Equivalence":"Equivalencia",
  "Lorentz":"Lorentz","Transformation":"Transformación",
  "Velocity":"Velocidad","Addition":"Adición",
  "Twin":"Gemelos","Paradox":"Paradoja",
  "Kepler":"Kepler","Third":"Tercera","Law":"Ley",
  "Hohmann":"Hohmann","Transfer":"Transferencia",
  "Tsiolkovsky":"Tsiolkovsky","Rocket":"Cohete",
  "Specific":"Específico","Impulse":"Impulso",
  "Van der Waals":"Van der Waals",
  "Kinetic":"Cinética","Theory":"Teoría",
  "Maxwell-Boltzmann":"Maxwell-Boltzmann",
  "Engine":"Máquina Térmica","Carnot":"Carnot","Otto":"Otto",
  "Diesel":"Diesel","Brayton":"Brayton",
  "Mass":"Porcentaje","Percent":"en Masa",
  "Combustion":"Combustión","Analysis":"Análisis",
  "Moles":"Moles","Particles":"Partículas",
  "Empirical":"Empírica","Molecular":"Molecular",
  "Salt":"Sal","Hydrolysis":"Hidrólisis",
  "Common":"Común","Ion":"Iónico","Effect":"Efecto",
  "Ksp":"Kps","Solubility":"Solubilidad","Product":"Producto",
  "Precipitation":"Precipitación","Conditions":"Condiciones",
  "Complex":"Complejo","Ion":"Iónico","Equilibrium":"Equilibrio",
  "Reaction":"Reacción","Quotient":"Cociente",
  "Equilibrium":"Equilibrio","Constant":"Constante",
  "Rate":"Velocidad","Law":"Ley",
  "Integrated":"Integrada","First":"Primer","Order":"Orden",
  "Second":"Segundo","Zero":"Cero","Arrhenius":"Arrhenius",
  "Activation":"Activación","Reaction":"Reacción","Mechanism":"Mecanismo",
  "Catalyst":"Catalizador","Effect":"Efecto",
  "Electrochemical":"Electroquímica","Cell":"Celda",
  "Standard":"Estándar","Cell":"Celda","Potential":"Potencial",
  "Nernst":"Nernst","Equation":"Ecuación",
  "Faraday":"Faraday","Constant":"Constante",
  "Oxidation":"Número de Oxidación","Number":"Número",
  "Coordination":"Número de Coordinación",
  "Crystal":"Cristal","Field":"Campo","Theory":"Teoría",
  "Ligand":"Ligando","Field":"Campo","Magnetic":"Magnético",
  "Moment":"Momento","Rydberg":"Rydberg","Equation":"Ecuación",
  "Spectral":"Espectrales","Lines":"Líneas",
  "Molar":"Absortividad Molar","Absorptivity":"Absortividad",
  "Beer-Lambert":"Beer-Lambert","Spectrophotometer":"Espectrofotómetro",
  "Molarity":"Molaridad","Dilution":"Dilución","M1V1":"M1V1",
  "Normality":"Normalidad","Molality":"Molalidad",
  "Mole":"Fracción Molar","Fraction":"Fracción",
  "Formal":"Concentración Formal","Concentration":"Concentración",
  "Ionic":"Fuerza Iónica","Strength":"Fuerza",
  "Activity":"Coeficiente de Actividad",
  "Coefficient":"Coeficiente","Debye-Hückel":"Debye-Hückel",
  "Radioactivity":"Dosis de Radiactividad","Dose":"Dosis",
  "Half-Life":"Vida Media","Radioactive":"Radiactivo",
  "Carbon-14":"Carbono-14","Dating":"Datación",
  // Engineering additional
  "Truss":"Armadura","Analysis":"Análisis","Joints":"Nodos",
  "Method":"Método","Of":"de","Sections":"Secciones",
  "Frame":"Marco","Analysis":"Análisis",
  "Beam":"Viga","Reactions":"Reacciones",
  "Shear":"Cortante","Moment":"Momento","Diagram":"Diagrama",
  "Conjugate":"Conjugado","Beam":"Viga","Method":"Método",
  "Area":"Área","Method":"Método","Virtual":"Virtual","Work":"Trabajo",
  "Strain":"Energía de Deformación","Energy":"Energía",
  "Indeterminate":"Viga Indeterminada","Beam":"Viga",
  "Slope":"Pendiente","Deflection":"Deflexión",
  "Stiffness":"Matriz de Rigidez","Truss":"Armadura",
  "Flexibility":"Matriz de Flexibilidad","Matrix":"Matriz",
  "Influence":"Línea de Influencia","Line":"Línea",
  "Plastic":"Análisis Plástico","Analysis":"Análisis",
  "Section":"Módulo de Sección","Modulus":"Módulo",
  "Moment":"Momento de Inercia","Of":"de","Inertia":"Inercia",
  "Product":"Producto de Inercia","Of":"de","Principal":"Principal",
  "Moment":"Momento Principal de Inercia","Principal":"Principal",
  "Torsion":"Torsión de Eje","Of":"de","Shaft":"Eje",
  "Thin":"Pared Delgada","Walled":"Presión en Vaso","Pressure":"Presión",
  "Vessel":"Vaso","Thick":"Pared Gruesa","Walled":"Cilindro",
  "Cylinder":"Cilindro","Lame":"Lame","Combined":"Combinado",
  "Stress":"Esfuerzo","Mohr":"Círculo de Mohr","Circle":"Círculo",
  "2D":"2D","3D":"3D","Failure":"Teorías de Falla",
  "Fatigue":"Vida a Fatiga","Life":"Vida","S-N":"S-N",
  "Goodman":"Diagrama de Goodman","Diagram":"Diagrama",
  "Soderberg":"Línea de Soderberg","Line":"Línea",
  "Gerber":"Parábola de Gerber","Parabola":"Parábola",
  "Stress":"Concentración de Esfuerzos","Concentration":"Concentración",
  "Crack":"Crecimiento de Grietas","Growth":"Ley de Paris",
  "Paris":"Paris","Law":"Ley","Fracture":"Tenacidad de Fractura",
  "Toughness":"Tenacidad",
  "Column":"Pandeo de Euler en Columnas","Buckling":"Pandeo",
  "Euler":"Euler","Plate":"Pandeo de Placas","Buckling":"Pandeo",
  "Shell":"Pandeo de Cáscaras","SDOF":"Vibración 1GL",
  "MDOF":"Vibración MGL","Vibration":"Vibración",
  "Modal":"Análisis Modal","Analysis":"Análisis",
  "Base":"Aislamiento de Base","Isolation":"Aislamiento",
  "Pipe":"Flujo Darcy-Weisbach en Tuberías","Flow":"Flujo",
  "Minor":"Pérdidas Menores","Losses":"Pérdidas",
  "Pipe":"Red Hardy Cross","Network":"Red","Water":"Golpe de Ariete",
  "Hammer":"Golpe de Ariete",
  "Open":"Canal Abierto","Channel":"Canal","Manning":"Manning",
  "Notch":"Muesca de Vertedero","Weir":"Vertedero",
  "Energy":"Energía Específica","Specific":"Específica",
  "Sediment":"Transporte de Sedimentos","Transport":"Transporte",
  "Mixing":"Tanque de Mezcla","Tank":"Tanque",
  "Conduction":"Transferencia de Calor por Conducción","Heat":"Calor",
  "Transfer":"Transferencia","Convection":"Convección",
  "Radiation":"Radiación","Fins":"Aletas",
  "Heat":"Intercambiador de Calor","Exchanger":"Intercambiador",
  "NTU":"NTU","LMTD":"MLTD",
  "Transient":"Conducción Transitoria de Calor",
  "Refrigeration":"Ciclo de Refrigeración","Cycle":"Ciclo",
  "Nozzle":"Flujo Isentrópico en Tobera","Flow":"Flujo",
  "Isentropic":"Isentrópico","Diffuser":"Difusor",
  "Shock":"Onda de Choque","Wave":"Onda",
  "Fan":"Mapa de Rendimiento de Ventilador","Performance":"Rendimiento",
  "Pump":"Mapa de Rendimiento de Bomba","Compressor":"Compresor",
  "Gas":"Ciclo Brayton de Turbina de Gas","Turbine":"Turbina",
  "Steam":"Ciclo Rankine de Vapor","Rankine":"Rankine",
  "Cogeneration":"Cogeneración","Chiller":"Rendimiento de Enfriador",
  "Cooling":"Torre de Enfriamiento","Tower":"Torre",
  "HVAC":"Carga de Enfriamiento HVAC","Heating":"Calefacción",
  "Duct":"Diseño de Conductos","Equal":"Igual","Friction":"Fricción",
  "Handler":"Dimensionamiento de Manejador de Aire","Sizing":"Dimensionamiento",
  "VAV":"Dimensionamiento de Caja VAV","Box":"Caja",
  "Differential":"Sedimentación Diferencial","Settling":"Sedimentación",
  "Cyclone":"Separador Ciclónico","Separator":"Separador",
  "Baghouse":"Filtro de Bolsa","Filter":"Filtro",
  "Electrostatic":"Precipitador Electrostático","Precipitator":"Precipitador",
  "CSTR":"Reactor CSTR","PFR":"Reactor PFR",
  "Batch":"Reactor Discontinuo","Catalyst":"Lecho Catalítico",
  "Bed":"Lecho","Distillation":"Columna de Destilación",
  "Column":"Columna","Absorption":"Columna de Absorción",
  "Liquid-Liquid":"Extracción Líquido-Líquido","Extraction":"Extracción",
  "Adsorption":"Columna de Adsorción","Membrane":"Separación por Membrana",
  "Separation":"Separación","Crystallization":"Cristalización",
  "Drying":"Velocidad de Secado","Filtration":"Filtración",
  "Centrifugation":"Centrifugación","Mixer":"Diseño de Mezclador",
  "Agitated":"Vaso Agitado","Vessel":"Vaso",
  "Pinch":"Análisis Pinch","Mass":"Balance de Masa",
  "Energy":"Balance de Energía","PID":"Sintonización PID",
  "Control":"Estabilidad del Lazo de Control",
  "Loop":"Lazo","Stability":"Estabilidad",
  "Block":"Reducción de Diagrama de Bloques","Diagram":"Diagrama",
  "Bode":"Diagrama de Bode","Nyquist":"Diagrama de Nyquist",
  "Root":"Lugar de las Raíces","Locus":"Locus",
  // Every day terms
  "Takeout":"Comida para Llevar vs Cocinar","Cooking":"Cocinar",
  "Tip":"Propina","By":"Por","Quality":"Calidad","Service":"Servicio",
  "Bill":"División de Cuenta","Split":"Dividir",
  "Coupon":"Acumulación de Cupones","Gift":"Tarjeta de Regalo",
  "Card":"Tarjeta","Value":"Saldo",
  "Price":"Precio por Unidad","Per":"Por","Unit":"Unidad",
  "Unit":"Comparación de Precios por Unidad","Pricing":"Precios",
  "BOGO":"Oferta 2x1","Deal":"Comparación de Ofertas",
  "Gas":"Rendimiento de Gasolina","Mileage":"Rendimiento",
  "EV":"VE vs Gasolina","Gas":"Gasolina",
  "Public":"Tarifa de Transporte Público","Transit":"Transporte",
  "Packing":"Lista de Empaque","Travel":"Seguro de Viaje",
  "Security":"Depósito de Seguridad","Renters":"Seguro de Inquilinos",
  "Cell":"Plan de Teléfono Celular","Phone":"Teléfono",
  "Streaming":"Servicios de Streaming","Cable":"Cable vs Streaming",
  "Gym":"Membresía de Gimnasio","Pet":"Seguro de Mascotas",
  "Home":"Mantenimiento del Hogar","Maintenance":"Mantenimiento",
  "Cleaning":"Suministros de Limpieza","Water":"Factura de Agua",
  "Electric":"Factura de Electricidad","Appliance":"Energía de Electrodomésticos",
  "Phantom":"Carga Fantasma","Power":"Potencia",
  "LED":"LED vs Incandescente","Incandescent":"Incandescente",
  "Generator":"Dimensionamiento de Generador",
  "Secret":"Amigo Secreto","Santa":"Santa",
  "Charity":"Donación Caritativa","Fundraiser":"Meta de Recaudación",
  "eBay":"Tarifas de eBay","Etsy":"Tarifas de Etsy",
  "PayPal":"Tarifas de PayPal","Stripe":"Tarifas de Stripe",
  "Yard":"Precios de Venta de Garaje","Sale":"Venta",
  "Craigslist":"Precios de Craigslist","Pawn":"Préstamo Prendario",
  "Consignment":"Precios de Consignación","Auction":"Martillo de Subasta",
  "Lottery":"Probabilidades de Lotería","Raffle":"Boletos de Rifa",
  "Sweepstakes":"Participación en Sorteos","Entry":"Participación",
  "Bingo":"Probabilidad de Bingo","Poker":"Probabilidades de Manos de Póquer",
  "Hand":"Mano","Odds":"Probabilidades",
  "Blackjack":"Estrategia Básica de Blackjack","Basic":"Básica",
  "Roulette":"Probabilidades de Ruleta","Craps":"Probabilidades de Craps",
  "Horse":"Probabilidades de Carreras de Caballos","Racing":"Carreras",
  "Sports":"Apuestas Deportivas","Betting":"Apuestas",
  "Parlay":"Probabilidades de Apuestas Combinadas",
  "Debt":"Bola de Nieve de Deuda","Snowball":"Bola de Nieve",
  "Avalanche":"Avalancha de Deuda","Hustle":"Ingresos Extra",
  "Freelance":"Tarifa Freelance","Passive":"Ingreso Pasivo",
  "Net":"Patrimonio Neto","Worth":"Patrimonio",
  // Calendar/Date specific
  "Human":"Humano","Years":"Años","Dog":"Perro","In":"en",
  "Furniture":"Muebles","Arrangement":"Disposición",
  "Break-Even":"Punto de Equilibrio",
  "Cost":"Costo","Volume":"Volumen","Profit":"Ganancia",
  "Debt":"Deuda","Service":"Servicio","Coverage":"Cobertura",
  "Interest":"Interés","Coverage":"Cobertura",
  "Ratio":"Relación","Fixed":"Fija","Charge":"Cargo",
  "Times":"Veces","Interest":"Intereses","Earned":"Ganados",
  "Earnings":"Ganancias","Per":"Por","Share":"Acción",
  "Small":"Pequeña","Business":"Negocio","Hard":"Difícil",
  "Money":"Dinero","Reverse":"Inversa","Mortgage":"Hipoteca",
  "Shared":"Compartida","Appreciation":"Apreciación",
  "Seller":"Vendedor","Financing":"Financiamiento",
  "Real":"Bienes","Estate":"Raíces","Rental":"Alquiler",
  "Property":"Propiedad","Capital":"Capital","Asset":"Activos",
  "Pricing":"Valoración","Model":"Modelo","WACC":"WACC",
  "Discounted":"Flujo de Caja Descontado","Cash":"Efectivo",
  "Flow":"Flujo","Terminal":"Valor Terminal","Enterprise":"Empresa",
  "Pre-Money":"Valoración Pre-Money","Post-Money":"Post-Money",
  "Valuation":"Valoración","Security":"Seguridad","Social":"Social",
  "Break-Even":"Punto de Equilibrio","Benefits":"Prestaciones",
  "Lump":"Suma","Sum":"Única","Annuity":"Anualidad",
  "Roth":"Roth","Traditional":"Tradicional",
  "Backdoor":"Trasero","Required":"Requerida","Minimum":"Mínima",
  "Distribution":"Distribución","Inherited":"Heredada",
  "Stretch":"Extendida","Health":"Salud","Savings":"Ahorros",
  "Account":"Cuenta","Interest":"Intereses","Income":"Ingresos",
  "Tax":"Impuesto","Rental":"Alquiler","Gig":"Trabajo Independiente",
  "Economy":"Economía","Tax":"Impuesto","Effective":"Efectiva",
  "Tax":"Tasa","Rate":"Impositiva","Marginal":"Marginal",
  "Itemized":"Detallada","Standard":"Estándar","Deduction":"Deducción",
  "Payoff":"Liquidación","Consolidation":"Consolidación",
  "Affordability":"Capacidad de Pago","Value":"Valor",
  "Churn":"Rotación","Recurring":"Recurrente","Revenue":"Ingresos",
  "Contribution":"Margen de Contribución","Margin":"Margen",
  "Operating":"Apalancamiento Operativo","Financial":"Financiero",
  "Leverage":"Apalancamiento","Term":"Plazo","Whole":"Vida Entera",
  "Disability":"Discapacidad","Long-Term":"Largo Plazo",
  "Short-Term":"Corto Plazo","Health":"Salud","Insurance":"Seguro",
  "Out-of-Pocket":"De Bolsillo","Maximum":"Máximo",
  "Debt-to-Asset":"Deuda a Activos","Debt-to-Equity":"Deuda a Capital",
  "Price-to-Book":"Precio a Valor Contable","Price-to-Sales":"Precio a Ventas",
  "PEG":"PEG","Dividend":"Dividendo","Growth":"Crecimiento",
  "Payout":"Pago","Retention":"Retención","Plowback":"Reinversión",
  // Acronyms (keep as-is or with known translations)
  "BSA":"SC","FENa":"FeNa","QTc":"QTc","CKD-EPI":"CKD-EPI",
  "MELD":"MELD","NYHA":"NYHA","Killip":"Killip","TIMI":"TIMI",
  "GRACE":"GRACE","SYNTAX":"SYNTAX","CURB-65":"CURB-65",
  "qSOFA":"qSOFA","PIOPED":"PIOPED","Wells":"Wells",
  "Geneva":"Ginebra","ADNEX":"ADNEX","BI-RADS":"BI-RADS",
  "TI-RADS":"TI-RADS","PI-RADS":"PI-RADS","O-RADS":"O-RADS",
  "ChIP-qPCR":"ChIP-qPCR","Codominance":"Codominancia",
  "qPCR":"qPCR",
};

writeFileSync(join(dictDir, 'es.json'), JSON.stringify(es));
console.log('Spanish dict: ' + Object.keys(es).length + ' entries');
