@echo off
echo Setting up database...
echo Running Prisma generate...
call npx prisma generate
echo Running Prisma db push...
call npx prisma db push
echo Running seed...
call npx tsx prisma/seed.ts
echo Done!
