import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASE = join(__dirname, '..', 'src', 'i18n', 'calculator-overrides');
const dictDir = join(__dirname, 'dict');

const en = JSON.parse(readFileSync(join(BASE, 'en.json'), 'utf-8'));
const locales = ['es','fr','de','pt','ru','ar','hi','ja','zh-CN'];

function loadJSON(fp) {
  try { return JSON.parse(readFileSync(fp, 'utf-8')); }
  catch(e) { return {}; }
}

function loadDict(locale) {
  return loadJSON(join(dictDir, locale + '.json'));
}

function loadExact(locale) {
  return loadJSON(join(dictDir, locale + '-exact.json'));
}

// ========== EXACT PHRASES ==========
const exactMap = {
  es: {
    ...loadExact('es'),
    // Spanish remaining 108 - compound terms that need full phrase translation
    "Bonus Depreciation":"Depreciación Extraordinaria",
    "Growing Equity":"Capital Creciente",
    "Generation Skipping":"Salto Generacional",
    "Portability Election":"Elección de Portabilidad",
    "Crummey Powers":"Poderes Crummey",
    "Innocent Spouse":"Cónyuge Inocente",
    "Executive Bonus":"Bono Ejecutivo",
    "IRA Rollover":"Transferencia IRA",
    "IRA Recharacterization":"Recaracterización IRA",
    "529 Prepaid Tuition":"Tuición Prepagada 529",
    "Homocysteine":"Homocisteína",
    "CRP Cardiovascular":"PCR Cardiovascular",
    "Mifflin BMR":"TMB Mifflin",
    "Katch-McArdle BMR":"TMB Katch-McArdle",
    "BMI Ethnicity Adjusted":"IMC Ajustado por Etnia",
    "BMI for Children":"IMC para Niños",
    "BMI for Teens":"IMC para Adolescentes",
    "Gauss-Legendre Quadrature":"Cuadratura Gauss-Legendre",
    "Gauss-Laguerre Quadrature":"Cuadratura Gauss-Laguerre",
    "Gauss-Hermite Quadrature":"Cuadratura Gauss-Hermite",
    "Gauss-Chebyshev Quadrature":"Cuadratura Gauss-Chebyshev",
    "Mann-Whitney U":"U de Mann-Whitney",
    "Tukey HSD Post-Hoc":"HSD Post-Hoc de Tukey",
    "Bonferroni Post-Hoc":"Post-Hoc de Bonferroni",
    "Dunnett Post-Hoc":"Post-Hoc de Dunnett",
    "Kendall Tau":"Tau de Kendall",
    "Cramer V":"V de Cramer",
    "Cohen Kappa":"Kappa de Cohen",
    "Hedges G":"G de Hedges",
    "Herfindahl-Hirschman":"Herfindahl-Hirschman",
    "Work-Study":"Trabajo-Estudio",
    "RC Circuit":"Circuito RC",
    "RL Circuit":"Circuito RL",
    "LC Circuit":"Circuito LC",
    "RLC Series":"RLC Serie",
    "Van der Waals":"Van der Waals",
    "Maxwell-Boltzmann":"Maxwell-Boltzmann",
    "Polyprotic Acid pH":"pH de Ácido Poliprótico",
    "Clausius-Clapeyron":"Clausius-Clapeyron",
    "ChIP-qPCR":"ChIP-qPCR",
    "Wet Bulb Globe":"Globo de Bulbo Húmedo",
    "Hill Sphere":"Esfera de Hill",
    "Photoperiod":"Fotoperíodo",
    "Psychrometric":"Psicrometría",
    "Tsunami Runup":"Ascenso del Tsunami",
    "Manning n":"n de Manning",
    "Morse Taper":"Cono Morse",
    "Passing-Bablok":"Passing-Bablok",
    "Coverdell ESA":"Cuenta Coverdell ESA",
    "Maxwell-Boltzmann":"Maxwell-Boltzmann",
    "Roth 401k":"401k Roth",
    "SIMPLE 401k":"401k SIMPLE",
    "Safe Harbor 401k":"401k Safe Harbor",
    "Child-Pugh":"Child-Pugh",
    "Stub Matching":"Adaptación de Stub",
    "ABI":"ITB",
    "CVP":"PVC",
    "JVP":"PYD",
    "VSWR":"ROE",
    "EIRP":"PIRE",
    "PVR":"RVP",
    "SVR":"RVS",
    "PAP":"PAP",
    "PCWP":"PCP",
    "FeNa":"FeNa",
    "FeCl":"FeCl",
    "FiO2":"FiO2",
    "URR":"URR",
    "Kt/V":"Kt/V",
    "MELD-Na":"MELD-Na",
    "NQDC":"RPDNO",
  },
  fr: loadExact('fr'),
  de: loadExact('de'),
  pt: loadExact('pt'),
  ru: {
    "M² Beam Quality":"Качество луча M²",
    "Padé Approximant":"Аппроксимант Паде",
    "Activity Coefficient Debye-Hückel":"Коэффициент активности Дебая-Хюккеля"
  },
  ar: {},
  hi: {},
  ja: {},
  "zh-CN": {}
};

// ========== SUFFIX PATTERNS ==========
const suffixPatterns = {
  es: [
    { suffix: "Analysis", fmt: "Análisis {p}" },
    { suffix: "Law", fmt: "Ley {p}" },
    { suffix: "Laws", fmt: "Leyes {p}" },
    { suffix: "Effect", fmt: "Efecto {p}" },
    { suffix: "Equation", fmt: "Ecuación {p}" },
    { suffix: "Equations", fmt: "Ecuaciones {p}" },
    { suffix: "Theorem", fmt: "Teorema {p}" },
    { suffix: "Theory", fmt: "Teoría {p}" },
    { suffix: "Theories", fmt: "Teorías {p}" },
    { suffix: "Principle", fmt: "Principio {p}" },
    { suffix: "Principles", fmt: "Principios {p}" },
    { suffix: "Formula", fmt: "Fórmula {p}" },
    { suffix: "Method", fmt: "Método {p}" },
    { suffix: "Model", fmt: "Modelo {p}" },
    { suffix: "Function", fmt: "Función {p}" },
    { suffix: "Operator", fmt: "Operador {p}" },
    { suffix: "Transform", fmt: "Transformada {p}" },
    { suffix: "Rule", fmt: "Regla {p}" },
    { suffix: "Coefficient", fmt: "Coeficiente {p}" },
    { suffix: "Constant", fmt: "Constante {p}" },
    { suffix: "Variable", fmt: "Variable {p}" },
    { suffix: "Parameter", fmt: "Parámetro {p}" },
    { suffix: "Parameters", fmt: "Parámetros {p}" },
    { suffix: "Factor", fmt: "Factor {p}" },
    { suffix: "Limit", fmt: "Límite {p}" },
    { suffix: "Cycle", fmt: "Ciclo {p}" },
    { suffix: "Design", fmt: "Diseño {p}" },
    { suffix: "Process", fmt: "Proceso {p}" },
    { suffix: "Testing", fmt: "Pruebas {p}" },
    { suffix: "Scale", fmt: "Escala {p}" },
    { suffix: "Criterion", fmt: "Criterio {p}" },
    { suffix: "Criteria", fmt: "Criterios {p}" },
    { suffix: "Point", fmt: "Punto {p}" },
    { suffix: "Points", fmt: "Puntos {p}" },
    { suffix: "Zone", fmt: "Zona {p}" },
    { suffix: "Mode", fmt: "Modo {p}" },
    { suffix: "Phase", fmt: "Fase {p}" },
    { suffix: "Date", fmt: "Fecha {p}" },
    { suffix: "Dates", fmt: "Fechas {p}" },
    { suffix: "Time", fmt: "Tiempo {p}" },
    { suffix: "Schedule", fmt: "Horario {p}" },
    { suffix: "Plan", fmt: "Plan {p}" },
    { suffix: "Curve", fmt: "Curva {p}" },
    { suffix: "Matrix", fmt: "Matriz {p}" },
    { suffix: "Vector", fmt: "Vector {p}" },
    { suffix: "Space", fmt: "Espacio {p}" },
    { suffix: "Field", fmt: "Campo {p}" },
    { suffix: "Map", fmt: "Mapa {p}" },
    { suffix: "Plot", fmt: "Gráfico {p}" },
    { suffix: "Chart", fmt: "Gráfico {p}" },
    { suffix: "Risk", fmt: "Riesgo {p}" },
    { suffix: "Margin", fmt: "Margen {p}" },
    { suffix: "Error", fmt: "Error {p}" },
    { suffix: "Difference", fmt: "Diferencia {p}" },
    { suffix: "Trend", fmt: "Tendencia {p}" },
    { suffix: "Flow", fmt: "Flujo {p}" },
    { suffix: "Rate", fmt: "Tasa {p}" },
    { suffix: "Gradient", fmt: "Gradiente {p}" },
    { suffix: "Wave", fmt: "Onda {p}" },
    { suffix: "Signal", fmt: "Señal {p}" },
    { suffix: "Norm", fmt: "Norma {p}" },
    { suffix: "Budget", fmt: "Presupuesto {p}" },
    { suffix: "Cost", fmt: "Costo {p}" },
    { suffix: "Costs", fmt: "Costos {p}" },
    { suffix: "Fee", fmt: "Tarifa {p}" },
    { suffix: "Fees", fmt: "Tarifas {p}" },
    { suffix: "Tax", fmt: "Impuesto {p}" },
    { suffix: "Payment", fmt: "Pago {p}" },
    { suffix: "Balance", fmt: "Saldo {p}" },
    { suffix: "Savings", fmt: "Ahorros {p}" },
    { suffix: "Loan", fmt: "Préstamo {p}" },
    { suffix: "Debt", fmt: "Deuda {p}" },
    { suffix: "Income", fmt: "Ingreso {p}" },
    { suffix: "Expense", fmt: "Gasto {p}" },
    { suffix: "Return", fmt: "Retorno {p}" },
    { suffix: "Growth", fmt: "Crecimiento {p}" },
    { suffix: "Investment", fmt: "Inversión {p}" },
    { suffix: "Trust", fmt: "Fideicomiso {p}" },
    { suffix: "Deduction", fmt: "Deducción {p}" },
    { suffix: "Credit", fmt: "Crédito {p}" },
    { suffix: "Credits", fmt: "Créditos {p}" },
    { suffix: "Exclusion", fmt: "Exclusión {p}" },
    { suffix: "Duration", fmt: "Duración {p}" },
    { suffix: "Period", fmt: "Período {p}" },
    { suffix: "Count", fmt: "Conteo {p}" },
    { suffix: "Measurement", fmt: "Medición {p}" },
    { suffix: "Correction", fmt: "Corrección {p}" },
    { suffix: "Mixture", fmt: "Mezcla {p}" },
    { suffix: "Solution", fmt: "Solución {p}" },
    { suffix: "Concentration", fmt: "Concentración {p}" },
    { suffix: "Variation", fmt: "Variación {p}" },
    { suffix: "Surface", fmt: "Superficie {p}" },
    { suffix: "Stability", fmt: "Estabilidad {p}" },
    { suffix: "Safety", fmt: "Seguridad {p}" },
    { suffix: "Protection", fmt: "Protección {p}" },
    { suffix: "Requirements", fmt: "Requisitos {p}" },
    { suffix: "Sizing", fmt: "Dimensionamiento {p}" },
    { suffix: "Payoff", fmt: "Liquidación {p}" },
    { suffix: "Penalty", fmt: "Penalización {p}" },
    { suffix: "Test", fmt: "Prueba {p}" },
    { suffix: "Check", fmt: "Verificación {p}" },
    { suffix: "Assessment", fmt: "Evaluación {p}" },
    { suffix: "Audit", fmt: "Auditoría {p}" },
    { suffix: "Benefits", fmt: "Beneficios {p}" },
    { suffix: "Planning", fmt: "Planificación {p}" },
    { suffix: "Status", fmt: "Estado {p}" },
    { suffix: "Position", fmt: "Posición {p}" },
    { suffix: "Location", fmt: "Ubicación {p}" },
    { suffix: "Slope", fmt: "Pendiente {p}" },
    { suffix: "Suspension", fmt: "Suspensión {p}" },
    { suffix: "Probation", fmt: "Probación {p}" },
    { suffix: "Allowance", fmt: "Asignación {p}" },
    { suffix: "Rating", fmt: "Evaluación {p}" },
    { suffix: "Ratings", fmt: "Evaluaciones {p}" },
    { suffix: "Score", fmt: "Puntuación {p}" },
    { suffix: "Index", fmt: "Índice {p}" },
    { suffix: "Ratio", fmt: "Relación {p}" },
    { suffix: "Line", fmt: "Línea {p}" },
    { suffix: "Load", fmt: "Carga {p}" },
    { suffix: "Force", fmt: "Fuerza {p}" },
    { suffix: "Temperature", fmt: "Temperatura {p}" },
    { suffix: "Temp", fmt: "Temp {p}" },
    { suffix: "Pressure", fmt: "Presión {p}" },
    { suffix: "Density", fmt: "Densidad {p}" },
    { suffix: "Viscosity", fmt: "Viscosidad {p}" },
    { suffix: "Conductivity", fmt: "Conductividad {p}" },
    { suffix: "Resistance", fmt: "Resistencia {p}" },
    { suffix: "Impedance", fmt: "Impedancia {p}" },
    { suffix: "Capacitance", fmt: "Capacitancia {p}" },
    { suffix: "Inductance", fmt: "Inductancia {p}" },
    { suffix: "Strength", fmt: "Fuerza {p}" },
    { suffix: "Speed", fmt: "Velocidad {p}" },
    { suffix: "Velocity", fmt: "Velocidad {p}" },
    { suffix: "Acceleration", fmt: "Aceleración {p}" },
    { suffix: "Momentum", fmt: "Momento {p}" },
    { suffix: "Energy", fmt: "Energía {p}" },
    { suffix: "Power", fmt: "Potencia {p}" },
    { suffix: "Frequency", fmt: "Frecuencia {p}" },
    { suffix: "Voltage", fmt: "Voltaje {p}" },
    { suffix: "Length", fmt: "Longitud {p}" },
    { suffix: "Width", fmt: "Ancho {p}" },
    { suffix: "Height", fmt: "Altura {p}" },
    { suffix: "Depth", fmt: "Profundidad {p}" },
    { suffix: "Thickness", fmt: "Grosor {p}" },
    { suffix: "Diameter", fmt: "Diámetro {p}" },
    { suffix: "Radius", fmt: "Radio {p}" },
    { suffix: "Angle", fmt: "Ángulo {p}" },
    { suffix: "Mass", fmt: "Masa {p}" },
    { suffix: "Weight", fmt: "Peso {p}" },
    { suffix: "Size", fmt: "Tamaño {p}" },
    { suffix: "Volume", fmt: "Volumen {p}" },
    { suffix: "Area", fmt: "Área {p}" },
    { suffix: "Capacity", fmt: "Capacidad {p}" },
    { suffix: "Efficiency", fmt: "Eficiencia {p}" },
    { suffix: "Performance", fmt: "Rendimiento {p}" },
    { suffix: "Loss", fmt: "Pérdida {p}" },
    { suffix: "Losses", fmt: "Pérdidas {p}" },
    { suffix: "Value", fmt: "Valor {p}" },
    { suffix: "Level", fmt: "Nivel {p}" },
    { suffix: "Levels", fmt: "Niveles {p}" },
    { suffix: "Quality", fmt: "Calidad {p}" },
    { suffix: "Distance", fmt: "Distancia {p}" },
    { suffix: "Range", fmt: "Rango {p}" },
    { suffix: "Section", fmt: "Sección {p}" },
    { suffix: "Sections", fmt: "Secciones {p}" },
    { suffix: "Grade", fmt: "Calificación {p}" },
    { suffix: "Work", fmt: "Trabajo {p}" },
    { suffix: "Heat", fmt: "Calor {p}" },
    { suffix: "Current", fmt: "Corriente {p}" },
    { suffix: "Tension", fmt: "Tensión {p}" },
    { suffix: "Stress", fmt: "Esfuerzo {p}" },
    { suffix: "Strain", fmt: "Deformación {p}" },
    { suffix: "Modulus", fmt: "Módulo {p}" },
    { suffix: "Hardness", fmt: "Dureza {p}" },
    { suffix: "Pair", fmt: "Par {p}" },
    { suffix: "Band", fmt: "Banda {p}" },
    { suffix: "Conversion", fmt: "Conversión {p}" },
    { suffix: "Setting", fmt: "Ajuste {p}" },
    { suffix: "Burn", fmt: "Consumo {p}" },
    { suffix: "Agreement", fmt: "Acuerdo {p}" },
    { suffix: "Financing", fmt: "Financiamiento {p}" },
    { suffix: "Renewal", fmt: "Renovación {p}" },
    { suffix: "Expiration", fmt: "Vencimiento {p}" },
    { suffix: "Milestone", fmt: "Hito {p}" },
    { suffix: "Timeline", fmt: "Cronograma {p}" },
    { suffix: "Timer", fmt: "Temporizador {p}" },
    { suffix: "Interval", fmt: "Intervalo {p}" },
    { suffix: "Timestamp", fmt: "Marca de Tiempo {p}" },
    { suffix: "View", fmt: "Vista {p}" },
    { suffix: "Interpolation", fmt: "Interpolación {p}" },
    { suffix: "Integration", fmt: "Integración {p}" },
    { suffix: "Decomposition", fmt: "Descomposición {p}" },
    { suffix: "Transformation", fmt: "Transformación {p}" },
    { suffix: "Iteration", fmt: "Iteración {p}" },
    { suffix: "Factorization", fmt: "Factorización {p}" },
    { suffix: "Smoothing", fmt: "Suavizado {p}" },
    { suffix: "Classifier", fmt: "Clasificador {p}" },
    { suffix: "Clustering", fmt: "Agrupamiento {p}" },
    { suffix: "Regression", fmt: "Regresión {p}" },
    { suffix: "Correlation", fmt: "Correlación {p}" },
    { suffix: "Survival", fmt: "Supervivencia {p}" },
    { suffix: "Filter", fmt: "Filtro {p}" },
    { suffix: "Separator", fmt: "Separador {p}" },
    { suffix: "Extraction", fmt: "Extracción {p}" },
    { suffix: "Vibration", fmt: "Vibración {p}" },
    { suffix: "Isolation", fmt: "Aislamiento {p}" },
    { suffix: "Reduction", fmt: "Reducción {p}" },
    { suffix: "Loop", fmt: "Lazo {p}" },
    { suffix: "Simulation", fmt: "Simulación {p}" },
    { suffix: "Standardization", fmt: "Estandarización {p}" },
    { suffix: "Identification", fmt: "Identificación {p}" },
    { suffix: "Forgiveness", fmt: "Condónación {p}" },
    { suffix: "Certification", fmt: "Certificación {p}" },
  ],
  fr: [
    { suffix: "Analysis", fmt: "Analyse {p}" },
    { suffix: "Law", fmt: "Loi {p}" },
    { suffix: "Effect", fmt: "Effet {p}" },
    { suffix: "Equation", fmt: "Équation {p}" },
    { suffix: "Equations", fmt: "Équations {p}" },
    { suffix: "Theorem", fmt: "Théorème {p}" },
    { suffix: "Theory", fmt: "Théorie {p}" },
    { suffix: "Principle", fmt: "Principe {p}" },
    { suffix: "Method", fmt: "Méthode {p}" },
    { suffix: "Model", fmt: "Modèle {p}" },
    { suffix: "Function", fmt: "Fonction {p}" },
    { suffix: "Operator", fmt: "Opérateur {p}" },
    { suffix: "Transform", fmt: "Transformée {p}" },
    { suffix: "Rule", fmt: "Règle {p}" },
    { suffix: "Coefficient", fmt: "Coefficient {p}" },
    { suffix: "Constant", fmt: "Constante {p}" },
    { suffix: "Variable", fmt: "Variable {p}" },
    { suffix: "Parameter", fmt: "Paramètre {p}" },
    { suffix: "Parameters", fmt: "Paramètres {p}" },
    { suffix: "Factor", fmt: "Facteur {p}" },
    { suffix: "Limit", fmt: "Limite {p}" },
    { suffix: "Cycle", fmt: "Cycle {p}" },
    { suffix: "Design", fmt: "Conception {p}" },
    { suffix: "Process", fmt: "Processus {p}" },
    { suffix: "Scale", fmt: "Échelle {p}" },
    { suffix: "Criterion", fmt: "Critère {p}" },
    { suffix: "Criteria", fmt: "Critères {p}" },
    { suffix: "Point", fmt: "Point {p}" },
    { suffix: "Points", fmt: "Points {p}" },
    { suffix: "Zone", fmt: "Zone {p}" },
    { suffix: "Mode", fmt: "Mode {p}" },
    { suffix: "Phase", fmt: "Phase {p}" },
    { suffix: "Time", fmt: "Temps {p}" },
    { suffix: "Schedule", fmt: "Horaire {p}" },
    { suffix: "Plan", fmt: "Plan {p}" },
    { suffix: "Curve", fmt: "Courbe {p}" },
    { suffix: "Matrix", fmt: "Matrice {p}" },
    { suffix: "Vector", fmt: "Vecteur {p}" },
    { suffix: "Space", fmt: "Espace {p}" },
    { suffix: "Field", fmt: "Champ {p}" },
    { suffix: "Map", fmt: "Carte {p}" },
    { suffix: "Plot", fmt: "Graphique {p}" },
    { suffix: "Chart", fmt: "Graphique {p}" },
    { suffix: "Risk", fmt: "Risque {p}" },
    { suffix: "Margin", fmt: "Marge {p}" },
    { suffix: "Error", fmt: "Erreur {p}" },
    { suffix: "Difference", fmt: "Différence {p}" },
    { suffix: "Trend", fmt: "Tendance {p}" },
    { suffix: "Flow", fmt: "Flux {p}" },
    { suffix: "Rate", fmt: "Taux {p}" },
    { suffix: "Gradient", fmt: "Gradient {p}" },
    { suffix: "Wave", fmt: "Onde {p}" },
    { suffix: "Signal", fmt: "Signal {p}" },
    { suffix: "Norm", fmt: "Norme {p}" },
    { suffix: "Budget", fmt: "Budget {p}" },
    { suffix: "Cost", fmt: "Coût {p}" },
    { suffix: "Costs", fmt: "Coûts {p}" },
    { suffix: "Fee", fmt: "Frais {p}" },
    { suffix: "Tax", fmt: "Impôt {p}" },
    { suffix: "Payment", fmt: "Paiement {p}" },
    { suffix: "Balance", fmt: "Solde {p}" },
    { suffix: "Savings", fmt: "Épargne {p}" },
    { suffix: "Loan", fmt: "Prêt {p}" },
    { suffix: "Debt", fmt: "Dette {p}" },
    { suffix: "Income", fmt: "Revenu {p}" },
    { suffix: "Expense", fmt: "Dépense {p}" },
    { suffix: "Return", fmt: "Rendement {p}" },
    { suffix: "Growth", fmt: "Croissance {p}" },
    { suffix: "Investment", fmt: "Investissement {p}" },
    { suffix: "Trust", fmt: "Fiducie {p}" },
    { suffix: "Deduction", fmt: "Déduction {p}" },
    { suffix: "Credit", fmt: "Crédit {p}" },
    { suffix: "Exclusion", fmt: "Exclusion {p}" },
    { suffix: "Duration", fmt: "Durée {p}" },
    { suffix: "Period", fmt: "Période {p}" },
    { suffix: "Count", fmt: "Comptage {p}" },
    { suffix: "Measurement", fmt: "Mesure {p}" },
    { suffix: "Correction", fmt: "Correction {p}" },
    { suffix: "Mixture", fmt: "Mélange {p}" },
    { suffix: "Solution", fmt: "Solution {p}" },
    { suffix: "Concentration", fmt: "Concentration {p}" },
    { suffix: "Variation", fmt: "Variation {p}" },
    { suffix: "Surface", fmt: "Surface {p}" },
    { suffix: "Stability", fmt: "Stabilité {p}" },
    { suffix: "Safety", fmt: "Sécurité {p}" },
    { suffix: "Protection", fmt: "Protection {p}" },
    { suffix: "Planning", fmt: "Planification {p}" },
    { suffix: "Sizing", fmt: "Dimensionnement {p}" },
    { suffix: "Payoff", fmt: "Remboursement {p}" },
    { suffix: "Penalty", fmt: "Pénalité {p}" },
    { suffix: "Test", fmt: "Test {p}" },
    { suffix: "Check", fmt: "Vérification {p}" },
    { suffix: "Assessment", fmt: "Évaluation {p}" },
    { suffix: "Audit", fmt: "Audit {p}" },
    { suffix: "Benefits", fmt: "Prestations {p}" },
    { suffix: "Status", fmt: "Statut {p}" },
    { suffix: "Position", fmt: "Position {p}" },
    { suffix: "Location", fmt: "Emplacement {p}" },
    { suffix: "Slope", fmt: "Pente {p}" },
    { suffix: "Suspension", fmt: "Suspension {p}" },
    { suffix: "Probation", fmt: "Probation {p}" },
    { suffix: "Allowance", fmt: "Allocation {p}" },
    { suffix: "Score", fmt: "Score {p}" },
    { suffix: "Index", fmt: "Indice {p}" },
    { suffix: "Ratio", fmt: "Rapport {p}" },
    { suffix: "Line", fmt: "Ligne {p}" },
    { suffix: "Load", fmt: "Charge {p}" },
    { suffix: "Force", fmt: "Force {p}" },
    { suffix: "Temperature", fmt: "Température {p}" },
    { suffix: "Pressure", fmt: "Pression {p}" },
    { suffix: "Density", fmt: "Densité {p}" },
    { suffix: "Viscosity", fmt: "Viscosité {p}" },
    { suffix: "Conductivity", fmt: "Conductivité {p}" },
    { suffix: "Resistance", fmt: "Résistance {p}" },
    { suffix: "Impedance", fmt: "Impédance {p}" },
    { suffix: "Capacitance", fmt: "Capacité {p}" },
    { suffix: "Inductance", fmt: "Inductance {p}" },
    { suffix: "Strength", fmt: "Résistance {p}" },
    { suffix: "Speed", fmt: "Vitesse {p}" },
    { suffix: "Velocity", fmt: "Vitesse {p}" },
    { suffix: "Acceleration", fmt: "Accélération {p}" },
    { suffix: "Momentum", fmt: "Quantité de Mouvement {p}" },
    { suffix: "Energy", fmt: "Énergie {p}" },
    { suffix: "Power", fmt: "Puissance {p}" },
    { suffix: "Frequency", fmt: "Fréquence {p}" },
    { suffix: "Voltage", fmt: "Tension {p}" },
    { suffix: "Length", fmt: "Longueur {p}" },
    { suffix: "Width", fmt: "Largeur {p}" },
    { suffix: "Height", fmt: "Hauteur {p}" },
    { suffix: "Depth", fmt: "Profondeur {p}" },
    { suffix: "Thickness", fmt: "Épaisseur {p}" },
    { suffix: "Diameter", fmt: "Diamètre {p}" },
    { suffix: "Radius", fmt: "Rayon {p}" },
    { suffix: "Angle", fmt: "Angle {p}" },
    { suffix: "Mass", fmt: "Masse {p}" },
    { suffix: "Weight", fmt: "Poids {p}" },
    { suffix: "Size", fmt: "Taille {p}" },
    { suffix: "Volume", fmt: "Volume {p}" },
    { suffix: "Area", fmt: "Surface {p}" },
    { suffix: "Capacity", fmt: "Capacité {p}" },
    { suffix: "Efficiency", fmt: "Efficacité {p}" },
    { suffix: "Performance", fmt: "Performance {p}" },
    { suffix: "Loss", fmt: "Perte {p}" },
    { suffix: "Losses", fmt: "Pertes {p}" },
    { suffix: "Value", fmt: "Valeur {p}" },
    { suffix: "Quality", fmt: "Qualité {p}" },
    { suffix: "Distance", fmt: "Distance {p}" },
    { suffix: "Range", fmt: "Portée {p}" },
    { suffix: "Section", fmt: "Section {p}" },
    { suffix: "Grade", fmt: "Note {p}" },
    { suffix: "Work", fmt: "Travail {p}" },
    { suffix: "Heat", fmt: "Chaleur {p}" },
    { suffix: "Current", fmt: "Courant {p}" },
    { suffix: "Stress", fmt: "Contrainte {p}" },
    { suffix: "Strain", fmt: "Déformation {p}" },
    { suffix: "Modulus", fmt: "Module {p}" },
    { suffix: "Hardness", fmt: "Dureté {p}" },
    { suffix: "Band", fmt: "Bande {p}" },
    { suffix: "Conversion", fmt: "Conversion {p}" },
    { suffix: "Setting", fmt: "Réglage {p}" },
    { suffix: "Renewal", fmt: "Renouvellement {p}" },
    { suffix: "Expiration", fmt: "Expiration {p}" },
    { suffix: "Milestone", fmt: "Jalon {p}" },
    { suffix: "Timeline", fmt: "Chronologie {p}" },
    { suffix: "Timer", fmt: "Minuteur {p}" },
    { suffix: "Interval", fmt: "Intervalle {p}" },
    { suffix: "Interpolation", fmt: "Interpolation {p}" },
    { suffix: "Integration", fmt: "Intégration {p}" },
    { suffix: "Decomposition", fmt: "Décomposition {p}" },
    { suffix: "Transformation", fmt: "Transformation {p}" },
    { suffix: "Iteration", fmt: "Itération {p}" },
    { suffix: "Factorization", fmt: "Factorisation {p}" },
    { suffix: "Smoothing", fmt: "Lissage {p}" },
    { suffix: "Regression", fmt: "Régression {p}" },
    { suffix: "Correlation", fmt: "Corrélation {p}" },
    { suffix: "Filter", fmt: "Filtre {p}" },
    { suffix: "Separator", fmt: "Séparateur {p}" },
    { suffix: "Extraction", fmt: "Extraction {p}" },
    { suffix: "Vibration", fmt: "Vibration {p}" },
    { suffix: "Isolation", fmt: "Isolation {p}" },
    { suffix: "Reduction", fmt: "Réduction {p}" },
    { suffix: "Loop", fmt: "Boucle {p}" },
    { suffix: "Simulation", fmt: "Simulation {p}" },
    { suffix: "Allocation", fmt: "Allocation {p}" },
    { suffix: "Monitoring", fmt: "Surveillance {p}" },
  ],
  de: [
    { suffix: "Analysis", fmt: "Analyse {p}" },
    { suffix: "Law", fmt: "Gesetz {p}" },
    { suffix: "Effect", fmt: "Effekt {p}" },
    { suffix: "Equation", fmt: "Gleichung {p}" },
    { suffix: "Equations", fmt: "Gleichungen {p}" },
    { suffix: "Theorem", fmt: "Satz {p}" },
    { suffix: "Theory", fmt: "Theorie {p}" },
    { suffix: "Principle", fmt: "Prinzip {p}" },
    { suffix: "Formula", fmt: "Formel {p}" },
    { suffix: "Method", fmt: "Methode {p}" },
    { suffix: "Model", fmt: "Modell {p}" },
    { suffix: "Function", fmt: "Funktion {p}" },
    { suffix: "Operator", fmt: "Operator {p}" },
    { suffix: "Transform", fmt: "Transformierte {p}" },
    { suffix: "Rule", fmt: "Regel {p}" },
    { suffix: "Coefficient", fmt: "Koeffizient {p}" },
    { suffix: "Constant", fmt: "Konstante {p}" },
    { suffix: "Variable", fmt: "Variable {p}" },
    { suffix: "Parameter", fmt: "Parameter {p}" },
    { suffix: "Factor", fmt: "Faktor {p}" },
    { suffix: "Limit", fmt: "Grenze {p}" },
    { suffix: "Cycle", fmt: "Zyklus {p}" },
    { suffix: "Design", fmt: "Entwurf {p}" },
    { suffix: "Process", fmt: "Prozess {p}" },
    { suffix: "Testing", fmt: "Testen {p}" },
    { suffix: "Scale", fmt: "Skala {p}" },
    { suffix: "Criterion", fmt: "Kriterium {p}" },
    { suffix: "Criteria", fmt: "Kriterien {p}" },
    { suffix: "Point", fmt: "Punkt {p}" },
    { suffix: "Points", fmt: "Punkte {p}" },
    { suffix: "Zone", fmt: "Zone {p}" },
    { suffix: "Mode", fmt: "Modus {p}" },
    { suffix: "Phase", fmt: "Phase {p}" },
    { suffix: "Date", fmt: "Datum {p}" },
    { suffix: "Time", fmt: "Zeit {p}" },
    { suffix: "Schedule", fmt: "Zeitplan {p}" },
    { suffix: "Plan", fmt: "Plan {p}" },
    { suffix: "Curve", fmt: "Kurve {p}" },
    { suffix: "Matrix", fmt: "Matrix {p}" },
    { suffix: "Vector", fmt: "Vektor {p}" },
    { suffix: "Space", fmt: "Raum {p}" },
    { suffix: "Field", fmt: "Feld {p}" },
    { suffix: "Map", fmt: "Karte {p}" },
    { suffix: "Chart", fmt: "Diagramm {p}" },
    { suffix: "Risk", fmt: "Risiko {p}" },
    { suffix: "Margin", fmt: "Marge {p}" },
    { suffix: "Error", fmt: "Fehler {p}" },
    { suffix: "Difference", fmt: "Differenz {p}" },
    { suffix: "Trend", fmt: "Trend {p}" },
    { suffix: "Flow", fmt: "Strömung {p}" },
    { suffix: "Rate", fmt: "Rate {p}" },
    { suffix: "Gradient", fmt: "Gradient {p}" },
    { suffix: "Wave", fmt: "Welle {p}" },
    { suffix: "Signal", fmt: "Signal {p}" },
    { suffix: "Norm", fmt: "Norm {p}" },
    { suffix: "Budget", fmt: "Budget {p}" },
    { suffix: "Cost", fmt: "Kosten {p}" },
    { suffix: "Costs", fmt: "Kosten {p}" },
    { suffix: "Fee", fmt: "Gebühr {p}" },
    { suffix: "Tax", fmt: "Steuer {p}" },
    { suffix: "Payment", fmt: "Zahlung {p}" },
    { suffix: "Balance", fmt: "Saldo {p}" },
    { suffix: "Savings", fmt: "Ersparnisse {p}" },
    { suffix: "Loan", fmt: "Darlehen {p}" },
    { suffix: "Debt", fmt: "Schulden {p}" },
    { suffix: "Income", fmt: "Einkommen {p}" },
    { suffix: "Expense", fmt: "Ausgabe {p}" },
    { suffix: "Return", fmt: "Rendite {p}" },
    { suffix: "Growth", fmt: "Wachstum {p}" },
    { suffix: "Investment", fmt: "Investition {p}" },
    { suffix: "Trust", fmt: "Treuhand {p}" },
    { suffix: "Deduction", fmt: "Abzug {p}" },
    { suffix: "Credit", fmt: "Kredit {p}" },
    { suffix: "Exclusion", fmt: "Ausschluss {p}" },
    { suffix: "Duration", fmt: "Dauer {p}" },
    { suffix: "Period", fmt: "Periode {p}" },
    { suffix: "Count", fmt: "Zählung {p}" },
    { suffix: "Measurement", fmt: "Messung {p}" },
    { suffix: "Correction", fmt: "Korrektur {p}" },
    { suffix: "Mixture", fmt: "Gemisch {p}" },
    { suffix: "Solution", fmt: "Lösung {p}" },
    { suffix: "Concentration", fmt: "Konzentration {p}" },
    { suffix: "Variation", fmt: "Variation {p}" },
    { suffix: "Surface", fmt: "Oberfläche {p}" },
    { suffix: "Stability", fmt: "Stabilität {p}" },
    { suffix: "Safety", fmt: "Sicherheit {p}" },
    { suffix: "Protection", fmt: "Schutz {p}" },
    { suffix: "Planning", fmt: "Planung {p}" },
    { suffix: "Sizing", fmt: "Dimensionierung {p}" },
    { suffix: "Payoff", fmt: "Auszahlung {p}" },
    { suffix: "Penalty", fmt: "Strafe {p}" },
    { suffix: "Test", fmt: "Test {p}" },
    { suffix: "Check", fmt: "Prüfung {p}" },
    { suffix: "Assessment", fmt: "Bewertung {p}" },
    { suffix: "Audit", fmt: "Prüfung {p}" },
    { suffix: "Benefits", fmt: "Leistungen {p}" },
    { suffix: "Status", fmt: "Status {p}" },
    { suffix: "Position", fmt: "Position {p}" },
    { suffix: "Location", fmt: "Standort {p}" },
    { suffix: "Slope", fmt: "Steigung {p}" },
    { suffix: "Suspension", fmt: "Aufhängung {p}" },
    { suffix: "Probation", fmt: "Bewährung {p}" },
    { suffix: "Allowance", fmt: "Zulage {p}" },
    { suffix: "Rating", fmt: "Bewertung {p}" },
    { suffix: "Score", fmt: "Punktzahl {p}" },
    { suffix: "Index", fmt: "Index {p}" },
    { suffix: "Ratio", fmt: "Verhältnis {p}" },
    { suffix: "Line", fmt: "Linie {p}" },
    { suffix: "Load", fmt: "Last {p}" },
    { suffix: "Force", fmt: "Kraft {p}" },
    { suffix: "Temperature", fmt: "Temperatur {p}" },
    { suffix: "Pressure", fmt: "Druck {p}" },
    { suffix: "Density", fmt: "Dichte {p}" },
    { suffix: "Viscosity", fmt: "Viskosität {p}" },
    { suffix: "Conductivity", fmt: "Leitfähigkeit {p}" },
    { suffix: "Resistance", fmt: "Widerstand {p}" },
    { suffix: "Impedance", fmt: "Impedanz {p}" },
    { suffix: "Capacitance", fmt: "Kapazität {p}" },
    { suffix: "Inductance", fmt: "Induktivität {p}" },
    { suffix: "Strength", fmt: "Festigkeit {p}" },
    { suffix: "Speed", fmt: "Geschwindigkeit {p}" },
    { suffix: "Velocity", fmt: "Geschwindigkeit {p}" },
    { suffix: "Acceleration", fmt: "Beschleunigung {p}" },
    { suffix: "Momentum", fmt: "Impuls {p}" },
    { suffix: "Energy", fmt: "Energie {p}" },
    { suffix: "Power", fmt: "Leistung {p}" },
    { suffix: "Frequency", fmt: "Frequenz {p}" },
    { suffix: "Voltage", fmt: "Spannung {p}" },
    { suffix: "Length", fmt: "Länge {p}" },
    { suffix: "Width", fmt: "Breite {p}" },
    { suffix: "Height", fmt: "Höhe {p}" },
    { suffix: "Depth", fmt: "Tiefe {p}" },
    { suffix: "Thickness", fmt: "Dicke {p}" },
    { suffix: "Diameter", fmt: "Durchmesser {p}" },
    { suffix: "Radius", fmt: "Radius {p}" },
    { suffix: "Angle", fmt: "Winkel {p}" },
    { suffix: "Mass", fmt: "Masse {p}" },
    { suffix: "Weight", fmt: "Gewicht {p}" },
    { suffix: "Size", fmt: "Größe {p}" },
    { suffix: "Volume", fmt: "Volumen {p}" },
    { suffix: "Area", fmt: "Fläche {p}" },
    { suffix: "Capacity", fmt: "Kapazität {p}" },
    { suffix: "Efficiency", fmt: "Effizienz {p}" },
    { suffix: "Performance", fmt: "Leistung {p}" },
    { suffix: "Loss", fmt: "Verlust {p}" },
    { suffix: "Losses", fmt: "Verluste {p}" },
    { suffix: "Value", fmt: "Wert {p}" },
    { suffix: "Quality", fmt: "Qualität {p}" },
    { suffix: "Distance", fmt: "Entfernung {p}" },
    { suffix: "Range", fmt: "Bereich {p}" },
    { suffix: "Section", fmt: "Abschnitt {p}" },
    { suffix: "Grade", fmt: "Note {p}" },
    { suffix: "Work", fmt: "Arbeit {p}" },
    { suffix: "Heat", fmt: "Wärme {p}" },
    { suffix: "Current", fmt: "Strom {p}" },
    { suffix: "Tension", fmt: "Spannung {p}" },
    { suffix: "Stress", fmt: "Spannung {p}" },
    { suffix: "Strain", fmt: "Dehnung {p}" },
    { suffix: "Modulus", fmt: "Modul {p}" },
    { suffix: "Hardness", fmt: "Härte {p}" },
    { suffix: "Band", fmt: "Band {p}" },
    { suffix: "Conversion", fmt: "Umrechnung {p}" },
    { suffix: "Setting", fmt: "Einstellung {p}" },
    { suffix: "Renewal", fmt: "Verlängerung {p}" },
    { suffix: "Expiration", fmt: "Ablauf {p}" },
    { suffix: "Milestone", fmt: "Meilenstein {p}" },
    { suffix: "Timeline", fmt: "Zeitstrahl {p}" },
    { suffix: "Timer", fmt: "Timer {p}" },
    { suffix: "Interval", fmt: "Intervall {p}" },
    { suffix: "Interpolation", fmt: "Interpolation {p}" },
    { suffix: "Integration", fmt: "Integration {p}" },
    { suffix: "Decomposition", fmt: "Zerlegung {p}" },
    { suffix: "Transformation", fmt: "Transformation {p}" },
    { suffix: "Iteration", fmt: "Iteration {p}" },
    { suffix: "Regression", fmt: "Regression {p}" },
    { suffix: "Correlation", fmt: "Korrelation {p}" },
    { suffix: "Filter", fmt: "Filter {p}" },
    { suffix: "Extraction", fmt: "Extraktion {p}" },
    { suffix: "Vibration", fmt: "Schwingung {p}" },
    { suffix: "Isolation", fmt: "Isolierung {p}" },
    { suffix: "Reduction", fmt: "Reduktion {p}" },
    { suffix: "Loop", fmt: "Schleife {p}" },
    { suffix: "Simulation", fmt: "Simulation {p}" },
    { suffix: "Allocation", fmt: "Allokation {p}" },
  ],
  pt: [
    { suffix: "Analysis", fmt: "Análise {p}" },
    { suffix: "Law", fmt: "Lei {p}" },
    { suffix: "Effect", fmt: "Efeito {p}" },
    { suffix: "Equation", fmt: "Equação {p}" },
    { suffix: "Theorem", fmt: "Teorema {p}" },
    { suffix: "Theory", fmt: "Teoria {p}" },
    { suffix: "Principle", fmt: "Princípio {p}" },
    { suffix: "Formula", fmt: "Fórmula {p}" },
    { suffix: "Method", fmt: "Método {p}" },
    { suffix: "Model", fmt: "Modelo {p}" },
    { suffix: "Function", fmt: "Função {p}" },
    { suffix: "Transform", fmt: "Transformada {p}" },
    { suffix: "Rule", fmt: "Regra {p}" },
    { suffix: "Coefficient", fmt: "Coeficiente {p}" },
    { suffix: "Constant", fmt: "Constante {p}" },
    { suffix: "Factor", fmt: "Fator {p}" },
    { suffix: "Limit", fmt: "Limite {p}" },
    { suffix: "Cycle", fmt: "Ciclo {p}" },
    { suffix: "Scale", fmt: "Escala {p}" },
    { suffix: "Point", fmt: "Ponto {p}" },
    { suffix: "Points", fmt: "Pontos {p}" },
    { suffix: "Zone", fmt: "Zona {p}" },
    { suffix: "Mode", fmt: "Modo {p}" },
    { suffix: "Phase", fmt: "Fase {p}" },
    { suffix: "Date", fmt: "Data {p}" },
    { suffix: "Time", fmt: "Tempo {p}" },
    { suffix: "Curve", fmt: "Curva {p}" },
    { suffix: "Matrix", fmt: "Matriz {p}" },
    { suffix: "Risk", fmt: "Risco {p}" },
    { suffix: "Margin", fmt: "Margem {p}" },
    { suffix: "Error", fmt: "Erro {p}" },
    { suffix: "Difference", fmt: "Diferença {p}" },
    { suffix: "Flow", fmt: "Fluxo {p}" },
    { suffix: "Rate", fmt: "Taxa {p}" },
    { suffix: "Wave", fmt: "Onda {p}" },
    { suffix: "Signal", fmt: "Sinal {p}" },
    { suffix: "Budget", fmt: "Orçamento {p}" },
    { suffix: "Cost", fmt: "Custo {p}" },
    { suffix: "Tax", fmt: "Imposto {p}" },
    { suffix: "Payment", fmt: "Pagamento {p}" },
    { suffix: "Balance", fmt: "Saldo {p}" },
    { suffix: "Loan", fmt: "Empréstimo {p}" },
    { suffix: "Debt", fmt: "Dívida {p}" },
    { suffix: "Income", fmt: "Rendimento {p}" },
    { suffix: "Expense", fmt: "Despesa {p}" },
    { suffix: "Return", fmt: "Retorno {p}" },
    { suffix: "Growth", fmt: "Crescimento {p}" },
    { suffix: "Investment", fmt: "Investimento {p}" },
    { suffix: "Trust", fmt: "Fideicomisso {p}" },
    { suffix: "Deduction", fmt: "Dedução {p}" },
    { suffix: "Credit", fmt: "Crédito {p}" },
    { suffix: "Duration", fmt: "Duração {p}" },
    { suffix: "Period", fmt: "Período {p}" },
    { suffix: "Correction", fmt: "Correção {p}" },
    { suffix: "Concentration", fmt: "Concentração {p}" },
    { suffix: "Stability", fmt: "Estabilidade {p}" },
    { suffix: "Safety", fmt: "Segurança {p}" },
    { suffix: "Protection", fmt: "Proteção {p}" },
    { suffix: "Penalty", fmt: "Penalidade {p}" },
    { suffix: "Score", fmt: "Pontuação {p}" },
    { suffix: "Index", fmt: "Índice {p}" },
    { suffix: "Ratio", fmt: "Relação {p}" },
    { suffix: "Line", fmt: "Linha {p}" },
    { suffix: "Load", fmt: "Carga {p}" },
    { suffix: "Force", fmt: "Força {p}" },
    { suffix: "Temperature", fmt: "Temperatura {p}" },
    { suffix: "Pressure", fmt: "Pressão {p}" },
    { suffix: "Density", fmt: "Densidade {p}" },
    { suffix: "Viscosity", fmt: "Viscosidade {p}" },
    { suffix: "Resistance", fmt: "Resistência {p}" },
    { suffix: "Strength", fmt: "Força {p}" },
    { suffix: "Speed", fmt: "Velocidade {p}" },
    { suffix: "Acceleration", fmt: "Aceleração {p}" },
    { suffix: "Energy", fmt: "Energia {p}" },
    { suffix: "Power", fmt: "Potência {p}" },
    { suffix: "Frequency", fmt: "Frequência {p}" },
    { suffix: "Voltage", fmt: "Tensão {p}" },
    { suffix: "Length", fmt: "Comprimento {p}" },
    { suffix: "Width", fmt: "Largura {p}" },
    { suffix: "Height", fmt: "Altura {p}" },
    { suffix: "Depth", fmt: "Profundidade {p}" },
    { suffix: "Thickness", fmt: "Espessura {p}" },
    { suffix: "Diameter", fmt: "Diâmetro {p}" },
    { suffix: "Radius", fmt: "Raio {p}" },
    { suffix: "Angle", fmt: "Ângulo {p}" },
    { suffix: "Mass", fmt: "Massa {p}" },
    { suffix: "Weight", fmt: "Peso {p}" },
    { suffix: "Size", fmt: "Tamanho {p}" },
    { suffix: "Volume", fmt: "Volume {p}" },
    { suffix: "Area", fmt: "Área {p}" },
    { suffix: "Capacity", fmt: "Capacidade {p}" },
    { suffix: "Efficiency", fmt: "Eficiência {p}" },
    { suffix: "Performance", fmt: "Desempenho {p}" },
    { suffix: "Loss", fmt: "Perda {p}" },
    { suffix: "Value", fmt: "Valor {p}" },
    { suffix: "Quality", fmt: "Qualidade {p}" },
    { suffix: "Distance", fmt: "Distância {p}" },
    { suffix: "Range", fmt: "Alcance {p}" },
    { suffix: "Section", fmt: "Seção {p}" },
    { suffix: "Grade", fmt: "Nota {p}" },
    { suffix: "Work", fmt: "Trabalho {p}" },
    { suffix: "Heat", fmt: "Calor {p}" },
    { suffix: "Current", fmt: "Corrente {p}" },
    { suffix: "Stress", fmt: "Tensão {p}" },
    { suffix: "Strain", fmt: "Deformação {p}" },
    { suffix: "Modulus", fmt: "Módulo {p}" },
    { suffix: "Hardness", fmt: "Dureza {p}" },
    { suffix: "Conversion", fmt: "Conversão {p}" },
    { suffix: "Filter", fmt: "Filtro {p}" },
    { suffix: "Loop", fmt: "Malha {p}" },
    { suffix: "Simulation", fmt: "Simulação {p}" },
  ],
  ru: [],
  ar: [
    { suffix: "Analysis", fmt: "تحليل {p}" },
    { suffix: "Law", fmt: "قانون {p}" },
    { suffix: "Effect", fmt: "تأثير {p}" },
    { suffix: "Equation", fmt: "معادلة {p}" },
    { suffix: "Theorem", fmt: "نظرية {p}" },
    { suffix: "Theory", fmt: "نظرية {p}" },
    { suffix: "Method", fmt: "طريقة {p}" },
    { suffix: "Model", fmt: "نموذج {p}" },
    { suffix: "Function", fmt: "دالة {p}" },
    { suffix: "Calculator", fmt: "حاسبة {p}" },
    { suffix: "Converter", fmt: "محول {p}" },
    { suffix: "Score", fmt: "درجة {p}" },
    { suffix: "Index", fmt: "مؤشر {p}" },
    { suffix: "Ratio", fmt: "نسبة {p}" },
    { suffix: "Test", fmt: "اختبار {p}" },
    { suffix: "Rate", fmt: "معدل {p}" },
    { suffix: "Value", fmt: "قيمة {p}" },
    { suffix: "Level", fmt: "مستوى {p}" },
    { suffix: "Time", fmt: "وقت {p}" },
    { suffix: "Date", fmt: "تاريخ {p}" },
    { suffix: "Cost", fmt: "تكلفة {p}" },
    { suffix: "Tax", fmt: "ضريبة {p}" },
    { suffix: "Payment", fmt: "دفعة {p}" },
    { suffix: "Balance", fmt: "رصيد {p}" },
    { suffix: "Loan", fmt: "قرض {p}" },
    { suffix: "Debt", fmt: "دين {p}" },
    { suffix: "Income", fmt: "دخل {p}" },
    { suffix: "Expense", fmt: "مصروف {p}" },
    { suffix: "Return", fmt: "عائد {p}" },
    { suffix: "Growth", fmt: "نمو {p}" },
    { suffix: "Investment", fmt: "استثمار {p}" },
    { suffix: "Risk", fmt: "مخاطرة {p}" },
    { suffix: "Duration", fmt: "مدة {p}" },
    { suffix: "Period", fmt: "فترة {p}" },
    { suffix: "Speed", fmt: "سرعة {p}" },
    { suffix: "Force", fmt: "قوة {p}" },
    { suffix: "Power", fmt: "قدرة {p}" },
    { suffix: "Energy", fmt: "طاقة {p}" },
    { suffix: "Pressure", fmt: "ضغط {p}" },
    { suffix: "Temperature", fmt: "درجة حرارة {p}" },
    { suffix: "Volume", fmt: "حجم {p}" },
    { suffix: "Area", fmt: "مساحة {p}" },
    { suffix: "Length", fmt: "طول {p}" },
    { suffix: "Weight", fmt: "وزن {p}" },
    { suffix: "Mass", fmt: "كتلة {p}" },
    { suffix: "Density", fmt: "كثافة {p}" },
    { suffix: "Resistance", fmt: "مقاومة {p}" },
    { suffix: "Frequency", fmt: "تردد {p}" },
    { suffix: "Voltage", fmt: "جهد {p}" },
    { suffix: "Stress", fmt: "إجهاد {p}" },
    { suffix: "Strain", fmt: "انفعال {p}" },
    { suffix: "Modulus", fmt: "معامل {p}" },
    { suffix: "Strength", fmt: "قوة {p}" },
    { suffix: "Capacity", fmt: "سعة {p}" },
    { suffix: "Efficiency", fmt: "كفاءة {p}" },
    { suffix: "Loss", fmt: "خسارة {p}" },
    { suffix: "Losses", fmt: "خسائر {p}" },
    { suffix: "Quality", fmt: "جودة {p}" },
    { suffix: "Distance", fmt: "مسافة {p}" },
    { suffix: "Range", fmt: "مدى {p}" },
    { suffix: "Grade", fmt: "درجة {p}" },
    { suffix: "Work", fmt: "عمل {p}" },
    { suffix: "Heat", fmt: "حرارة {p}" },
    { suffix: "Current", fmt: "تيار {p}" },
    { suffix: "Scale", fmt: "مقياس {p}" },
    { suffix: "Conversion", fmt: "تحويل {p}" },
    { suffix: "Filter", fmt: "فلتر {p}" },
    { suffix: "Flow", fmt: "تدفق {p}" },
    { suffix: "Wave", fmt: "موجة {p}" },
    { suffix: "Signal", fmt: "إشارة {p}" },
    { suffix: "Field", fmt: "مجال {p}" },
    { suffix: "Space", fmt: "فضاء {p}" },
    { suffix: "Phase", fmt: "طور {p}" },
    { suffix: "Budget", fmt: "ميزانية {p}" },
    { suffix: "Plan", fmt: "خطة {p}" },
    { suffix: "Design", fmt: "تصميم {p}" },
    { suffix: "Process", fmt: "عملية {p}" },
    { suffix: "Savings", fmt: "مدخرات {p}" },
  ],
  hi: [
    { suffix: "Analysis", fmt: "{p} विश्लेषण" },
    { suffix: "Law", fmt: "{p} नियम" },
    { suffix: "Effect", fmt: "{p} प्रभाव" },
    { suffix: "Equation", fmt: "{p} समीकरण" },
    { suffix: "Theorem", fmt: "{p} प्रमेय" },
    { suffix: "Theory", fmt: "{p} सिद्धांत" },
    { suffix: "Method", fmt: "{p} विधि" },
    { suffix: "Model", fmt: "{p} मॉडल" },
    { suffix: "Function", fmt: "{p} फलन" },
    { suffix: "Calculator", fmt: "{p} कैलकुलेटर" },
    { suffix: "Converter", fmt: "{p} कनवर्टर" },
    { suffix: "Score", fmt: "{p} स्कोर" },
    { suffix: "Index", fmt: "{p} सूचकांक" },
    { suffix: "Ratio", fmt: "{p} अनुपात" },
    { suffix: "Test", fmt: "{p} परीक्षण" },
    { suffix: "Rate", fmt: "{p} दर" },
    { suffix: "Value", fmt: "{p} मूल्य" },
    { suffix: "Level", fmt: "{p} स्तर" },
    { suffix: "Time", fmt: "{p} समय" },
    { suffix: "Date", fmt: "{p} तारीख" },
    { suffix: "Cost", fmt: "{p} लागत" },
    { suffix: "Tax", fmt: "{p} कर" },
    { suffix: "Payment", fmt: "{p} भुगतान" },
    { suffix: "Balance", fmt: "{p} शेष" },
    { suffix: "Loan", fmt: "{p} ऋण" },
    { suffix: "Debt", fmt: "{p} कर्ज" },
    { suffix: "Income", fmt: "{p} आय" },
    { suffix: "Expense", fmt: "{p} व्यय" },
    { suffix: "Return", fmt: "{p} प्रतिफल" },
    { suffix: "Growth", fmt: "{p} वृद्धि" },
    { suffix: "Investment", fmt: "{p} निवेश" },
    { suffix: "Risk", fmt: "{p} जोखिम" },
    { suffix: "Duration", fmt: "{p} अवधि" },
    { suffix: "Period", fmt: "{p} अवधि" },
    { suffix: "Speed", fmt: "{p} गति" },
    { suffix: "Force", fmt: "{p} बल" },
    { suffix: "Power", fmt: "{p} शक्ति" },
    { suffix: "Energy", fmt: "{p} ऊर्जा" },
    { suffix: "Pressure", fmt: "{p} दबाव" },
    { suffix: "Temperature", fmt: "{p} तापमान" },
    { suffix: "Volume", fmt: "{p} आयतन" },
    { suffix: "Area", fmt: "{p} क्षेत्रफल" },
    { suffix: "Length", fmt: "{p} लंबाई" },
    { suffix: "Weight", fmt: "{p} वजन" },
    { suffix: "Mass", fmt: "{p} द्रव्यमान" },
    { suffix: "Density", fmt: "{p} घनत्व" },
    { suffix: "Resistance", fmt: "{p} प्रतिरोध" },
    { suffix: "Frequency", fmt: "{p} आवृत्ति" },
    { suffix: "Voltage", fmt: "{p} वोल्टेज" },
    { suffix: "Stress", fmt: "{p} प्रतिबल" },
    { suffix: "Strain", fmt: "{p} विकृति" },
    { suffix: "Strength", fmt: "{p} सामर्थ्य" },
    { suffix: "Capacity", fmt: "{p} क्षमता" },
    { suffix: "Efficiency", fmt: "{p} दक्षता" },
    { suffix: "Loss", fmt: "{p} हानि" },
    { suffix: "Quality", fmt: "{p} गुणवत्ता" },
    { suffix: "Distance", fmt: "{p} दूरी" },
    { suffix: "Grade", fmt: "{p} ग्रेड" },
    { suffix: "Work", fmt: "{p} कार्य" },
    { suffix: "Heat", fmt: "{p} गर्मी" },
    { suffix: "Current", fmt: "{p} धारा" },
    { suffix: "Scale", fmt: "{p} पैमाना" },
    { suffix: "Conversion", fmt: "{p} रूपांतरण" },
    { suffix: "Flow", fmt: "{p} प्रवाह" },
    { suffix: "Wave", fmt: "{p} तरंग" },
    { suffix: "Budget", fmt: "{p} बजट" },
    { suffix: "Plan", fmt: "{p} योजना" },
    { suffix: "Design", fmt: "{p} डिज़ाइन" },
    { suffix: "Savings", fmt: "{p} बचत" },
  ],
  ja: [
    { suffix: "Analysis", fmt: "{p}分析" },
    { suffix: "Law", fmt: "{p}の法則" },
    { suffix: "Effect", fmt: "{p}効果" },
    { suffix: "Equation", fmt: "{p}方程式" },
    { suffix: "Theorem", fmt: "{p}定理" },
    { suffix: "Theory", fmt: "{p}理論" },
    { suffix: "Method", fmt: "{p}法" },
    { suffix: "Model", fmt: "{p}モデル" },
    { suffix: "Function", fmt: "{p}関数" },
    { suffix: "Calculator", fmt: "{p}計算機" },
    { suffix: "Converter", fmt: "{p}変換器" },
    { suffix: "Score", fmt: "{p}スコア" },
    { suffix: "Index", fmt: "{p}指数" },
    { suffix: "Ratio", fmt: "{p}比率" },
    { suffix: "Test", fmt: "{p}テスト" },
    { suffix: "Rate", fmt: "{p}レート" },
    { suffix: "Value", fmt: "{p}値" },
    { suffix: "Level", fmt: "{p}レベル" },
    { suffix: "Time", fmt: "{p}時間" },
    { suffix: "Date", fmt: "{p}日付" },
    { suffix: "Cost", fmt: "{p}コスト" },
    { suffix: "Tax", fmt: "{p}税金" },
    { suffix: "Payment", fmt: "{p}支払い" },
    { suffix: "Balance", fmt: "{p}残高" },
    { suffix: "Loan", fmt: "{p}ローン" },
    { suffix: "Debt", fmt: "{p}負債" },
    { suffix: "Income", fmt: "{p}収入" },
    { suffix: "Expense", fmt: "{p}経費" },
    { suffix: "Return", fmt: "{p}収益" },
    { suffix: "Growth", fmt: "{p}成長" },
    { suffix: "Investment", fmt: "{p}投資" },
    { suffix: "Risk", fmt: "{p}リスク" },
    { suffix: "Duration", fmt: "{p}期間" },
    { suffix: "Period", fmt: "{p}期間" },
    { suffix: "Speed", fmt: "{p}速度" },
    { suffix: "Force", fmt: "{p}力" },
    { suffix: "Power", fmt: "{p}電力" },
    { suffix: "Energy", fmt: "{p}エネルギー" },
    { suffix: "Pressure", fmt: "{p}圧力" },
    { suffix: "Temperature", fmt: "{p}温度" },
    { suffix: "Volume", fmt: "{p}体積" },
    { suffix: "Area", fmt: "{p}面積" },
    { suffix: "Length", fmt: "{p}長さ" },
    { suffix: "Weight", fmt: "{p}重量" },
    { suffix: "Mass", fmt: "{p}質量" },
    { suffix: "Density", fmt: "{p}密度" },
    { suffix: "Resistance", fmt: "{p}抵抗" },
    { suffix: "Frequency", fmt: "{p}周波数" },
    { suffix: "Voltage", fmt: "{p}電圧" },
    { suffix: "Stress", fmt: "{p}応力" },
    { suffix: "Strain", fmt: "{p}ひずみ" },
    { suffix: "Strength", fmt: "{p}強度" },
    { suffix: "Capacity", fmt: "{p}容量" },
    { suffix: "Efficiency", fmt: "{p}効率" },
    { suffix: "Loss", fmt: "{p}損失" },
    { suffix: "Quality", fmt: "{p}品質" },
    { suffix: "Distance", fmt: "{p}距離" },
    { suffix: "Grade", fmt: "{p}成績" },
    { suffix: "Work", fmt: "{p}仕事" },
    { suffix: "Heat", fmt: "{p}熱" },
    { suffix: "Current", fmt: "{p}電流" },
    { suffix: "Scale", fmt: "{p}規模" },
    { suffix: "Conversion", fmt: "{p}変換" },
    { suffix: "Flow", fmt: "{p}流れ" },
    { suffix: "Wave", fmt: "{p}波" },
    { suffix: "Budget", fmt: "{p}予算" },
    { suffix: "Plan", fmt: "{p}計画" },
    { suffix: "Savings", fmt: "{p}貯蓄" },
  ],
  "zh-CN": [
    { suffix: "Analysis", fmt: "{p}分析" },
    { suffix: "Law", fmt: "{p}定律" },
    { suffix: "Effect", fmt: "{p}效应" },
    { suffix: "Equation", fmt: "{p}方程" },
    { suffix: "Theorem", fmt: "{p}定理" },
    { suffix: "Theory", fmt: "{p}理论" },
    { suffix: "Method", fmt: "{p}方法" },
    { suffix: "Model", fmt: "{p}模型" },
    { suffix: "Function", fmt: "{p}函数" },
    { suffix: "Calculator", fmt: "{p}计算器" },
    { suffix: "Converter", fmt: "{p}转换器" },
    { suffix: "Score", fmt: "{p}分数" },
    { suffix: "Index", fmt: "{p}指数" },
    { suffix: "Ratio", fmt: "{p}比率" },
    { suffix: "Test", fmt: "{p}测试" },
    { suffix: "Rate", fmt: "{p}率" },
    { suffix: "Value", fmt: "{p}值" },
    { suffix: "Level", fmt: "{p}水平" },
    { suffix: "Time", fmt: "{p}时间" },
    { suffix: "Date", fmt: "{p}日期" },
    { suffix: "Cost", fmt: "{p}成本" },
    { suffix: "Tax", fmt: "{p}税" },
    { suffix: "Payment", fmt: "{p}付款" },
    { suffix: "Balance", fmt: "{p}余额" },
    { suffix: "Loan", fmt: "{p}贷款" },
    { suffix: "Debt", fmt: "{p}债务" },
    { suffix: "Income", fmt: "{p}收入" },
    { suffix: "Expense", fmt: "{p}费用" },
    { suffix: "Return", fmt: "{p}回报" },
    { suffix: "Growth", fmt: "{p}增长" },
    { suffix: "Investment", fmt: "{p}投资" },
    { suffix: "Risk", fmt: "{p}风险" },
    { suffix: "Duration", fmt: "{p}期间" },
    { suffix: "Period", fmt: "{p}周期" },
    { suffix: "Speed", fmt: "{p}速度" },
    { suffix: "Force", fmt: "{p}力" },
    { suffix: "Power", fmt: "{p}功率" },
    { suffix: "Energy", fmt: "{p}能量" },
    { suffix: "Pressure", fmt: "{p}压力" },
    { suffix: "Temperature", fmt: "{p}温度" },
    { suffix: "Volume", fmt: "{p}体积" },
    { suffix: "Area", fmt: "{p}面积" },
    { suffix: "Length", fmt: "{p}长度" },
    { suffix: "Weight", fmt: "{p}重量" },
    { suffix: "Mass", fmt: "{p}质量" },
    { suffix: "Density", fmt: "{p}密度" },
    { suffix: "Resistance", fmt: "{p}电阻" },
    { suffix: "Frequency", fmt: "{p}频率" },
    { suffix: "Voltage", fmt: "{p}电压" },
    { suffix: "Stress", fmt: "{p}应力" },
    { suffix: "Strain", fmt: "{p}应变" },
    { suffix: "Strength", fmt: "{p}强度" },
    { suffix: "Capacity", fmt: "{p}容量" },
    { suffix: "Efficiency", fmt: "{p}效率" },
    { suffix: "Loss", fmt: "{p}损失" },
    { suffix: "Quality", fmt: "{p}质量" },
    { suffix: "Distance", fmt: "{p}距离" },
    { suffix: "Grade", fmt: "{p}成绩" },
    { suffix: "Work", fmt: "{p}功" },
    { suffix: "Heat", fmt: "{p}热量" },
    { suffix: "Current", fmt: "{p}电流" },
    { suffix: "Scale", fmt: "{p}规模" },
    { suffix: "Conversion", fmt: "{p}转换" },
    { suffix: "Flow", fmt: "{p}流量" },
    { suffix: "Wave", fmt: "{p}波" },
    { suffix: "Budget", fmt: "{p}预算" },
    { suffix: "Plan", fmt: "{p}计划" },
    { suffix: "Savings", fmt: "{p}储蓄" },
  ]
};

// ========== TRANSLATION FUNCTIONS ==========

function applyWord(text, locale, wdict) {
  const keys = Object.keys(wdict).sort((a,b) => b.length - a.length);
  let result = text;
  for (const enW of keys) {
    const re = new RegExp('\\b' + enW.replace(/[.*+?^${}()|[\]\\]/g,'\\$&') + '\\b', 'g');
    result = result.replace(re, wdict[enW]);
  }
  return result;
}

function translateWords(title, locale, wdict) {
  const words = title.split(/\s+/);
  const translated = words.map(w => {
    if (/^[0-9\-.]+$/.test(w) || /^[A-Z0-9\/\-]{2,}$/.test(w)) return w;
    return wdict[w] || w;
  });
  return translated.join(' ');
}

function translateTitle(title, locale, wdict) {
  // 1. Check exact phrase match
  const exact = exactMap[locale] || {};
  if (exact[title]) return exact[title];

  // 2. Check suffix patterns
  const patterns = suffixPatterns[locale] || [];
  for (const p of patterns) {
    const s = p.suffix;
    if (title.endsWith(s) && title.length > s.length) {
      const prefix = title.slice(0, -s.length).trim().replace(/\s+$/,'');
      const tp = applyWord(prefix, locale, wdict);
      const result = p.fmt.replace('{p}', tp);
      if (result !== title) return result;
    }
  }

  // 3. Word-by-word translation
  const wbw = translateWords(title, locale, wdict);
  if (wbw !== title) return wbw;

  return null;
}

// ========== MAIN ==========
console.log('=== TRANSLATING REMAINING TITLES ===\n');

for (const locale of locales) {
  const fp = join(BASE, locale + '.json');
  const bp = join(BASE, locale + '.json.bak2');
  if (!existsSync(bp) && existsSync(fp)) {
    copyFileSync(fp, bp);
    console.log('Backed up ' + locale + '.json');
  }

  const wdict = loadDict(locale);
  console.log(locale + ': loaded ' + Object.keys(wdict).length + ' word dict entries');
  const exactCount = Object.keys(exactMap[locale] || {}).length;
  console.log('  exact phrases: ' + exactCount);
  
  const data = JSON.parse(readFileSync(fp, 'utf-8'));
  let changed = 0;
  const samples = [];

  for (const key of Object.keys(en)) {
    if (!data[key]) continue;
    const enT = en[key].title;
    if (enT === data[key].title) {
      const t = translateTitle(enT, locale, wdict);
      if (t) {
        if (samples.length < 5) samples.push({key, before: enT, after: t});
        data[key].title = t;
        changed++;
      }
    }
  }

  writeFileSync(fp, JSON.stringify(data, null, 2) + '\n', 'utf-8');
  console.log('  changed=' + changed);
  for (const s of samples) console.log('  EX: ' + s.key + ': "' + s.before + '" → "' + s.after + '"');
}

console.log('\n=== VERIFY ===');
for (const loc of ['en',...locales]) {
  try {
    const d = JSON.parse(readFileSync(join(BASE, loc + '.json'), 'utf-8'));
    console.log(loc + '.json: OK (' + Object.keys(d).length + ')');
  } catch(e) { console.log(loc + '.json: INVALID - ' + e.message); }
}

console.log('\n=== REMAINING ENGLISH ===');
for (const locale of locales) {
  const data = JSON.parse(readFileSync(join(BASE, locale + '.json'), 'utf-8'));
  let n=0; const s=[];
  for (const k of Object.keys(en)) {
    if (data[k] && data[k].title === en[k].title) {
      if (n<10) s.push(en[k].title);
      n++;
    }
  }
  console.log(locale + ': ' + n + ' remaining');
  if (s.length) console.log('  e.g.: ' + s.join('; '));
}
