import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ age: z.string().min(1,'Required').refine(v=>parseFloat(v)>=18,'≥18'), gender: z.string().min(1,'Required'), skinfold1: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0'), skinfold2: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0'), skinfold3: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0'), skinfold4: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0'), skinfold5: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0'), skinfold6: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0'), skinfold7: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0') }),
  fields: [{ name:'age', label:'Age (years)', type:'number', min:18, max:80, step:'1' }, { name:'gender', label:'Gender', type:'select', options:[{value:'male',label:'Male'},{value:'female',label:'Female'}] }, { name:'skinfold1', label:'Chest (mm)', type:'number', min:3, max:60, step:'1' }, { name:'skinfold2', label:'Midaxillary (mm)', type:'number', min:3, max:60, step:'1' }, { name:'skinfold3', label:'Triceps (mm)', type:'number', min:3, max:60, step:'1' }, { name:'skinfold4', label:'Subscapular (mm)', type:'number', min:3, max:60, step:'1' }, { name:'skinfold5', label:'Abdomen (mm)', type:'number', min:3, max:60, step:'1' }, { name:'skinfold6', label:'Suprailiac (mm)', type:'number', min:3, max:60, step:'1' }, { name:'skinfold7', label:'Thigh (mm)', type:'number', min:3, max:60, step:'1' }],
  compute: (v) => { const age=parseFloat(v.age)||30; const gender=v.gender||'male'; const sf1=parseFloat(v.skinfold1)||0; const sf2=parseFloat(v.skinfold2)||0; const sf3=parseFloat(v.skinfold3)||0; const sf4=parseFloat(v.skinfold4)||0; const sf5=parseFloat(v.skinfold5)||0; const sf6=parseFloat(v.skinfold6)||0; const sf7=parseFloat(v.skinfold7)||0; const sum=sf1+sf2+sf3+sf4+sf5+sf6+sf7; let bd; if(gender==='female'){bd=1.097-0.00046971*sum+0.00000056*sum*sum-0.00012828*age} else {bd=1.112-0.00043499*sum+0.00000055*sum*sum-0.00028826*age}; const bf=(4.570/bd-4.142)*100; return { result:bf, label:'Body Fat', unit:'%', steps:[{ label:'Gender', value:gender==='male'?'Male':'Female' },{ label:'Sum 7 Skinfolds', value:sum.toFixed(1) },{ label:'Body Density (Jackson-Pollock)', value:bd.toFixed(4) },{ label:'Body Fat % (Brozek)', value:bf.toFixed(1) }] } },
  description: 'Estimate body density using Jackson & Pollock 7-site skinfold method. Sites: chest, midaxillary, triceps, subscapular, abdomen, suprailiac, thigh. Uses Brozek formula for body fat percentage.',
  formula: 'Men: BD = 1.112 - 0.00043499×S + 0.00000055×S² - 0.00028826×Age. Women: BD = 1.097 - 0.00046971×S + 0.00000056×S² - 0.00012828×Age. Brozek: BF% = (4.570/BD - 4.142)×100',
  interpretation: 'Essential 8-15%, Athletes 6-13%, Fitness 14-17%, Average 18-24%, Obese >25%.'
}

export default calcDef
