import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ age: z.string().min(1,'Required').refine(v=>parseFloat(v)>=40,'≥40'), totalChol: z.string().min(1,'Required').refine(v=>parseFloat(v)>0,'>0'), hdl: z.string().min(1,'Required').refine(v=>parseFloat(v)>0,'>0'), systolic: z.string().min(1,'Required').refine(v=>parseFloat(v)>=60,'≥60'), smoker: z.enum(['yes','no']), diabetic: z.enum(['yes','no']), hypertensive: z.enum(['yes','no']), gender: z.enum(['male','female']) }),
  fields: [{ name:'age', label:'Age', type:'number', min:40, max:79, step:'1' }, { name:'totalChol', label:'Total Cholesterol', type:'number', min:50, max:400, step:'1' }, { name:'hdl', label:'HDL', type:'number', min:10, max:150, step:'1' }, { name:'systolic', label:'Systolic BP', type:'number', min:60, max:300, step:'1' }, { name:'smoker', label:'Smoker', type:'select', options:[{ label:'No', value:'no' },{ label:'Yes', value:'yes' }] }, { name:'diabetic', label:'Diabetic', type:'select', options:[{ label:'No', value:'no' },{ label:'Yes', value:'yes' }] }, { name:'hypertensive', label:'On BP Treatment', type:'select', options:[{ label:'No', value:'no' },{ label:'Yes', value:'yes' }] }, { name:'gender', label:'Gender', type:'select', options:[{ label:'Male', value:'male' },{ label:'Female', value:'female' }] }],
  compute: (v) => { const a=parseFloat(v.age)||50; const tc=parseFloat(v.totalChol)||200; const h=parseFloat(v.hdl)||50; const sbp=parseFloat(v.systolic)||120; const sm=v.smoker||'no'; const dm=v.diabetic||'no'; const htn=v.hypertensive||'no'; const g=v.gender||'male'; const lnA=Math.log(a); const lnTc=Math.log(tc); const lnH=Math.log(h); const lnSbp=Math.log(sbp); const smk=sm==='yes'?1:0; const diab=dm==='yes'?1:0; const tr=htn==='yes'?1:0; let s1=0; let expBeta=0; if(g==='male'){s1=11.1129-0.9149*lnA-0.2782*lnTc-0.2767*lnH-0.1757*lnSbp; expBeta=91.4998*Math.exp(lnA*lnTc*0.6185+lnA*lnH*(-0.1759)+lnA*lnSbp*0.8027+lnA*smk*0.4827+lnA*diab*0.6225+(smk?0.1982:0)+(diab?0.5482:0)+(tr?0.0387:0)-s1);}else{s1=-29.799-1.469*lnA-0.1145*lnTc-0.3108*lnH-0.0526*lnSbp; expBeta=83.5702*Math.exp(lnA*lnTc*0.5284+lnA*lnH*(-0.0692)+lnA*lnSbp*1.544+lnA*smk*0.6468+lnA*diab*0.4572+(smk?0.2005:0)+(diab?0.577:0)+(tr?0.2407:0)-s1);} const risk=Math.max(0,Math.min(100,1-Math.pow(0.9144,expBeta))*100); return{result:risk, label:'10-Yr ASCVD Risk', unit:'%', steps:[{ label:'Risk Score', value:risk.toFixed(1) }] } },
  description: 'ACC/AHA Pooled Cohort Equations for 10-year ASCVD risk prediction.',
  formula: 'Pooled cohort equations using age, cholesterol, BP, diabetes, smoking, and treatment status.',
  interpretation: '<5% Low; 5-7.4% Borderline; 7.5-19.9% Intermediate; ≥20% High. Statin recommended for ≥7.5%.'
}

export default calcDef
