import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ age: z.string().min(1,'Required').refine(v=>parseFloat(v)>=30,'≥30'), totalChol: z.string().min(1,'Required').refine(v=>parseFloat(v)>0,'>0'), hdl: z.string().min(1,'Required').refine(v=>parseFloat(v)>0,'>0'), systolic: z.string().min(1,'Required').refine(v=>parseFloat(v)>=60,'≥60'), smoker: z.enum(['yes','no']), diabetic: z.enum(['yes','no']), treated: z.enum(['yes','no']), gender: z.enum(['male','female']) }),
  fields: [{ name:'age', label:'Age', type:'number', min:30, max:79, step:'1' }, { name:'totalChol', label:'Total Cholesterol', type:'number', min:50, max:400, step:'1' }, { name:'hdl', label:'HDL', type:'number', min:10, max:150, step:'1' }, { name:'systolic', label:'Systolic BP', type:'number', min:60, max:300, step:'1' }, { name:'smoker', label:'Smoker', type:'select', options:[{ label:'No', value:'no' },{ label:'Yes', value:'yes' }] }, { name:'diabetic', label:'Diabetic', type:'select', options:[{ label:'No', value:'no' },{ label:'Yes', value:'yes' }] }, { name:'treated', label:'On BP Treatment', type:'select', options:[{ label:'No', value:'no' },{ label:'Yes', value:'yes' }] }, { name:'gender', label:'Gender', type:'select', options:[{ label:'Male', value:'male' },{ label:'Female', value:'female' }] }],
  compute: (v) => { const a=parseFloat(v.age)||50; const tc=parseFloat(v.totalChol)||200; const h=parseFloat(v.hdl)||50; const sbp=parseFloat(v.systolic)||120; const sm=v.smoker||'no'; const dm=v.diabetic||'no'; const tr=v.treated||'no'; const g=v.gender||'male'; const lnA=Math.log(a); const lnTc=Math.log(tc); const lnH=Math.log(h); const lnSbp=Math.log(sbp); const smk=sm==='yes'?1:0; const diab=dm==='yes'?1:0; const tre=tr==='yes'?1:0; let base=0; let meanCoeff=0; if(g==='male'){base=52.01-0.506*lnA-0.105*lnTc-0.076*lnH-0.081*lnSbp; const comp=lnA*lnTc*0.243+lnA*lnH*(-0.127)+lnA*lnSbp*0.479+lnA*smk*0.457+lnA*diab*0.571-4.066*tre*lnSbp; meanCoeff=52.01*Math.exp(comp-base);}else{base=-64.11-0.416*lnA-0.003*lnTc-0.125*lnH-0.063*lnSbp; const comp=lnA*lnTc*(-0.009)+lnA*lnH*(-0.068)+lnA*lnSbp*0.601+lnA*smk*0.377+lnA*diab*0.59-3.837*tre*lnSbp; meanCoeff=64.11*Math.exp(comp-base);} const risk=Math.max(0,Math.min(100,1-Math.pow(0.9402,meanCoeff))*100); return{result:risk,label:'Framingham 10yr CHD Risk',unit:'%',steps:[{label:'Risk',value:risk.toFixed(1)},{label:'Goal <10%',value:risk<10?'Good control':'Consider statin'}]}},
  description: 'Framingham Risk Score for 10-year coronary heart disease risk prediction.',
  formula: 'NCEP ATP III version using age, cholesterol, BP, smoking, diabetes, and treatment.',
  interpretation: '<10%: Low. 10-20%: Moderate (consider statin). >20%: High (statin recommended per ATP III).'
}

export default calcDef
