import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ age: z.string().min(1,'Required').refine(v=>parseInt(v)>=0,'≥0'), temperature: z.string().min(1,'Required').refine(v=>parseFloat(v)>=35,'≥35'), respiratoryRate: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0'), oxygenSat: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0'), comorbidity: z.string().min(1,'Required'), durationDays: z.string().min(1,'Required').refine(v=>parseFloat(v)>=0,'≥0') }),
  fields: [{ name:'age', label:'Age (years)', type:'number', min:0, step:'1' }, { name:'temperature', label:'Temperature (°C)', type:'number', min:35, max:42, step:'0.1' }, { name:'respiratoryRate', label:'Respiratory Rate (/min)', type:'number', min:0, step:'1' }, { name:'oxygenSat', label:'Oxygen Saturation (%)', type:'number', min:0, max:100, step:'1' }, { name:'comorbidity', label:'Comorbidity', type:'select', options:[{value:'none',label:'None'},{value:'asthma',label:'Asthma/COPD'},{value:'cardiac',label:'Cardiac'},{value:'diabetes',label:'Diabetes'},{value:'immuno',label:'Immunocompromised'},{value:'pregnancy',label:'Pregnancy'}] }, { name:'durationDays', label:'Duration (days)', type:'number', min:0, step:'1' }],
  compute: (v) => { const a=parseInt(v.age)||30; const t=parseFloat(v.temperature)||37; const rr=parseFloat(v.respiratoryRate)||16; const o2=parseFloat(v.oxygenSat)||98; const d=parseFloat(v.durationDays)||1; const cm=({none:0,asthma:2,cardiac:3,diabetes:2,immuno:4,pregnancy:2} as Record<string, number>)[v.comorbidity]||0; const ar=a>65?3:a>50?2:a>18?0:a>2?1:2; const sev=ar+cm+(t>=39?2:t>=38?1:0)+(rr>=30?3:rr>=24?2:rr>=20?1:0)+(o2<90?4:o2<94?2:0)+(d>7?2:d>3?1:0); const l=sev<=3?'Outpatient (uncomplicated)':sev<=6?'Outpatient with monitoring':sev<=9?'Hospital admission advised':'ICU admission recommended'; return { result:sev, label:'Severity Score', unit:'', steps:[{ label:'Age Risk', value:ar.toString() },{ label:'Comorbidity', value:cm.toString() },{ label:'Fever', value:t>=39?'+2':t>=38?'+1':'0' },{ label:'Tachypnea', value:rr>=30?'+3':rr>=24?'+2':rr>=20?'+1':'0' },{ label:'Hypoxia', value:o2<90?'+4':o2<94?'+2':'0' },{ label:'Duration', value:d>7?'+2':d>3?'+1':'0' },{ label:'Total Score', value:sev.toString() },{ label:'Severity', value:l }] } },
  description: 'Influenza severity assessment for clinical triage and hospitalization decision-making per IDSA guidelines.',
  formula: 'Scoring: age risk (0-3) + comorbidity (0-4) + fever (0-2) + RR (0-3) + SpO2 (0-4) + duration (0-2). Range 0-18.',
  interpretation: '0-3: supportive care, oseltamivir if <48h symptoms. 4-6: consider chest X-ray, antivirals. 7-9: admit, oxygen. 10+: ICU, consider baloxavir.'
}

export default calcDef
