import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ activeCancer: z.string().min(1,'Required'), priorVte: z.string().min(1,'Required'), immobility: z.string().min(1,'Required'), thrombophilia: z.string().min(1,'Required'), surgery: z.string().min(1,'Required'), age: z.string().min(1,'Required'), hf: z.string().min(1,'Required'), mi: z.string().min(1,'Required'), stroke: z.string().min(1,'Required'), obesity: z.string().min(1,'Required'), hormones: z.string().min(1,'Required') }),
  fields: [{ name:'activeCancer', label:'Active Cancer (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'priorVte', label:'Prior VTE (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'immobility', label:'Reduced Mobility (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'thrombophilia', label:'Thrombophilia (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'surgery', label:'Recent Surgery/Trauma (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'age', label:'Age ≥70 (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'hf', label:'Heart Failure (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'mi', label:'MI/Stroke (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'stroke', label:'Acute Infection/Rheumatologic (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'obesity', label:'Obesity (BMI >30) (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'hormones', label:'Hormonal Therapy (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }],
  compute: (v) => { const cancer=parseFloat(v.activeCancer)||0; const prior=parseFloat(v.priorVte)||0; const immob=parseFloat(v.immobility)||0; const thrombo=parseFloat(v.thrombophilia)||0; const surg=parseFloat(v.surgery)||0; const age=parseFloat(v.age)||0; const hf=parseFloat(v.hf)||0; const mi=parseFloat(v.mi)||0; const stroke=parseFloat(v.stroke)||0; const ob=parseFloat(v.obesity)||0; const horm=parseFloat(v.hormones)||0; const score=cancer*3+prior*3+immob*3+thrombo*3+surg*2+age*1+hf*1+mi*1+stroke*1+ob*1+horm*1; return { result:score, label:'Padua Prediction Score', steps:[{ label:'Total Score', value:score.toFixed(0) }] } },
  description: 'Padua prediction score estimates risk of venous thromboembolism in hospitalized medical patients.',
  formula: 'Score = Cancer(3) + Prior VTE(3) + Immobility(3) + Thrombophilia(3) + Surgery(2) + Age≥70(1) + HF(1) + MI(1) + Infection(1) + Obesity(1) + Hormones(1).',
  interpretation: 'Score <4: low risk (11% VTE). Score ≥4: high risk (38% VTE). High-risk patients should receive pharmacologic thromboprophylaxis unless contraindicated.'
}
export default calcDef
