import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ age: z.string().min(1,'Required').refine(v=>parseFloat(v)>0,'>0'), male: z.string().min(1,'Required'), nursingHome: z.string().min(1,'Required'), neoplasm: z.string().min(1,'Required'), liverDisease: z.string().min(1,'Required'), chf: z.string().min(1,'Required'), cvd: z.string().min(1,'Required'), renal: z.string().min(1,'Required'), alteredMental: z.string().min(1,'Required'), rr: z.string().min(1,'Required'), sbp: z.string().min(1,'Required'), temp: z.string().min(1,'Required'), hr: z.string().min(1,'Required'), ph: z.string().min(1,'Required'), bun: z.string().min(1,'Required'), sodium: z.string().min(1,'Required'), glucose: z.string().min(1,'Required'), hct: z.string().min(1,'Required'), pleuraEff: z.string().min(1,'Required') }),
  fields: [{ name:'age', label:'Age (years)', type:'number', min:18, max:110, step:'1' }, { name:'male', label:'Male (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'nursingHome', label:'Nursing Home (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'neoplasm', label:'Cancer (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'liverDisease', label:'Liver Disease (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'chf', label:'CHF (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'cvd', label:'Cerebrovascular (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'renal', label:'Renal Disease (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'alteredMental', label:'Altered Mental Status (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'rr', label:'Resp Rate (breaths/min)', type:'number', min:10, max:60, step:'1' }, { name:'sbp', label:'Systolic BP (mmHg)', type:'number', min:50, max:250, step:'1' }, { name:'temp', label:'Temperature (°C)', type:'number', min:35, max:42, step:'0.1' }, { name:'hr', label:'Heart Rate (bpm)', type:'number', min:30, max:250, step:'1' }, { name:'ph', label:'Arterial pH', type:'number', min:7, max:7.6, step:'0.01' }, { name:'bun', label:'BUN (mg/dL)', type:'number', min:0, step:'1' }, { name:'sodium', label:'Sodium (mEq/L)', type:'number', min:110, max:170, step:'1' }, { name:'glucose', label:'Glucose (mg/dL)', type:'number', min:40, step:'1' }, { name:'hct', label:'Hematocrit (%)', type:'number', min:15, max:60, step:'1' }, { name:'pleuraEff', label:'Pleural Effusion (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }],
  compute: (v) => { const age=parseFloat(v.age)||65; const male=parseFloat(v.male)||1; const nh=parseFloat(v.nursingHome)||0; const neo=parseFloat(v.neoplasm)||0; const liver=parseFloat(v.liverDisease)||0; const chf=parseFloat(v.chf)||0; const cvd=parseFloat(v.cvd)||0; const renal=parseFloat(v.renal)||0; const ams=parseFloat(v.alteredMental)||0; const rr=parseFloat(v.rr)||20; const sbp=parseFloat(v.sbp)||120; const temp=parseFloat(v.temp)||37; const hr=parseFloat(v.hr)||80; const ph=parseFloat(v.ph)||7.4; const bun=parseFloat(v.bun)||15; const na=parseFloat(v.sodium)||140; const glu=parseFloat(v.glucose)||100; const hct=parseFloat(v.hct)||40; const pe=parseFloat(v.pleuraEff)||0; const score=(male?0:age-10)+nh*10+neo*30+liver*20+chf*10+cvd*10+renal*10+ams*20+(rr>=30?20:0)+(sbp<90?20:0)+(temp<35||temp>=40?15:0)+(hr>=125?10:0)+(ph<7.35?30:0)+(bun>=30?20:0)+(na<130?20:0)+(glu>=250?10:0)+(hct<30?10:0)+pe*10; return { result:score, label:'PSI/PORT Score', steps:[{ label:'Total Score', value:score.toFixed(0) }] } },
  description: 'Pneumonia Severity Index (PSI) predicts 30-day mortality in community-acquired pneumonia (CAP).',
  formula: 'PSI = Age (female -10) + Nursing home(10) + Neoplasm(30) + Liver(20) + CHF(10) + CVD(10) + Renal(10) + AMS(20) + RR≥30(20) + SBP<90(20) + Temp<35/≥40(15) + HR≥125(10) + pH<7.35(30) + BUN≥30(20) + Na<130(20) + Glu≥250(10) + Hct<30(10) + Pleural eff(10).',
  interpretation: 'Class I (<50): low risk, outpatient. Class II (51-70): outpatient. Class III (71-90): brief admission. Class IV (91-130): hospitalized. Class V (>130): high mortality, ICU.'
}
export default calcDef
