import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ activeCancer: z.string().min(1,'Required'), paralysis: z.string().min(1,'Required'), bedridden: z.string().min(1,'Required'), localizedTenderness: z.string().min(1,'Required'), entireLegSwollen: z.string().min(1,'Required'), calfSwelling: z.string().min(1,'Required'), pittingEdema: z.string().min(1,'Required'), collateralVeins: z.string().min(1,'Required'), altDiagnosis: z.string().min(1,'Required') }),
  fields: [{ name:'activeCancer', label:'Active Cancer (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'paralysis', label:'Paralysis/Paresis (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'bedridden', label:'Bedridden >3 days / Surgery (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'localizedTenderness', label:'Localized Tenderness (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'entireLegSwollen', label:'Entire Leg Swollen (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'calfSwelling', label:'Calf Swelling >3cm (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'pittingEdema', label:'Pitting Edema (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'collateralVeins', label:'Collateral Superficial Veins (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }, { name:'altDiagnosis', label:'Alternative Diagnosis More Likely (1=Yes,0=No)', type:'number', min:0, max:1, step:'1' }],
  compute: (v) => { const cancer=parseFloat(v.activeCancer)||0; const palsy=parseFloat(v.paralysis)||0; const bed=parseFloat(v.bedridden)||0; const tender=parseFloat(v.localizedTenderness)||0; const leg=parseFloat(v.entireLegSwollen)||0; const calf=parseFloat(v.calfSwelling)||0; const edema=parseFloat(v.pittingEdema)||0; const veins=parseFloat(v.collateralVeins)||0; const alt=parseFloat(v.altDiagnosis)||0; const score=cancer*1+palsy*1+bed*1+tender*1+leg*1+calf*1+edema*1+veins*1+alt*(-2); return { result:score, label:'Wells Score for DVT', steps:[{ label:'Clinical Signs Total', value:(cancer+palsy+bed+tender+leg+calf+edema+veins).toFixed(0) },{ label:'Alternative Dx', value:'-'+((alt*2).toFixed(0)) },{ label:'Total Score', value:score.toFixed(0) }] } },
  description: 'Wells criteria estimate the pre-test probability of deep vein thrombosis (DVT) based on clinical findings.',
  formula: 'Score = Active cancer(1) + Paralysis(1) + Bedridden(1) + Localized tenderness(1) + Entire leg swollen(1) + Calf swelling(1) + Pitting edema(1) + Collateral veins(1) - Alternative diagnosis(2).',
  interpretation: 'Score ≤0: low probability (~5% DVT). Score 1-2: moderate probability (~17% DVT). Score ≥3: high probability (~55% DVT). D-dimer and imaging follow based on probability tier.'
}
export default calcDef
