import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ force: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), density: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), velocity: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), area: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [{ name: 'force', label: 'Lift Force F_l', type: 'number', unit: 'N', min: 0.01, step: '0.01' }, { name: 'density', label: 'Fluid Density ρ', type: 'number', unit: 'kg/m³', min: 0.01, step: '0.01' }, { name: 'velocity', label: 'Velocity v', type: 'number', unit: 'm/s', min: 0.1, step: '0.1' }, { name: 'area', label: 'Wing Area A', type: 'number', unit: 'm²', min: 0.001, step: '0.001' }],
  compute: (v) => { const Cl = 2 * v.force / (v.density * v.velocity * v.velocity * v.area); return { result: Cl, label: 'Lift Coefficient C_l', unit: '', steps: [{ label: 'Formula', value: 'C_l = 2F_l/(ρv²A)' }, { label: 'Result', value: `${Cl.toFixed(4)}` }] } },
  description: 'The lift coefficient is a dimensionless quantity that relates the lift generated by a lifting body to the fluid density, velocity, and reference area.',
  formula: 'C_l = 2F_l/(ρ·v²·A)',
  interpretation: 'Typical aircraft wing C_l ranges from 0.3 (cruise) to 1.5-2.0 (takeoff with flaps). Higher C_l means more lift at the same speed. Stall occurs when C_l reaches its maximum and then drops sharply.'
}

export default calcDef
