import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ tankGallons: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), fishPerGallon: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [
    { name: 'tankGallons', label: 'Tank Size (gallons)', type: 'number', min: 1, step: '5' },
    { name: 'fishPerGallon', label: 'Fish per Gallon', type: 'number', min: 0.1, step: '0.5' },
  ],
  defaults: { tankGallons: '20', fishPerGallon: '0.5' },
  presets: [
    { label: '10 gal Nano Community', values: { tankGallons: '10', fishPerGallon: '0.3' } },
    { label: '55 gal Cichlid Tank', values: { tankGallons: '55', fishPerGallon: '0.3' } },
    { label: '29 gal Community Mixed', values: { tankGallons: '29', fishPerGallon: '0.5' } },
    { label: '75 gal Discus Setup', values: { tankGallons: '75', fishPerGallon: '0.2' } },
  ],
  compute: (v) => { const g = parseFloat(v.tankGallons)||0; const fpg = parseFloat(v.fishPerGallon)||0; const maxFish = g * fpg; const oneInch = maxFish; const twoInch = maxFish * 0.5; const threeInch = maxFish * 0.33; const heavyBio = maxFish * 0.6; const community = maxFish * 0.8; const aggressive = maxFish * 0.4; return { result: maxFish, label: 'Max Fish (1-inch rule)', unit: '', steps: [{ label: 'Tank Volume', value: `${g} gal (${(g * 3.785).toFixed(1)} L)` }, { label: 'Stocking Rate', value: `${fpg} fish/gal` }, { label: 'Max Fish (1-inch rule)', value: `${Math.floor(maxFish)} fish` }, { label: 'If Fish Avg 2 inches', value: `${Math.floor(twoInch)} fish` }, { label: 'If Fish Avg 3 inches', value: `${Math.floor(threeInch)} fish` }, { label: 'Heavy Bio-load (cichlids/goldfish)', value: `${Math.floor(heavyBio)} fish` }, { label: 'Community Tank (tetras/rasboras)', value: `${Math.floor(community)} fish` }, { label: 'Aggressive Species Limiter', value: `${Math.floor(aggressive)} fish` }] ,
    extras: [
      { label: 'One-Inch Rule Explained', value: `The classic "1 inch of fish per gallon" rule works for small, slender fish (<3 inches). For larger fish, use the surface area rule: ${g > 0 ? (g > 55 ? 'your tank has adequate surface area for gas exchange' : g > 20 ? 'your ' + g + ' gal has moderate surface area — consider longer/wider tanks over tall ones' : 'your ' + g + ' gal is small — surface area is limited, stock conservatively') : ''}. Actual safe capacity depends on filtration, plants, and maintenance schedule.` },
      { label: 'Filtration Capacity Check', value: `${g > 0 ? 'For ' + g + ' gal: minimum filter rating ' + (g * 3).toFixed(0) + ' GPH (4-6× turnover for freshwater, 8-10× for saltwater). Canister filters handle ' + Math.floor(maxFish * 0.7) + '-' + Math.floor(maxFish) + ' fish at your density. HOB filters: ' + Math.floor(maxFish * 0.5) + '-' + Math.floor(community) + ' fish. Overstocking requires 10-15× GPH turnover and weekly 30% water changes.' : 'Enter tank size for filtration recommendations.'}` },
      { label: 'Fish Size & Growth Impact', value: `Many fish grow beyond their store size. Neon tetras: 1.5 in. Angelfish: 6 in. Common pleco: 12-18 in. At your ${fpg} fish/gal rate, ${Math.floor(twoInch)} × 2 in fish = ${Math.floor(twoInch * 2)} inches total — ${(twoInch * 2 / g * 100).toFixed(0)}% of your ${g} gal tank capacity. Account for adult sizes when stocking.` },
      { label: 'Nitrogen Cycle & Bioload', value: `Your ${Math.floor(maxFish)} fish produce ~${(maxFish * 0.5).toFixed(0)} mg/L ammonia daily. A cycled tank converts: ammonia → nitrite (24 hrs) → nitrate (48 hrs). At ${g} gal, keep nitrate <20 ppm. Fish density >1 inch/gal doubles waste output — requires 50% weekly water changes vs 25% for conservative stocking.` },
      { label: 'Tank Shape Considerations', value: `${g > 0 ? (g <= 20 ? 'Small tanks (' + g + ' gal) fluctuate temperature and chemistry rapidly. Longer tanks (>30 in) provide more swimming area and surface area for gas exchange. Tall tanks (>20 in deep) limit light penetration and make aquascaping harder.' : 'Your ' + g + ' gal benefits from more stable parameters. A 55 gal standard (48×13×21 in) offers 624 sq in surface area vs 36 gal bowfront (30×15×18 in) at 450 sq in.') : 'Enter tank size for shape-specific advice.'}` },
      { label: 'Beginner Stocking Plan', value: `For your ${g} gal tank: try ${Math.floor(community)} community fish (tetras, danios, corydoras). A planted community could include: ${Math.floor(community * 0.3)} schooling fish + ${Math.floor(community * 0.2)} bottom dwellers + ${Math.ceil(community * 0.1)} centerpiece fish. Always quarantine new fish for 2-3 weeks in a separate tank.` },
      { label: 'Weekly Maintenance Estimate', value: `${g > 0 ? 'At ' + Math.floor(maxFish) + ' fish: ' + (g <= 20 ? '2× weekly 25% water change (w/ gravel vac), 15 min' : g <= 55 ? 'weekly 25% water change, 25 min' : 'weekly 30% water change, 40 min') + '. Filter cleaning: monthly, never use tap water. Test kit: ammonia, nitrite, nitrate, pH weekly. Budget: $15-25/month for food, chemicals, and electricity.' : ''}` },
      { label: 'Stocking Level Warning', value: `${maxFish > g * 0.8 ? '⚠ Heavy stocking (' + Math.floor(maxFish) + ' fish in ' + g + ' gal). Consider: (1) reduce to ' + Math.floor(g * 0.5) + ' fish for easier maintenance, (2) upgrade filter to ' + (g * 6).toFixed(0) + ' GPH, (3) add live plants for natural filtration, (4) test water weekly. Overstocking is the #1 cause of new tank syndrome.' : 'Your ' + Math.floor(maxFish) + ' fish in ' + g + ' gal is ' + (maxFish / g <= 0.5 ? 'lightly stocked ✓ — easy to maintain' : 'moderately stocked — regular maintenance required') + '. Watch for aggression, ensure hiding spots, and maintain consistent feeding schedule.'}` },
    ]} },
  description: 'Estimate the maximum number of fish your aquarium can safely hold based on tank volume and stocking density. Includes fish-size variants, filtration needs, bioload analysis, and beginner-friendly stocking plans.',
  formula: 'Max Fish = Tank Gallons × Fish per Gallon | Variants: 2-inch fish × 0.5, 3-inch × 0.33, Heavy Bioload × 0.6, Community × 0.8, Aggressive × 0.4',
  interpretation: 'The 1-inch-per-gallon rule is a starting point — actual capacity depends on fish species, filtration (4-10× GPH turnover), plants, and maintenance schedule. Small fish (<2 in) like tetras and rasboras allow denser stocking. Large/messy fish like goldfish and cichlids need 2-5× more space per inch. Overstocking causes stress, aggression, and poor water quality. A heavily planted 20-gal can safely hold more fish than a bare 40-gal. Always research adult sizes — many pet-store fish grow 3-10× their juvenile size. Cycle the tank fully (4-8 weeks) before adding fish.'
}

export default calcDef
