import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ steps: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0'), weight: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), stride: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [
    { name: 'steps', label: 'Daily Steps', type: 'number', min: 0, step: '100' },
    { name: 'weight', label: 'Body Weight (lb)', type: 'number', min: 50, step: '5' },
    { name: 'stride', label: 'Stride Length (in)', type: 'number', min: 12, step: '1' },
  ],
  defaults: { steps: '8000', weight: '160', stride: '30' },
  presets: [
    { label: 'Sedentary Office Worker', values: { steps: '5000', weight: '180', stride: '28' } },
    { label: 'Active Walker (10k Goal)', values: { steps: '10000', weight: '150', stride: '30' } },
    { label: 'Fitness Enthusiast', values: { steps: '15000', weight: '170', stride: '32' } },
    { label: 'Weight Loss Walk', values: { steps: '12000', weight: '200', stride: '28' } },
  ],
  compute: (v) => { const s = parseFloat(v.steps)||0; const w = parseFloat(v.weight)||0; const st = parseFloat(v.stride)||0; const distMi = (s * st) / 63360; const distKm = distMi * 1.609; const calPerLbPerMi = 0.57; const cal = distMi * w * calPerLbPerMi; const calPerHour = w > 0 ? cal / (distMi / 3) : 0; const calMonthly = cal * 30; const calYearly = cal * 365; const lbsMonthly = calMonthly / 3500; const lbsYearly = calYearly / 3500; const stepsPerMi = st > 0 ? 63360 / st : 0; return { result: cal, label: 'Calories Burned', unit: 'kcal', steps: [{ label: 'Distance Walked', value: `${distMi.toFixed(2)} mi (${distKm.toFixed(2)} km)` }, { label: 'Stride Length', value: `${st} in (${(st * 2.54).toFixed(0)} cm)` }, { label: 'Steps per Mile', value: `${stepsPerMi.toFixed(0)} steps` }, { label: 'Walking Time (3 mph)', value: `${(distMi / 3 * 60).toFixed(0)} min` }, { label: 'Calories Burned', value: `${cal.toFixed(0)} kcal` }, { label: 'Calories per Hour', value: `${calPerHour.toFixed(0)} kcal/hr` }, { label: 'Monthly Estimate (30 days)', value: `${calMonthly.toFixed(0)} kcal (${lbsMonthly.toFixed(1)} lb fat)` }, { label: 'Yearly Estimate (365 days)', value: `${calYearly.toFixed(0)} kcal (${lbsYearly.toFixed(1)} lb fat)` }] ,
    extras: [
      { label: 'Pace & Intensity Impact', value: `At 3 mph (20 min/mi): ${cal.toFixed(0)} kcal. At 3.5 mph (17 min/mi): +20% = ${(cal * 1.2).toFixed(0)} kcal. At 4 mph (15 min/mi): +40% = ${(cal * 1.4).toFixed(0)} kcal. Brisk walking burns 3-5 METs vs 2-3 METs casual. Incorporate intervals: 3 min fast + 2 min moderate to boost EPOC afterburn by 15% for 1-2 hours post-walk.` },
      { label: 'Weight Loss Projection', value: `Walking ${s.toFixed(0)} steps/day burns ~${cal.toFixed(0)} kcal/day. At this rate: ${lbsMonthly.toFixed(1)} lb/month fat loss (${lbsYearly.toFixed(1)} lb/year). Combined with 500 kcal/day diet deficit: ${(lbsMonthly + 4.3).toFixed(1)} lb/month. For 1 lb/week (500 kcal/day deficit), target ${((3500 / 30 / calPerLbPerMi + distMi * w * 0.57) / w / 0.57 * 63360 / st).toFixed(0)} steps/day at 3 mph.` },
      { label: 'Steps vs Other Activities', value: `${s.toFixed(0)} steps = ${cal.toFixed(0)} kcal. Equivalent to: ${(cal / 8).toFixed(0)} min jogging, ${(cal / 5).toFixed(0)} min cycling moderate, ${(cal / 3).toFixed(0)} min yoga, ${(cal / 10).toFixed(0)} min swimming. Walking is low-impact, requires no equipment, and has the highest compliance rate of any exercise — 80% of people stick with it vs 50% for gym programs.` },
      { label: 'Tracker Accuracy Check', value: `Most fitness trackers overestimate steps by 10-30% and calories by 20-50%. Your calculation (${cal.toFixed(0)} kcal) uses the validated formula: distance × weight × 0.57 kcal/lb/mi. A wrist tracker might report ${(cal * 1.3).toFixed(0)} kcal. For best accuracy: calibrate stride length manually (${st} in here), choose running if jogging, and enter correct weight (${w} lb). Phone pedometers are typically ±15% accurate.` },
      { label: 'Heart Rate Zone Guide', value: `For walking (${distMi > 0 ? (distMi / 3 * 60).toFixed(0) + ' min' : '0 min'}): target HR zone = 50-70% max (220-age). Fat burn zone: 50-60% (longer duration). Cardio zone: 60-70% (better VO2 max improvement). At 3 mph most adults reach 60-65% max HR. A ${w} lb person at ${st} in stride burns more calories per minute at ${Math.round(calPerHour)} kcal/hr than running at same speed due to walking biomechanics.` },
      { label: 'Incline & Terrain Effect', value: `Flat walking (0% grade): ${cal.toFixed(0)} kcal. Add incline: +50% at 5% grade = ${(cal * 1.5).toFixed(0)} kcal, +100% at 10% = ${(cal * 2).toFixed(0)} kcal. Stairs: 8-11 kcal/min — 3× flat walking. Trail walking (uneven terrain): +20-30% = ${(cal * 1.25).toFixed(0)} kcal. Hiking with 10 lb pack: +15%. Even gentle hills boost calorie burn significantly for a ${w} lb person.` },
      { label: 'Weekly Movement Goals', value: `Your ${s.toFixed(0)} steps/day = ${(s * 7).toFixed(0)} steps/week. CDC recommends 150 min/week moderate activity = ~7,000-8,000 steps/day. You're at ${s >= 10000 ? '10,000+ — highly active tier' : s >= 7500 ? '7,500-10,000 — somewhat active, meeting guidelines' : s >= 5000 ? '5,000-7,500 — low active, increase by ' + (10000 - s).toFixed(0) + ' steps/day' : 'under 5,000 — sedentary, aim for +2,000 steps/day'}. Adding ${(10000 - s).toFixed(0)} steps/day = ${((10000 - s) / stepsPerMi * w * 0.57 * 365 / 3500).toFixed(1)} lb/year.` },
      { label: 'Form & Recovery Tips', value: `To maximize ${s.toFixed(0)} steps: maintain upright posture, engage core, roll through foot heel-to-toe, swing arms 90°. ${distMi.toFixed(1)} mi/day = ${(distMi * 7 * 365 / 12).toFixed(0)} mi/year — replace walking shoes every 300-500 mi ($${(distMi * 365 / 400 * 100).toFixed(0)}/year). Post-walk hydrate ${(w * 0.67).toFixed(0)} oz water + stretch hamstrings, quads, glutes for 5 min.` },
    ]} },
  description: 'Estimate calories burned from walking based on step count, body weight, and stride length. Includes pace variants, weight loss projections, incline effects, and heart zone analysis for optimized fitness results.',
  formula: 'Calories = (Steps × Stride) ÷ 63360 × Weight × 0.57 | Distance = Steps × Stride ÷ 63360 | Fat Loss = Calories × Days ÷ 3500 | Steps per Mile = 63360 ÷ Stride',
  interpretation: 'A 160 lb person burns ~100 kcal per mile walking regardless of speed (walking is 80-90% efficient). The 0.57 factor accounts for walking biomechanics (vs 0.75 for running). Step trackers often overestimate by 20-50%; this gives a science-based estimate. To lose 1 lb/week (500 kcal/day deficit), a 160 lb person needs ~12,000 steps/day at their current diet or ~8,000 steps with a 300 kcal diet cut. Increase intensity with hills (doubles burn), Nordic poles (+20%), or intervals. Walking 30 min/day reduces all-cause mortality by 20% and is the single most sustainable exercise for long-term health.'
}

export default calcDef
