import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ roomLength: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), roomWidth: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), pricePerSqFt: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), wastePct: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0') }),
  fields: [
    { name: 'roomLength', label: 'Room Length (ft)', type: 'number', min: 1, step: '1' },
    { name: 'roomWidth', label: 'Room Width (ft)', type: 'number', min: 1, step: '1' },
    { name: 'pricePerSqFt', label: 'Price per Sq Ft ($)', type: 'number', min: 0.5, step: '0.5' },
    { name: 'wastePct', label: 'Waste Factor (%)', type: 'number', min: 0, max: 30, step: '1' },
  ],
  defaults: { roomLength: '15', roomWidth: '12', pricePerSqFt: '4', wastePct: '10' },
  presets: [
    { label: 'Living Room Hardwood', values: { roomLength: '20', roomWidth: '15', pricePerSqFt: '8', wastePct: '10' } },
    { label: 'Bedroom Laminate', values: { roomLength: '14', roomWidth: '12', pricePerSqFt: '3', wastePct: '7' } },
    { label: 'Kitchen Tile', values: { roomLength: '12', roomWidth: '10', pricePerSqFt: '6', wastePct: '15' } },
    { label: 'Basement Vinyl Plank', values: { roomLength: '30', roomWidth: '25', pricePerSqFt: '2.5', wastePct: '10' } },
  ],
  compute: (v) => { const l = parseFloat(v.roomLength)||0; const w = parseFloat(v.roomWidth)||0; const p = parseFloat(v.pricePerSqFt)||0; const wp = parseFloat(v.wastePct)||0; const area = l * w; const waste = area * (wp / 100); const net = area + waste; const total = net * p; const totalSqYds = net / 9; const boxes = Math.ceil(net / 20); const labor = net * 2.5; const installedTotal = total + labor; return { result: total, label: 'Material Cost', unit: '$', steps: [{ label: 'Room Dimensions', value: `${l} × ${w} ft` }, { label: 'Room Area', value: `${area.toFixed(1)} sq ft (${area.toFixed(1)} sq ft)` }, { label: `Waste Allowance (${wp}%)`, value: `${waste.toFixed(1)} sq ft` }, { label: 'Total to Purchase', value: `${net.toFixed(1)} sq ft (${totalSqYds.toFixed(1)} sq yd)` }, { label: 'Boxes Needed (20 sq ft/box)', value: `${boxes} boxes` }, { label: 'Material Cost', value: `$${total.toFixed(2)} @ $${p.toFixed(2)}/sq ft` }, { label: 'Est. Labor ($2.50/sq ft)', value: `$${labor.toFixed(2)}` }, { label: 'Installed Total (materials + labor)', value: `$${installedTotal.toFixed(2)}` }] ,
    extras: [
      { label: 'Material Grade Comparison', value: `At $${p.toFixed(2)}/sq ft: budget tier ($${p < 3 ? '✓' : '✗'}), mid-range (${p >= 3 && p <= 7 ? '✓' : p < 3 ? 'add $1-3/sq ft' : '✓'}), premium (${p > 7 ? '✓' : 'add $3-8/sq ft'}). Hardwood: $5-15/sq ft installed. Laminate: $3-8/sq ft. Vinyl plank: $3-7/sq ft. Tile: $5-15/sq ft. Your $${p.toFixed(2)}/sq ft is ${p < 3 ? 'budget-friendly — expect lower durability (5-10 year lifespan)' : p < 6 ? 'mid-range — good balance of cost and quality (10-20 years)' : 'premium — high-quality materials (20-50+ year lifespan)'}.` },
      { label: 'Waste Factor Optimization', value: `${wp}% waste on ${area.toFixed(0)} sq ft = ${waste.toFixed(1)} sq ft extra. For ${l}×${w} ft room: straight lay = 5-7% waste. Diagonal: 10-15%. Herringbone: 15-20%. Patterned tile: 15-25%. Your ${wp}% is ${wp <= 7 ? 'conservative — fine for straight lay with minimal cuts' : wp <= 12 ? 'adequate for diagonal or moderate complexity' : 'generous — suitable for complex patterns'}. Reducing waste from ${wp}% to 7% saves $${(net * p - (area * 1.07 * p)).toFixed(2)}.` },
      { label: 'Subfloor Preparation Cost', value: `Add $0.50-1.50/sq ft for subfloor prep. ${area.toFixed(0)} sq ft = $${(area * 1).toFixed(0)}-${(area * 1.5).toFixed(0)}. Includes: moisture barrier ($${(area * 0.25).toFixed(0)}), self-leveling compound ($${(area * 0.75).toFixed(0)} if needed), underlayment ($${(area * 0.35).toFixed(0)} for floating floors). Factor into total budget: $${(installedTotal + area * 1).toFixed(0)}-${(installedTotal + area * 1.5).toFixed(0)} with subfloor prep. Concrete subfloor needs moisture testing before installation.` },
      { label: 'Per-Square-Foot True Cost', value: `Room ${area.toFixed(0)} sq ft: material $${p.toFixed(2)} + waste $${((net - area) * p / area).toFixed(2)}/sq ft + labor $2.50/sq ft + subfloor $1/sq ft = ~$${(p + ((net - area) * p / area) + 2.5 + 1).toFixed(2)}/sq ft installed. For your ${area.toFixed(0)} sq ft room: material $${total.toFixed(0)} (${(total / installedTotal * 100).toFixed(0)}%) + labor $${labor.toFixed(0)} (${(labor / installedTotal * 100).toFixed(0)}%) = ~$${installedTotal.toFixed(0)} total installed.` },
      { label: 'Acclimation & Installation', value: `Let flooring acclimate in-room for ${p >= 5 ? '72' : '48'} hours before installation (${p >= 5 ? 'hardwood/engineered wood requires 3+ days' : 'laminate/vinyl needs 48 hours'}). Keep room temp 65-75°F, humidity 35-55%. ${l}' × ${w}' room: expect ${(l * w / 100).toFixed(1)}-${(l * w / 60).toFixed(1)} days installation for a professional crew. Remove baseboards ($${(2 * (l + w) * 12 / 12 * 0.5).toFixed(0)}-${(2 * (l + w) * 12 / 12 * 1).toFixed(0)}) and reinstall after.` },
      { label: 'Room-by-Room Cost Projection', value: `At $${p.toFixed(2)}/sq ft: ${area.toFixed(0)} sq ft room = $${total.toFixed(0)} material. Whole-house estimate (1,500 sq ft): $${(1500 * p * 1.1).toFixed(0)} material + $${(1500 * 2.5).toFixed(0)} labor + $${(1500 * 1).toFixed(0)} subfloor = $${(1500 * p * 1.1 + 1500 * 3.5).toFixed(0)} total. Multi-room: account for transition strips ($15-30 each), quarter round ($1-2/ft), and thresholds ($20-50 each). Order 10-15% extra for whole-house vs 10% for single room.` },
      { label: 'Long-Term Value Assessment', value: `$${total.toFixed(0)} material investment. Expected lifespan at $${p.toFixed(2)}/sq ft: ${p < 3 ? '5-10 years (budget laminate/vinyl)' : p < 6 ? '10-20 years (mid-range)' : '20-50+ years (premium hardwood/tile)'}. Annual cost per year: $${(total / (p < 3 ? 7 : p < 6 ? 15 : 30)).toFixed(2)}. Premium flooring adds $${(area * 2).toFixed(0)}-${(area * 5).toFixed(0)} to home resale value — 70-90% cost recovery. Good mid-range flooring recovers 50-70%. Budget: 30-50%.` },
      { label: 'DIY vs Pro Savings Calculator', value: `DIY saves $${labor.toFixed(2)} in labor. Tools needed: $50-200 (saw, trowel, spacers, pull bar). ${l}×${w} ft (${area.toFixed(0)} sq ft) at $${p.toFixed(2)}/sq ft: DIY total = $${(total + 100).toFixed(0)}. Pro total = $${installedTotal.toFixed(0)}. DIY saves $${(installedTotal - total - 100).toFixed(0)} (${((installedTotal - total - 100) / installedTotal * 100).toFixed(0)}%). But mistakes cost: error rate 10-20% for first-timers = $${(net * p * 0.15).toFixed(0)} potential waste. Pro: guaranteed work, warranty, 2-3× faster.` },
    ]} },
  description: 'Calculate flooring material costs including waste factor for cutting and mistakes. Enter room dimensions and material price. Includes grade comparison, subfloor prep, labor estimates, and DIY vs professional cost analysis.',
  formula: 'Total Material Cost = (Length × Width × (1 + Waste%)) × Price/sq ft | Labor = Area × $2.50/sq ft | Boxes = Ceil(Total Sq Ft ÷ 20) | Installed = Material + Labor + Subfloor ($1/sq ft)',
  interpretation: 'Standard waste factor: 5-10% for straight layouts, 10-15% for diagonal or patterned installs. Budget $2.50/sq ft for professional installation and $1/sq ft for subfloor preparation. Flooring prices range from $2/sq ft (laminate) to $15/sq ft (hardwood/tile). Always buy extra for future repairs — store matching spare boxes in a climate-controlled area. For a typical 200 sq ft room, expect to pay $800-2,000 installed for mid-range materials. Pro installation is recommended for tile (precision cuts) and hardwood (nailing pattern), while click-lock vinyl plank is DIY-friendly.'
}

export default calcDef
