import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ ingredientCost: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), servings: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), markupPct: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0') }),
  fields: [
    { name: 'ingredientCost', label: 'Total Ingredient Cost ($)', type: 'number', min: 0.5, step: '1' },
    { name: 'servings', label: 'Number of Servings', type: 'number', min: 1, step: '1' },
    { name: 'markupPct', label: 'Markup (%)', type: 'number', min: 0, max: 500, step: '5' },
  ],
  defaults: { ingredientCost: '15', servings: '4', markupPct: '300' },
  presets: [
    { label: 'Home Batch Cooking (chili)', values: { ingredientCost: '15', servings: '6', markupPct: '0' } },
    { label: 'Restaurant Pasta Dish', values: { ingredientCost: '6', servings: '1', markupPct: '300' } },
    { label: 'Catering Sandwich Platter', values: { ingredientCost: '40', servings: '10', markupPct: '100' } },
    { label: 'Bakery Cookies (dozen)', values: { ingredientCost: '8', servings: '12', markupPct: '200' } },
  ],
  compute: (v) => { const ic = parseFloat(v.ingredientCost)||0; const s = parseFloat(v.servings)||0; const mp = parseFloat(v.markupPct)||0; const perServing = ic / s; const sellPrice = perServing * (1 + mp / 100); const totalRevenue = sellPrice * s; const grossProfit = totalRevenue - ic; const grossMargin = totalRevenue > 0 ? (grossProfit / totalRevenue) * 100 : 0; const foodCostPct = sellPrice > 0 ? (perServing / sellPrice) * 100 : 0; const profitPerServe = sellPrice - perServing; const annualRev = totalRevenue * 52; return { result: perServing, label: 'Cost per Serving', unit: '$', steps: [{ label: 'Total Ingredient Cost', value: `$${ic.toFixed(2)}` }, { label: 'Servings', value: `${s}` }, { label: 'Cost per Serving', value: `$${perServing.toFixed(2)}` }, { label: 'Desired Markup', value: `${mp}%` }, { label: 'Sell Price per Serving', value: `$${sellPrice.toFixed(2)}` }, { label: 'Total Revenue (all servings)', value: `$${totalRevenue.toFixed(2)}` }, { label: 'Profit per Serving', value: `$${profitPerServe.toFixed(2)}` }, { label: 'Food Cost %', value: `${foodCostPct.toFixed(1)}%` }] ,
    extras: [
      { label: 'Food Cost Target Analysis', value: `Your food cost: ${foodCostPct.toFixed(1)}%. Restaurant ideal: 25-35%. Fast food: 30-35%. Fine dining: 35-40%. Bakery: 25-30%. Your ${foodCostPct.toFixed(1)}% is ${foodCostPct < 25 ? 'very low — high profitability, but check quality perception' : foodCostPct < 35 ? 'within target range — excellent' : foodCostPct < 45 ? 'slightly high — consider pricing review or cost reduction' : 'high — need to increase sell price or reduce ingredient cost'}. At ${mp}% markup (${foodCostPct.toFixed(0)}% food cost), you make $${profitPerServe.toFixed(2)}/serve. To hit 30% food cost: set markup to ${((1 / 0.3 - 1) * 100).toFixed(0)}% = sell at $${(perServing / 0.3).toFixed(2)}.` },
      { label: 'Markup Strategy Comparison', value: `${mp}% markup = ${foodCostPct.toFixed(0)}% food cost. Industry standards: 100% (50% food cost) — catering, convenience. 200% (33%) — casual dining. 300% (25%) — standard restaurant. 400% (20%) — premium/fine dining. Your ${mp}% is ${mp <= 150 ? 'low — good for volume/wholesale' : mp <= 250 ? 'moderate — casual dining range' : mp <= 350 ? 'standard restaurant range — balanced' : 'premium — expects excellent presentation/service'}. 300% (4× cost) is the traditional restaurant benchmark. At $${sellPrice.toFixed(2)}/serve, ${s} servings = $${totalRevenue.toFixed(2)} total.` },
      { label: 'Volume & Scaling Economics', value: `Your $${ic.toFixed(2)} batch makes ${s} servings. Double batch: $${(ic * 1.8).toFixed(2)} cost (10% bulk discount) = $${(ic * 1.8 / (s * 2)).toFixed(2)}/serve (save $${(perServing - ic * 1.8 / (s * 2)).toFixed(2)}/serve). At current $${perServing.toFixed(2)}/serve cost and $${sellPrice.toFixed(2)} sell price: selling ${s * 10} servings/week = $${(profitPerServe * s * 10 * 4.3).toFixed(0)}/mo profit. Scaling to ${s * 30}/day = $${(profitPerServe * s * 30 * 30).toFixed(0)}/mo. Each % reduction in food cost improves profit by ~$${(ic * 0.01 * (s * 30 * 30 / ic)).toFixed(0)}/mo at scale.` },
      { label: 'Seasonal Cost Variation', value: `Ingredient cost $${ic.toFixed(2)}. In-season: -15-25% = $${(ic * 0.8).toFixed(2)}. Out-of-season: +20-40% = $${(ic * 1.3).toFixed(2)}. Using $${(ic * 0.8).toFixed(2)} ingredients at $${sellPrice.toFixed(2)} sell price: food cost drops to ${((perServing * 0.8 / sellPrice) * 100).toFixed(1)}% — profit rises to $${(sellPrice - perServing * 0.8).toFixed(2)}/serve. Menu engineering: update pricing quarterly based on ingredient costs. 80% of menu profit typically comes from 20% of items.` },
      { label: 'Labor & Overhead Allocation', value: `This calculator covers ingredient cost only. Full cost: food $${perServing.toFixed(2)} + labor ($$${(perServing * 0.35).toFixed(2)}, 35% of food cost) + overhead ($$${(perServing * 0.15).toFixed(2)}, 15%) = $${(perServing * 1.5).toFixed(2)} total cost/serve. At $${sellPrice.toFixed(2)} sell price: net margin = $${(sellPrice - perServing * 1.5).toFixed(2)}/serve. Prime cost (food + labor) should be <60% of revenue. Your prime cost: ${(foodCostPct + 10).toFixed(0)}% (food ${foodCostPct.toFixed(0)}% + est. labor at ${(foodCostPct * 0.3).toFixed(0)}% = ${(foodCostPct * 1.3).toFixed(0)}%).` },
      { label: 'Menu Price Psychology', value: `$${sellPrice.toFixed(2)}/serve. Pricing psychology: $${(sellPrice - 0.01).toFixed(2)} (charm pricing) often outsells $${sellPrice.toFixed(2)} by 15-25%. Value menu: $${(perServing * 1.5).toFixed(2)} (40% food cost). Premium: $${(perServing * 4).toFixed(2)} (25% food cost). For $${perServing.toFixed(2)} cost: suggested menu prices — budget $${(perServing * 2.5).toFixed(2)}, standard $${(perServing * 4).toFixed(2)}, premium $${(perServing * 5.5).toFixed(2)}. A $${sellPrice.toFixed(2)} item at ${s} servings/day × 30 days = $${(sellPrice * s * 30).toFixed(0)}/mo revenue. Adding a ${(perServing * 0.5).toFixed(2)} side garnish costs you $${(perServing * 0.5).toFixed(2)} but supports a $${(sellPrice + 1).toFixed(0)} menu price.` },
      { label: 'Batch Comparison Tool', value: `Your recipe: $${ic.toFixed(2)} → ${s} servings at $${perServing.toFixed(2)} each. If you bought pre-prepped (diced veggies, pre-marinated meat): +30-50% cost = $${(perServing * 1.4).toFixed(2)}/serve but saves 20-40 min labor. If you make from scratch (whole ingredients): -20% cost = $${(perServing * 0.8).toFixed(2)} but +15-30 min labor. For a restaurant at $25/hr labor, the break-even is when prep time exceeds ${(perServing * 0.4 / (25 / 60)).toFixed(0)} min. Home cook: scratch is almost always cheaper since labor is unpaid.` },
      { label: 'Nutritional Cost Efficiency', value: `$${perServing.toFixed(2)}/serving. Cost per 100g protein: $${(perServing / 20 * 100).toFixed(2)} (assuming 20g protein/serving). Compare: chicken breast $0.67/100g, tofu $0.33/100g, eggs $0.50/100g. Your dish at $${perServing.toFixed(2)}/serve is $${perServing <= 3 ? 'budget-friendly' : perServing <= 6 ? 'moderate cost' : 'premium cost'}. For healthy margins, pair high-cost proteins ($$${(perServing * 0.5).toFixed(2)}) with low-cost starches ($$0.50-1.00) and vegetables ($$0.75-1.50). Target plate cost ratio: protein 40%, produce 25%, starch 20%, sauce 15%.` },
    ]} },
  description: 'Calculate per-serving food cost and suggested menu pricing with markup. Includes food cost percentage, profit analysis, volume economics, and menu price psychology for restaurants and home batch cooking.',
  formula: 'Cost/Serving = Total Ingredients ÷ Servings | Sell Price = Cost/Serving × (1 + Markup%) | Food Cost % = Cost ÷ Sell Price × 100 | Gross Profit = Revenue − Ingredient Cost | Gross Margin % = Profit ÷ Revenue × 100',
  interpretation: 'Restaurant target food cost: 25-35% of menu price. 300% markup (4× cost) is standard — a dish costing $4 to make sells for $16 at 25% food cost. Premium ingredients may require lower food cost targets (30-35%) to maintain quality perception. Track food cost weekly and adjust pricing when ingredient costs shift. The most profitable restaurants maintain 25-28% food cost with consistent portion control and seasonal menu adjustments. For home cooks, skipping the markup gives you the true savings vs eating out — a $4/serving home meal would cost $12-20 at a restaurant.'
}

export default calcDef
