import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ dailyMeals: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), costPerMeal: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), people: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [
    { name: 'dailyMeals', label: 'Meals per Day', type: 'number', min: 1, step: '1' },
    { name: 'costPerMeal', label: 'Avg Cost per Meal ($)', type: 'number', min: 1, step: '1' },
    { name: 'people', label: 'Number of People', type: 'number', min: 1, step: '1' },
  ],
  defaults: { dailyMeals: '3', costPerMeal: '5', people: '2' },
  presets: [
    { label: 'Single Person Cooking at Home', values: { dailyMeals: '3', costPerMeal: '4', people: '1' } },
    { label: 'Family of 4 Mix Cook/Dine Out', values: { dailyMeals: '3', costPerMeal: '8', people: '4' } },
    { label: 'Couple Budget-Conscious', values: { dailyMeals: '3', costPerMeal: '3', people: '2' } },
    { label: 'Student Meal Plan + Eating Out', values: { dailyMeals: '3', costPerMeal: '7', people: '1' } },
  ],
  compute: (v) => { const m = parseFloat(v.dailyMeals)||0; const c = parseFloat(v.costPerMeal)||0; const p = parseFloat(v.people)||0; const daily = m * c * p; const weekly = daily * 7; const monthly = daily * 30; const yearly = daily * 365; const perPersonDaily = daily / p; const perPersonMonthly = monthly / p; const diningOutPct = c > 5 ? c * 0.35 : c * 0.15; const cookAtHome = m * (c - diningOutPct) * p; const diningOut = daily - cookAtHome; return { result: monthly, label: 'Monthly Food Budget', unit: '$', steps: [{ label: 'Meals per Day', value: `${m} meals × ${p} person(s) = ${m * p} meals/day` }, { label: 'Cost per Meal', value: `$${c.toFixed(2)}` }, { label: 'Daily Total', value: `$${daily.toFixed(2)}` }, { label: 'Weekly Total', value: `$${weekly.toFixed(2)}` }, { label: 'Monthly Total', value: `$${monthly.toFixed(2)}` }, { label: 'Yearly Total', value: `$${yearly.toFixed(2)}` }, { label: 'Per Person Daily', value: `$${perPersonDaily.toFixed(2)}` }, { label: 'Per Person Monthly', value: `$${perPersonMonthly.toFixed(2)}` }] ,
    extras: [
      { label: 'Thrifty vs Moderate vs Liberal Plan', value: `For ${p} person(s): USDA Thrifty ($${(perPersonMonthly * 0.75).toFixed(0)}/person/mo) = $${(perPersonMonthly * 0.75 * p).toFixed(0)}. Moderate ($${(perPersonMonthly).toFixed(0)}/person/mo) = $${(perPersonMonthly * p).toFixed(0)}. Liberal ($${(perPersonMonthly * 1.3).toFixed(0)}/person/mo) = $${(perPersonMonthly * 1.3 * p).toFixed(0)}. Your plan: $${perPersonMonthly.toFixed(0)}/person = ${perPersonMonthly < 300 ? 'thrifty to moderate' : perPersonMonthly < 450 ? 'moderate' : 'liberal'} tier. USDA recommends $${(p >= 4 ? p * 320 : p * 370).toFixed(0)}-${(p >= 4 ? p * 520 : p * 550).toFixed(0)}/month for ${p} person(s).` },
      { label: 'Cook at Home vs Dining Out Split', value: `At $${c.toFixed(2)}/meal avg: home-cooked = $${(c * 0.6).toFixed(2)}/meal ($$${(c * 0.6 * m * p * 30).toFixed(0)}/mo), restaurant = $${(c * 1.8).toFixed(2)}/meal ($$${(c * 1.8 * m * 0.2 * p * 30).toFixed(0)}/mo for 20% of meals). If you eat out ${c > 6 ? 'frequently ($$' + (c * 0.3 * m * p * 30).toFixed(0) + '/mo on dining)' : 'occasionally (~$$' + (c * 0.15 * m * p * 30).toFixed(0) + '/mo)'}. Cooking at home saves 40-60% per meal. Switching 5 meals/week from $${(c * 1.8).toFixed(2)} to $${(c * 0.6).toFixed(2)} saves $${(5 * (c * 1.8 - c * 0.6) * 4.3).toFixed(0)}/month.` },
      { label: 'Meal Prep & Bulk Savings', value: `Your $${(perPersonDaily).toFixed(2)}/person/day. Meal prep weekly: reduce cost 20-30%. Bulk buying rice/beans: $0.15-0.30/serving (vs $0.50-1.00). Buying whole chicken ($1.50/lb) vs parts ($3-5/lb): save 50-60%. Seasonal vegetables: 30-50% cheaper. For ${p} people: bulk cooking 2×/week saves $${(monthly * 0.15).toFixed(0)}-${(monthly * 0.25).toFixed(0)}/mo. Frozen vegetables: same nutrition as fresh, 40% cheaper, zero waste. $${monthly.toFixed(0)}/mo could be $${(monthly * 0.8).toFixed(0)} with strategic bulk + prep.` },
      { label: 'Protein Cost Efficiency', value: `Best $/g protein: Lentils $0.01/g, Eggs $0.03/g, Chicken breast $0.04/g, Canned tuna $0.05/g, Tofu $0.02/g, Ground beef $0.06/g, Salmon $0.10/g. At your $${c.toFixed(2)}/meal, replacing beef with lentils 3×/week saves ~$${(3 * (c * 0.2)).toFixed(0)}/week = $${(3 * (c * 0.2) * 4.3).toFixed(0)}/month. For ${p} people, that's $${(3 * (c * 0.2) * p * 4.3).toFixed(0)}/month. Plant protein costs 50-80% less than animal protein with equivalent nutrition.` },
      { label: 'Food Budget by Diet Type', value: `Standard: $${perPersonMonthly.toFixed(0)}/person/mo. Vegetarian: $${(perPersonMonthly * 0.8).toFixed(0)}/mo (-20%, less meat). Vegan: $${(perPersonMonthly * 0.7).toFixed(0)}/mo (-30%). Paleo/Keto: $${(perPersonMonthly * 1.3).toFixed(0)}/mo (+30%, more meat/protein). Gluten-free: $${(perPersonMonthly * 1.15).toFixed(0)}/mo (+15%). Organic-only: $${(perPersonMonthly * 1.5).toFixed(0)}/mo (+50%). If you follow a specialized diet, adjust budget by these factors. A family of ${p} on a ${p > 1 ? 'flexitarian diet saves $' + (perPersonMonthly * 0.15 * p).toFixed(0) + '/mo vs standard' : 'standard diet at $' + perPersonMonthly.toFixed(0) + '/person/mo'}.` },
      { label: 'Weekly Meal Planning Template', value: `For ${p} people, $${c.toFixed(2)}/meal: plan ${m} meals/day × 7 days = ${m * 7} meals/week. Template: 3 breakfasts ($$${(c * 0.5 * p * 3).toFixed(0)}), 4 lunches ($$${(c * 0.6 * p * 4).toFixed(0)}), 4 dinners cooking ($$${(c * 0.8 * p * 4).toFixed(0)}), 1-2 restaurant ($$${(c * 1.5 * p * 2).toFixed(0)}), leftovers 3 meals (free). Total: ~$$${(c * 0.5 * p * 3 + c * 0.6 * p * 4 + c * 0.8 * p * 4 + c * 1.5 * p * 2).toFixed(0)}/week vs your $${weekly.toFixed(0)} projection. Planned shopping reduces impulse buys by 30%.` },
      { label: 'Inflation & Seasonal Adjustment', value: `Your $${c.toFixed(2)}/meal avg. US food inflation 2024-25: 2-4%/year. In 1 year: ~$${(c * 1.03).toFixed(2)}/meal = $${(monthly * 1.03).toFixed(0)}/mo. In 5 years: ~$${(c * 1.16).toFixed(2)}/meal = $${(monthly * 1.16).toFixed(0)}/mo. Seasonal: produce in-season is 30-50% cheaper. Summer eating (more BBQs, fresh produce) can be 15% cheaper than winter (more roasts, indoor dining). Your annual budget: $${yearly.toFixed(0)}, with inflation buffer: $${(yearly * 1.03).toFixed(0)}.` },
    ]} },
  description: 'Plan your monthly food budget by meals per day, average cost per meal, and household size. Includes USDA plan comparison, diet type adjustments, meal prep savings, and cook-at-home vs dining-out analysis.',
  formula: 'Monthly = Meals/Day × Cost/Meal × People × 30 | Yearly = Monthly × 12 | Per Person = Monthly ÷ People | Dining Out = Total × (0.15-0.35 depending on meal cost)',
  interpretation: 'USDA thrifty plan: ~$300/person/month. Moderate: ~$400. Liberal: ~$500+. Cooking at home saves 40-60% vs dining out. A family of 4 can save $200-400/month by reducing restaurant meals and meal prepping. Protein choice has the biggest budget impact — replacing beef with lentils 3×/week saves $30-50/month per person. Weekly meal planning with a shopping list reduces food spending by 20-30% by eliminating impulse purchases and food waste.'
}

export default calcDef
