import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ mealsCooked: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), mealsWasted: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0'), avgMealCost: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [
    { name: 'mealsCooked', label: 'Meals Cooked per Week', type: 'number', min: 1, step: '1' },
    { name: 'mealsWasted', label: 'Meals Wasted per Week', type: 'number', min: 0, step: '1' },
    { name: 'avgMealCost', label: 'Avg Cost per Meal ($)', type: 'number', min: 1, step: '1' },
  ],
  defaults: { mealsCooked: '14', mealsWasted: '4', avgMealCost: '6' },
  presets: [
    { label: 'Busy Family with Leftovers Waste', values: { mealsCooked: '21', mealsWasted: '7', avgMealCost: '5' } },
    { label: 'Single Person, Good Habits', values: { mealsCooked: '10', mealsWasted: '1', avgMealCost: '4' } },
    { label: 'Couple, Frequent Dining Out', values: { mealsCooked: '8', mealsWasted: '3', avgMealCost: '8' } },
    { label: 'Large Family, Bulk Cooking', values: { mealsCooked: '28', mealsWasted: '6', avgMealCost: '4' } },
  ],
  compute: (v) => { const mc = parseFloat(v.mealsCooked)||0; const mw = parseFloat(v.mealsWasted)||0; const ac = parseFloat(v.avgMealCost)||0; const wastePct = mc > 0 ? (mw / mc) * 100 : 0; const weeklyWaste = mw * ac; const annualWaste = weeklyWaste * 52; const tenYearWaste = annualWaste * 10; const monthlyCO2 = mw * 2.5; const annualCO2 = monthlyCO2 * 52; const targetWaste = mw > 0 ? Math.ceil(mw * 0.5) : 0; const targetSavings = Math.max(0, (mw - targetWaste)) * ac; const investedValue = annualWaste * 1.08; return { result: wastePct, label: 'Food Waste Rate', unit: '%', steps: [{ label: 'Meals Cooked per Week', value: `${mc}` }, { label: 'Meals Wasted per Week', value: `${mw}` }, { label: 'Waste Rate', value: `${wastePct.toFixed(1)}%` }, { label: 'Weekly Waste Value', value: `$${weeklyWaste.toFixed(2)}` }, { label: 'Annual Waste Value', value: `$${annualWaste.toFixed(2)}` }, { label: '10-Year Waste Cost', value: `$${tenYearWaste.toFixed(2)}` }, { label: 'Annual CO₂ Impact', value: `${annualCO2.toFixed(0)} kg CO₂e` }, { label: 'If Invested (8% return)', value: `$${investedValue.toFixed(2)}/year` }] ,
    extras: [
      { label: 'Waste Reduction Target', value: `Cut waste by 50%: from ${mw} → ${targetWaste} wasted meals/week saves $${targetSavings.toFixed(2)}/week = $${(targetSavings * 52).toFixed(2)}/year. US average: 30-40% waste. Your ${wastePct.toFixed(1)}% is ${wastePct < 15 ? 'excellent — well below average' : wastePct < 25 ? 'good — below national average' : wastePct < 35 ? 'average — typical US household' : 'high — ' + (wastePct - 30).toFixed(0) + '% above average'}. Simple changes: meal planning (cuts waste 25-30%), proper storage (15-20%), using leftovers (20%). Target: under 20% waste rate.` },
      { label: 'Environmental Cost per Meal', value: `${mw} wasted meals/week = ${annualCO2.toFixed(0)} kg CO₂e/year — equivalent to driving ${(annualCO2 / 0.4).toFixed(0)} miles or ${(annualCO2 / 400).toFixed(1)} months of household electricity. Each wasted meal wastes: the food itself ($${ac.toFixed(2)}), plus the water (100-500 gal/lb of food), fertilizer, transport, packaging, and labor. US food waste = 4% of total national energy consumption. Landfill food waste generates methane — 25× more potent than CO₂.` },
      { label: 'Top 5 Waste Reduction Strategies', value: `1) Weekly meal plan before shopping — cuts 25% waste. 2) "First in, first out" fridge rotation — save 15%. 3) Freeze leftovers immediately — extends life 3-6 months. 4) Use vegetable scraps for broth — reduces waste by 10%. 5) Shop from a list, never hungry — cuts impulse buys 30%. For your $${annualWaste.toFixed(0)}/year waste: implementing all 5 could save $${(annualWaste * 0.6).toFixed(0)}-${(annualWaste * 0.75).toFixed(0)}/year. Start with meal planning — see $${(annualWaste * 0.25).toFixed(0)} savings immediately.` },
      { label: 'Storage Optimization Guide', value: `Proper storage saves $${(weeklyWaste * 0.2 * 52).toFixed(0)}/year: Keep fridge at 34-38°F. Store herbs: stems in water, refrigerated (lasts 2 weeks vs 3 days). Apples/ethylene producers separate from leafy greens. Bread: freezer for >3 day storage. Onions & potatoes: separate (onions hasten potato sprouting). Berries: wash before eating, not before storing. Greens: paper towel in bag absorbs moisture. These fixes alone could reduce your ${mw} wasted meals by ${Math.ceil(mw * 0.25)} meals/week.` },
      { label: 'Leftover Reinvention Ideas', value: `$${weeklyWaste.toFixed(0)}/week in waste = ~$${(weeklyWaste / ac).toFixed(0)} meals. Reinvention strategies: Day 1 roast chicken → Day 2 chicken tacos → Day 3 chicken soup. Extra rice → fried rice or rice pudding. Over-ripe bananas → banana bread (freeze for later). Vegetable scraps + bones → stock (freeze in portions). Stale bread → croutons or breadcrumbs. Herbs about to wilt → pesto or compound butter. Each reinvented meal saves $${ac.toFixed(2)} and 30 min of future cooking.` },
      { label: 'Smart Shopping & Bulk Management', value: `Your $${ac.toFixed(2)}/meal avg. Shop with a list based on ${mc} meals × ${mw > 0 ? Math.ceil(mc / (mc - mw)) : 1} weeks = ${mc * (mw > 0 ? Math.ceil(mc / (mc - mw)) : 1)} meals planned. Buy produce 2-3×/week (smaller, fresher batches) vs one big trip. Bulk: only for non-perishables (rice, pasta, spices) and items you use consistently. Check fridge inventory before shopping. "Shop your pantry" challenge 1×/month: cook only from what you have — average savings $50-100/month = $${(50 * 12 / 52 / ac).toFixed(0)} fewer wasted meals/week.` },
      { label: 'Composting & Circular Economy', value: `$${weeklyWaste.toFixed(0)}/week × 52 = $${annualWaste.toFixed(0)}/year in food. Even with best habits, some waste is unavoidable (peels, bones, coffee grounds). Composting these: eliminates methane (converts to CO₂ neutral), creates free soil (value ~$50-100/year), reduces trash volume by 30%. Worm bin (vermicompost): best for apartments, processes 1 lb scraps/week. Outdoor compost: handles 5+ lb/week. Your ${mw} wasted meals = ~${(mw * 0.5).toFixed(1)} lb organic waste/week — ${mw > 3 ? 'great candidate for composting' : 'manageable amount for countertop collection'}.` },
      { label: 'Future Savings if Invested', value: `$${annualWaste.toFixed(2)}/year currently wasted. Invested at 8% return: $${investedValue.toFixed(2)} after 1 year. After 10 years: $${(annualWaste * (Math.pow(1.08, 10) - 1) / 0.08).toFixed(0)}. After 30 years: $${(annualWaste * (Math.pow(1.08, 30) - 1) / 0.08).toFixed(0)}. Halving your ${wastePct.toFixed(0)}% waste rate to ${(wastePct / 2).toFixed(0)}% saves $${(annualWaste / 2).toFixed(0)}/year — $${((annualWaste / 2) * (Math.pow(1.08, 10) - 1) / 0.08).toFixed(0)} over 10 years invested. The cheapest meal is the one already in your fridge.` },
    ]} },
  description: 'Track household food waste by comparing meals cooked vs wasted. Calculate the financial, environmental, and long-term investment impact of food waste with actionable reduction strategies.',
  formula: 'Waste% = (Meals Wasted ÷ Meals Cooked) × 100 | Annual Waste $ = Meals Wasted × Cost × 52 | CO₂ = Wasted Meals × 2.5 kg × 52 | 10 Year Waste = Annual × 10 | Invested Value = Annual × (1 + 0.08)^Year',
  interpretation: 'Average US household wastes 30-40% of food — $1,500+/year for a family of four. This represents not just money lost but 25% of all freshwater consumed in the US and 4% of national energy. Meal planning, proper storage, and leftover reinvention can cut waste by 50-75%. The EPA estimates that reducing food waste is the #3 most effective climate solution after reducing fossil fuel use. A household that cuts waste from 30% to 15% saves ~$800/year and ~1,200 kg CO₂e annually — equivalent to taking one car off the road.'
}

export default calcDef
