import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ annualIncomeGoal: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), billableWeeks: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), hoursPerWeekBillable: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), overheadPercent: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0'), taxRatePercent: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0') }),
  fields: [
    { name: 'annualIncomeGoal', label: 'Annual Income Goal ($)', type: 'number', min: 10000, step: '5000' },
    { name: 'billableWeeks', label: 'Billable Weeks per Year', type: 'number', min: 1, max: 52, step: '1' },
    { name: 'hoursPerWeekBillable', label: 'Billable Hours per Week', type: 'number', min: 1, step: '1' },
    { name: 'overheadPercent', label: 'Overhead (% of Revenue)', type: 'number', min: 0, max: 60, step: '5' },
    { name: 'taxRatePercent', label: 'Tax Rate (%)', type: 'number', min: 0, max: 50, step: '1' },
  ],
  defaults: { annualIncomeGoal: '80000', billableWeeks: '48', hoursPerWeekBillable: '25', overheadPercent: '20', taxRatePercent: '30' },
  presets: [
    { label: 'Creative Freelancer (Design/Writing)', values: { annualIncomeGoal: '65000', billableWeeks: '47', hoursPerWeekBillable: '20', overheadPercent: '15', taxRatePercent: '25' } },
    { label: 'Tech Contractor (Dev/Consulting)', values: { annualIncomeGoal: '120000', billableWeeks: '48', hoursPerWeekBillable: '30', overheadPercent: '25', taxRatePercent: '32' } },
    { label: 'Coach / Consultant (Part-Time)', values: { annualIncomeGoal: '50000', billableWeeks: '40', hoursPerWeekBillable: '15', overheadPercent: '10', taxRatePercent: '22' } },
    { label: 'Full-Time Agency Owner', values: { annualIncomeGoal: '200000', billableWeeks: '50', hoursPerWeekBillable: '35', overheadPercent: '35', taxRatePercent: '37' } },
  ],
  compute: (v) => {
    const totalBillableHours = v.billableWeeks * v.hoursPerWeekBillable
    const revenueNeeded = v.annualIncomeGoal / (1 - v.taxRatePercent / 100) / (1 - v.overheadPercent / 100)
    const hourlyRate = revenueNeeded / totalBillableHours
    const weeklyRate = hourlyRate * v.hoursPerWeekBillable
    const monthlyRevenue = revenueNeeded / 12
    const project10Hr = hourlyRate * 10
    const project40Hr = hourlyRate * 40
    const grossIncome = hourlyRate * totalBillableHours
    const afterTaxIncome = grossIncome * (1 - v.taxRatePercent / 100) * (1 - v.overheadPercent / 100)
    const utilPct = (v.hoursPerWeekBillable / 40) * 100
    return { result: hourlyRate, label: 'Minimum Hourly Rate', unit: '$/hr', steps: [{ label: 'Income Goal (after-tax)', value: `$${v.annualIncomeGoal.toFixed(0)}` }, { label: 'Tax Load', value: `${v.taxRatePercent}% = $${(v.annualIncomeGoal / (1 - v.taxRatePercent / 100) - v.annualIncomeGoal).toFixed(0)} extra` }, { label: 'Overhead Load', value: `${v.overheadPercent}% = $${(revenueNeeded - v.annualIncomeGoal / (1 - v.taxRatePercent / 100)).toFixed(0)} extra` }, { label: 'Total Revenue Needed', value: `$${revenueNeeded.toFixed(0)}` }, { label: 'Billable Hours/Year', value: `${v.billableWeeks} weeks × ${v.hoursPerWeekBillable} hrs = ${totalBillableHours} hrs` }, { label: 'Hourly Rate', value: `$${hourlyRate.toFixed(2)}/hr` }, { label: 'Weekly Revenue Target', value: `$${weeklyRate.toFixed(2)}` }, { label: 'Monthly Revenue Target', value: `$${monthlyRevenue.toFixed(2)}` }] ,
    extras: [
      { label: 'The Pyramid of Freelance Costs', value: `$${revenueNeeded.toFixed(0)} total revenue needed. Breakdown: $${v.annualIncomeGoal.toFixed(0)} (${(v.annualIncomeGoal / revenueNeeded * 100).toFixed(0)}%) take-home + $${(v.annualIncomeGoal / (1 - v.taxRatePercent / 100) - v.annualIncomeGoal).toFixed(0)} (${(v.taxRatePercent).toFixed(0)}%) taxes + $${(revenueNeeded - v.annualIncomeGoal / (1 - v.taxRatePercent / 100)).toFixed(0)} (${v.overheadPercent.toFixed(0)}%) overhead. Many freelancers forget to multiply by taxes AND overhead — this calculator accounts for both. Rule of thumb: rate = desired hourly × 2-3× to cover taxes, overhead, and non-billable time. Your $${hourlyRate.toFixed(2)}/hr = ${(hourlyRate / (v.annualIncomeGoal / (v.billableWeeks * v.hoursPerWeekBillable))).toFixed(1)}× the base hourly.` },
      { label: 'Utilization & Non-Billable Time', value: `${v.hoursPerWeekBillable} billable hrs/week = ${utilPct.toFixed(0)}% utilization (of 40 hr week). Standard target: 60-75%. ${utilPct < 50 ? 'Low — only half your time is billable. Reduce admin/marketing or increase rates.' : utilPct < 70 ? 'Moderate — typical for established freelancers' : 'High — ' + (utilPct - 70).toFixed(0) + '% above typical. Risk of burnout; consider delegation or rate increase.'} Non-billable time ($${(40 - v.hoursPerWeekBillable).toFixed(0)} hrs/week) goes to: marketing (5-10 hrs), admin (3-5 hrs), professional dev (2-5 hrs), networking (2-4 hrs). Your $${hourlyRate.toFixed(2)}/hr effectively needs to cover 40 hours of your time, not ${v.hoursPerWeekBillable}.` },
      { label: 'Pricing Strategy: Hourly vs Value', value: `$${hourlyRate.toFixed(2)}/hr minimum. Value pricing: 2-5× this for outcome-based projects. A $${project40Hr.toFixed(0)} project (40 hrs) could be quoted at $${(project40Hr * 2).toFixed(0)}-$${(project40Hr * 4).toFixed(0)} if the value to client is clear. Retainer: $${weeklyRate.toFixed(0)}/week × ${v.billableWeeks} weeks = $${(weeklyRate * v.billableWeeks).toFixed(0)}/year. Monthly retainer: $${monthlyRevenue.toFixed(0)}. Retainers provide predictable income and reduce non-billable time by 15-25% (no proposal writing). Goal: convert 60-70% of clients to retainers.` },
      { label: 'Overhead Optimization', value: `${v.overheadPercent}% overhead = $${(revenueNeeded * v.overheadPercent / 100).toFixed(0)}/year. Common: coworking $200-500/mo, software $100-300/mo, insurance $100-300/mo, marketing $200-1000/mo, accounting $100-300/mo. Reducing overhead from ${v.overheadPercent}% to ${Math.max(10, v.overheadPercent - 5)}% saves $${(revenueNeeded * 0.05).toFixed(0)}/year — equivalent to raising your rate by $${((revenueNeeded * 0.05) / totalBillableHours).toFixed(2)}/hr. Use home office deduction ($${(revenueNeeded * 0.05).toFixed(0)}-$${(revenueNeeded * 0.1).toFixed(0)} saved), open source tools, and co-working only 2-3 days/week.` },
      { label: 'Tax Structure Comparison', value: `${v.taxRatePercent}% effective tax rate = ~$${(revenueNeeded * v.taxRatePercent / 100).toFixed(0)} taxes on $${revenueNeeded.toFixed(0)} revenue. LLC S-Corp: save ~$${(revenueNeeded * 0.02).toFixed(0)}-$${(revenueNeeded * 0.04).toFixed(0)} on self-employment tax ($${(revenueNeeded * 0.153 * (revenueNeeded > 137700 ? 137700 / revenueNeeded : 1)).toFixed(0)} SE tax if sole prop). Solo 401k: defer $${(Math.min(v.annualIncomeGoal, 69000) * 0.25).toFixed(0)}-$${Math.min(v.annualIncomeGoal, 69000).toFixed(0)} pre-tax. HSA: $4,150 individual / $8,300 family pre-tax. Quarterly estimated taxes: $${((revenueNeeded - (revenueNeeded * v.overheadPercent / 100)) * (v.taxRatePercent / 100) / 4).toFixed(0)}/quarter.` },
      { label: 'Growth & Rate Escalation Plan', value: `Your $${hourlyRate.toFixed(2)}/hr today. Yearly increases: 10% = $${(hourlyRate * 1.1).toFixed(2)} next year, $${(hourlyRate * 1.21).toFixed(2)} year 3, $${(hourlyRate * 1.33).toFixed(2)} year 4, $${(hourlyRate * 1.46).toFixed(2)} year 5. With same hours: $${(hourlyRate * 1.1 * totalBillableHours).toFixed(0)} → $${(hourlyRate * 1.46 * totalBillableHours).toFixed(0)} revenue in 5 years. Reduce weeks to 44 (more vacation): rate needs to be $${(revenueNeeded / (Math.max(1, v.billableWeeks - 4) * v.hoursPerWeekBillable)).toFixed(2)}/hr. Add specialization premium: niche skills command 20-50% more.` },
      { label: 'Project Pipeline & Cash Flow', value: `$${monthlyRevenue.toFixed(0)}/mo target. Pipeline needed: 3× monthly revenue in proposals = $${(monthlyRevenue * 3).toFixed(0)} active pipeline. Close rate 30-50%: submit $${(monthlyRevenue * 3 * (3)).toFixed(0)}-$${(monthlyRevenue * 3 * (3)).toFixed(0)} in proposals monthly. Average project $${project40Hr.toFixed(0)} at $${hourlyRate.toFixed(2)}/hr: need ${Math.ceil(v.annualIncomeGoal / project40Hr)} clients/year or ${Math.ceil(v.annualIncomeGoal / project40Hr / 12)} new clients/month. Retainer clients ($${monthlyRevenue.toFixed(0)}/mo each): need ${Math.ceil(v.annualIncomeGoal / (monthlyRevenue * 12))} retainer clients to hit target. Build 3-month cash reserve: $${(monthlyRevenue * 3).toFixed(0)}.` },
    ]}
  },
  description: 'Calculate your freelance hourly rate based on income goals, billable hours, overhead, and taxes. Includes utilization analysis, value-based pricing comparison, tax strategy, and multi-year growth projection.',
  formula: 'Rate = Income Goal ÷ (1 - Tax%) ÷ (1 - Overhead%) ÷ (Billable Weeks × Hours/Week) | Utilization % = Billable Hrs ÷ 40 × 100 | Monthly Revenue = (Rate × Total Hours) ÷ 12 | Gross Income = Rate × Total Hours',
  interpretation: 'Freelancers should bill 2-3× their desired hourly wage. Only 50-70% of working hours are billable — the rest goes to admin, marketing, and professional development. A $80,000 take-home target with 30% taxes and 20% overhead requires ~$150,000 in gross revenue — at 48 weeks × 25 billable hours = $125/hr minimum. The three levers to increase income: raise rates (10-15%/year), increase billable hours (optimize utilization), or reduce overhead. Most freelancers undercharge by 20-40% — this calculator ensures you cover all costs and hit your target net income.'
}

export default calcDef
