import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ roomLengthFt: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), roomWidthFt: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), sofaLength: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0'), tableLength: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0'), chairs: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0'), clearanceFt: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [
    { name: 'roomLengthFt', label: 'Room Length (ft)', type: 'number', min: 5, step: '1' },
    { name: 'roomWidthFt', label: 'Room Width (ft)', type: 'number', min: 5, step: '1' },
    { name: 'sofaLength', label: 'Sofa Length (ft)', type: 'number', min: 0, step: '1' },
    { name: 'tableLength', label: 'Coffee/Table Length (ft)', type: 'number', min: 0, step: '1' },
    { name: 'chairs', label: 'Number of Chairs', type: 'number', min: 0, step: '1' },
    { name: 'clearanceFt', label: 'Walkway Clearance (ft)', type: 'number', min: 1.5, step: '0.5' },
  ],
  defaults: { roomLengthFt: '18', roomWidthFt: '14', sofaLength: '7', tableLength: '4', chairs: '4', clearanceFt: '3' },
  presets: [
    { label: 'Small Living Room (12×14)', values: { roomLengthFt: '14', roomWidthFt: '12', sofaLength: '6', tableLength: '3', chairs: '2', clearanceFt: '2.5' } },
    { label: 'Open Concept (20×16)', values: { roomLengthFt: '20', roomWidthFt: '16', sofaLength: '8', tableLength: '5', chairs: '6', clearanceFt: '3' } },
    { label: 'Dining Room Only Setup', values: { roomLengthFt: '14', roomWidthFt: '12', sofaLength: '0', tableLength: '6', chairs: '6', clearanceFt: '3.5' } },
    { label: 'Minimalist Studio', values: { roomLengthFt: '16', roomWidthFt: '10', sofaLength: '5', tableLength: '2', chairs: '1', clearanceFt: '2' } },
  ],
  compute: (v) => {
    const roomArea = v.roomLengthFt * v.roomWidthFt
    const sofaArea = v.sofaLength * 3
    const tableArea = v.tableLength * 2.5
    const chairsArea = v.chairs * 2.5
    const furnitureTotal = sofaArea + tableArea + chairsArea
    const walkwayArea = (v.roomLengthFt + v.roomWidthFt) * 2 * v.clearanceFt
    const usableArea = roomArea - walkwayArea
    const spaceUsedPct = (furnitureTotal / roomArea) * 100
    const openArea = roomArea - furnitureTotal - walkwayArea
    const sofaSeats = v.sofaLength > 0 ? Math.floor(v.sofaLength / 2.5) * 2 : 0
    const totalSeats = sofaSeats + v.chairs * 1
    const seatsPerSqFt = roomArea > 0 ? totalSeats / roomArea : 0
    return { result: spaceUsedPct, label: 'Floor Space Used', unit: '%', steps: [{ label: 'Room Dimensions', value: `${v.roomLengthFt} × ${v.roomWidthFt} ft` }, { label: 'Room Area', value: `${roomArea.toFixed(1)} sq ft` }, { label: 'Furniture Footprint', value: `${furnitureTotal.toFixed(1)} sq ft (sofa ${sofaArea}, table ${tableArea}, chairs ${chairsArea})` }, { label: 'Walkway Clearance Space', value: `${walkwayArea.toFixed(1)} sq ft` }, { label: 'Open Floor Space', value: `${Math.max(0, openArea).toFixed(1)} sq ft` }, { label: 'Furniture Coverage', value: `${spaceUsedPct.toFixed(0)}% of floor` }, { label: 'Seating Capacity', value: `${totalSeats} seats (sofa ${sofaSeats} + ${v.chairs} chairs)` }, { label: 'Seats per 100 sq ft', value: `${(seatsPerSqFt * 100).toFixed(1)}` }] ,
    extras: [
      { label: 'Walkway Clearance Standards', value: `${v.clearanceFt} ft walkways. Standards: main walkway 3-4 ft (36-48 in), secondary 2-3 ft (24-36 in), between coffee table & sofa 1.5-2 ft (18-24 in), dining table clearance 3.5-4 ft (42-48 in) for chairs + walking. Your ${v.clearanceFt} ft = ${v.clearanceFt >= 3.5 ? 'generous — comfortable for a dining setup' : v.clearanceFt >= 3 ? 'adequate — standard living room clearance' : v.clearanceFt >= 2.5 ? 'tight — okay for secondary paths' : 'minimal — consider reducing or rearranging for comfort'}. For a ${v.roomLengthFt}×${v.roomWidthFt} room, ${v.clearanceFt} ft clearance uses ${walkwayArea.toFixed(0)} sq ft (${(walkwayArea / roomArea * 100).toFixed(0)}% of room).` },
      { label: 'Furniture-to-Room Balance', value: `${spaceUsedPct.toFixed(0)}% furniture coverage. Design ideal: 30-50%. ${spaceUsedPct < 30 ? spaceUsedPct < 20 ? 'Under-furnished — room may feel empty. Add area rug, larger sofa, or accent pieces. Consider multi-functional furniture like ottomans with storage.' : 'Cozy — some additional pieces could warm the space. A small accent chair or side table would bring it to ideal range.' : spaceUsedPct <= 50 ? 'Perfect balance — visually pleasing and functional ✓' : spaceUsedPct <= 60 ? 'Slightly crowded — consider removing 1-2 pieces or choosing slimmer profiles' : 'Overcrowded — ' + (spaceUsedPct - 50).toFixed(0) + '% over ideal. Remove non-essential pieces or downsize. Floating furniture away from walls creates more breathing room.'} Target: ${(30 + (50 - 30) / 2).toFixed(0)}% for a balanced look.` },
      { label: 'Sofa Size & Configuration', value: `${v.sofaLength} ft sofa = ${sofaSeats} seats (${v.sofaLength} ft ÷ 2.5 ft/person). Loveseat (4-5 ft): 2 seats. 3-seater (6-7 ft): ${v.sofaLength >= 6 ? 'standard 3-person' : 'tight 3-person'}. Sectional (8-12 ft): 5-8 seats. Your ${v.sofaLength} ft = ${v.sofaLength < 5 ? 'loveseat/small' : v.sofaLength < 7 ? '3-seater' : v.sofaLength < 9 ? 'large sofa/small sectional' : 'large sectional'} at ${sofaSeats} seats. Distance from coffee table: 14-18 in for easy reach. Chaise lounge adds 3 ft but reduces walkway by ${v.clearanceFt} ft — ${v.clearanceFt < 2.5 ? 'not recommended' : 'okay'}.` },
      { label: 'Coffee Table & Dining Table Sizing', value: `Table ${v.tableLength} ft = ${parseFloat(v.tableLength) >= 4 ? 'full-size' : 'accent/small'} piece. Coffee table: 30-60 in long, 12-18 in from sofa. Your table (${v.tableLength} ft = ${(v.tableLength * 12).toFixed(0)} in) is ${v.tableLength > 4 ? 'generous for a coffee table or small dining' : 'appropriate for a coffee table'}. Dining: allow 2 ft per person + 2 ft ends. Table ${v.tableLength} ft seats ${Math.floor((v.tableLength * 12 - 24) / 24)}-${Math.floor((v.tableLength * 12) / 24)} people. If used for dining, table + ${v.chairs} chairs × ${Math.max(0, 2.5)} sq ft each + walkway = ${v.chairs * 2.5 + v.tableLength * 2.5 + v.clearanceFt * (v.roomLengthFt + v.roomWidthFt) * 2 < roomArea ? 'fits ✓' : 'tight — need more clearance'}.` },
      { label: 'Visual Weight & Layout Balance', value: `Room ${v.roomLengthFt}×${v.roomWidthFt} ft = ${roomArea.toFixed(0)} sq ft. Furniture weight: sofa (heaviest) + table + ${v.chairs} chairs. Arrange focal point (TV/fireplace on long wall). Symmetrical: sofa centered, chairs flanking. Asymmetrical: sofa offset, chairs grouped. Rule: largest piece (sofa) on longest wall. For ${v.roomLengthFt}×${v.roomWidthFt}: ${v.roomLengthFt >= v.roomWidthFt ? 'sofa across ' + v.roomWidthFt + ' ft wall works well' : 'consider diagonal layout to break up narrow space'}. Floating furniture 6-12 in from walls creates illusion of more space in a ${roomArea} sq ft room.` },
      { label: 'Lighting & Flow Zones', value: `${roomArea.toFixed(0)} sq ft needs: ambient (overhead 60-100W equiv), task (reading lamps ~${totalSeats} sources), accent (art/cabinet). Zone planning: conversation zone (sofa + ${v.chairs} chairs = ${totalSeats} seats), media zone (${v.tableLength} ft table for drinks), circulation (${walkwayArea.toFixed(0)} sq ft walkway = ${(walkwayArea / roomArea * 100).toFixed(0)}% of room). Path from door to seating: minimum ${v.clearanceFt} ft. A well-lit room with ${roomArea} sq ft needs ${Math.ceil(roomArea / 200)} overhead fixtures + ${totalSeats} task lights.` },
      { label: 'Traffic Flow & Ergonomics', value: `Walkways ${v.clearanceFt} ft = ${v.clearanceFt * 12} in. Standards: sofa to coffee table 14-18 in, dining chair pull-out 36-48 in, TV viewing 7-10 ft (55-85 in TV). Your ${v.roomLengthFt}×${v.roomWidthFt} ft = ${(v.roomLengthFt * 12).toFixed(0)}×${(v.roomWidthFt * 12).toFixed(0)} in. Traffic lanes: primary (door to seating) needs ${v.clearanceFt >= 3 ? '✓' : '✗ — minimum 36 in'}. Secondary (around seating areas): ${v.clearanceFt >= 2.5 ? '✓' : '✗ — minimum 30 in'}. Reach to table from sofa: ${v.tableLength > 0 ? v.sofaLength > 0 ? '14-18 in ideal' : 'n/a' : 'no table to consider'}. Door swing radius: 36 in — ${v.clearanceFt >= 3 ? 'no conflict' : 'check door swing path'}.` },
      { label: 'Arrangement Layout Types', value: `For ${v.roomLengthFt}×${v.roomWidthFt} ft with ${v.sofaLength} ft sofa + ${v.chairs} chairs: try L-shape (sofa on long wall, chairs perpendicular) — works in ${v.roomWidthFt >= 12 ? 'any wide room' : 'narrow rooms with caution'}. U-shape (sofa + chairs + ottoman) — needs ${(v.sofaLength + v.chairs * 2)} ft of furniture perimeter. Parallel (two sofas facing) — social but needs ${v.roomWidthFt >= 14 ? 'adequate width' : 'tight'}. Sectional with chaise — needs corner, uses ${v.sofaLength + 3} ft on two walls. Floating (all furniture away from walls) — visually expands ${v.roomLengthFt}×${v.roomWidthFt} room. Best for your dimensions: ${v.roomWidthFt >= 14 ? 'L-shape or parallel' : v.roomWidthFt >= 12 ? 'L-shape or floating' : 'single-wall or L-shape'}.` },
    ]} },
  description: 'Plan your furniture arrangement by calculating floor space usage, walkway clearance, and furniture footprint in any room. Includes seating capacity analysis, visual weight balance, and layout configuration recommendations.',
  formula: 'Space Used % = Furniture Area / Room Area × 100 | Furniture Area = (Sofa × 3) + (Table × 2.5) + (Chairs × 2.5) | Walkway = 2 × (L + W) × Clearance | Seats = (Sofa Length ÷ 2.5 × 2) + Chairs | Seats per 100 sq ft = Total Seats ÷ Room Area × 100',
  interpretation: 'Keep 18-36 in walkways for comfortable movement. Sofa: 6-8 ft (3-seater). Coffee table: 3-4 ft from sofa. Allow 2 ft per dining chair when pulled out. Ideal furniture coverage is 30-50% of floor area — over 60% feels cluttered, under 20% feels empty. Seating capacity should match room purpose: a living room needs 1 seat per 40-60 sq ft, while a family room can be more dense. Always leave at least 36 in for main pathways and 24 in for secondary paths. Measure furniture arms, not just seat width, when planning layout.'
}

export default calcDef
