import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ hoursWorked: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), hourlyRate: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), expenses: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0'), taxRate: z.string().min(1).refine(v => parseFloat(v) >= 0, '>=0') }),
  fields: [
    { name: 'hoursWorked', label: 'Hours Worked', type: 'number', min: 1, step: '1' },
    { name: 'hourlyRate', label: 'Hourly Rate ($)', type: 'number', min: 1, step: '5' },
    { name: 'expenses', label: 'Business Expenses ($)', type: 'number', min: 0, step: '10' },
    { name: 'taxRate', label: 'Self-Employment Tax (%)', type: 'number', min: 0, max: 50, step: '1' },
  ],
  defaults: { hoursWorked: '20', hourlyRate: '25', expenses: '50', taxRate: '15.3' },
  presets: [
    { label: 'Rideshare Driver (weekly)', values: { hoursWorked: '25', hourlyRate: '18', expenses: '80', taxRate: '15.3' } },
    { label: 'Freelance Designer (monthly)', values: { hoursWorked: '80', hourlyRate: '65', expenses: '200', taxRate: '15.3' } },
    { label: 'TaskRabbit Handyman', values: { hoursWorked: '15', hourlyRate: '35', expenses: '40', taxRate: '15.3' } },
    { label: 'Dog Walker / Sitter', values: { hoursWorked: '30', hourlyRate: '20', expenses: '30', taxRate: '15.3' } },
  ],
  compute: (v) => { const h = parseFloat(v.hoursWorked)||0; const r = parseFloat(v.hourlyRate)||0; const e = parseFloat(v.expenses)||0; const tr = parseFloat(v.taxRate)||0; const gross = h * r; const netBeforeTax = gross - e; const tax = netBeforeTax * (tr / 100); const net = netBeforeTax - tax; const effectiveHourly = net / h; const expensePct = (e / gross) * 100; const taxPct = (tax / gross) * 100; const netPct = (net / gross) * 100; const weeklyFullTime = net * 40 / h; const annualProjected = net * 50; return { result: net, label: 'Net Pay', unit: '$', steps: [{ label: 'Gross Pay', value: `$${gross.toFixed(2)} (${h} hrs × $${r.toFixed(2)}/hr)` }, { label: 'Business Expenses', value: `-$${e.toFixed(2)} (${expensePct.toFixed(1)}% of gross)` }, { label: 'Taxable Income', value: `$${netBeforeTax.toFixed(2)}` }, { label: 'Self-Employment Tax', value: `-$${tax.toFixed(2)} (${taxPct.toFixed(1)}% of gross)` }, { label: 'Net Pay (take-home)', value: `$${net.toFixed(2)} (${netPct.toFixed(1)}% of gross)` }, { label: 'Effective Hourly Rate', value: `$${effectiveHourly.toFixed(2)}/hr` }, { label: 'Projected Annual (50 wk)', value: `$${annualProjected.toFixed(0)}` }, { label: 'Full-Time Equivalent', value: `$${weeklyFullTime.toFixed(2)}/wk at 40 hrs` }] ,
    extras: [
      { label: 'Expense Deduction Breakdown', value: `Your $${e.toFixed(2)} in expenses = ${expensePct.toFixed(1)}% of gross. Common gig deductions: mileage ($0.655/mi 2024), phone/internet (${(e * 0.2).toFixed(0)}% prorated), supplies, professional development, health insurance premiums, retirement contributions (SEP IRA up to 25% of net). Each $1 in deductions saves $${(tr / 100).toFixed(2)} in taxes. You could potentially deduct more — consult Schedule C guidelines.` },
      { label: 'True Hourly Rate: Gigs vs W-2', value: `Effective: $${effectiveHourly.toFixed(2)}/hr net. For a W-2 job at $${r.toFixed(2)}/hr, employer pays 7.65% FICA (your W-2 equivalent cost to employer: $${(r * 1.0765).toFixed(2)}/hr). After W-2 taxes (7.65% employee FICA), W-2 net = ~$${(r * (1 - 0.0765 - 0.12)).toFixed(2)}/hr (est 12% bracket). Your $${effectiveHourly.toFixed(2)}/hr net gig rate is $${(effectiveHourly > r * 0.8 ? 'better' : 'worse')} than W-2 equivalent when accounting for flexibility.` },
      { label: 'Quarterly Tax Payment Guidance', value: `On this $${gross.toFixed(0)} gross, estimated quarterly tax: ~$${(tax / 4).toFixed(0)}/quarter (if this is a monthly figure: $${(tax * 3 / 4).toFixed(0)}/quarter). IRS requires quarterly payments if you expect to owe >$1,000. Deadlines: Apr 15, Jun 15, Sep 15, Jan 15. Use Form 1040-ES. Missing deadlines adds 0.5% penalty per month. Set aside ${tr.toFixed(0)}% of every gig payment immediately in a separate account.` },
      { label: 'Retirement Savings Options for Gig Workers', value: `SEP IRA: contribute up to 25% of net self-employment income (max $69,000 for 2024). Solo 401(k): up to $23,000 employee + 25% employer (total ~$69,000). Traditional IRA: $7,000 ($8,000 if 50+). On projected $${annualProjected.toFixed(0)}/yr net: a 15% SEP IRA contribution = $${(annualProjected * 0.15).toFixed(0)}/yr, saving $${(annualProjected * 0.15 * tr / 100).toFixed(0)} in taxes annually.` },
      { label: 'Health Insurance Deduction', value: `Self-employed individuals can deduct 100% of health insurance premiums (Medicare, dental, long-term care) from AGI (not just Schedule C). Avg monthly premium for self-employed: $450-700/individual, $1,200-2,000/family. Deducting $${(6000 / 12).toFixed(0)}/mo = $${6000}/yr reduces taxable income by same amount — saving $${(6000 * tr / 100).toFixed(0)}/yr in taxes. Use the marketplace (healthcare.gov) for potentially subsidized plans based on your net income.` },
      { label: 'Gig Income Stability & Diversification', value: `Relying on one gig platform is risky — average gig worker uses 2-3 platforms. Diversify: rideshare + deliveries + TaskRabbit; or Upwork + Fiverr + direct clients. At $${r.toFixed(2)}/hr, losing one platform could cut income 30-50%. Build an emergency fund of 3-6 months of your $${(annualProjected / 12).toFixed(0)}/mo expenses. Save 3 months = $${((annualProjected / 12) * 3).toFixed(0)}.` },
      { label: 'Mileage vs Actual Vehicle Expenses', value: `Standard mileage deduction 2024: $0.655/mi vs actual expenses (gas, insurance, maintenance, depreciation, loan interest). For rideshare/delivery: mileage usually wins (avg cost ~$0.50/mi real, so $0.655 gives extra deduction). On $${e.toFixed(0)} expenses claimed, if you drive ${(e / 0.655).toFixed(0)} mi, that's $${(e * 1).toFixed(0)} additional deduction. Track every mile with an app (Stride, MileIQ).` },
      { label: 'Tax Bracket & Withholding Strategy', value: `At projected $${annualProjected.toFixed(0)}/yr net, you're in the ${annualProjected < 11600 ? '0% (standard deduction covers)' : annualProjected < 47150 ? '12%' : annualProjected < 100525 ? '22%' : '24%+'} federal bracket. Self-employment tax: 15.3% on first $168,600 (2024) of net earnings. Combined effective rate: ~${(tr + 10).toFixed(0)}-${(tr + 22).toFixed(0)}%. Strategy: pay quarterly estimates, max retirement contributions to lower AGI, consider S-corp election if net >$60,000 (saves ~2-4% on SE tax).` },
    ]} },
  description: 'Calculate net gig economy pay after business expenses and self-employment taxes. Get effective hourly rate, annual projections, expense-to-income ratios, and full-time wage equivalents. Includes tax strategy, retirement planning, and expense optimization insights.',
  formula: 'Net Pay = (Hours × Rate) − Expenses − ((Gross − Expenses) × Tax Rate) | Effective Hourly = Net ÷ Hours | Expense Ratio = Expenses ÷ Gross × 100 | Net Retention = Net ÷ Gross × 100',
  interpretation: 'Self-employment tax is 15.3% (Social Security + Medicare) on net earnings. Deduct legitimate business expenses (mileage at $0.655/mi, home office, supplies, phone, health insurance premiums) to lower taxable income — each $1 deducted saves your marginal tax rate. Set aside 25-30% of gross for taxes in a separate account. Max SEP IRA ($69,000 or 25% of net) to reduce taxable income. Pay quarterly estimated taxes to avoid penalties. Your effective hourly rate after expenses and taxes is typically 40-60% of your gross hourly rate.'
}

export default calcDef
