import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ weeks: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), weeklyBudget: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), householdSize: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [
    { name: 'weeks', label: 'Number of Weeks', type: 'number', min: 1, step: '1' },
    { name: 'weeklyBudget', label: 'Weekly Budget ($)', type: 'number', min: 10, step: '10' },
    { name: 'householdSize', label: 'Household Size', type: 'number', min: 1, step: '1' },
  ],
  defaults: { weeks: '4', weeklyBudget: '100', householdSize: '3' },
  presets: [
    { label: 'Monthly Budget (4 wks)', values: { weeks: '4', weeklyBudget: '100', householdSize: '2' } },
    { label: 'Biweekly Shopping Trip', values: { weeks: '2', weeklyBudget: '120', householdSize: '4' } },
    { label: 'Semester Meal Plan', values: { weeks: '16', weeklyBudget: '65', householdSize: '1' } },
    { label: 'Annual Grocery Budget', values: { weeks: '52', weeklyBudget: '80', householdSize: '3' } },
  ],
  compute: (v) => { const w = parseFloat(v.weeks)||0; const wb = parseFloat(v.weeklyBudget)||0; const hs = parseFloat(v.householdSize)||0; const total = w * wb * hs; const perPerson = wb * w; const weeklyHousehold = wb * hs; const perPersonPerDay = wb / 7; const monthlyProj = weeklyHousehold * 4.33; const annualProj = weeklyHousehold * 52; const perPersonAnnual = wb * 52; const pctIncome = annualProj / 60000 * 100; return { result: total, label: 'Total Grocery Budget', unit: '$', steps: [{ label: 'Time Period', value: `${w} weeks` }, { label: 'Weekly Budget per Person', value: `$${wb.toFixed(2)}` }, { label: 'Household Size', value: `${hs} people` }, { label: 'Weekly Household Budget', value: `$${weeklyHousehold.toFixed(2)}` }, { label: 'Total for Period', value: `$${total.toFixed(2)}` }, { label: 'Per Person for Period', value: `$${perPerson.toFixed(2)}` }, { label: 'Monthly Equivalent', value: `$${monthlyProj.toFixed(2)}` }, { label: '% of $60k Income', value: `${pctIncome.toFixed(1)}%` }] ,
    extras: [
      { label: 'Budget by Period Comparison', value: `Over ${w} weeks: $${total.toFixed(0)} total = $${(total / w).toFixed(0)}/wk household = $${(total / w / hs).toFixed(0)}/person/week. For perspective: a month (4.33 wk) would be $${monthlyProj.toFixed(0)}, a year (52 wk) would be $${annualProj.toFixed(0)}. If this is a ${w >= 52 ? 'long-term' : w >= 12 ? 'medium-term' : 'short-term'} plan, review price changes every 3-6 months.` },
      { label: 'Per-Person Daily Allowance', value: `$${wb.toFixed(2)}/person/week = $${perPersonPerDay.toFixed(2)}/person/day across 3 meals + snacks. That's ~$${(perPersonPerDay / 3).toFixed(2)} per meal per person. ${perPersonPerDay < 8 ? 'This is a thrifty budget — focus on rice, beans, seasonal produce, and bulk proteins.' : perPersonPerDay < 12 ? 'Moderate budget — mix of fresh and budget-friendly staples.' : 'Liberal budget — plenty of room for organic, prepped foods, and treats.'}` },
      { label: 'Meal Cost Breakdown Per Person', value: `At $${wb.toFixed(2)}/person/week = $${perPersonPerDay.toFixed(2)}/person/day: Breakfast ~$${(perPersonPerDay * 0.2).toFixed(2)}, Lunch ~$${(perPersonPerDay * 0.3).toFixed(2)}, Dinner ~$${(perPersonPerDay * 0.4).toFixed(2)}, Snacks ~$${(perPersonPerDay * 0.1).toFixed(2)}. Compare: average restaurant lunch $12-15, dinner $20-30. Cooking at home saves $${(12 - perPersonPerDay * 0.3).toFixed(0)}-${(30 - perPersonPerDay * 0.4).toFixed(0)} per meal per person.` },
      { label: 'Bulk Buying & Stock-Up Strategy', value: `Your $${weeklyHousehold.toFixed(2)}/wk household budget. Buying staples in bulk saves 10-30%: rice (25-lb bag: $0.50/lb vs $1.00/lb boxed), beans (10-lb: $0.80/lb vs $1.50/lb canned), oats (10-lb: $0.60/lb vs $1.20/lb boxed). With ${hs} people, bulk saves ~$${(weeklyHousehold * 0.15 * w).toFixed(0)} over ${w} weeks. Invest in airtight containers for bulk storage — prevents pests and maintains freshness.` },
      { label: 'Seasonal Shopping Calendar', value: `Produce prices vary 30-50% by season. Plan your $${wb.toFixed(2)}/person/week around what's in-season: Summer: berries, tomatoes, corn, zucchini (cheapest). Fall: squash, apples, sweet potatoes, greens. Winter: citrus, root veg, cabbage (imported = expensive). Spring: asparagus, peas, strawberries, artichokes. Shopping farmers markets in peak season saves $${(wb * 0.15).toFixed(0)}-${(wb * 0.25).toFixed(0)}/person/week vs grocery store.` },
      { label: 'Store Brand vs Name Brand Savings', value: `Store brands save 15-25% vs name brands on identical ingredients. On your $${weeklyHousehold.toFixed(0)}/wk household budget: switching 50% of purchases to store brand saves $${(weeklyHousehold * 0.1).toFixed(0)}-${(weeklyHousehold * 0.125).toFixed(0)}/wk = $${(weeklyHousehold * 0.1125 * w).toFixed(0)} over ${w} weeks. Most store brands are manufactured by the same companies as name brands (same product, different label).` },
      { label: 'Emergency Buffer & Price Fluctuations', value: `Adding 10% buffer for price spikes/splurges: $${(total * 0.1).toFixed(0)} extra = $${(total * 1.1).toFixed(0)} total. Food prices fluctuate 5-15% throughout the year (holiday spikes, weather events). A 10% month-to-month swing on your $${weeklyHousehold.toFixed(0)}/wk = $${(weeklyHousehold * 0.1).toFixed(0)} variation. Keep $50-100 in your grocery fund for unexpected needs (birthday party, potluck, sick day comfort food delivery).` },
      { label: 'Tracking & Adjustment System', value: `Track actual spend vs your $${weeklyHousehold.toFixed(0)}/wk budget weekly. Use: envelope system ($${weeklyHousehold.toFixed(0)} cash/wk = visual limit), spreadsheet, or budgeting app (YNAB, Mint, EveryDollar). If you overspend one week by 20% ($${(weeklyHousehold * 0.2).toFixed(0)}), trim 20% the next. After ${w} weeks, review: adjust your $${wb.toFixed(0)}/person/week based on actual spending — 80% accuracy is good; adjust mid-period for better precision.` },
    ]} },
  description: 'Plan your grocery budget over any time period (weekly, monthly, semester, annual) with per-person and per-household breakdowns. Includes meal cost analysis, bulk buying strategy, seasonal shopping calendar, store brand savings, and weekly tracking system.',
  formula: 'Total Period Budget = Weeks × Weekly Budget per Person × Household Size | Weekly Household = Budget per Person × Size | Per Person Period = Budget per Person × Weeks | Monthly Projection = Weekly Household × 4.33 | Annual Projection = Weekly Household × 52',
  interpretation: 'USDA moderate plan: $80-100/person/week. Store brands save 15-25% vs name brands. Bulk buying rice, beans, oats saves 10-30%. Seasonal produce costs 30-50% less than out-of-season. Adding 10% buffer for price fluctuations is recommended. Track weekly and adjust: a 20% overspend one week should be offset the next week. Food inflation at 5-8%/yr means budgets need annual recalibration.'
}

export default calcDef
