import { z } from 'zod'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
  schema: z.object({ initialValue: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), finalValue: z.string().min(1).refine(v => parseFloat(v) > 0, '>0'), years: z.string().min(1).refine(v => parseFloat(v) > 0, '>0') }),
  fields: [
    { name: 'initialValue', label: 'Initial Value', type: 'number', min: 1, step: '100' },
    { name: 'finalValue', label: 'Final Value', type: 'number', min: 1, step: '100' },
    { name: 'years', label: 'Time Period (years)', type: 'number', min: 0.5, step: '1' },
  ],
  defaults: { initialValue: '1000', finalValue: '2000', years: '5' },
  presets: [
    { label: 'Stock Investment (S&P 500 avg)', values: { initialValue: '10000', finalValue: '19500', years: '10' } },
    { label: 'Small Business Revenue Growth', values: { initialValue: '50000', finalValue: '150000', years: '3' } },
    { label: 'Real Estate Appreciation', values: { initialValue: '300000', finalValue: '450000', years: '10' } },
    { label: 'Portfolio Doubled in 7 Years', values: { initialValue: '25000', finalValue: '50000', years: '7' } },
  ],
  compute: (v) => { const iv = parseFloat(v.initialValue)||0; const fv = parseFloat(v.finalValue)||0; const y = parseFloat(v.years)||0; const totalGrowth = ((fv - iv) / iv) * 100; const cagr = iv > 0 && y > 0 ? (Math.pow(fv / iv, 1 / y) - 1) * 100 : 0; const annualAbsolute = (fv - iv) / y; const multiFactor = fv / iv; const doublingYears = cagr > 0 ? 72 / cagr : 0; const futureValue10yr = iv * Math.pow(1 + cagr / 100, 10); const monthlyAbsolute = annualAbsolute / 12; const benchmarkSP500 = cagr - 10; return { result: cagr, label: 'CAGR', unit: '%', steps: [{ label: 'Initial Value', value: `$${iv.toFixed(2)}` }, { label: 'Final Value', value: `$${fv.toFixed(2)}` }, { label: 'Time Period', value: `${y} yrs` }, { label: 'Total Growth', value: `${totalGrowth.toFixed(1)}%` }, { label: 'CAGR (Annualized)', value: `${cagr.toFixed(2)}%` }, { label: 'Growth Multiple', value: `${multiFactor.toFixed(2)}×` }, { label: 'Rule of 72 (double time)', value: `${doublingYears.toFixed(1)} yrs at this CAGR` }, { label: 'Projected at 10 Yrs', value: `$${futureValue10yr.toFixed(0)} if CAGR continues` }] ,
    extras: [
      { label: 'CAGR vs Average Return — Critical Difference', value: `CAGR: ${cagr.toFixed(2)}% (geometric mean). Average annual return: ${(totalGrowth / y).toFixed(2)}% (arithmetic mean). These differ when returns vary year to year. CAGR is always ≤ arithmetic mean due to volatility drag. Example: +50% then −50% = 0% total (CAGR 0%), but average return = 0%. CAGR is the honest measure of what you actually earned.` },
      { label: 'Rule of 72: Doubling Time', value: `At ${cagr.toFixed(2)}% CAGR, your investment doubles every ${doublingYears.toFixed(1)} years (72 ÷ ${cagr.toFixed(2)} = ${doublingYears.toFixed(1)}). To double in 10 years, you need 7.2% CAGR. In 5 years: 14.4% CAGR. Historical S&P 500 CAGR (~10%): doubles every 7.2 years. Your ${cagr.toFixed(2)}% CAGR would turn $${iv.toFixed(0)} into $${(iv * Math.pow(2, Math.floor(y / doublingYears))).toFixed(0)} after ${Math.floor(y / doublingYears) * Math.round(doublingYears)} years (${Math.floor(y / doublingYears)} doubling periods).` },
      { label: 'Real vs Nominal Growth', value: `Your CAGR: ${cagr.toFixed(2)}% nominal. With 3% avg inflation, real CAGR = ${(cagr - 3).toFixed(2)}%. At ${cagr.toFixed(2)}% nominal over ${y} years, $${iv.toFixed(0)} grew to $${fv.toFixed(0)}. After inflation: purchasing power = $${(fv / Math.pow(1.03, y)).toFixed(0)} in today's dollars. Real total growth: ${(((fv / Math.pow(1.03, y)) / iv) * 100 - 100).toFixed(1)}% vs nominal ${totalGrowth.toFixed(1)}%.` },
      { label: 'Compounding Frequency Impact', value: `CAGR assumes annual compounding. If your returns compound: quarterly: effective annual = ${(Math.pow(1 + cagr / 100 / 4, 4) - 1).toFixed(2)}% vs ${cagr.toFixed(2)}% annually. Over ${y} years: quarterly compounding = $${(iv * Math.pow(1 + cagr / 100 / 4, 4 * y)).toFixed(0)} vs $${fv.toFixed(0)} annual — difference of $${(iv * Math.pow(1 + cagr / 100 / 4, 4 * y) - fv).toFixed(0)}. More frequent compounding = higher effective return (but same CAGR formula apples-to-apples).` },
      { label: 'Benchmark Comparison', value: `Your ${cagr.toFixed(2)}% CAGR over ${y} years. S&P 500 (1926-2024): ~10% CAGR long-term. S&P 500 last 10 years: ~12-13% CAGR. 10-year Treasury: ~3-5% CAGR. Inflation: ~3% CAGR. Your return is ${benchmarkSP500 > 2 ? `${benchmarkSP500.toFixed(1)}% above S&P 500 avg` : benchmarkSP500 > -2 ? 'roughly matching S&P 500' : `${Math.abs(benchmarkSP500).toFixed(1)}% below S&P 500 avg`}. ${cagr > 25 ? 'Unsustainable long-term — likely includes luck or leverage.' : cagr > 15 ? 'Excellent — top-quartile performance.' : cagr > 8 ? 'Good — solid market-like returns.' : cagr > 4 ? 'Moderate — beat inflation.' : 'Below historical market avg — consider index funds.'}` },
      { label: 'Volatility & Risk Consideration', value: `CAGR of ${cagr.toFixed(2)}% doesn't show the journey. A fund could have: +30%, +30%, −20% = CAGR ~11.3% (same as steady 11.3% each year). But max drawdown of 20% means you need +25% to recover. Higher CAGR usually means higher volatility. Dicey fact: a 50% loss requires 100% gain to break even. Sequence of returns matters — especially if withdrawing during down years (retirement).` },
      { label: 'Monthly Contribution Equivalent', value: `To reach $${fv.toFixed(0)} from $${iv.toFixed(0)} in ${y} years at ${cagr.toFixed(2)}% CAGR without growth, you'd need $${monthlyAbsolute.toFixed(0)}/mo in straight savings ($${annualAbsolute.toFixed(0)}/yr). But with compounding, the same result requires less if starting earlier. $${iv.toFixed(0)} at ${cagr.toFixed(2)}% for ${y} years → $${fv.toFixed(0)}. Adding $100/mo with same return: → $${(fv + 100 * ((Math.pow(1 + cagr / 100 / 12, 12 * y) - 1) / (cagr / 100 / 12))).toFixed(0)}.` },
      { label: 'Tax & Fee Impact on Net Return', value: `Pre-tax CAGR: ${cagr.toFixed(2)}%. After 15% capital gains tax (US long-term): ~${(cagr * 0.85).toFixed(2)}% net. After 1% annual fee (typical active fund): ~${(cagr - 1).toFixed(2)}% net. Over ${y} years, 1% fees consume ${((1 - Math.pow(1 + (cagr - 1) / 100, y) / Math.pow(1 + cagr / 100, y)) * 100).toFixed(0)}% of your final value. On $${fv.toFixed(0)}: $${(fv * (1 - Math.pow(1 + (cagr - 1) / 100, y) / Math.pow(1 + cagr / 100, y))).toFixed(0)} lost to fees. Use low-cost index funds (0.03-0.10% fees).` },
    ]} },
  description: 'Calculate growth rates over any time period — CAGR (Compound Annual Growth Rate), total growth percentage, annual absolute change, growth multiple, and Rule of 72 doubling time. Works for investments, business revenue, real estate appreciation, and population growth.',
  formula: 'CAGR (%) = ((Final Value ÷ Initial Value)^(1 ÷ Years) − 1) × 100 | Total Growth (%) = ((Final − Initial) ÷ Initial) × 100 | Growth Multiple = Final ÷ Initial | Doubling Time (Rule of 72) = 72 ÷ CAGR | Real CAGR = Nominal CAGR − Inflation Rate',
  interpretation: 'CAGR smooths volatility into a single annualized rate — use for comparing investments of different durations. Total growth is raw percentage; CAGR accounts for compounding. S&P 500 historical CAGR: ~10%. Rule of 72: at 10% CAGR, money doubles every 7.2 years. At 7%: doubles every 10.3 years. CAGR is always ≤ arithmetic mean due to volatility drag. After 3% inflation, subtract from CAGR for real purchasing power growth. Low-cost index funds (0.03-0.10% fees) preserve 96-99% of returns vs 1%+ fee funds.'
}

export default calcDef
