import { z } from 'zod'
import { n, step, numField, selectField, num2Schema, num3Schema, textField, fact, gcd, ni } from '../../../lib/hub-helpers'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
    schema: z.object({ n: z.string().min(1).refine(v => !isNaN(parseFloat(v)) && parseFloat(v) >= 0 && Number.isInteger(Number(v)) && Number(v) <= 14, '0-14 integer') }),
    fields: [numField('n', 'n (0-14)', { min: 0, max: 14, step: '1' })],
    defaults: { n: '6' },
    compute: (v) => {
      const nVal = Math.round(n(v.n)); const B = [1, -1/2, 1/6, 0, -1/30, 0, 1/42, 0, -1/30, 0, 5/66, 0, -691/2730, 0, 7/6]
      return { result: B[nVal].toFixed(6), label: 'B?', steps: [step('n', '' + nVal), step('B?', B[nVal].toFixed(6))] ,
    extras: [
      { label: "Mathematical Significance", value: "Fundamental concept in number theory and discrete mathematics." },
      { label: "Computational Note", value: "Large inputs may require optimized algorithms for performance." },
      { label: "Historical Context", value: "Studied by mathematicians across centuries for its unique properties." },
      { label: "Related Sequences", value: "Related to other integer sequences and special numbers." },
      { label: "Pattern Recognition", value: "Observe recurring patterns and relationships between values." }
    ]}
    },
    formula: 'B0 = 1, B1 = -1/2. Generated by t/(e?-1) = S B? tn/n!.',
    description: 'Calculate the nth Bernoulli number.',
    interpretation: 'Bernoulli numbers appear in the expansion of t/(e?-1).',
    presets: [
      { label: 'Default', values: {  } }
    ]
}

export default calcDef
