import { z } from 'zod'
import { n, step, numField, selectField, num2Schema, num3Schema, textField, fact, gcd, ni } from '../../../lib/hub-helpers'
import type { CalcDef } from '../../../lib/generic-fallback'

const calcDef: CalcDef = {
    schema: z.object({ a: z.string().min(1).refine(v => !isNaN(parseFloat(v)) && parseFloat(v) >= 1 && Number.isInteger(Number(v)), 'Must be integer >= 1'), b: z.string().min(1).refine(v => !isNaN(parseFloat(v)) && parseFloat(v) >= 1 && Number.isInteger(Number(v)), 'Must be integer >= 1'), type: z.enum(['arithmetic', 'geometric']) }),
    fields: [numField('a', 'First term (n=1)', { step: '1' }), numField('b', 'Number of terms', { min: 1, step: '1' }), selectField('type', 'Type', [{ value: 'arithmetic', label: 'Arithmetic' }, { value: 'geometric', label: 'Geometric' }])],
    defaults: { a: '2', b: '5', type: 'arithmetic' },
    compute: (v) => {
      const first = n(v.a), nTerms = Math.round(n(v.b))
      const type = v.type || 'arithmetic'
      const terms: number[] = []
      if (type === 'arithmetic') { for (let i = 0; i < nTerms; i++) terms.push(first + i * first) }
      else { let val = 1; for (let i = 0; i < nTerms; i++) { terms.push(val * first); val *= 2 } }
      return { result: terms.join(', '), label: 'Sequence', steps: [step('Type:', type), step('Terms:', terms.join(', '))] }
    },
    formula: 'Arithmetic: a_n = a + (n-1)d. Geometric: a_n = a x r^(n-1)',
    description: 'Generate an arithmetic or geometric sequence.',
    interpretation: 'The sequence of terms generated by the given rule.'
}

export default calcDef
